### ISSUE TITLE
Event location summary formatting

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#1002]
An event Location will be summarised on the Event page.  A user can click on "Full Description" to see the full text.
See this example:
[https://aeva.asn.au/events/73/](url)
On the Event page the Location section is displaying "&nbsp".

![Summary](https://user-images.githubusercontent.com/64681720/113055315-314c5300-91f6-11eb-8772-4237cfe5d372.png)
Opening the Full Description displays correctly:
![Full_Description](https://user-images.githubusercontent.com/64681720/113055312-301b2600-91f6-11eb-982c-be55ac258b8a.png)

**Comment by jennyq** [comment]
Thanks @CWalkden ! Resolved.
