### ISSUE TITLE
Add Filter ability to Template Tag ListNode

### ISSUE THREAD

**Issue by theox26** [tendenci/tendenci#1003]
https://github.com/tendenci/tendenci/blob/3ee10421305f5afeb1f4dbc0ff02de62c6f20862/tendenci/apps/base/template_tags.py#L35

My actual need is to grab only the featured FAQ from the help_files 'list_help_files' tag. I could make a tag specifically for it or add to the function there but it seems like putting it in this place not only gives me what I need but adds the ability for a lot of other possible uses.

I'll be adding it to my own fork either way, would you like it pushed back here as well?

**Comment by jennyq** [comment]
Hi @theox26, 
If you think it would benefit for everybody else, feel free to submit a pull request. Thanks!
