### ISSUE TITLE
Cannot create membership forms

### ISSUE THREAD

**Issue by bernd-wechner** [tendenci/tendenci#1008]
When I try it crashes with:

```
IntegrityError at /admin/memberships/membershipapp/add/
duplicate key value violates unique constraint "memberships_membershipapp_membership_types_pkey"
DETAIL:  Key (id)=(5) already exists.
```
Logging it here while I investigate. But it's rather cryptic and odd. All I see is:

![image](https://user-images.githubusercontent.com/7296506/113680533-49dfd000-9704-11eb-84f6-f8dc538e7120.png)

and I click Add Membership Application.

I have to work out what "memberships_membershipapp_membership_types_pkey" is first ;-). But it smells of a local database config issue, albeit with a poorly (not gracefully) handled bail. That said it looks to be entirely within django admin and not tendenci. As I said, logging here to track work on it as it is a roadblock in managing our tendenci site right now.

**Comment by bernd-wechner** [comment]
Found the constraint:

```
-- Constraint: memberships_membershipapp_membership_types_pkey

-- ALTER TABLE public.memberships_membershipapp_membership_types DROP CONSTRAINT memberships_membershipapp_membership_types_pkey;

ALTER TABLE public.memberships_membershipapp_membership_types
    ADD CONSTRAINT memberships_membershipapp_membership_types_pkey PRIMARY KEY (id);
```

And sure that table contains6 tuples including one with ID/Key 5.

![image](https://user-images.githubusercontent.com/7296506/113682414-7694e700-9706-11eb-9f84-dbe781c431fe.png)

But that is totally in order given we have 6 membership types.

![image](https://user-images.githubusercontent.com/7296506/113682637-b52aa180-9706-11eb-9ded-2e4fa9d642e8.png)

The mystery deepens as to why adding a membership application form should want to write to this table let along arbitrarily one of the 6 membership types.

**Comment by bernd-wechner** [comment]
And it's sorted. I was watching all the SQL queries after a form submission (and man there are a lot, so I zoomed into INSERT and UPDATE queries only). What I noticed then by the time I'd found the culprit query, is that it worked. What was happening is bizarre and mildy concerning at numerous levels. 

Ordinarily I would expect Postgresql managed autoincrementing keys itself. Further I would expect that it would be some major feat of incredible low level hacking to confuse Postgresql in this space, that is, somehow get data into a table while the next free key ID was pointing to an already used key. Certainly cannot for the life of me imagine how that could happen.

To wit, lacking firm evidence, I'm mildly concerned that Django or Tendenci is managing this particular key and that somehow I did (by injecting data into the database) circumvent some higher level next-free-key tracker in Django or Tendenci, which if it does exist, exhibits the concerning feature that after every failed INSERT effort it advances ... and so after a few submission effort sin this debug process, it finally hit an actual free Key value and  the submission just worked ...

All I can say is, odd.  the process of deeper diagnosis. Needed as this was a blocking issue for our site. But we're rolling once more.

**Comment by jennyq** [comment]
Did you load fixtures with the loaddata command? It seems to be an issue with Postgres table sequence. https://code.djangoproject.com/ticket/3915. I encountered the similar issue long time ago, but I don't see it anymore. My solution was to reset the sequence for the affected table.

**Comment by bernd-wechner** [comment]
Don't think I ever used loaddata. But that ticket does lend credence to the idea (that I didn't believe possible) that Python can do that. I held the impression that the autoincrementing keys are managed with integrity by the RDBMS and not something that could be corrupted by a SQL command. But apparently not. I haven't worked out how to see the current value in pgadmin of the sequence pointer, or a way to reset it in pgadmin. 

Either way, was a bizarre experience, and has gone away.
