### ISSUE TITLE
NOTICE FROM A NATIONAL NGO IN INDIA

### ISSUE THREAD

**Issue by khumaer** [tendenci/tendenci#1011]
Kindly revert back to our emails

**Comment by khumaer** [comment]
We just want to thank you for your awesome software.Especially your Help Files which are in depth. 
This is by far THE BEST in MEMBERSHIP CATEGORY in THE WHOLE WORLD. Once again Thank you.

**Comment by lashirley21** [comment]
> We just want to thank you for your awesome software.Especially your Help Files which are in depth.
> This is by far THE BEST in MEMBERSHIP CATEGORY in THE WHOLE WORLD. Once again Thank you.

@khumaer Thank You for this review. Can you please be so kind and help us out by leaving us a review in our Capterra listing? This will help us so much! Here is the link: https://reviews.capterra.com/new/44378
