### ISSUE TITLE
Required field has no asterisk

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#1014]
Our membership form is here:
https://aeva.asn.au/memberships/applications/aeva-membership/
The Username is a required field:
![Screenshot at 2021-05-23 20-17-09](https://user-images.githubusercontent.com/64681720/119256396-e6522900-bc03-11eb-9843-a72f655020d6.png)

But it does not have a red asterisk on the form:
![Screenshot at 2021-05-23 20-14-13](https://user-images.githubusercontent.com/64681720/119256324-83f92880-bc03-11eb-8f6e-72f169149dd7.png)

Any idea why this doesn't have the asterisk?  It is a bit confusing.

**Comment by jennyq** [comment]
Fixed. Thank you for reporting the issue!
