### ISSUE TITLE
Recurring payments in Membership Module

### ISSUE THREAD

**Issue by theox26** [tendenci/tendenci#1015]
I can't seem to get recurring payments to function with membership.

I have a form setup that has functioning recurring payment but can't seem to find where to activate it anywhere else. Is there some other setting needed I don't see or is this functionality that needs to be added to the module?

**Comment by CWalkden** [comment]
I'm not aware that this is currently a function.  But it would be great if it was!

**Comment by theox26** [comment]
> 
> 
> I'm not aware that this is currently a function. But it would be great if it was!

[This](https://www.tendenci.com/help-files/how-set-recurring-payment-account/) documentation mentions it as being part of memberships and forms while instructing how to set one up for manual addition. I see it in Forms and the manual addition.

I found it in the code for the Memberships and am testing now. It looks like you need to go into the 'Full Settings' options the Memberships and turn on auto-renew as an option.

I'm still digging to figure out how to get it to active.

**Comment by jennyq** [comment]
Hi @theox26, below are the links on how to enable memberships auto renewal. 
https://www.tendenci.com/help-files/how-enable-memberships-auto-renew-stripe/
https://www.tendenci.com/help-files/how-to-update-current-members-for-autorenewals/

**Comment by theox26** [comment]
Thank you @jennyq. Is there a current way to have the membership go right into the recurring payment instead of an invoice first? 

If not, I think I'll add that for our use case.

**Comment by theox26** [comment]
I see now after more testing that it is an option on the form once enabled in all the right places. It auto fills the CC info from the other payment method and is all setup. Thanks!

**Comment by jennyq** [comment]
Great! Glad it helped.
