### ISSUE TITLE
Edit add_edit.html template

### ISSUE THREAD

**Issue by avkovalevs** [tendenci/tendenci#1020]
HI @jennyq 
The add_edit.html template in profiles has the following block of the code:
`   <div class="form-group">
        <label for="id_url" class="col-sm-3 control-label">{{ form.url.label }}{%if from.url.label in required_fields_list%}<span class="body-copy-alerts">*</span>{% endif %}</label>
        <div class="col-sm-9">
          {% if form.url.errors %}
             <div class="text-danger">{{ form.url.errors }}</div>
          {% endif %}
          
          {{ form.url }}
          
          {% if form.url.help_text %}
          <div class="help-block">{{ form.url.help_text }}</div>
          {% endif %}
        </div>
     </div>`
As I understand, form.url.label  has a label "Website",   form.url.help_text  is a text field. What is the form.url.errors and  required_fields_list?  I see these variables mentioned in forms.py and views.py.
The second question, there is a way to combine add_edit.html with educational fields (schools, years, degree)?
Which template contains educational fields? How to reduce educational years from 1930 to 2030 from the list?

**Comment by jennyq** [comment]
When form.is_valid() is called, if validation fails on the url field, the errors attribute would be assigned. As for the "required_fields_list", it is supposed to have a setting to define additional required fields https://github.com/tendenci/tendenci/blob/master/tendenci/apps/profiles/views.py#L445. But I don't see that setting in the profiles/settings.json. So, ignore it for now.  

To have educational fields on profile add/edit, it would need to update in the profiles/view.py; it can not simply combine add_edit.html with educational fields. 

The educational fields can be edited with membership applications.  The YEAR_CHOICES is defined in the form EducationForm and currently can not be changed without changing tendenci core. The https://github.com/tendenci/tendenci/blob/master/tendenci/apps/memberships/forms.py#L885

**Comment by avkovalevs** [comment]
@jennyq  Thank you for the explanation. How to change the label "Website" to another value? How to add help text to the form for the"Website" label?

**Comment by jennyq** [comment]
To change the label and help text for the url field, you'd have to pull down the template in the theme editor, then change `{{ form.url.label }}` and `{{ form.url.help_text }}` to your preferred values.

The "Region Code" is already in there. Where do you want to display it?

**Comment by avkovalevs** [comment]
The "Region code" insert to first column instad of numbers.

**Comment by jennyq** [comment]
It is the standard across the modules to have the id as the first column. I'm afraid it cannot be changed. Is there a reason why you want the "Region code" in the first column?

**Comment by avkovalevs** [comment]
We have an idea to remove unuseful id. But if it is a standard, then ok. 
Is there a way to change some required fields on usual (none-required)?

**Comment by jennyq** [comment]
Currently required fields can not be changed to non-required fields.

**Comment by avkovalevs** [comment]
Ok, thanks. 
How to increase the value from 100 characters to 200 for url field in a profile form?
I know that on a database level it is easy. But the application level is still unknown to me. 
Talking about the region filed in the profile form it shows me a number instead of a shortcode.
How to change this to a shortcode?

**Comment by jennyq** [comment]
You cannot change the URL length on your end, it'd need to change in Tendenci core https://github.com/tendenci/tendenci/blob/master/tendenci/libs/abstracts/models.py#L125. 
But I think 100 is a reasonable length for an URL. URLs with 80 characters or less is more SEO friendly than the longer ones.

As for the region, I'm not sure which form you're talking about. A screenshot or a link would be helpful.

**Comment by avkovalevs** [comment]
Thank you, the form with the region is attached.
![profiles](https://user-images.githubusercontent.com/22083701/125786064-b475d5fa-b502-4da1-af53-9a719ff909c3.jpg)

**Comment by jennyq** [comment]
Hi @avkovalevs, 

I don't see that in the Tendenci core. Besides, Region in profiles is a char field https://github.com/tendenci/tendenci/blob/master/tendenci/libs/abstracts/models.py#L107. 

Is the template "profiles/index.html" pulled down to your site? If so, can you take a look at it in the theme editor /theme-editor/editor/?file=templates/profiles/index.html and paste the code snippet related to the Region?

**Comment by avkovalevs** [comment]
{% if can_edit or not profile.hide_address %}
              {% if profile.region %}
              <tr>
                <td>Région</td>
                <td style="font-weight:normal;">{{ profile.region }} {{ region_code }}</td>
              </tr>
              {% endif %}
            <tr>
              <td>Lieu</td>
              <td style="font-weight:normal;">{{ profile.address }} <span class="city-state-zip">{{ city_state_zip }}</span></td>
            </tr>
            {% endif %}

**Comment by jennyq** [comment]
Hi @avkovalevs, 

Great catch! It has been resolved. Please update your site to the latest version of Tendenci, then replace `{{ profile.region }}` with `{{ profile.get_region_name }}` in your template profiles/index.html. (remove the `{{ region_code }}` as it is not defined).
