### ISSUE TITLE
Duplicate Key Value for Key(user_id)=(1) on fresh installation

### ISSUE THREAD

**Issue by proffalken** [tendenci/tendenci#1021]
Hi all,

I'm running a fresh install on a Digital Ocean Ubuntu 20LTS instance, and everything in the docs worked perfectly apart from `python manage.py load_tendenci_defaults` which exits with the following error:

```
tendenci_default_profiles_profile.json
Traceback (most recent call last):
  File "/srv/tendenci/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "profiles_profile_user_id_key"
DETAIL:  Key (user_id)=(1) already exists.
```

When I run the other commands and log in to the site, I don't see any content for the `resources` boxes on the home page, and clicking on the `join our mailing list` button just displays a blank box:

![2021-06-30_20-42](https://user-images.githubusercontent.com/262545/124021715-c91f3000-d9e3-11eb-89d4-c6b0af7ef195.png)

I'm not sure if these are connected, however I also can't tell from the docs how to populate the resources or how to get the form showing for the mailing list, so I'm out of ideas on how to test it!

Is there a way to fix this?

**Comment by proffalken** [comment]
OK, I've "fixed" this by commenting out the `profiles_profile` and `explorer` parts at the bottom of `apps/base/management/commands/load_tendenci_defaults.py`, and the site now renders correctly, but it would be good to know why this was happening on a fresh installation so it doesn't happen in future!

**Comment by jennyq** [comment]
@proffalken, 

Thank you for pointing out the issue! I've pushed out a fix for the `tendenci_default_explorer.json` https://github.com/tendenci/tendenci/commit/65f98cb73d7662dd2915b8fa3c3e9d95f31df578. Tested the fresh install and it works fine now.  The "duplicate key" error you got is probably because you ran the "createsuperuser" command before running "load_tendenci_defaults". That order matters.

**Comment by proffalken** [comment]
Fantastic, thanks @jennyq 

I ran the `createsuperuser` after the `load_tendenci_defaults` failed the first time just so I could get in and see what the platform was like, I then tried to re-run the `load_tendenci_defaults` afterwards which is when I started editing the files.

Great to know it's fixed, and thanks for the quick response!
