### ISSUE TITLE
Ecommerce in Tendenci - any plans to revisit it?

### ISSUE THREAD

**Issue by proffalken** [tendenci/tendenci#1022]
Hi all,

I'm just wondering if there are any plans to revisit https://github.com/tendenci/tendenci/issues/473 ?

I'm about to start using Tendenci to run a Makerspace website, and we're also considering a "members-only shop" selling kit for our members - it would be great if we could integrated the two, however I also realise it's a fairly niche requirement...

**Comment by jennyq** [comment]
Hi @proffalken, 

Currently there is no plan for that.

Check out the custom forms module to see if it can fit your needs https://www.yourdomain/admin/forms/form/. You can set up a custom form that restricts the access to members only.

**Comment by proffalken** [comment]
Thanks @jennyq, totally understand, we can always host something on a different sub-domain and see if we can link it back to Tendenci somehow...
