### ISSUE TITLE
Accessing tendenci data via an API?

### ISSUE THREAD

**Issue by proffalken** [tendenci/tendenci#1023]
Hey all,

Still getting to grips with this, but it's looking really good.

Is there an API that I can call to get information about membership/events/etc?

I'm writing a discord bot for our Maker Space and it would be awesome to be able to get the events data from Tendenci without having to hack directly into the database!

I've found the following links on the main tendenci website:

* https://www.tendenci.com/help-files/open-source-ams-api-integrations/
* https://www.tendenci.com/help-files/5-0/tendenci-api/
* https://blog.tendenci.com/tendenci-ams-api-integration/

However all of them are well out of date as far as I can tell, and are also lacking in detail on how to set up API Access to Tendenci (if I'm honest, they seem like marketing "fluff" designed to help with search engine results! ;) )

The docs don't appear to have anything on this either.

Can anyone help?

**Comment by jennyq** [comment]
Hi @proffalken,

Tendenci has [django-tastypie](https://django-tastypie.readthedocs.io)  integrated long time ago. It is limited to superuser only. For authentication, it uses API key authentication. 

To add your API key, go to admin backend at /admin/tastypie/apikey/. 

Example url to pull a list of events:
https://www.example.com/api_tasty/v1/event/?format=json&username=myusername&api_key=mysupersecureapikey
(or specify an Authorization header)

To view a list of available resources for the API, go to:
https://www.example.com/api_tasty/v1/?format=json

If you spot issues and would like to fix them, pull requests are always welcome.

**Comment by proffalken** [comment]
Amazing, thanks @jennyq!

**Comment by proffalken** [comment]
@jennyq I've got this working now, but the results are a little bit odd:

```json
{
   "meta" : {
      "limit" : 20,
      "next" : "/api_tasty/v1/event/?format=json&username=<MYUSER>&api_key=<MYKEY>&limit=20&offset=20",
      "offset" : 0,
      "previous" : null,
      "total_count" : 21
   },
   "objects" : [
      {
         "creator" : "/api_tasty/v1/user/1/",
         "entity" : "/api_tasty/v1/entity/1/",
         "owner" : "/api_tasty/v1/user/1/",
         "place" : "/api_tasty/v1/place/1/",
         "type" : "/api_tasty/v1/type/1/"
      }
  ]
}
```
I'd expect to see a start date/end date etc. as part of the return.

I thought I'd query the entity endpoint to see if that gave me a result, but all I get back from that is this:

```json
{
   "error" : "The model '&lt;Entity: 0001 YOUR ORGANIZATIONS NAME&gt;' has an empty attribute 'creator' and doesn't allow a null value."
}
```

Any ideas what might be causing this?

**Comment by jennyq** [comment]
I've just pushed out a fix to address the error https://github.com/tendenci/tendenci/commit/0fd76740e982244fd34e645c21202d1d6d843a8a.  The event issue is also resolved in another commit https://github.com/tendenci/tendenci/commit/3ad4d63930e6c0aee64b5fd579bb37fb59dfc8e7. Before we do a version bump, you can pull from github tendenci repo.

**Comment by proffalken** [comment]
Thanks @jennyq - is there a schedule to releases, or is it "release when ready"?

**Comment by jennyq** [comment]
Most of the time it's "release when ready". We'll issue a new release next week (probably on Tuesday).

**Comment by proffalken** [comment]
Amazing, thanks, I can wait until then :)

**Comment by jennyq** [comment]
A new version has just been released.

**Comment by proffalken** [comment]
Calendar data fixed in latest release, closing ticket as API responds with correct data.
