### ISSUE TITLE
Web address in HTML renewal email are not linked

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#1025]
Our renewal emails were based on the default ones supplied in the Tendenci package.  They have lines like this:
`<p>To renew your membership visit {{ renew_link }}</p>`

This results in an HTML email without a link - the 'link' is plain text.
Many email clients automatically turn the text into a link, but many do not.

We were able to fix this by replacing the above code with:
`<p>To renew your membership visit this link:&nbsp; <a href="{{ renew_link }}">{{ renew_link }}</a></p>`

It would be good if the example emails were set up like this.

**Comment by jennyq** [comment]
Thanks @CWalkden ! Updated https://github.com/tendenci/tendenci/commit/d2f524b998984580b9bfa6704cec4a7619df9f2a.
