### ISSUE TITLE
Mismatch of profile and directory field parameters

### ISSUE THREAD

**Issue by SidBergstresser** [tendenci/tendenci#1029]
The address field on the profiles_profile table is varchar(150) but the address field on the directories_directory table is varchar(100). If a user has an address longer than 100 characters on their profile, when the membership application is approved and the system attempts to create their directory, the creation process fails because the 100 character limit of the address field on the directories_directory table is exceeded.
Many international addresses can be longer than 100 characters. Can you change the parameter of the address field on the directories_directory table to varchar(150) in order to match the corresponding field on the profiles_profile table?

**Comment by jennyq** [comment]
@SidBergstresser Thanks for reporting the issue! Fixed https://github.com/tendenci/tendenci/commit/acec4bec7af2ce01a80404ac14ea51907f5a3d4e
