### ISSUE TITLE
Username Requirements

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#1031]
We're using Tendenci versions 12.5.3 and 12.5.6.
A potential user has complained that this message comes up:
![Screenshot at 2021-08-03 20-57-29](https://user-images.githubusercontent.com/64681720/128004447-33811007-feff-48e5-a522-e3dae3be403e.png)
She is asking a sensible question - what is a 'valid value' for a username?
I've done some experiments and found that "@" and "." are both not allowed.  This is only for self-registering users though, both symbols are allowed in the username if signing up as a member.

Is there a reason why the requirements for a username are different between a user and a member?
What are the requirements - can we list them on that page?

**Comment by jennyq** [comment]
Resolved https://github.com/tendenci/tendenci/commit/6bb4792be2dbb7e0f14357b5572e9ba99a32c5c2. @CWalkden, thanks for reporting the issue!
