### ISSUE TITLE
Forms Payments

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#1032]
We're using a form to sell a product, link is here:  [https://www.aeva.asn.au/forms/ev-licence-plate-tag/](https://www.aeva.asn.au/forms/ev-licence-plate-tag/)
We have two issues:

I had feedback from a user that the form layout caused her some confusion.  She said that she filled things in in order down to the CAPTCHA, then presumably pressed Enter, which submitted the form.  She didn't expect it to submit the form at that stage, she hadn't entered the information in the final section (Billing Information).  I agree with her that the CAPTCHA would be more logical at the end of the form.  As far as I can see, this isn't something that we have control over when we create the form.

Secondly, when I look at the form entries, I cannot tell if an entry has been paid or not.  I have two entries, one where the payment was abandoned and one where it was successful, but they look identical.  The only way I can find to tell is if I go into the Invoices module and check each one.

**Comment by jennyq** [comment]
Resolved in https://github.com/tendenci/tendenci/commit/a16de081567fd83bf9011cee094e5de383971118 and https://github.com/tendenci/tendenci/commit/e35a8870e5638b3b5e651135e9c3e302e6cdd540

**Comment by CWalkden** [comment]
In fact I just noticed that the entire Billing Information section isn't required on this page.  When you press the submit button you are taken to another screen with Billing Information.  Not sure if that is addressed by your changes?

**Comment by jennyq** [comment]
@CWalkden I don't see that behavior. Is this site on the latest version of tendenci?

**Comment by CWalkden** [comment]
> @CWalkden I don't see that behavior. Is this site on the latest version of tendenci?

No, it's on 12.5.3.  I'll get it updated and check.

**Comment by CWalkden** [comment]
> @CWalkden I don't see that behavior. Is this site on the latest version of tendenci?

I've checked now and in version 12.5.8 this problem has gone.
