### ISSUE TITLE
Membership import username field character limits

### ISSUE THREAD

**Issue by SidBergstresser** [tendenci/tendenci#1034]
The username field on the membership import is limited to 30 characters even though usernames can be longer than that. So when attempting to conduct a bulk update by exporting, updating information, and then importing, any usernames over 30 characters are truncated and the import attempts to insert a new record rather than update the existing record. Recommend increasing character limits for all fields on the membership import to match the allowed characters of those fields. 
Thanks!

**Comment by jennyq** [comment]
Fixed. Thanks @SidBergstresser for pointing it out!
