### ISSUE TITLE
Dashboard is broken! https://blog.tendenci.com/feed/ is down!

### ISSUE THREAD

**Issue by bernd-wechner** [tendenci/tendenci#1045]
This is pretty critical. Our site lost its dashboard. Tracing the reason it's because of this:

https://github.com/tendenci/tendenci/blob/4ad7adc62828826af723115b410203b970d84fb0/tendenci/themes/t7-base/templates/dashboard/new.html#L214

And so I've removed that block locally. But at tendenci this probably warrants getting the blog up and reliable and making this code more robust against its being down.

**Comment by jennyq** [comment]
The dashboard error should be gone.  New blog coming soon.

Thanks @bernd-wechner again for pointing out the issue to us!
