### ISSUE TITLE
Spelling error in help file

### ISSUE THREAD

**Issue by bernd-wechner** [tendenci/tendenci#1046]
Visit:

https://www.tendenci.com/help-files/add-and-manage-membership-types/

On this page you will find:

> **Rnewal Price**
> 
> If you Allow Renewals at this Membership Type, you'll set a Renewal Price. It can be the same price you set for the first time signup, but you do need to define that here. You may want to give renewals a discounted price.

I logged in, but can't edit the page. Am happy to fix such typos as and when if ind them if you trust me with edit priviledges ont he tendenci help. Just let me know.

**Comment by ndavis2** [comment]
Hi Bernd,

Odd, I checked and you're in a group called "Help-file editors" that I've given permission to edit this particular help-file (https://www.tendenci.com/profiles/ThumbOne/). When you log in, in your toolbar are you able to see Apps -> 2. Content -> Help-files? When you click on help-files, you should then have a drop-down menu at the top right that's specific to the help-files module. In that dropdown, select "edit help-file". 

I hope this helps - please let me know if you still experience issues trying to edit this help-file.

Best,
<img width="863" alt="Screen Shot 2021-09-22 at 5 55 37 PM" src="https://user-images.githubusercontent.com/38054131/134433271-d76d8213-6e4d-4b71-a4e1-34fd54c81114.png">

Nicole, Team Tendenci

**Comment by bernd-wechner** [comment]
Thanks Nicole, I've been nose down pumping out little fixes in the lead up to an AGM and conference that I sort od needed. One of the chunkier ones was editing form entries (oddly lacking from Tendenci and needed for full workflow on an expense claim form I built to make my like as treasurer easier - I need a way to edit the entry and mark it as paid for example - all no possible).

**Comment by bernd-wechner** [comment]
Finally got round to this again, and checked and yes, could edit, and did and fixed that typo! Thanks heaps.
