### ISSUE TITLE
Formatting in Event Speaker

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#1076]
I created a speaker bio in an Event, and it is not showing correctly.
Here it is on the Event page, where it displays correctly:
![image](https://user-images.githubusercontent.com/64681720/145548337-2d0f455a-f91d-44d4-bc46-94546c86973a.png)
But if I press the View all Speakers button I see this:
![image](https://user-images.githubusercontent.com/64681720/145548467-99bd7919-4969-45eb-9a37-83cb481ddee6.png)

Tendenci version 12.5.3

**Comment by CWalkden** [comment]
We've installed Tendenci 14.0.1 and this is still an issue.

**Comment by jennyq** [comment]
Thanks @CWalkden for reporting the issue! It has been fixed https://github.com/tendenci/tendenci/commit/4b4973fa1443140e5f044d878fce8923dd620a78.
