### ISSUE TITLE
Usergroups missing in Newsletters module

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#1081]
In the Newsletters module, when you select a usergroup to send the newsletter to, only 'public' groups are shown.  This is presumably a permissions issue, as all groups are displayed if the newsletter writer is a Supersuer.

There is a group property called 'Sync for Newsletters', but this field doesn't control which groups are listed.

Tendenci version 14.0.1

This is an important issue for us, it is stopping us upgrading (we're still on 12.5.3 which has the desired functionality).  Please let us know if the current functionality is intended, as we'll need to work around it somehow.

**Comment by jennyq** [comment]
You're right - the 'Sync for Newsletters" boolean field should be taken account into. A fix https://github.com/tendenci/tendenci/commit/c638f89527d63f74bb97005d0136d8be94647be5 has been pushed out which should resolve your issue. We'll do a version bump next week.
