### ISSUE TITLE
Groups not shown in Events

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#1086]
Tendenci version 14.0.3
When adding an event, the list of groups is not complete.  Some groups are shown, but not all, and I can't figure out the logic as to which ones are there.
In the group properties is a field "Show for Events".  I would assume that the groups shown in the Events module should honour that field, but it does not.

**Comment by jennyq** [comment]
Hi @CWalkden,

The "Show for Events" boolean field **IS** respected. Furthermore, for non superusers, it filters groups that user has the view or change permissions depending on how the setting "Permission (view/change perm) Required for Groups to Show up in Group Dropdown" is set up /settings/module/user_groups/#id_permrequiredingd.

**Comment by CWalkden** [comment]
> The "Show for Events" boolean field **IS** respected. Furthermore, for non superusers, it filters groups that user has the view or change permissions depending on how the setting "Permission (view/change perm) Required for Groups to Show up in Group Dropdown" is set up /settings/module/user_groups/#id_permrequiredingd.

Ok, here is what I'm seeing:
 /settings/module/user_groups/#id_permrequiredingd  is set to View.
Some groups are shown in the list, some are not (for a non superuser).
All groups have the "Show for Events" field ticked.
I've figured out that the difference is that the shown groups have the property "Public can View" set.  The groups not shown do not have this property set.

We use the "Public can View" property to filter the groups that a User (non-member) can add themselves to.  They see a list when they press the gear icon on their profile page.  This field filters the groups shown in the list.

In the Newsletters module, for that same non-superuser, the drop-down list is populated by all relevant groups (thanks to the change that you recently made).

**Comment by CWalkden** [comment]
This is still happening in Tendenci Version 14.1.
When creating a new Event, the groups shown in the drop-down list are filtered by 'Public can View'.  My understanding is that this should not be the case.
The equivalent drop-down list in the Newsletters module is better, groups are not filtered in this way.

**Comment by CWalkden** [comment]
Just checked on Tendenci Version 14.2.  This problem is still there.

**Comment by jennyq** [comment]
Hi @CWalkden,

Some sites allow regular users to add/edit their events. We don't want to disclose private groups to those users unless they have the permissions to view the groups. 

To resolve your issue, you can either assign the permission "user_groups | Groups | Can view Group" to the non superusers who can add/edit events. Or make those groups to allow view by users. Will that work for you?

**Comment by CWalkden** [comment]
> To resolve your issue, you can either assign the permission "user_groups | Groups | Can view Group" to the non superusers who can add/edit events. Or make those groups to allow view by users. Will that work for you?

The first option here should be ok for us, but I just tried it, and it didn't work.  The way I did this was:
We give only certain members access to add events (and other content).  This is controlled by putting them into a group called "Tas Content".  The Content group has permissions to let them do the things.
So I added the permission "user_groups | Groups | Can view Group" to the Tas Content group.  
![image](https://user-images.githubusercontent.com/64681720/180668212-a0159c18-90bc-45cb-abc8-c3f853a31fbf.png)

This did not change the groups that the members can see, it is still as described above.
![image](https://user-images.githubusercontent.com/64681720/180668254-fd24423b-4e72-4f79-a6d9-536e42cc1560.png)


I found another problem that may be related.  I'll raise another Issue for it.

**Comment by CWalkden** [comment]
This problem in a nutshell:
We have a set of groups which members can select when they join.  They are for mailing lists:
![image](https://user-images.githubusercontent.com/64681720/180669546-5e3658ab-e44f-49c8-b1e8-9027b10ce252.png)
We don't want regular users to be able to see these groups, it would be confusing for them.  To do this, we make the groups invisible to the public (untick 'Public can view'):
![image](https://user-images.githubusercontent.com/64681720/180669580-abc493af-7b03-4f27-9d12-57fca0d0c23b.png)

We have non-superuser members who have access to create content.  They are put into a 'Content' group, which gives them certain permissions.
They can create a page, and can choose groups as shown:
![image](https://user-images.githubusercontent.com/64681720/180669687-fe226fa8-29c5-44fb-8d7d-531c0aea7c0f.png)
They can create an article, but the groups are different.  None of the 'Members' groups are shown:
![image](https://user-images.githubusercontent.com/64681720/180669777-dd986a23-5ec6-4bb3-a9d3-8bba67593a63.png)
They can create an event, but the groups are different again:
![image](https://user-images.githubusercontent.com/64681720/180669856-bda5e286-d849-43e0-81ae-9c3038484461.png)
Note that in the permissions screenshot above, the field 'Show for Events' is ticked.  Shouldn't that be all that is required to show up in the Events module?

**Comment by jennyq** [comment]
Pushed out a fix which should allow you to use the option 1.
https://github.com/tendenci/tendenci/commit/9f619a9c8313f46663255844865cad4a42f8eae1
