### ISSUE TITLE
Disable Gravatar for the site

### ISSUE THREAD

**Issue by vsatmydynipnet** [tendenci/tendenci#1097]
Hi,

I run into the problem that I need to remove Gravatar for the site. Mainly because of GDPR risks, but also because there should be no 3rd parties serving stuff for the site. All should and must come from the sites  server, not from others.

I saw in the code, that if 
```
def get_gravatar_url(self, size):
        if self.photo:
            photo_url = self.get_photo_url(size=size)
            if photo_url:
                return photo_url
........
```
a user pic exists, everything works as I want it, but I found no way to set some default image for new profiles to avoid having tracking at Gravatar, which adds wp.com as second 3rd party server too,  of the users.

Is there any solution to set a default image and avoid loading Gravatar/WP.com?

Use Old Avatar As Default  is set to true

Thank you

**Comment by jennyq** [comment]
Resolved https://github.com/tendenci/tendenci/commit/256b08b4776fb250b475d50750f4634f1290dea8. Added a setting "Disable Gravatar". It can be turned on at /settings/module/users/#id_disablegravatar.
