### ISSUE TITLE
error installing on ubuntu 20.04

### ISSUE THREAD

**Issue by abobakr-ahmed** [tendenci/tendenci#1103]
followed instructions and getting error when deploying
when running:
```
python manage.py deploy
```
i receive the following error
```
ImportError: cannot import name 'getStringIO' from 'reportlab.lib.utils' (/srv/mysite/lib/python3.8/site-packages/reportlab/lib/utils.py)
```

**Comment by jennyq** [comment]
It has been resolved in the commit https://github.com/tendenci/tendenci/commit/265fc09115e8f51b7aa8621ee7c08e9472647bea. Will be pushed to PYPI with the next version bump.
