### ISSUE TITLE
New Install of Tendenci 14.04 - Ubuntu 20.04 LTS - Fails

### ISSUE THREAD

**Issue by W4JEW** [tendenci/tendenci#1107]
Hello,

I've been trying to follow the steps to build a server running Tendenci. I uncovered an issue yesterday that I was able to work past. Unfortunately, I'm unable to finish building the server. The documentation is very confusing and, as many times as I've reviewed it, I'm wondering when the last time the author actually went through the setup of a server from scratch by following the documentation.

While I am not well-versed in Django, I was able to build a Tendenci server based on a pre-14.x release without issues.

I'm sorry but this version of the documentation is an utter disaster!

This "Issue" is going to be lengthy....

I will break down a list of issues that I've uncovered below by section:

## Database Preparation

[https://tendenci.readthedocs.io/en/latest/installation/installation.html#database-preparation](https://tendenci.readthedocs.io/en/latest/installation/installation.html#database-preparation)

```
# switch to the "postgres" user assuming installation above went correctly
```

There's no guidance in terms of how to switch to the Postgres user - only an assumption that the administrator already knows how to do this.

I made a note from the previous (successful) attempt of installing Tendenci that said the option to switch to the postgres user was:

```
admin@ubuntu:~$ sudo -i -u postgres
postgres@ubuntu:~$
```

Moving on to the next section of how to create the database - there's some confusing statements about running commands as the 'postgres' user but then the commands are preceded with 'sudo' which is counterintuitive.

```
Next create your database still as the ‘postgres’ user:
```

Followed by a series of commands that begin with:

```
sudo -u postgres psql <COMMAND>
```

If the admin already switched to the postgres user context, why would they prepend 'sudo -u postgres' before every command? The user 'postgres' certainly isn't a member of /etc/sudoers, so either the documentation should remove any reference to running commands as the postgres user, or the commands should be modified to reflect running within the context of the postgres user.

## Virtualenv

This section also has some confusing steps.

[https://tendenci.readthedocs.io/en/latest/installation/installation.html#virtualenv-preparation](https://tendenci.readthedocs.io/en/latest/installation/installation.html#virtualenv-preparation)

In the 'Prepare a virtualenv for Tendenci' section, there are two parts that distinguish steps for Ubuntu 20.04 LTS and Ubuntu 18.04 LTS.

```
# whoami - make sure you are NOT "root". If so, type "exit" to back up one level.
sudo apt install virtualenv
sudo mkdir -p /srv
sudo chown "$(id -u -n)" /srv/
cd /srv/
# For Ubuntu 20.04 LTS
virtualenv mysite
# For Ubuntu 18.04 LTS
python3.8 -m virtualenv -p python3.8 mysite
sudo chown root /srv/
```

It is not clear as to whether or not the 'sudo chown root /srv/' is only needed for Ubuntu 18.04 LTS or if it applies to both versions. The way the text is formatted, it appears as though it only applies for Ubuntu 18.04 LTS, but it would seem logical that the step applies to both. Adding one more line that's commented out that shows if the command applies to one version, the other, or both versions would make that section easier to understand.

Additionally, the command 'virtualenv mysite' seems to denote the name of the Tendenci installation should literally be "mysite". I tried using a different name for the virtual environment, then when I got to the section on installing Tendenci and had to run the startproject command, I received an error for using a different name. The only way I was successful was using 'mysite' for both the virtualenv as well as for the startproject command (tendenci startproject mysite mysite).

Examples of how to create the virtual environment and multiple examples of what name(s) to use would make things a LOT clearer. I'm sure customers that are installing multiple instances of Tendenci on the same server would appreciate it.

Further down, there is a part that starts with:

"To prepare a virtualenv for Tendenci"

```
virtualenv -p venv
```
Wasn't this already done in the previous series of commands? Why are we creating yet another virtualenv? What is the point of this command?

Regardless - if I try to run that command, I get the following:

```
admin@ubuntu:~$ cd /srv/
admin@ubuntu:~$ virtualenv -p venv
RuntimeError: failed to find interpreter for Builtin discover of python_spec='venv'
```

So - what's supposed to happen here?

## Tendenci Configuration

OK - so there's comments about "For testing" and "the default should be sufficient". What about in cases where the installation goes beyond testing? Wouldn't it make sense to include examples of how to configure Tendenci for a non-dev/testing installation?

```
For live sites, set ALLOWED_HOSTS appropriately. For testing, the default should be sufficient.
```

I always love the term "appropriately". What's appropriate? What does the ALLOWED_HOSTS setting actually do?  Does it look at the Host header in the HTTP Request? 

And what happens if Nginx proxy is deployed in front of the Tendenci server (as is recommended)? Does that have any impact on the ALLOWED_HOSTS setting?

## Tendenci Installation

[https://tendenci.readthedocs.io/en/latest/installation/installation.html#tendenci-installation](https://tendenci.readthedocs.io/en/latest/installation/installation.html#tendenci-installation)

The last series of commands in this section - under "Install Tendenci and its dependencies"

```
cd /var/www/mysite/
pip install -r requirements/dev.txt --upgrade
```
The fact that the pip install points to the dev.txt implies that this is a development installation. However, there is another section further down that refers to how to install Tendenci in a development setting. So why would it be that we'd install the dependencies here?

## Things Get Ugly Fast!

From this point forward, the documentation is an utter disaster. Sorry - but that's the reality of my experience. I've burned hours trying to make sense of what's written here and not having much luck.

There are far too many assumptions made by the author in terms of the reader's level of knowledge.

I write a lot of technical documentation. 

When I work with others that need to write documentation, I tell them to pretend they know absolutely nothing about the product - to put themselves in the shoes of someone that never installed it before. 

Would they be successful in installing/configuring the product based on what's written? If not, then that needs to be fixed.

Whoever wrote the documentation needs to sit down and read the entire installation section of the guide from start to finish.

[https://tendenci.readthedocs.io/en/latest/installation/installation.html](https://tendenci.readthedocs.io/en/latest/installation/installation.html}

## Live Site Setup

Skipping to this section for a moment...

The entire section is:

```
This section covers additional recommended setup to prepare for running a live site.

You may want to check the Django documentation and PostgreSQL documentation for database configuration/tuning suggestions.
```

Where's the "additional recommended setup"? It's completely missing! Unless the sections below are meant to be inclusive of what the author wants to point out.

That's what we refer to as a "cop-out". Pointing someone to a MASSIVE library of third-party documentation without any recommendations of what to focus on is not something your readers are going to appreciate. I know I did not when I went to look.

## Stay Tuned

I have more to add - but this is plenty to start with. It's 3:40 AM EDT...I need to get some sleep! :-)

**Comment by jennyq** [comment]
Hi @W4JEW, 

Sorry to hear that you're experiencing some difficulties on tendenci installation. The installation guide hasn't been changed much since the initial release of T14 on December 15, 2021. We appreciate your time very much for submitting the issue!

We'll revisit the installation guide. In the meantime, you're welcome to submit pull requests to help us improve it.

**Comment by W4JEW** [comment]
I would love to contribute - but I cannot if I can't get it installed.
