### ISSUE TITLE
reCAPTCHA setup for more than one domain?

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#1121]
We've had our domain aeva.asn.au for a while, but we've just purchased aeva.au as well.
This has been set up so that both will point to the same website.  So both of these will work:
aeva.asn.au/contact
aeva.au/contact

We've just used this for the first time, to advertise an event with a shorter URL.  But we've found that you can't register for the event if you go in through the shorter URL, as the reCAPTCHA doesn't work.
So I registered aeva.au in reCAPTCHA and received new site keys.
Our existing keys are in  conf/settings.py as per this guide:  https://www.tendenci.com/help-files/how-use-google-recaptcha-tendenci-site/
Is there a way that we can add both sets of keys?

**Comment by jennyq** [comment]
Hi @CWalkden ,

Instead of two sets of keys, you can tie multiple domains to a set of keys.

Just go to your Google recaptcha admin console for the site aeva.asn.au, click the Settings icon,  under the "Domains", you can add your other site aeva.au.

**Comment by CWalkden** [comment]
> Just go to your Google recaptcha admin console for the site aeva.asn.au, click the Settings icon, under the "Domains", you can add your other site aeva.au.

Thank you - this worked!
