### ISSUE TITLE
Changing an individual away from a Corporate Membership isn't working correctly

### ISSUE THREAD

**Issue by JustinLewisSMA** [tendenci/tendenci#1123]
We have a member who was part of a corporate membership.

We went into the backend admin area and changed the membership to an individual membership type.

If you go to the individual's profile, they're no longer showing any attachment to the corporate membership, but if you look up the corporate member, the individual is still there. How do we fully detach an individual?

**Comment by jennyq** [comment]
Hi Justin,

When you edit at the admin backend, make sure the Corporate Membership field is deselected, then edit again at front end. It should completely remove the attachment. 

However, to preserve the history, it probably would be better to expire the corp individual then sign up a new membership..
