### ISSUE TITLE
reCAPTCHA Errors/Information Request

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#1125]
Tendenci V14.2
reCAPTCHA V3

We occasionally get people complaining that they get reCAPTCHA errors:
![image](https://user-images.githubusercontent.com/64681720/183772847-a07f8dd5-e417-4d0a-b8c8-2abfde242f95.png)
They try again (as per the error message) and get the same result.  This is frustrating for them, as they say 'but there was no reCAPTCHA question!'.

My standard response is to ask them to:
- Try again later.
- Try another device.
- Try another browser.
- Clear the cache.

As far as I can tell, most people get it to work with one of the first two options.
We have recently changed the reCAPTCHA threshold so that it is very lenient (0.2) - but we are still getting false captchas.

I'm wondering how I can help these people.  Here are a couple of thoughts:
- Is there a log somewhere that we can check to give us more information on these events?  We have overall stats through the reCAPTCHA interface, but it would be good if we had the information that was on the form at the time of submission, tied to a particular time/date and perhaps the browser/device in use.
- Can we alter the error message to include some or all of the above points?  And possibly remove the prominent use of the word 'reCAPTCHA'.  Some people half-know about this term, and it gives them the wrong idea that they have failed in some test.

**Comment by jennyq** [comment]
Resolved https://github.com/tendenci/tendenci/commit/ca6136fd0f8054bae516381b16f741724d707cb0
