### ISSUE TITLE
Events page not showing calendar link

### ISSUE THREAD

**Issue by WessleyKoop** [tendenci/tendenci#1129]
The default code for viewing of events does not show people who are not, logged in, the link to add the event to their calendar or print a paper copy of the event.

For our website  http://aeva.asn.au I have changed line 13 in the events/meta.html template from;
{% if user.is_authenticated %}
 to
[% if user %}

Given that the rest of the code is well written this only gives users not, logged in, access to print and add the event to their calendar.

Regards
Wessley Koop
Volunteer HTML coder for the AEVA

**Comment by jennyq** [comment]
Good point. Thanks @WessleyKoop ! I've updated it. https://github.com/tendenci/tendenci/commit/0d31e6314594dfd24a79d757d3d181e074299e14
