### ISSUE TITLE
Can localize field label of custom forms?

### ISSUE THREAD

**Issue by Pandaski** [tendenci/tendenci#1133]
I noticed the label of a custom form (added through `/admin/forms/form/add/`) would not be translated in the form's view when the user switches languages. Is it an expected behavior or something I missed? Thanks.

**Comment by jennyq** [comment]
@Pandaski, That is an expected behavior. Everything entered by users or site admins will not be translated.

**Comment by Pandaski** [comment]
got it. thanks.
