### ISSUE TITLE
Frequent error in error log

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#1155]
In our Test server, where we have debugging turned on in the Django settings, we're getting this error quite a bit in our logs:

Traceback (most recent call last):
  File "/srv/tendenci_test/environment.py-3.8/lib/python3.8/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "/srv/tendenci_test/environment.py-3.8/lib/python3.8/site-packages/django/forms/forms.py", line 155, in _getitem_
    raise KeyError(
KeyError: "Key 'registration' not found in 'EventSearchForm'. Choices are: end_dt, event_group, event_place_type, event_type, national_only, q, search_category, start_dt."

Here's what I assume is the offending code from the HTML template: templates/events/search-form.html

{% if form.registration %}  
<div class="row">
  <div class="col-sm-12 form-group">
        <div class="checkbox">
          <label>
            {{ form.registration }} {{ form.registration.label }}
          </label>
       </div>
    </div>
</div>
{% endif %} 

We haven't customised this template.

**Comment by jennyq** [comment]
Non-existent variables will be interpreted as '' (an empty string) or None for the if template tag in django templates https://docs.djangoproject.com/en/3.2/ref/templates/api/#how-invalid-variables-are-handled. So this type of errors can be safely ignored. You can disable app_log by setting disable_app_log() in your conf/settings.py. 

However, to get rid of this error, we can update the template by chaning `{% if  form.registration %}` to
{% if request.user.is_authenticated and form.registration %}.
