### ISSUE TITLE
No directory listings displayed at /directories/ unless you search

### ISSUE THREAD

**Issue by BenSturmfels** [tendenci/tendenci#1157]
Hi Folks,

After enabling the Directories app under directory settings and adding a directory, when I select "All directories" from my my admin menu at the top (/directories/), I see no directories. Only after I hit "search" does one show up. I would have expected to see all directory listings by default, and would probably assume that there were none. Am I missing something? Happy to look at making a code change if that seemed useful.

Thanks for your continued hard work on the platform!

**Comment by jennyq** [comment]
Hi @BenSturmfels,

There is a setting "Display Search Results Without Search" /settings/module/directories/#id_showresultswithoutsearch that controls that behavior. By default, this setting is set to "true", which means you'll see all directory listings without search. Did you or somebody else on your team turn it off by any chance?

**Comment by BenSturmfels** [comment]
Thanks @jennyq. It appears we don't even have that setting listed at `/settings/module/directories/`. After some hunting it looks as though this is a record missing from the `site_settings_setting` table. (It also looks like we have a bunch of junk records in that table with names like "label" and "enabled". Probably not an issue in practise.) I see there is a management command called `update_settings`. Running this in my development environment seems to add the `showresultswithoutsearch` setting, but not as far as I can see does not modify other settings - is that how this management command works? (ie. it's safe to run on an existing site)

**Comment by jennyq** [comment]
@BenSturmfels, Yes, it's safe to run on an existing site. That `update_setting` command is included in the command `python manage.py deploy` which should be run when you do a tendenci update https://tendenci.readthedocs.io/en/latest/upgrade/point-update.html.

**Comment by BenSturmfels** [comment]
Thanks Jenny, we'd overlooked that command in our upgrade process. Much appreciated!
