### ISSUE TITLE
pip install tendenci --upgrade fails on Ubuntu 22.04.2 LTS

### ISSUE THREAD

**Issue by fhummelgren** [tendenci/tendenci#1169]
Trying to install Tendenci on Ubuntu 22.04.2 fails:

`pip install tendenci --upgrade`

_INFO: pip is looking at multiple versions of tendenci to determine which version is compatible with other requirements. This could take a while.
Collecting tendenci
  Using cached tendenci-14.3.5-py3-none-any.whl (48.5 MB)
  Using cached tendenci-14.3.4-py3-none-any.whl (48.5 MB)
  Using cached tendenci-14.3.3-py3-none-any.whl (48.5 MB)
  Using cached tendenci-14.3.2-py3-none-any.whl (48.4 MB)
  Using cached tendenci-14.3.1-py3-none-any.whl (48.4 MB)
  Using cached tendenci-14.3-py3-none-any.whl (48.4 MB)
  Using cached tendenci-14.2-py3-none-any.whl (48.4 MB)
INFO: pip is looking at multiple versions of tendenci to determine which version is compatible with other requirements. This could take a while.
  Using cached tendenci-14.1.1-py3-none-any.whl (48.4 MB)
  Using cached tendenci-14.1-py3-none-any.whl (48.4 MB)
  Using cached tendenci-14.0.4-py3-none-any.whl (50.9 MB)
  Using cached tendenci-14.0.3-py3-none-any.whl (50.9 MB)
  Using cached tendenci-14.0.2-py3-none-any.whl (50.9 MB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached tendenci-14.0.1-py3-none-any.whl (50.9 MB)
  Using cached tendenci-14.0-py3-none-any.whl (50.8 MB)
  Using cached tendenci-12.5.11-py3-none-any.whl (48.1 MB)
Collecting Django<3.0,>=2.2.24 (from tendenci)
  Using cached Django-2.2.28-py3-none-any.whl (7.5 MB)
Collecting tendenci
  Using cached tendenci-12.5.10-py3-none-any.whl (48.1 MB)
  Using cached tendenci-12.5.9-py3-none-any.whl (48.1 MB)_

If you force to install latest version the following error appears:

ERROR: Could not find a version that satisfies the requirement pisa (from tendenci) (from versions: none)
ERROR: No matching distribution found for pisa

**Comment by jennyq** [comment]
Resolved in the latest tendenci version 14.4. Please try again.

**Comment by fhummelgren** [comment]
Thank you so much! Confirming that it works in latest version again.
