### ISSUE TITLE
Having trouble sending email via Contact Form

### ISSUE THREAD

**Issue by lashirley21** [tendenci/tendenci#1175]
Jenny or Community - Posting this question on behalf of a contact form we received hoping Micheal Reeves joins and finds a solution. 

"I am the administrator for www.isc2boulderchapter.org and am having trouble with Tendenci provided functionality. For example, the Contact Us page (https://isc2boulderchapter.org /contact/) does not seem to send any emails. The theme selection functionality seems to be broken as the bootstrap file (bootstrap.min.css) is inaccessible. And I am unable to determine what list the \u201cJoin our Mailing List\u201d button controls. Any assistance you can provide would be very appreciated.

**Comment by jennyq** [comment]
Hi Micheal,

Have you set up the settings for the emails? Do you have a SPF TXT record set up in DNS? If so, please test if the password reset email work. If the email is set up correctly, then check if there is any email address entered in the "Send copies to:" field for the contact form at admin backend /admin/forms/form/1/change/. If everything is in place but you still don't receive emails, please check if went to spam folder ...

The theme selection functionality has been removed in the latest version of tendenci.

**Comment by rurinix** [comment]
The last comment baffles me.  If theme selection functionality has been removed and the underlining bootstrap css file is no longer accessible to me, how do I update the look-and-feel of the site?

**Comment by jennyq** [comment]
@rurinix, You can't switch themes, but you should be able to update the look-and-feel on your current theme, right?

**Comment by rurinix** [comment]
> @rurinix, You can't switch themes, but you should be able to update the look-and-feel on your current theme, right?

Considering much of the theme is coming from the bootstrap.min.css file that I don’t seem to have access with, I don’t see how.  The only work-around is know is poor coding practice, such as relying on the !important keyword.

**Comment by jennyq** [comment]
The `bootstrap.min.css` should be already included in the base.html. If not, you can add it to your base.html. https://github.com/tendenci/tendenci/blob/master/tendenci/themes/t7-base/templates/base.html#L38

**Comment by rurinix** [comment]
@jennyq we seem to be talking past each other.  The bootstrap.min.css is linked in my base.html.  That is setting many overarching look-and-feel settings.  I do not have access to the bootstrap.min.css file in order to do things like change color values.  Because of CSS priority definitions, making those changes in the .css file that I do have access to does not work.  The only work-around is to use keywords like !important to override CSS priorities, which is poor coding practice since it forces nonconformity with the protocol.

**Comment by jennyq** [comment]
Oh, I see what you meant now. So you want to edit the file `bootstrap.min.css` directly, right? I'd say you shouldn't do that. Reasons: 1) The minified version of bootstrap.css is not easy to edit. 2) When bootstrap is updated to a newer version, you'd need to go in there and do it all over again. 

You should be able to make those changes in the css file you have access. You might need to use !important to override some styles occasionally, but most of the time, you can simply override by specifying some IDs and/or classes. For more on "Specificity", please check out https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance#specificity_2

**Comment by rurinix** [comment]
I think I found the problem but still don't know the solution.  I have found the following error message when trying to send a newsletter:

Email relay is not configured properly.

Where are the email relay settings?

**Comment by jennyq** [comment]
Newsletter relies on a separate set of settings. Check this out https://tendenci.readthedocs.io/en/latest/testing/post-install-checklist.html#basic-functionality-testing

For the rest of email notifications including the contact form is based on the regular email settings. Do you have those set up in your conf/settings.py?

    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_USE_TLS = True
    EMAIL_HOST = 'your-email-host'
    EMAIL_PORT = 'your-email-port'
    EMAIL_HOST_USER = 'your-email-user'
    EMAIL_HOST_PASSWORD = 'your-email-password'

**Comment by jennyq** [comment]
Sorry, I assumed you knew that file if you installed your site. The `conf/settings.py` file is located in your site directory, not accessible from your website. Do you have the access to your server? Some settings belong to there instead of the "Settings" page, because they either need high level of security or have to be loaded on site start.

**Comment by rurinix** [comment]
Thank you!  You have identified the missing piece I have been trying to figure out.  The site was already in place when I came onboard and was only given web-access.  I assumed this was a SaaS solution or something and that everything was on the web interface, being the first time to use Tendenci.  Now that I know this, I think I know where to go to resolve back-end configurations (like you described above).  This helped a ton! Thanks again.

**Comment by jennyq** [comment]
You're welcome! Glad it helped. 
Since you're new to Tendenci, you might want to check out Tendenci doc on read the docs https://tendenci.readthedocs.io/en/latest/.

**Comment by lashirley21** [comment]
Awesome!
