### ISSUE TITLE
Author can't see their own News item

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#1176]
If a user creates a new News item, and puts a release date into the future, when they save it they then can't see it until the release date.  This means that an author can't see or edit their own News item, unless they are an administrator.
It would be useful if an author could edit their news item before the release date, in case they made any mistakes!
This also applies to members of groups with edit access (via the Advanced Permissions) on the News item.
It probably also applies to Stories, although I haven't tried them.

**Comment by jennyq** [comment]
Fixed https://github.com/tendenci/tendenci/commit/15275448cf7a0da9d96c09a0e1492ce757796a6f. Thanks @CWalkden !

**Comment by CWalkden** [comment]
I assume that this fix is not yet released?  I had a user complain about it the other day.

**Comment by jennyq** [comment]
It is fixed. What tendenci version are you on?

**Comment by CWalkden** [comment]
We're using version 14.5.1.
Symptom is exactly the same.  A non-administrator makes a News item with a release date in the future.  They save the item and then can't see it in the list of News items (/news).

**Comment by CWalkden** [comment]
> That's right - non-admins can only see released news from the list view. But they can access their own news if they have the links. On their profiles, there is a "Contributions" section, they can access from there.

Ah, I see.  
They might work that out if they are particularly switched on, or if they use the News module a lot, but this doesn't describe most of my users, including me. :) 
Any chance of making it visible in the list view?

**Comment by lashirley21** [comment]
CWalkden, 
I am sure Jenny can suggest a good approach/workaround for you. You can even maybe leverage groups and permissions. I just wanted to share this very important part: Tendenci takes security and privacy very seriously and this is good news. A user is a user is a user. Tendenci was built under the Django Framework, please read https://realpython.com/manage-users-in-django-admin/.

**Comment by CWalkden** [comment]
> I'd suggest to create another news list just for the news owners, so that you can check a list of news that you added and/or edited.

We probably have about 20 people who can post News, but they don't do so very often.  They probably average about one News item every six months.  And they would rarely schedule News for the future.  
I don't think that a special list would help them, as they wouldn't know that it existed.  If we had to train them to find the list, we might as well train them to look at their 'Contributions', as mentioned above.

This reminds me of another complaint that people have mentioned.  It happens because our members are in different timezones.  Someone will create a News item with a release date of 'now', but they don't notice that the timezone is not correct for them.  So they save the News and it doesn't appear, because they've accidentally scheduled a future release date.
Could we perhaps fix both these problems with some extra text on the News Add form?
![image](https://github.com/tendenci/tendenci/assets/64681720/84f856a2-e4d9-47dc-9d04-1a975f256a55)

Is is possible to put some text below the Release Date, which only appears if the Release Date is calculated to be in the future?  Something like this:
**"The Release Date is in the future.  This News item will not appear on the list view until the Release Date.  To view/edit your News item before it is released, access it directly via this URL: XXXXXXXXXX"**
The URL would be taken from the URL field at the top of the form.

**Comment by jennyq** [comment]
@CWalkden, I've figured it out that the real issue is **not** they (creators or owners) cannot view but they can't **search** their own items. Fixed https://github.com/tendenci/tendenci/commit/0c9e279da77cf8d7c9867752d2278e5883bf4dfa.

**Comment by CWalkden** [comment]
Hi @jennyq,
I just tested this in Tendenci 14.8.1, and the problem persists.
Here is a News item as seen by an Administrator:
![image](https://github.com/tendenci/tendenci/assets/64681720/4d573b91-adca-44dd-9cc7-5844f8ce0b43)

Note the release date is in the future.
The author of this News item, who is not an administrator, cannot find this News item via this search page.
![image](https://github.com/tendenci/tendenci/assets/64681720/5b98fed4-07ae-41b2-aa5a-1fc4a5a9fe23)
