### ISSUE TITLE
It is possible to add regions to the membership reports?

### ISSUE THREAD

**Issue by jalovick** [tendenci/tendenci#1200]
Hi,

We would like to add charts for our various membership levels to Tendenci covering each region. Is it possible to add an option to show the totals as is available now, and a dropdown to also select per-region?

Thanks

Jamie

**Comment by jennyq** [comment]
Hi Jamie, 

Yes, it's possible. Which membership reports were you referring to?

**Comment by jalovick** [comment]
Hi,

Any of the report with existing charts, and any others that don't require going into explorer:
- /memberships/reports/overview/
- /memberships/reports/members_stats/
- /memberships/reports/member_quick_list/ (adding membership number, status, and Email would be useful on this report as well, similar to the active membership report)
- /memberships/reports/active_members/
- /memberships/reports/renewed_members/
- /memberships/reports/expired_members/
- /memberships/reports/members_in_renewal_period/
- /memberships/reports/members_in_grace_period/
- /memberships/reports/members_over_time/
- /memberships/reports/active_members_ytd/
- /memberships/reports/members_ytd_type/
- /memberships/reports/join_summary
- /invoices/report/overview/
- /memberships/reports/members_donated/ (adding the fact they donated may be a useful flag for the member list reports)

There are probably a few more reports that it's worth adding it, particularly the corporate ones (we don't currently use that feature), but basically anything that lists users or stats on users, it would be good to filter by region.

Thanks

Jamie

**Comment by rob-hills** [comment]
@jennyq I'd be happy to have a crack at this if you could give me some pointers.  Maybe an example of something similar and which template and/or python file(s) contain the logic for the example?

TIA,

Rob

**Comment by rob-hills** [comment]
> Hi @rob-hills, Thank you for pitching in. I'll create an example when I get the chance.

Thanks @jennyq , I don't necessarily think I need you to create an example.  What I believe I need is just an overview of which program and template files make up a report and how they interact.

If you were to just pick one of the reports that Jamie listed above and list the template(s) and python files that are required to generate the content, hopefully I can build from there.  I understand the MVC concepts behind Django, I'm just struggling to find which elements are behind a specific report.

**Comment by jennyq** [comment]
@rob-hills, 

Take /memberships/reports/overview/ for an example, First, you'd locate the view from apps/memberships/urls.py, which is `memberships_overview` https://github.com/tendenci/tendenci/blob/master/tendenci/apps/memberships/views.py#L2799. In the view, you'll see the `template_name='reports/overview.html'`. The physical location of that template is at https://github.com/tendenci/tendenci/blob/master/tendenci/themes/t7-base/templates/reports/overview.html. You can then add a form with the region field to it. The choices of the region field should get from the Region's table. Not sure if this helps. Feel free to let me know what else you need.

**Comment by rob-hills** [comment]
Thank you @jennyq , I think that's likely all I'll need.  I'll check it out and let you know if I encounter any roadblocks

**Comment by rob-hills** [comment]
I've done some preliminary work on this in a branch on my fork of the main Tendenci code:
[https://github.com/rob-hills/tendenci/tree/report_overview_by_region](https://github.com/rob-hills/tendenci/tree/report_overview_by_region)

I'm now awaiting @jalovick 's review of the interface and functionality before I clean things up and then apply to other reports he's listed.

**Comment by jalovick** [comment]
Hi Rob,

Thanks for your work on this. I'll be checking over it later this week.

Happy New Year!

Jamie

**Comment by rob-hills** [comment]
Hi Jamie,

Happy New Year to you as well!  The interface/functionality change is very subtle at present so shouldn't take long to check out.  I've modified one report only so far to include a "Select a Region" field to enable the report to be filtered by that region:
[https://test.aeva.asn.au/memberships/reports/member_quick_list/](https://test.aeva.asn.au/memberships/reports/member_quick_list/).

If this is what you had in mind, I can apply the same concept to most if not all the other reports you've listed [above](https://github.com/tendenci/tendenci/issues/1200#issuecomment-1678579270)

Rob

**Comment by jalovick** [comment]
Hi,

Yes, the drop down and auto-refresh works well, thank you.

Jamie

**Comment by rob-hills** [comment]
Pull request #1247 created and awaiting review
