### ISSUE TITLE
"'FreeTypeFont' object has no attribute 'getsize'" at /captcha/image/.../ with Pillow 10.1.0

### ISSUE THREAD

**Issue by BenSturmfels** [tendenci/tendenci#1240]
I just updated to Tendenci 14.8 and started getting the following error:

```
Internal Server Error: /captcha/image/d4c8471160e689b7cc05c93c20eddaf75d65446e/

AttributeError at /captcha/image/d4c8471160e689b7cc05c93c20eddaf75d65446e/
'FreeTypeFont' object has no attribute 'getsize'
```

This appears to caused by Pillow 10.1.0 remove the `getsize` method. Downgrading to 9.5.0 (the newest version < 10) resolved this for me.

**Comment by jennyq** [comment]
Thanks @BenSturmfels! Resolved by updating the django-simple-captcha from 0.5.14 to 0.5.20 https://github.com/tendenci/tendenci/commit/ea0017c769baf3585edf4bc549d883a17e14ba6d

**Comment by BenSturmfels** [comment]
Thanks @jennyq!
