### ISSUE TITLE
Form doesn't request payment

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#1244]
Our Form has changed operation since the upgrade to Tendenci 14.8.
Here is the form: [https://aeva.asn.au/forms/ev-licence-plate-tag/](url)
When you fill in this form and press the Submit button, it used to go to a page which would ask for payment.  It now goes directly to the /sent/ page.  It does generate an invoice, but does not present this to the user.
![image](https://github.com/tendenci/tendenci/assets/64681720/2fcfaf37-3cd6-4fc8-994f-9f31d241a5b8)

In the meantime, I'll go into each invoice that has been generated and send them to the users.

**Comment by jennyq** [comment]
It's been resolved https://github.com/tendenci/tendenci/commit/12bfcc767f18ccf7a302e668612f30a8df975285.  Thanks @CWalkden !
