### ISSUE TITLE
Pending memberships don't expire

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#1246]
We have a large number of membership records in our database with the status 'pending'.
Some of these are people (possibly bots) who have filled out the membership form, generated an invoice, and never paid the invoice.  The system generates a membership record in the state of pending.

We have ignored these records up until now, just left them there pending.
I've noticed that some of these are quite old, and it can make it confusing when looking at the records, either individually or in reports.  Would it be possible, or appropriate, for these pending 'memberships' to expire automatically?  Perhaps if an invoice is unpaid for 2 months it should automatically void itself, and delete the associated membership?

**Comment by jennyq** [comment]
If they're not real people joining memberships, I think you should just delete them. It's easy to bulk delete them at admin backend. Expiring them automatically might result some bad reports. Also, you don't want to send renewal reminders to those spammers.

**Comment by CWalkden** [comment]
> If they're not real people joining memberships, I think you should just delete them. It's easy to bulk delete them at admin backend. Expiring them automatically might result some bad reports. Also, you don't want to send renewal reminders to those spammers.

To be honest we don't know if any of these are bots, it's just that we get some applicants who give an overseas address and then don't pay the invoice.  Our organisation doesn't really benefit people from outside Australia, so we don't expect international members.  We get many more Australian people who do the same thing, so the vast majority of these are probably real people who don't go through with the process.  Some then do go on and create a membership later, but the Pending one still sits there.
I went through and deleted all of the Pending memberships, there were probably a couple of hundred.  The process I used was:

- Go to /admin/memberships/ and sort the list by Status.  This puts Pending memberships at the top.
- The page has a column for invoice, and that is hyperlinked.  Open the invoice associated with the Pending membership.
- Void the invoice, and tick the tickbox that says "Delete the corresponding memberships".

I would be very interested if there is a way to do this in bulk.  I found that I couldn't delete the membership if there was an invoice, so I had to do the invoice first.

**Comment by jennyq** [comment]
You can filter by status detail and select pending, which will show all pending memberships.
![image](https://github.com/tendenci/tendenci/assets/106448/797b39e8-ea77-49ec-9121-285e0dce1def)

If you don't already know how to bulk delete pending memberships, here are the steps: 1) click the checkbox in front of the memberships you want to delete, 2) select "Delete selected Memberships" from the Action dropdown, 3) click "Go". 4) On the confirmation page, click "Yes, I'm sure" to confirm deletion. 
![image](https://github.com/tendenci/tendenci/assets/106448/b887bf4a-b838-4ee2-91f5-49db86db0372)

**Comment by CWalkden** [comment]
> If you don't already know how to bulk delete pending memberships, here are the steps: 1) click the checkbox in front of the memberships you want to delete, 2) select "Delete selected Memberships" from the Action dropdown, 3) click "Go". 4) On the confirmation page, click "Yes, I'm sure" to confirm deletion. 

Oh, I see!
I just tried this (on our test server, which still has lots of Pending memberships), and it worked!
I thought that we couldn't do this with memberships if there was an active invoice.  But I was wrong, I may have been mixed up with Users.
This still leaves us with a bunch of unpaid invoices, but that may be ok.
