### ISSUE TITLE
Purchase Recordings & Materials - doesn't work

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#1256]
I like the idea of this feature, a button on our past Webinar to let people purchase the recording:
![image](https://github.com/tendenci/tendenci/assets/64681720/e328d2bf-99bc-4c94-b3a0-7ab63cd7e91a)
You can see the event here:  [https://aeva.asn.au/events/641/](url)
But the button doesn't work.
I enabled it for a free pricing (members only) and a non-free pricing (non-members).  Each have their own problems:

If logged-in member clicks the button, they are able to choose a pricing:
![image](https://github.com/tendenci/tendenci/assets/64681720/951ced21-bdf6-4565-9963-7e998c354ac4)

But when they press the Submit button, they are taken to an invoice ($0).  That is all, they don't get a registration email and they don't appear to be registered.  I was hoping that they would get a registration email, and so I put a link to the recording in that email.

If someone who is not logged in presses the button, they are asked to log in.  This is not the desired behaviour.

**Comment by jennyq** [comment]
This feature was to fulfill the request for a client site that connects with higher logic. Essentially, it pushes the user record to the corresponding community (for them to access the event assets there) once the payment is received. 

For other sites, if you want to use this feature, admin would need to manually send the event assets to those who purchased. You can also view a list of assets purchases at admin backend at /admin/events/assetspurchase/.
