### ISSUE TITLE
Recurring Event not available from Template

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#1257]
If I create a new Event from scratch, I get a box "Is Recurring?".
But this box is not there if I create an Event from a Template.  
The box is not there if I edit an event created earlier.
The box is not there if I create an event via "Clone Event".

Is there scope to make this more widely available?

**Comment by jennyq** [comment]
Yes, the "Is Recurring?" only available on event add due to the complex nature of recurring events. We currently don't have the plan to make it available to event edit and clone.
