### ISSUE TITLE
Cloned Event not visible on Calendar

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#1261]
A user cloned an existing Event.  The new Event (called "Devonport - Know your EV Workshop") appears in the list view:
![image](https://github.com/tendenci/tendenci/assets/64681720/e97aefc5-e02f-41db-9f28-a8c0289b10b9)

It is listed here with another event on the same day, which shows that we have the date correct.
But it doesn't appear on the calendar:
![image](https://github.com/tendenci/tendenci/assets/64681720/79ae856f-62c9-4856-8461-89756320123a)

Note that the Event is Active and Public.  Anyone can see it in the list view, and nobody (not even an administrator) can see it on the calendar view.
What's happening here?  Is there a setting that can stop an Event being shown on the calendar?

**Comment by jennyq** [comment]
Hmm, I can't replicate the issue. 

Please check if you have "Enable Private URL" checked for that event.
![image](https://github.com/tendenci/tendenci/assets/106448/684a551f-ac0c-4002-a041-7f7a099e0d80)

**Comment by CWalkden** [comment]
> Hmm, I can't replicate the issue.
> 
> Please check if you have "Enable Private URL" checked for that event. ![image](https://private-user-images.githubusercontent.com/106448/315596360-684a551f-ac0c-4002-a041-7f7a099e0d80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwODI3NDYsIm5iZiI6MTcxMTA4MjQ0NiwicGF0aCI6Ii8xMDY0NDgvMzE1NTk2MzYwLTY4NGE1NTFmLWFjMGMtNDAwMi1hMDQxLTdmN2EwOTllMGQ4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQwNDQwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzY2MWIyNThiNTk3NmM4ZGZiNDcyNDcyNjY1ZDNkMmIyYTYyY2JkMWZiNmYwYjk0ZDkwZjljNjQwOTg5NmY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cD_3XP_IOw__csshRykUVKTdedb4OZn7izp7a9gzwVU)

Where is this setting?
I can't find it when I edit the event, and I can't find it if I create a new one.

**Comment by jennyq** [comment]
@CWalkden, It's on event edit. Click " Show Advanced Permissions", you'll find it under the "Group Permissions".

**Comment by CWalkden** [comment]
> @CWalkden, It's on event edit. Click " Show Advanced Permissions", you'll find it under the "Group Permissions".

Ok, I see it.
No, it is not ticked.  I ticked, saved, unticked, saved, and all is still as before.

**Comment by CWalkden** [comment]
I figured it out!
It was this checkbox:
![image](https://github.com/tendenci/tendenci/assets/64681720/397296cb-d07a-4d67-b4b5-f71a2456a8bf)

The new date was on a weekend.
Odd that the weekend date was allowed, when that checkbox was ticked.
