### ISSUE TITLE
Newsletter Dates missing Data Validation

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#1262]
If you add a Newsletter you can choose dates that don't exist:
![image](https://github.com/tendenci/tendenci/assets/64681720/e0778e7c-00f2-49d3-8355-700679d9b076)

The 31st of April is not a valid date.
You are still able to press "Continue", but are unable to go to the next step.  There is no feedback as to why you can't go the next step, which is rather confusing!
Solutions to this problem include:
- Show an error message to say you have an invalid date.
- Change the way that dates are chosen, so that invalid dates are not possible.  This might also fix [Issue 1078](https://github.com/tendenci/tendenci/issues/1078).

**Comment by jennyq** [comment]
@CWalkden, Did you not see the error message like this?

![image](https://github.com/tendenci/tendenci/assets/106448/e0f3e061-8873-41f4-8262-81574d017fe6)

**Comment by CWalkden** [comment]
No error message, no.
Here is a screenshot of the same place on the form, after I've pressed the Continue button:
![image](https://github.com/tendenci/tendenci/assets/64681720/de84783d-3cbe-4ca3-a932-84557c998e1b)

**Comment by jennyq** [comment]
Check if you have the template "newsletters/add.html" pulled down to your site?

**Comment by CWalkden** [comment]
> Check if you have the template "newsletters/add.html" pulled down to your site?

This was it!
We found this template, applied the changes and it now works as it is supposed to.  Thanks!
