### ISSUE TITLE
Outdated Font Awesome

### ISSUE THREAD

**Issue by b-davies24** [tendenci/tendenci#1267]
tendenci/themes/t7-tendenci2020/media/font-awesome → The version of Font Awesome is now outdated, thus some of the logos (e.g. Twitter/X, YouTube) are old.

Could this please be updated, or is there another solution that we should use ourselves?

**Comment by jennyq** [comment]
@b-davies24, 
Thanks for pointing it out! I agree it needs to be updated. We'll work on it.

**Comment by jennyq** [comment]
Updated. https://github.com/tendenci/tendenci/commit/ab69c2c910cda8fdeb65095e55cddcbb8dee14f7 https://github.com/tendenci/tendenci/commit/0219af9b0cfdd380f4368d990d4443e6a7f0c293

Once that update is deployed to your site, your base.html will need to be updated.
Replace:
 
    <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.css' %}" type="text/css">

with 

     <link rel="stylesheet" href="{% static 'font-awesome/css/fontawesome.min.css' %}" type="text/css">
     <link rel="stylesheet" href="{% static 'font-awesome/css/brands.min.css' %}" type="text/css">
     <link rel="stylesheet" href="{% static 'font-awesome/css/solid.min.css' %}" type="text/css">
    
    <link href="{% static 'font-awesome/css/v4-shims.min.css' %}" rel="stylesheet" />
    <link href="{% static 'font-awesome/css/v4-font-face.min.css' %}" rel="stylesheet" /> 

Then, the font-awesome/ directory in your theme media/ directory can be removed.
