### ISSUE TITLE
Filtering News by tag does not work properly

### ISSUE THREAD

**Issue by b-davies24** [tendenci/tendenci#1272]
I recently went through numerous (>10) News articles and edited them to tag them with 'Media Release'. Now when I filter by tag 'Media Release' (i.e. /news/?q=tag:media release), only the latest News shows up: 

![image](https://github.com/tendenci/tendenci/assets/156738991/ee3c9165-b774-4610-93da-9ee6a7fff8c9)

This was the only News that was tagged with 'Media Release' while being created - the rest were edited to have the tag 'Media Release'.

**Comment by jennyq** [comment]
@b-davies24,
Please check if you have cron job set up for `process_unindexed`. https://tendenci.readthedocs.io/en/latest/installation/installation.html#cron-setup

If that is already set up, run the management command `python manage.py update_index` to see if it fixes the issue.

**Comment by rob-hills** [comment]
@jennyq I've checked and yes we have a cron job set up for porcess_unindexed, running every six hours as suggested in the docs you linked above.
