### ISSUE TITLE
Company Name on Invoices

### ISSUE THREAD

**Issue by WessleyKoop** [tendenci/tendenci#1277]
Can we add the company name to the invoicing script.
I have had a look at the code and I can't figure out how to pull the company name into the invoicing pages.  
Any help would be greatly appreciated.
Thanks in advance.

**Comment by jennyq** [comment]
You can pull down the template `invoices/view.html`, then  add `{{ SITE_GLOBAL_SITEDISPLAYNAME }}` right above the address https://github.com/tendenci/tendenci/blob/main/tendenci/themes/t7-base/templates/invoices/view.html#L20

**Comment by WessleyKoop** [comment]
Hi Jenny,

Not our company name, the members company name.
When we get a Business member signing up, we would like their company name above there member name.

Thanks for the quick reply.

**Comment by WessleyKoop** [comment]
Thank you Jenny.
That worked.
