### ISSUE TITLE
Unable to upload images with Tendenci 15.0

### ISSUE THREAD

**Issue by bje-** [tendenci/tendenci#1278]
Trying to upload a PNG image with Tendenci's image uploader, I see the attached error message.

![image](https://github.com/tendenci/tendenci/assets/4327840/a4c5e38d-e96a-4a65-835b-3ce2dca8bb7f)

**Comment by CWalkden** [comment]
I get this too.
Tendenci 15.0, Firefox.
I was doing this in an Event:
- Open TinyMCE
- Insert/edit image
- Browse Files
- Upload
- Select Images
- Choose an image from my HDD
- Upload
I get the same error message: "App label is required.. Model name is required."

**Comment by b-davies24** [comment]
@jennyq We are getting complaints from users about this problem. Are there any fixes that we can apply?

**Comment by rob-hills** [comment]
@jennyq  a similar sounding bug was fixed for the release of [version 12.5.2](https://github.com/tendenci/tendenci/blob/main/CHANGELOG.md#1252-2021-06-02).  I wonder if this is a regression issue?

**Comment by bje-** [comment]
Note that it works fine to upload the image as file with the File tool. It's only the Image Gallery that is the problem.

**Comment by rob-hills** [comment]
I've hunted through the issues reported as closed in the months leading up to the release of Version 12.5.2 but I can't find any issue that obviously refers to the "Error App label is required..." message mentioned in the Changelog

**Comment by rob-hills** [comment]
I've spent some time tonight trying to capture a traceback for this error.  While I can trigger the error easily enough in the interface, I can't find any Exception or traceback that is obviously connected to it.

**Comment by rob-hills** [comment]
Many thanks for this @jennyq my testing tonight on our test server seems to confirm that this has been fixed.
Hopefully version 15.1 won't be far away so we can get this fix onto our production server.
