### ISSUE TITLE
ICS files not showing events without an 'Organizer'

### ISSUE THREAD

**Issue by b-davies24** [tendenci/tendenci#1283]
When you export the event calendar as an ICS, events that don't have an 'Organizer' added will not show in the exported ICS file.

**Comment by jennyq** [comment]
Hmm.. I can't replicate it.

**Comment by b-davies24** [comment]
I've looked into this - On a Mac, both downloading the ics and 'subscribing' to https://[site]/events/ics works as intended. Google Calendar seems to import it as well. I'm not sure about Outlook. However, on Thunderbird, it has this bug.
