### ISSUE TITLE
Remove pre-fill event locations from list

### ISSUE THREAD

**Issue by b-davies24** [tendenci/tendenci#1297]
When adding an event, there is the option to select a previously-entered location from a drop-down.
![image](https://github.com/user-attachments/assets/e8ca5673-f01b-4fe2-b8dc-41d022ad2745)
This is really useful, however, it will store ANY information that is entered in the location - we have multiple errors from when people have mistyped/changed spelling/etc.
![image](https://github.com/user-attachments/assets/0b24d9d6-3c65-459b-9b08-040efd7b3b80)
Upon investigating this, there seems to be no obvious way for an admin to modify or delete these.

How would you suggest we deal with this?

**Comment by jennyq** [comment]
Currently there is no web interface to delete them. You can issue a sql query to delete them from db directly. For admin to easily manage places/locations, the Place model needs to be registered at admin backend. We'd accept a PR like that.

**Comment by rob-hills** [comment]
@jennyq I think we'd need to merge duplicate entries and update the foreign keys in the events_event table or else we'll end up events that have no location!  Is the place table linked to any others?

**Comment by jennyq** [comment]
> Is the place table linked to any others?

No, events_event is the only one it is linked to.

**Comment by rob-hills** [comment]
Thanks for that @jennyq , I've been working on this and have something almost ready to submit in a PR.  I'm just waiting for some others to test it first.
