### ISSUE TITLE
PDF invoices will not include Logo

### ISSUE THREAD

**Issue by WessleyKoop** [tendenci/tendenci#1300]
In the template to produce a PDF version of an invoice this portion of code does not work like the View, Email and Print versions;

      <tr>
          <td style="width: 50%;">
            <div>{{ SITE_GLOBAL_SITEDISPLAYNAME }}</div>
          {% if SITE_GLOBAL_SITEMAILINGADDRESS %}
          <address class="invoice-site-address">{{ SITE_GLOBAL_SITEMAILINGADDRESS }}</address>
          {% endif %}
          </td>
          <td class="td-right" style="width: 30%">
             {% if MODULE_INVOICES_INVOICELOGO %}
              <div class="invoice-meta-logo">
                <img src="/files/{{ MODULE_INVOICES_INVOICELOGO }}" width="150" height="300" alt="{% trans 'invoice logo' %}" title="{% trans 'invoice logo' %}">
              </div>
              {% endif %}
          </td>
      </tr>

The logo does no populate.
We use the Logo to display our Business number and without this function our invoices are not legal as they do not include our business number.

**Comment by WessleyKoop** [comment]
Screen shot of the Print view with the logo
![Screenshot of print view with logo](https://github.com/user-attachments/assets/02b44a9d-d88b-454b-8a57-0565e0139914)

Screen shot of the PDF version missing the logo.  Code is identical for both templates.
![Screenshot PDF invoice version missing Logo](https://github.com/user-attachments/assets/827a69af-ce84-415d-b2b8-ca9377769d18)

**Comment by goetzk** [comment]
I've just done some investigation on this issue so here is what technical information I can provide.
Not a lot, but hopefully it helps Jenny and co debug this.

- Ubuntu 20.04.6 LTS
- Tendenci 15.2.1

When a PDF invoice is requested (by clicking the button an invoices view page) the following is logged by tendenci:
```
==> /srv/tendenci_test/logs/tendenci-test.error.log <==
Cannot identify image file:
'<img src="data:image/png;base64,b\'iVBOR... all the encoded data\''

==> /srv/tendenci_test/logs/app-test.log <==
TIME="2024-10-16 12:06:13,600" LEVEL=WARNING PID=555301 LOGGER="xhtml2pdf.tags" MSG="Cannot identify image file:
'<img src="data:image/png;base64,b\'iVBORw0KGgoAAA... all the encoded data\''

==> /srv/tendenci_test/logs/tendenci-test.error.log <==
Could not get image data from src attribute: /files/3102/300x150/crop/90/
'<img src="/files/3102/300x150/crop/90/" alt="invoice logo" title="invoice logo"/>'

==> /srv/tendenci_test/logs/app-test.log <==
TIME="2024-10-16 12:06:13,646" LEVEL=WARNING PID=555301 LOGGER="xhtml2pdf.tags" MSG="Could not get image data from src attribute: /files/3102/300x150/crop/90/
'<img src="/files/3102/300x150/crop/90/" alt="invoice logo" title="invoice logo"/>'"

==> /srv/tendenci_test/logs/tendenci-test.access.log <==
127.0.0.1 - - [16/Oct/2024:12:06:13 +1100] "GET /invoices/download/7631/ HTTP/1.0" 200 3214 "https://example.org/invoices/7631/" "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
```

obviously 'all the encoded data' refers to the actual base64 encoded data.

To test if the file was OK i took the following steps
```
  cd /tmp/
  vi logo.b64
-> Pasted in base64 content from logs
  file logo.b64 
-> output is: logo.b64: ASCII text, with very long lines (36052)
  base64 --decode logo.b64  > logo.png
  file logo.png 
  xdg-open logo.png 
-> successfully opened the image file.
```

The error "Could not get data from src attribute" comes from xhtml2pdf (https://github.com/xhtml2pdf/xhtml2pdf/blob/master/xhtml2pdf/tags.py#L447); the if which goes with that catch is 100 lines up at https://github.com/xhtml2pdf/xhtml2pdf/blob/master/xhtml2pdf/tags.py#L357 ("if filedata:", it then jumps direct to that else-our-error-message case).

The other error text "Cannot identify image file" is not in tendenci or xhtml2pdf; perhaps from an upstream dependency? lots of reports that it occurs using pillow.
Following that thought I looked at https://github.com/python-pillow/Pillow/issues/5631 which shows that error might be masking another issue or two with the logo file. I tried using pngcheck as suggested but my file reports that it is valid.
```
pngcheck logo.png 
-> Output: OK: logo.png (300x150, 32-bit RGB+alpha, non-interlaced, 85.0%)
```
