### ISSUE TITLE
Topics on Help Files inconsistently formatted

### ISSUE THREAD

**Issue by b-davies24** [tendenci/tendenci#1303]
On the Help Files page, the Topics list seems to have some inconsistent formatting:
![image](https://github.com/user-attachments/assets/9ffa4a68-33ef-4bc6-88f4-6e1a305efb5b)
Are there any suggestions to fix this?

**Comment by jennyq** [comment]
Hi @b-davies24,

I don't see that format on our end. Did you change something in your template?

From the template, it splits the topics list and displays the two list groups.
https://github.com/tendenci/tendenci/blob/main/tendenci/themes/t7-base/templates/help_files/index.html#L78

**Comment by b-davies24** [comment]
After quickly looking at my browser inspector, and the template code, I may have found the problem:

https://github.com/tendenci/tendenci/blob/aa7e3207c86681a17008f650505a167fc2448403/tendenci/themes/t7-base/templates/help_files/index.html#L83C1-L88C16

Specific culprit:
https://github.com/tendenci/tendenci/blob/aa7e3207c86681a17008f650505a167fc2448403/tendenci/themes/t7-base/templates/help_files/index.html#L86

On our Test server, I deleted this `<br>`, and it fixed the spacing

Before deleting `<br>`:
![image](https://github.com/user-attachments/assets/74237ccd-08ca-45e4-93a5-ed9342fd7e73)

After deleting:
![image](https://github.com/user-attachments/assets/557a3999-9f1d-4ff1-b0ed-779bce9efa87)

**Comment by jennyq** [comment]
Nice catch.
