### ISSUE TITLE
Customising TinyMCE settings

### ISSUE THREAD

**Issue by b-davies24** [tendenci/tendenci#1304]
We are trying to make TinyMCE paste as plain text by default. In doing so, we cannot seem to find where TinyMCE is initialised in Tendenci, and thus can't figure out where to paste 
```
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  toolbar: 'paste',
  paste_as_text: true
});
```
as stated in TinyMCE documentation (https://www.tiny.cloud/docs/tinymce/latest/copy-and-paste/). Is there an easy way in Tendenci to customise the TinyMCE plugins?

**Comment by jennyq** [comment]
It is all configured in the dictionary `TINYMCE_DEFAULT_CONFIG` in [settings.py](https://github.com/tendenci/tendenci/blob/main/tendenci/settings.py#L649). In your case, you can add the following line In your conf/settings.py.

    TINYMCE_DEFAULT_CONFIG['paste_as_text'] = True

**Comment by rob-hills** [comment]
Thanks @jennyq , you can mark this issue as "resolved"

That said, perhaps it would be good to have this entry in the default settings.py that ships with Tendenci?  It would of course be commented out to maintain backwards compatibility, but at least if it was there in the file Admins would know it was an available setting.

Alternatively it would be good to have documentation of this and any other "hidden" settings in the [Tendenci Documentation](https://tendenci.readthedocs.io).  If you agree, I can create a new issue for that and even do a PR with some documentation of settings I am aware of, to kick things off.
