### ISSUE TITLE
404 trying to search chapter memberships after uploading one

### ISSUE THREAD

**Issue by UnbelievableGit2** [tendenci/tendenci#1317]
I uploaded my superadmin user as a member of a test chapter I created. I only filled in the mandatory fields:

`username,membership_type_id,chapter_id`

The upload was successful but when I try to navigate to "Search Chapter Member", I get:

```
Page not found (404)    
Request Method: | GET
http://18.171.151.105/chapters/memberships/search/1/
tendenci.apps.chapters.views.chapter_memberships_search
```

If I navigate to Admin Backend -> Chapter Members, I successfully get the page with the member listed (http://18.171.151.105/admin/chapters/chaptermembership/) but if I try to view the member, I get:

```
AttributeError at /chapters/memberships/1/
'NoneType' object has no attribute 'fields'
Request Method: | GET
Request URL: http://18.171.151.105/chapters/memberships/1/
Djang Version: 4.2.16
Exception Type: AttributeError
Exception Value: 'NoneType' object has no attribute 'fields'
Exception Location: /srv/venv_ugle/lib/python3.12/site-packages/tendenci/apps/chapters/views.py, line 773, in membership_details
Raised during: tendenci.apps.chapters.views.membership_details
Python Executable: /srv/venv_ugle/bin/python
Python Version: 3.12.3
Python Path: ['/var/www/ugle',
                      '/usr/lib/python312.zip',
                      '/usr/lib/python3.12',
                      '/usr/lib/python3.12/lib-dynload',
                      '/srv/venv_ugle/lib/python3.12/site-packages']
```

**Comment by jennyq** [comment]
I can't reproduce the issue. Please check if you have a chapter membership application set up at your http://18.171.151.105/admin/chapters/chaptermembershipapp/.

**Comment by UnbelievableGit2** [comment]
Yes, sorry Jenny, that was it. I didn't have a chapter membership application set up. Thanks!
