### ISSUE TITLE
Templatetag warning when running checks

### ISSUE THREAD

**Issue by bernd-wechner** [tendenci/tendenci#1328]
This warning arises on a ` python manage.py check`:

````
WARNINGS:
?: (templates.E003) 'static' is used for multiple template tag modules: 'django.templatetags.static', 'tendenci.apps.theme.templatetags.static'
```

It's defined here:

https://github.com/tendenci/tendenci/blob/7923f44d5c859bbd4c9d41edcfa214e8f00577e2/tendenci/apps/theme/templatetags/static.py#L102

And should probably be renamed in deference to this warning. Or if it's an intentional redefinition of the tag, at very least documented as such in the source and some modest effort made to determine if the warning might be suppressible (possibly by deregestering the Django one - alas I see no way of deregestering a templatetag in django at present).

**Comment by bernd-wechner** [comment]
Have looked rather extensively at options here and failed to find any. The Django test at:

https://github.com/django/django/blob/345a6652e6a15febbf4f68351dcea5dd674ea324/django/core/checks/templates.py#L51

is complicate in that it has two check cycles and in the first it records:

django.static: django.templatetags.static

and in the second:

static: django.templatetags.static
static: tendenci.apps.theme.templatetags.static

It is recording the Django built in twice once under django.static and once under static which clashes. 

This area was moved in Django 5 and the issue may go away.

**Comment by jennyq** [comment]
Yes, the django static tag is overridden by the one in Tendenci. We're going to ignore this warning for now.
