### ISSUE TITLE
Django error with Forms

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#1330]
Since the major upgrade we've been having this error reported:

Internal Server Error: /forms/ev-licence-plate-tag-1/

ValueError at /forms/ev-licence-plate-tag-1/
Cannot assign "''": "Profile.region" must be a "Region" instance.

Request Method: POST
Request URL: https://www.aeva.asn.au/forms/ev-licence-plate-tag-1/
Django Version: 4.2.13
Python Executable: /srv/tendenci/environment.tendenci-15/bin/python
Python Version: 3.8.20

Faultfinding information:
- The error happens when someone attempts to complete this form, but not every time.  People are able to repeat the process and complete the form.
- I haven't seen what happens when people can't complete the form, but from someone's description it sounds like they don't get an opportunity to pay the invoice.
- This is a form for the general public, so the field 'Region' is not applicable.
- I tried creating a new form (hence the "-1" on the end of the URL), and the problem persists with the new form.
- We have another form that is very similar, but for members only.  This one does not generate the error.

**Comment by jennyq** [comment]
This issue might be fixed in the commit https://github.com/tendenci/tendenci/commit/06deb40e2d7ce43d199479e4b87f52bbbd660bb4. Will push out a new release to PYPI soon.
