### ISSUE TITLE
TinyMCE menus inoperable in fullscreen

### ISSUE THREAD

**Issue by b-davies24** [tendenci/tendenci#1332]
I think it is related to commit [0945f57](https://github.com/tendenci/tendenci/commit/0945f578ef8c4e6f6958cff0cb4e88e7a9155f80) (issue #1318)

When the z-index was changed, it seems to have made the popup menus when you click 'file'/'edit'/etc go behind the main TinyMCE window, thus making them inaccessible when in fullscreen.

Correct:
![image](https://github.com/user-attachments/assets/a47b6f4b-e7f9-4327-bc9f-2246e3cc5283)

When in fullscreen (i.e. not showing):
![image](https://github.com/user-attachments/assets/2551e0f7-343a-4418-91c9-9e93c9928136)

**Comment by jennyq** [comment]
Thank you @b-davies24 !
Applied the fix similar to the change you did in PR https://github.com/tendenci/tendenci/pull/1331.
