### ISSUE TITLE
How to integrate Mail Chimp on Tendenci

### ISSUE THREAD

**Issue by vikkymedia** [tendenci/tendenci#358]
Hello Tendenci Team,

Can you help us how to integrate "Mail Chimp" on Tendenci CMS.

Thanks,
Vikas.

**Comment by eschipul** [comment]
Tremendously late replaying to this one. We got burned pretty bad programming in API specific to two different vendors and in T6 I've fallen back to the strategy of relaying email via secure smtp/tls.

By that I mean on AWS we use an IAM user and go through SES and then typically mailgun.com with routing rules to keep the bounce backs to SES at a minimum. Plus this reduces it to simple smtp authentication. The complications are that you must make a DKIM record to match all of the sending mail servers (web site, SES, mailgun, etc.) to be sure you get the sending mail server to sign it with authority to avoid spam filters.

Integration - we love Mailchimp. But... one more API. Feel free to do a pull request and submit if you have the time. For now you can also simply generate the newsletter in Tendenci and paste the HTML into the email provider of your choice for sending. Although mailguns' 10k emails free is pretty compelling. 

You could for example use django-sql-explorer (included with T6 - a South Migration of course) to pull a list and use that with the email provider of your choice. More on django-sql-explorer here along with some SQL samples. https://www.tendenci.com/help-files/how-use-django-sql-explorer-tendenci/
