### ISSUE TITLE
How to integrate with django-sis?

### ISSUE THREAD

**Issue by siolag161** [tendenci/tendenci#363]
Hi,  

According to your [blog post](http://blog.tendenci.com/open-education-one-thing-excited/) we can integrate with other django-apps/platform in particular `django-sis`. 

How could we do this (in an easy way, without much re-writing)? Or it is possible just because they are both django?

Thanks in advance

**Comment by eschipul** [comment]
We've handled SSO a number of different ways in the past, sometimes using a third party ldap provider. And Django has an SSO app. Right now after the recent revelations of flaws in kerberos I want to test the  django-mama-cas project but haven't yet.

http://django-mama-cas.readthedocs.org/en/latest/settings.html

Any recommendations on the best future-forward app? I'm still burning from snakeoil.pem responding by default on 443 for poodle so some of my security lately has been perhaps a bit over the top and I've been told to dial it back (OK, so I get you need to POST forms sometimes. Grrrr...... )

Anyway the balance is the hard part. A quick google shows the numerous options and they are all basically add to installed apps and sometimes middleware. And of course SSL on the auth server. All are only a few lines of code on the app, but you do need an app server. We'll probably have an sso.tendenci.com server up for third parties to use if I ever got around to writing an appropriate EULA (like stating the obvious - no we aren't going to steal user data, yes it's encrypted, yes it's ethical, etc.... but I'm not a lawyer and haven't budgeted to have a lawyer write one up. I guess I am a member of the EFF so I could ask them. Most of my photos are CC attribution for example. Hmmm.

Recommendations on providers and on a document that states this is a collective and we (that includes you) are guarding your data, not selling it?  I'd love to hear your thoughts as I've started down the mama-cas route a bit but not that far.

**Comment by eschipul** [comment]
one further item - I just took a look at sis which is already using compose (formerly FIG). very cool. We haven't announced or released it yet, but all of the latest Tendenci sites we are releasing are on dockers as well (like http://www.sfbig.org/ ). So it's cool to see the readme on django-sis. Now I need to get my tail in gear and update our stuff!

https://github.com/burke-software/django-sis

I'm actually excited to see the progress on SIS as well as OpenStax Textbook authoring now renamed CNX (another Django project from Rice University in Houston) 

http://cnx.org/about 

Between SIS, Tendenci and CNX that is a powerful alternative to Blackbaud IMHO. Grant Management and more advanced Donor Management (recurring intelligent / family awareness of donations etc) and the vision of Tendenci as part of a total multi-cultural multi-lingual package is something i dream about. Been at it 17 years so it always seems close, but now things are really picking up.

Not to get distracted - do you have a recommendation based on your insights into the best path forward for SSO?
