### ISSUE TITLE
theme_picker

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#368]
After installing tendenci 7, I did not run 

python mange.py load_npo_defaults 

I ran the **python manage.py runserver** and everything worked, I wanted to see the website barebones, then I logged it and it took me to the theme picker, so I picked **developer-boostrap3** and this was the result:

A server error occurred.  Please contact the administrator.

This is the output of the console that I see the problem might be:

 _File "/home/user/.virtualenvs/site/local/lib/python2.7/site-packages/tendenci/apps/theme/templatetags/theme_tags.py", line 154, in render
    context['setting_name'] = unicode(self.template_name).replace('MODULE_THEME_', '').lower()
AttributeError: 'SpaceIncludeNode' object has no attribute 'template_name'
[06/Aug/2015 12:54:52]"GET / HTTP/1.1" 500 59_

_  File "/home/user/.virtualenvs/site/local/lib/python2.7/site-packages/tendenci/apps/theme/templatetags/theme_tags.py", line 154, in render
    context['setting_name'] = unicode(self.template_name).replace('MODULE_THEME_', '').lower()
AttributeError: 'SpaceIncludeNode' object has no attribute 'template_name'
[06/Aug/2015 12:54:57]"GET / HTTP/1.1" 500 59_

Did I need to run the **python manage.py set_theme my-theme-name** before I chose the theme? I did it after all this mess but it did not solve the problem.

What should I do now? Do I need to do a fresh install again?

**Comment by jennyq** [comment]
Hi @dco5,

We've just pushed out a fix. Please pull the update to your site then try again. 

    pip install -r requirements.txt --upgrade

You'll need to restart the service.

**Comment by dco5** [comment]
@jennyq Thank you so much! Working fine now!
