### ISSUE TITLE
Reports link in Community has no action

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#370]
When logged in as administrator I looked in the top menu's Community dropdown and under 'Administration' clicked the 'Reports' link. Nothing happens when the link is clicked.
I have debug set to true in local_settings.py and no error is recorded in my error log or on screen.

**Comment by eschipul** [comment]
confirmed bug.

**Comment by jennyq** [comment]
Should we create a reports list page that lists all the reports? Then we can link the "Reports" link to the reports list page.

**Comment by bleven** [comment]
Long run, yes! We absolutely want a global page that shows all the reports available. 

See that as lower priority than cleaning up some of the bugs we have. 
For now lets go ahead and remove the dead reports link and that second col on the dropdown so we at least don't have that dead link.
