### ISSUE TITLE
Can't add members to groups

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#374]
http://192.168.56.101/groups/digital-photography/adduser/ and similar pages only show 'admin' in the list of possible members and don't show any of my current, active members.

**Comment by eschipul** [comment]
Are the users who are not appearing marked with both
status=1
statusdetail='active'

And do they have a user profile. For legacy reasons you can create an auth_user in Django at the command line (createsuperuser for example) without it creating a tendenci profile. Sometimes all it takes is editing the user in /profiles/ . Although a user who self-registers should automatically get both. 

Smoking gun is likely a missing profile. 
Second most likely is the group permissions don't "allowselfadd"

Can you confirm as I can't see your local dev (of course)?

**Comment by goetzk** [comment]
I've just tested on master branch and i have the same behaviour. the users are supplied in load_npo_defaults. checking a user (/profiles/edit/16/) i see Status Detail = Acrive. I don't see a place for status.
I can't see one in the db either, auth_user doesn't seem to include a status field.

tendenci=# select * from auth_user where id = 16;
 id |                                   password                                    |         last_login         | is_superuser | username | first_name | last_name |             email              | is_staff | is_active |        date_joined         
----+-------------------------------------------------------------------------------+----------------------------+--------------+----------+------------+-----------+--------------------------------+----------+-----------+----------------------------
 16 | pbkdf2_sha256$10000$FVViKvLCFvoc$eUBgIAbZ+CupkNc4RmZt79CFONSIV3EIV8jUPPl1JIg= | 2012-12-31 15:11:35.807+11 | f            | c_allen  | Chris      | Allen     | Chris.Allen@theassociation.com | f        | f         | 2012-12-31 15:11:35.807+11
(1 row)

**Comment by jennyq** [comment]
@goetzk the status and status_detail fields are in the Profile module. 

The users added with the load_npo_defaults are non-interactive (meaning they cannot log in). The add members page only lists the interactive users. Should we list both interactive and non-interactive users? It makes sense to me to list both.

**Comment by goetzk** [comment]
On Thu Sep 10 08:04:06 2015 Jenny Qian <notifications@github.com> wrote:
> @goetzk the status and status_detail fields are in the Profile module. 
> 
> The users added with the load_npo_defaults are non-interactive (meaning
> they cannot log in). The add members page only lists the interactive
> users. Should we list both interactive and non-interactive users? It
> makes sense to me to list both.

I think listing both makes sense, i can think of several reasons for a non interactive member to be part of a group.

**Comment by jennyq** [comment]
Resolved. 3280243
