### ISSUE TITLE
'Box' object has no attribute 'get_absolute_url'

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#382]
When I try to edit a box I get this: 

equest Method: 	GET
Request URL: 	http://127.0.0.1:8000/admin/boxes/box/1/
Django Version: 	1.8.3
Exception Type: 	AttributeError
Exception Value: 	

'Box' object has no attribute 'get_absolute_url'

Exception Location: 	/home/user/.virtualenvs/site/local/lib/python2.7/site-packages/tendenci/apps/perms/admin.py in view_on_site, line 56

/tendenci/apps/perms/admin.py in view_on_site

                            obj.get_absolute_url(),

     ...

▼ Local vars
Variable 	Value
link_icon 	

'/static/images/icons/external_16x16.png'

self 	

<tendenci.apps.boxes.admin.BoxAdmin object at 0x7fec97f41ad0>

obj 	

<Box: Header-Logo>

**Comment by eschipul** [comment]
we're looking at this one...

**Comment by jennyq** [comment]
Resolved. Boxes doesn't have the font view. In Django 1.7+, the view_on_site should be set to False. 2577e2a

Please pull.

    pip install -r requirements.txt --upgrade

**Comment by dco5** [comment]
Working now. Thanks.
