### ISSUE TITLE
Adding Event

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#383]
When adding and event I am getting: 
IntegrityError at /events/add/

null value in column "tax_rate" violates not-null constraint
DETAIL:  Failing row contains (2, 2, Non-Member, non-member test, 5, 200.00, f, null, t, 2015-08-17 08:00:00-05, 2015-10-16 14:19:00-05, t, f, t, t, null, 1).

For some is only when you add a second or third pricing.

**Comment by dco5** [comment]
The Tax Rate Field does not have any value when you add a new pricing to the event. That is why is null and throws an error.

**Comment by jennyq** [comment]
Fixed 43ed724.

**Comment by dco5** [comment]
Working now. Thanks.
