### ISSUE TITLE
Deploying in linode

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#385]
I am trying to deploy in linode to test tendeci remote and when I do the command

python deploy.py I am getting this error:
Rendering model states... DONE
  Applying pages.0001_initial... OK
  Applying committees.0001_initial... OK
  Applying contacts.0001_initial... OK
  Applying contacts.0002_auto_20150804_1545... OK
  Applying contributions.0001_initial... OK
  Applying regions.0001_initial... OK
  Applying industries.0001_initial... OK
  Applying directories.0001_initial... OK
  Applying memberships.0001_initial...Traceback (most recent call last):
  File "deploy.py", line 3, in <module>
    subprocess.check_call(['python', 'manage.py',  'migrate', '--noinput'])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', 'manage.py', 'migrate', '--noinput']' returned non-zero exit status -9

**Comment by jennyq** [comment]
Probably the migrate process got killed due to system running out RAM. How much RAM does the server have? It might resolve it self if you try again. I'm not sure why the django migration consume so much resources.. We'll need to look into it.

**Comment by dco5** [comment]
It has 2gbs of RAM, I had to rerun the command several times until it finished running all of them. It is working now, but I guess you need more than 2gbs to run it smoothly.
