### ISSUE TITLE
Changing Themes

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#387]
The themes are not working correctly, I am trying to change a theme but it will not change. I am stuck on the developer theme and if I make any change it will not display the change. If I change the theme to another it will still be on the developer theme. I already clear the cache but still nothing.

**Comment by dco5** [comment]
I had to stop gunicorn and start it again to be able to show the change of theme and for everything to work again.

**Comment by jennyq** [comment]
It's the same issue as in https://github.com/tendenci/tendenci/issues/391

**Comment by eschipul** [comment]
Closing and referencing #391 . 

Adding comments there.
