### ISSUE TITLE
Deleting Nav

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#388]
I was trying to delete the Main Navigation and got this error:
ValueError at /admin/navs/nav/

too many values to unpack

Request Method: 	POST
Request URL: 	http://127.0.0.1:8000/admin/navs/nav/
Django Version: 	1.8.4
Exception Type: 	ValueError
Exception Value: 	

too many values to unpack

Exception Location: 	/home/user/.virtualenvs/site/local/lib/python2.7/site-packages/tendenci/apps/perms/admin.py in soft_delete_selected, line 141
Python Executable: 	/home/user/.virtualenvs/site/bin/python
Python Version: 	2.7.6
Python Path: 	

['/home/user/web/site',
 '/home/user/web/site',
 '/home/user/.virtualenvs/site/lib/python2.7',
 '/home/user/.virtualenvs/site/lib/python2.7/plat-x86_64-linux-gnu',
 '/home/user/.virtualenvs/site/lib/python2.7/lib-tk',
 '/home/user/.virtualenvs/site/lib/python2.7/lib-old',
 '/home/user/.virtualenvs/site/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/user/.virtualenvs/site/local/lib/python2.7/site-packages']

**Comment by jennyq** [comment]
Fixed in commit 1ff43f3
