### ISSUE TITLE
Insert/Edit Media mceText editor

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#390]
When I click on the button to insert a media the Insert Media tab is blank. I can not insert a media. The File Gallery tab does work.

**Comment by jennyq** [comment]
The Insert Media tab works fine to me. Please check if your nginx conf has set to deny X-Frame.

**Comment by dco5** [comment]
This are my nginx settings:

server{
        listen 80;
        server_name whapl.com;

        charset utf-8;
        keepalive_timeout 65;
        client_max_body_size 30M;
        root /var/www/site/;

        location /static/{
                access_log off;
                expires 30d;
        }

        location /media/{
                access_log off;
                expires 30d;
        }

        location ~ /themes/([a-zA-Z0-9\-\_]+)/media/ {
            access_log off;
        }

         location / {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://127.0.0.1:8000/;
        }
    }

**Comment by jennyq** [comment]
Have you also checked /etc/nginx/nginx.conf?

**Comment by eschipul** [comment]
the file you included above @dco5 looks like your file from 

     /etc/nginx/sites-enabled/site-name

what Jennyq is asking is if you have double checked the file located at

     /etc/nginx/nginx.conf 

which is installed by the nginx package. It overrides the upload image sizes specified in tendenci itself. They both are needed as many sites go through a front end WAF (like securi or nginx-naxsi) but also to allow a webmaster to restrict file upload sizes on their particular site.

Can you please double check your settings in this file ---> /etc/nginx/nginx.conf

**Comment by dco5** [comment]
@eschipul I don’t see where it denies X-Frames, but I might be wrong.
user www-data;
worker_processes 4;
pid /run/nginx.pid;

events {
        worker_connections 768;
        # multi_accept on;
}

http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        # server_tokens off;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        ##
        # Gzip Settings
        ##

        gzip on;
        gzip_disable "msie6";

        # gzip_vary on;
        # gzip_proxied any;
        # gzip_comp_level 6;
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;
        # gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;

        ##
        # nginx-naxsi config
        ##
        # Uncomment it if you installed nginx-naxsi
        ## #include /etc/nginx/naxsi_core.rules;

        ##
        # nginx-passenger config
        ##
        # Uncomment it if you installed nginx-passenger
        ##

        #passenger_root /usr;
        #passenger_ruby /usr/bin/ruby;

        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}

**Comment by eschipul** [comment]
@dco5 you are correct sir. If it was blocking xframe /etc/nginx/nginx.conf would have a line like this (double check my syntax for nginx version etc if you choose to use it, but similar to)

    add_header X-Frame-Options "SAMEORIGIN";

So that isn't it as far as I can tell. Hmmmm. Would you mind typing this (nginx version) in terminal and letting me know the version of nginx you are on? You probably told me in another ticket so sorry to repeat myself.

    nginx -v

Another debug method I use is to turn "on" access logging so I can at least see what nginx thinks the wysiwyg is doing. That would be to comment out this line in your /etc/nginx/sites-enabled/sites-name file under /media/ and /static/ (basically I turn it off everywhere during dev so I can tail the logs.

    access_log off;

change to 

    # access_log off;

But ya, I doubt either of those are the solution. Hmmm. Gonna have to rattle that one around in my brain over a Saturday afternoon beer...
