### ISSUE TITLE
Editing a Field

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#394]
I got this error when Editing a membershipappfield:

AttributeError at /admin/memberships/membershipappfield/80/

'Options' object has no attribute 'module_name'

Request Method: 	POST
Request URL: 	http://127.0.0.1:8000/admin/memberships/membershipappfield/80/
Django Version: 	1.8.4
Exception Type: 	AttributeError
Exception Value: 	

'Options' object has no attribute 'module_name'

Exception Location: 	/home/user/.virtualenvs/site/local/lib/python2.7/site-packages/tendenci/apps/memberships/admin.py in response_change, line 854
Python Executable: 	/home/user/.virtualenvs/site/bin/python
Python Version: 	2.7.6
Python Path: 	

['/home/user/web/site',
 '/home/user/web/site',
 '/home/user/.virtualenvs/site/lib/python2.7',
 '/home/user/.virtualenvs/site/lib/python2.7/plat-x86_64-linux-gnu',
 '/home/user/.virtualenvs/site/lib/python2.7/lib-tk',
 '/home/user/.virtualenvs/site/lib/python2.7/lib-old',
 '/home/user/.virtualenvs/site/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/user/.virtualenvs/site/local/lib/python2.7/site-packages']

Server time: 	Wed, 26 Aug 2015 07:18:05 -0500

**Comment by jennyq** [comment]
Fixed 2ef1409
