### ISSUE TITLE
Different Registration Forms for pricings

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#395]
Is there a way to use different registration forms for different pricing? I see that each pricing has a Custom Registration Form Dropdown but it is not overriding the Registration Custom Registration Form. In the Registration Custom Registration Form there is only one option for Use one form for all pricings as a radio button. Is there another option missing there?

**Comment by jennyq** [comment]
@dco5, that feature has been disabled and is no longer available. We'll need to remove the dropdown from each pricing to eliminate the confusion.

**Comment by jennyq** [comment]
The Custom Registration Form dropdown has been removed from each pricing. 6934bc4
