### ISSUE TITLE
Membershiptype error

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#401]
AttributeError at /admin/memberships/membershiptype/1/

'MembershipType' object has no attribute 'get_absolute_url'

Request Method: 	GET
Request URL: 	http://104.237.129.227/admin/memberships/membershiptype/1/
Django Version: 	1.8.4
Exception Type: 	AttributeError
Exception Value: 	

'MembershipType' object has no attribute 'get_absolute_url'

Exception Location: 	/home/admin/.virtualenvs/whapl/local/lib/python2.7/site-packages/tendenci/apps/perms/admin.py in view_on_site, line 56
Python Executable: 	/home/user/.virtualenvs/site/bin/python
Python Version: 	2.7.6
Python Path: 	

['/var/www/site',
 '/home/admin/.virtualenvs/site/bin',
 '/home/admin/.virtualenvs/site/lib/python2.7',
 '/home/admin/.virtualenvs/site/lib/python2.7/plat-x86_64-linux-gnu',
 '/home/admin/.virtualenvs/site/lib/python2.7/lib-tk',
 '/home/admin/.virtualenvs/site/lib/python2.7/lib-old',
 '/home/admin/.virtualenvs/site/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/admin/.virtualenvs/site/local/lib/python2.7/site-packages']

Server time: 	Sat, 29 Aug 2015 09:33:18 -0500

**Comment by dco5** [comment]
I was able to fix this adding a get_absolute_url method, but I am not sure if what I added is correct. Is working thou....

**Comment by jennyq** [comment]
Fixed e38435e. This fix applies for all subclasses of TendenciBaseModelAdmin.
