### ISSUE TITLE
directories pricing needs default fixtures added

### ISSUE THREAD

**Issue by eschipul** [tendenci/tendenci#402]
When setting up a new site the directories module, a major revenue generator for tendenci npo sites typically, needs default directories pricing added to speed up the go-live process.

Example URL:
http://192.168.184.130/directories/pricing/search/

Additionally the form needs to be updated with css for bootstrap3 as it has the "white label on a white background" bug for form fields here:
http://192.168.184.130/directories/pricing/add/

However, a better solution would be to move directories pricing entirely into the admin back end as nobody but a super_user would ever be adding directory pricing, only directories are added when the module is turned on by non-super_users.

Still thinking on this one but wanted to put it out there for comments

**Comment by jennyq** [comment]
- Added directory pricing to admin backend: 9d6b720
- Updated directories pricing's add and edit pages to be bootstrap3 compatible: cb5128f
- Fixed the format on directories pricing's view page 3e6b3c1
- Updated the directory pricing search and top menu: 048ad62
- Added the fixture for directories pricing: 3210e91
