### ISSUE TITLE
Double Start Date and End Date creating an Event

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#406]
Why is there __Start Date/Time__ - __End Date/Time__ and then __Start Date__ - __End Date__ ??? That is extremely confusing

Also I think you guys should make like you had in T5 where if you click on recurring then the options for recurring event will be enabled. Right now they are showing all the time and that is also confusing. 

Also I think you guys should have the Time like in T5 where you click on the input field and you get a dropdown of times to be selected. It makes it easier for the user and also is hard for a user that does not know how the time should be formatted.

**Comment by bleven** [comment]
Hi dco5, 
Thank you for catching this. Agree is really confusing. 
This point was also brought up in another submitted issue here if you would like to read response from eschipul: https://github.com/tendenci/tendenci/issues/455. 
We'll be taking a look at the code there to try and simplify.

**Comment by jennyq** [comment]
Resolved. Same issue as https://github.com/tendenci/tendenci/issues/455
