### ISSUE TITLE
Bad masonry element: null in events/add/

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#407]
There is a javascript error in events/add/

Bad masonry element: null masonry.js:1776:7
Outlayer() masonry.js:1776
Layout() masonry.js:2548
<anonymous> jquery.wp.custom.js:38
n.Callbacks/j() jquery.min.js:2
n.Callbacks/k.fireWith() jquery.min.js:2
.ready() jquery.min.js:2
I() jquery.min.js:2

I know how hard and annoying a javascript error can be.

**Comment by eschipul** [comment]
I'm going to punt on this one as it could be anything from pulling down base.html and missing a link, security on the css or js files (common nginx config problem) but without further data and not having seen this I'm going to be bold and close this one out.

But, you know, I'm wrong a LOT. It's one of my specialties. So if you feel this is a global tendenci problem some relative links to the pages on your theme editor, the theme in use would be helpful. 

Last thought - we deploy in docker containers and for memory reasons we use the django template cache. Sometimes we have to actually stop and start the container. Or if in a VM or solo stop and start both the nginx and the "tendenci" service. It shouldn't throw the error, but it's going to be something in the theme files...

Also the version of tendenci really helps as we've been moving pretty quick lately and with the refactoring it's just going to be a crazy month. But the result will be soooooo much cleaner. I'm excited.
