### ISSUE TITLE
Import Membership

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#412]
I have been trying to import members using /memberships/import_default/ but every time I do it I get an error in the console __'ManyToOneRel' object has no attribute 'parent_model'__ and in the recap report all the members have an action or None. So add the end of the process no member is imported. I have been at this for a while and have not been able to figure it out.

**Comment by eschipul** [comment]
I haven't seen this one before but definitely a bug. My one suggestion for testing, and this is still a bug regardless, is if the carriage returns on the import file are "windows" or "unix" carriage returns as we sometimes forget to test the windows versions.

Again - a definite bug and if you could provide some sample data (fake of course) in the same format, say 10 lines, and some links to the exact page where you are doing the import that would be appreciated.

Hotfix - open 5432 to your IP and import there - but the software should be better than that. Just trying to give an option so it doesn't prevent your deployment.

**Comment by dco5** [comment]
instance:<class 'tendenci.apps.profiles.models.Profile'> | value:  | field_name: creator
exception: 'ManyToOneRel' object has no attribute 'parent_model'

instance:<class 'tendenci.apps.profiles.models.Profile'> | value:  | field_name: owner
exception: 'ManyToOneRel' object has no attribute 'parent_model'

instance:<class 'tendenci.apps.memberships.models.MembershipDefault'> | value: 1 | field_name: membership_type
exception: 'ManyToOneRel' object has no attribute 'parent_model'

instance:<class 'tendenci.apps.memberships.models.MembershipDefault'> | value: 1 | field_name: app
exception: 'ManyToOneRel' object has no attribute 'parent_model'

This are the errors that are preventing the import of members. I added a try/exception in __def assign_import_values_from_dict(self, instance, action)__ in members.utils.py and it resolved the issue. 

        for field_name in self.field_names:
                if field_name in assign_to_fields_names:
                    try:
                        if any([
                                    action == 'insert',
                            self.mimport.override,
                                            not hasattr(instance, field_name) or
                                                    getattr(instance, field_name) == '' or
                                            getattr(instance, field_name) == None
                        ]):
                            value = self.memb_data[field_name]
                            value = self.clean_data(value, assign_to_fields[field_name])

                            setattr(instance, field_name, value)
                    except Exception, e:
                        print "\ninstance:{} | value: {} | field_name: {}".format(instance.__class__,value,field_name)
                        print "exception: {}".format(e)

Now the it uses the default data, but before it was skipping the default data and was not saving the profile or membership because it could not handle the error. This is just for your information so you guys can handle it any way you want.

**Comment by jennyq** [comment]
Fixed. 3178313

Thanks @dco5 for reporting!
