### ISSUE TITLE
Merge common "add on" modules into tendenci/apps

### ISSUE THREAD

**Issue by eschipul** [tendenci/tendenci#413]
There is no need for the following add ons to be in their own repositories. It adds confusion and disk space is not a constraint for tendenci. They can be disabled to save memory as needed. The time saved by the developers is more important than the minor extra disk space used.

Move the following modules into https://github.com/tendenci/tendenci/tree/master/tendenci/apps and remove the "tendenci-" prefix as that is redundant

https://github.com/tendenci/tendenci-donations
https://github.com/tendenci/tendenci-case-studies
https://github.com/tendenci/tendenci-committees
https://github.com/tendenci/tendenci-staff
https://github.com/tendenci/tendenci-studygroups
https://github.com/tendenci/tendenci-testimonials
https://github.com/tendenci/tendenci-videos
https://github.com/tendenci/tendenci-speakers
https://github.com/tendenci/tendenci-social-services

**Comment by jennyq** [comment]
Merged all addons above but tendenci-social-services 72e3725. The tendenci-social-services is not T7 compatible yet. Going to convert to T7 compatible then merge.

**Comment by eschipul** [comment]
Awesome! Can't wait until we can update requirements back to master and push to pypi again soon!

**Comment by jennyq** [comment]
The tendenci-social-services has also been merged c52f36b. Should they be added to the INSTALLED_APPS in core or local_settings.py?

**Comment by eschipul** [comment]
Thank you @jennyq - marking this one closed. There will be further clean up on the apps but it is SO MUCH CLEARER NOW! I love it! 

Now on to fixtures but we'll do that in a different issue ticket. #rockon
