### ISSUE TITLE
Can't edit Newsletter title or group after creation

### ISSUE THREAD

**Issue by rschipul** [tendenci/tendenci#416]
In practice, I make a draft email newsletter before sending to the entire group. I do this here /newsletters/

When I am ready to send, I cannot edit the title or the group. An example URL on my site is /newsletters/view/details/153/

My workaround is to make a brand new email newsletter and copy and paste the HTML code from my finalized draft version. This workflow seems cumbersome. Can it be fixed?

**Comment by jennyq** [comment]
Rachel, you can change Newsletter title and group at Admin backend. Let me know if that works for you. Thanks!
