### ISSUE TITLE
Newsletter send generates 504 error

### ISSUE THREAD

**Issue by rschipul** [tendenci/tendenci#417]
When I send my newsletter to a group that is larger than 100 people, I get a 504 error on my site.

This is the URL after sending /newsletters/actions/step5/153/

The newsletter does send, however, I would like the page to reload after I hit send telling me the request has been submitted rather than hang during the process and return an error.

**Comment by jennyq** [comment]
I have troubleshooted but not able to replicate the issue on my local. This might be docker related. Will need further investigation..

**Comment by jennyq** [comment]
@rschipul, I've figured it out. The solution is to add `--close-on-exec` option when running uwsgi. Tested in a test container and it worked. Will going to update for other containers and docker repo.
