### ISSUE TITLE
Create Article on Newsletter Send not working

### ISSUE THREAD

**Issue by rschipul** [tendenci/tendenci#418]
When I send my newsletters, there is a box to Create an Article right above the Send option. I have checked this box but no Article is created.

**Comment by rschipul** [comment]
Wait. The article was created but returned an Oops error on view. Article record is requiring entries for Release Date and Time. Was able to edit the record and manually input this information - had to check another article record to get the exact syntax required for the date format. 

Article Create on Newsletter Send should either enter this information in the correct format or the Articles module should not require Release Date and Time.

**Comment by jennyq** [comment]
The error has been fixed in core 7e690dc.

**Comment by rschipul** [comment]
Thanks Jenny! Can you tell me what you did? Is Tendenci adding that information on Article Create or is the Articles module not requiring that data?

**Comment by rschipul** [comment]
Sorry. Saw the link to the commit. Thanks for the update.
