### ISSUE TITLE
corporate membership admin "preview" and "view on site" give errors

### ISSUE THREAD

**Issue by eschipul** [tendenci/tendenci#419]
In the Corporate Memberships Module

When editing or adding a corporate membership application in the /admin/ area - specifically an example would be
/admin/corporate_memberships/corpmembershipapp/1/

If you click "preview" or "view on site" it gives an error even if you have set up the "root url" setting for the module at:
/settings/module/corporate_memberships/%23id_enabled

**Comment by jennyq** [comment]
Pretty sure this issue has been resolved a while ago.

**Comment by eschipul** [comment]
OK
