### ISSUE TITLE
Links in email when a subscribed forum post has a new entry

### ISSUE THREAD

**Issue by brandonwagner** [tendenci/tendenci#420]
When @eschipul responded to the forum post I subscribed to I got an email with links that have two protocols at the front (http://https://www.tendenci...). Still worked fine in gmail but my iPhone tried to open the link as is and failed. 

![screen shot 2015-09-29 at 8 57 41 am](https://cloud.githubusercontent.com/assets/6494189/10164793/906783ee-6689-11e5-99a4-20181c97add4.png)

**Comment by jennyq** [comment]
Resolved. f3eb746. 
@brandonwagner, thank you for pointing it out!

**Comment by eschipul** [comment]
Great catch. @jennyq fixed this one @brandonwagner and it is committed to master. Thanks!

**Comment by eschipul** [comment]
I should add it came from the Site URL site setting variable which currently is set up to NOT have a protocol specified (e.g. http, https, ftp, etc.... So to fix it on your site the quick fix is to edit your site settings and remove the protocol prefix. The setting is at

/settings/site/global/

and it is named "Site URL:" a bit more than half way down the page (note to self - we should make site settings a numbered list so they are easier to discuss online. Hmmmmmm.)
