### ISSUE TITLE
Language Drop Down From the Admin Menu Not Working

### ISSUE THREAD

**Issue by bleven** [tendenci/tendenci#422]
The black administrator bar on the top of the page when logged in has a little Icon with a world on it and the language English selected. 

Selecting another language from that drop down doesn't change the language on the site. Software stays in English

![languagedropdown](https://cloud.githubusercontent.com/assets/4460314/10207070/d38363e4-678f-11e5-8a09-98e9d43ee2db.png)

**Comment by jennyq** [comment]
Fixed f0af210

The session key `django_language` is no longer read in django 1.8 https://docs.djangoproject.com/en/1.8/releases/1.8/#features-removed-in-1-8.
