### ISSUE TITLE
Mega Menu - Ability For Members to View Apps they Don't have Access to on Dropdown menu

### ISSUE THREAD

**Issue by bschipul** [tendenci/tendenci#425]
Currently Members have the ability to see everything on the apps drop down.

This includes items they don't have access to (they cannot access the actual pages but they can still see the dropdown items)

We need members to only see items they have access to

Please disable members from seeing any items in the dropdown they do not have access to (Example: Admin Backend, Boxes, Stories, Theme Editor), they should also not be able to see the full apps list, or reports

Members should not be able to see the "Support" Drop down item on the navigation.

**Comment by eschipul** [comment]
Definite bug. And while not a security risk, it is frustrating to end users so this one I view as high priority. On internal company project can you please give some exact links with the full URL including that of a client or a live site please?

**Comment by bleven** [comment]
@eschipul I created two test accounts on Tendenci.com blevenuser and blevenmember that I can provide you access to login with. 

As I was researching this I noticed that User Menu is the same if USER is a member and if User is not a member. 

Is this how we want to move forward with the software? 
In previous versions I believe that if USER was a member they had different menu options

**Comment by bleven** [comment]
ties into issue: https://github.com/tendenci/tendenci/issues/450

**Comment by jennyq** [comment]
This issue has been resolved. But for sites have top_menu pulled in, they won't get the update and need to update manually.
