### ISSUE TITLE
Membership Application Fields - Inputs Same Length, aligned right

### ISSUE THREAD

**Issue by bschipul** [tendenci/tendenci#426]
The input fields for membership are all the same length making it hard to read through. 
In addition the lables are aligned to the left of the input space rather than aligning to the right of the page.

**Comment by jennyq** [comment]
Resolved 1fa9f044e76f5d1b7d9bca8fcf2a85e0bda2c692 24e4cfe347b3109e30cf2c67619e22fa649faf4f

**Comment by eschipul** [comment]
thanks y'all. one small step towards more awesome "human tested" ux.
