### ISSUE TITLE
Membership Application - Required Fields not Indicated

### ISSUE THREAD

**Issue by bschipul** [tendenci/tendenci#427]
On membership application, fields that are marked as required are not indicated by astrick. 
Makes it difficult to know what fields are required.

**Comment by jennyq** [comment]
Resolved. If you don't see it on your site, check if your site have `base.html` pulled in and remove the comment from this line.

    {# <link href="{% static 'css/labels.css' %}" rel="stylesheet" type="text/css"> #}
