### ISSUE TITLE
base.html move the tag - {{ SITE_GLOBAL_SITEDISPLAYNAME }}

### ISSUE THREAD

**Issue by bschipul** [tendenci/tendenci#430]
Currently in Templates > base.html we have the following code:

{% block full_title }<title>{ block title }{ endblock } - {{ SITE_GLOBAL_SITEDISPLAYNAME }}</title>{ endblock %}

This should instead display as:

{% block full_title }<title>{ block title }{{ SITE_GLOBAL_SITEDISPLAYNAME }}{ endblock }</title>{ endblock %}

Please update this globally in base.html

**Comment by eschipul** [comment]
Can we get more detail? Are you talking about T5, T6 or T7.x?

And what is the file path to the template in github exactly so I can tell what you are talking about please? I definitely don't want to discourage helpful comments, but base.html was the *(&@(@#@ child in T5 that was finally extracted in T6+ so it makes a big difference.

Throw me a bone with a few github.com/tendenci/tendenci/ links or to a dev site please?

**Comment by bleven** [comment]
Hi Ed, 
This is an issue we need to address in T7 base.html https://github.com/tendenci/tendenci/blob/master/tendenci/templates/base.html

This ticket is based off a recommendation you made to update this template for SEO purposes. 

Currently it is being done manually on sites before we take them live. Would be better if base.html didn't have to be pulled down and customized.
