### ISSUE TITLE
Newsletters Footer Update

### ISSUE THREAD

**Issue by bschipul** [tendenci/tendenci#432]
Newsletter footers need to default to pull information from site settings.

Currently the default footer looks like this:
www.changethistoyourdomainname.com
Contact us: Replace This With Your Company Address | (555) 555-5555 | info@yourdomainname.com

Having trouble viewing this newsletter? 
View the web version here. 
Want to Unsubscribe from this newsletter?Click Here

**Comment by jennyq** [comment]
This has been resolved already.
