### ISSUE TITLE
Unable to upload files in IE - Tendenci 7

### ISSUE THREAD

**Issue by bschipul** [tendenci/tendenci#435]
I am currently unable to upload files to a page using IE browser.

Example - when uploading to a new page in Tendenci using IE 12 https://www.example.com/pages/add/ after clicking the icon to upload media and uploading a file, the file is stuck in pending state (image attached).

Neither the pdf files and jpg files seem to upload. The files module seemed to have no issues uploading files in IE.

**Comment by eschipul** [comment]
So this upload error is specific to trying to upload through the wyiwyg editor on pages add /pages/add/ ? If so it could be we need to upload the wysiwyg so I'm just trying to clarify?

**Comment by bleven** [comment]
@eschipul this is specific to uploading files through wysiwyg editor but problematic for multiple modules. We tested in articles and pages and in both modules using the wysiwyg editor to upload files the file is stuck in pending state

**Comment by christineprice** [comment]
![screenshot 1](https://cloud.githubusercontent.com/assets/370836/10801124/c0ef09d6-7d83-11e5-9399-02da519770c6.png)
Here is a screenshot of the wysiwyg "pending" error. When uploading a pdf in IE.

**Comment by jennyq** [comment]
Tested in IE 11 - it works fine with the new wysiwyg editor.
