### ISSUE TITLE
Admin View Staff> Department Delet Action  Throws an "Oops"Error

### ISSUE THREAD

**Issue by bleven** [tendenci/tendenci#436]
In the admin view of departments for the staff app (www.example.com/admin/staff/department/)
using the dropdown action "Delete selected departments" and clicking "Go" throws an error 
"Oops bleven, we caused a problem"
![deleteselected_departments](https://cloud.githubusercontent.com/assets/4460314/10255476/4373e47c-6910-11e5-9837-358f7cc748ba.png)

**Comment by eschipul** [comment]
Great catch. Will try to replicate. Any further detail from sentry or by changing debug=true in conf/local_settings.py is helpful, but not necessary as just catching and reporting the bug is the first step. Thank you!

**Comment by jennyq** [comment]
@bleven I'm not able to replicate the error. Can you please confirm if the error is still there?

**Comment by bleven** [comment]
@jennyq just tested and doesn't seem to be a problem anymore! closing out
