### ISSUE TITLE
Error Generating report 

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#440]
I am getting this error:

TypeError at /reports/add/
__init__() got an unexpected keyword argument 'iterable_as_array'

Request Method: 	POST
Request URL: 	http://127.0.0.1:8000/reports/add/
Django Version: 	1.8.4
Exception Type: 	TypeError
Exception Value: 	

__init__() got an unexpected keyword argument 'iterable_as_array'

Exception Location: 	/home/user/.virtualenvs/site/local/lib/python2.7/site-packages/simplejson/__init__.py in dumps, line 397
Python Executable: 	/home/user/.virtualenvs/site/bin/python
Python Version: 	2.7.6

**Comment by eschipul** [comment]
Can you provide a few more pieces of information?

1) What version of Tendenci are you using? (on the support menu drop down it should say)

That said, I was able to reproduce the error on our site as well so it is definitely a bug in 7.1. 
Location --> /reports/add/  - I'll check the logs in  bit.

**Comment by dco5** [comment]
Tendenci 7.0.15

**Comment by jennyq** [comment]
Fixed in the latest T7.1 b5ddfc0

@dco5 you'll need to update your site to 7.1. 
https://tendenci.readthedocs.org/en/latest/upgrade/upgrade-to-tendenci7.1.html
