### ISSUE TITLE
Admin Only - Default Setting for New Membership Types

### ISSUE THREAD

**Issue by bleven** [tendenci/tendenci#441]
Currently, when creating a new membership type at www.example.com/admin/memberships/membershiptype/add/, the default is for the membership type to be "Admin Only". 

![admin only checkbox](https://cloud.githubusercontent.com/assets/4460314/10405372/0d0fe406-6e9e-11e5-9a1e-a9784d4334a8.png)

The majority of users will be creating membership types that are open to more than just admins. 

Would be great if the "Admin Only" was not checked by default when adding a new membership type.

**Comment by jennyq** [comment]
Resolved.
