### ISSUE TITLE
Corporate Membership - Tax Exempt Field Requires "True" "False" answer

### ISSUE THREAD

**Issue by bleven** [tendenci/tendenci#444]
On the corporate membership application example: www.example.com/corporatememberships/corporate-membership/add/, the field for "Tax Exempt" requires a "True" "False" case sensitive answer. 

![taxexemptfield](https://cloud.githubusercontent.com/assets/4460314/10521765/2e798514-7337-11e5-9fac-8241f4480dc8.png)

I attempted to change the field type by going to the admin view for "Fields" at www.example.com/admin/corporate_memberships/corpmembershipappfield/ (pictured below)

![taxexamptfieldedit](https://cloud.githubusercontent.com/assets/4460314/10521882/bd882166-7337-11e5-9366-32f77de7b465.png)

But got the following error when clicking to edit the field "Tax Exempt"

Environment:

Request Method: GET
Request URL: http://create-project.tendenci.net/admin/corporate_memberships/corpmembershipappfield/16/

Django Version: 1.8.5
Python Version: 2.7.6
Installed Applications:
('django_admin_bootstrapped',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.humanize',
 'django.contrib.sitemaps',
 'django.contrib.messages',
 'django.contrib.admindocs',
 'django.contrib.staticfiles',
 'formtools',
 'bootstrap3',
 'pagination',
 'tagging',
 'avatar',
 'tinymce',
 'haystack',
 'captcha',
 'tendenci',
 'tendenci.libs.model_report',
 'tendenci.apps.entities',
 'tendenci.apps.base',
 'tendenci.apps.site_settings',
 'tendenci.apps.contributions',
 'tendenci.apps.search',
 'tendenci.apps.notifications',
 'tendenci.apps.registration',
 'tendenci.apps.registry',
 'tendenci.apps.api_tasty',
 'tendenci.apps.invoices',
 'tendenci.apps.payments',
 'tendenci.apps.recurring_payments',
 'tendenci.apps.forms_builder.forms',
 'tendenci.apps.accounts',
 'tendenci.apps.files',
 'tendenci.apps.user_groups',
 'tendenci.apps.perms',
 'tendenci.apps.profiles',
 'tendenci.apps.meta',
 'tendenci.apps.tags',
 'tendenci.apps.articles',
 'tendenci.apps.jobs',
 'tendenci.apps.news',
 'tendenci.apps.stories',
 'tendenci.apps.pages',
 'tendenci.apps.events',
 'tendenci.apps.photos',
 'tendenci.apps.memberships',
 'tendenci.apps.corporate_memberships',
 'tendenci.apps.locations',
 'tendenci.apps.industries',
 'tendenci.apps.regions',
 'tendenci.apps.educations',
 'tendenci.apps.careers',
 'tendenci.apps.make_payments',
 'tendenci.apps.accountings',
 'tendenci.apps.emails',
 'tendenci.apps.email_blocks',
 'tendenci.apps.contacts',
 'tendenci.apps.robots',
 'tendenci.apps.versions',
 'tendenci.apps.event_logs',
 'tendenci.apps.categories',
 'tendenci.apps.theme_editor',
 'tendenci.libs.styled_forms',
 'tendenci.apps.newsletters',
 'tendenci.apps.redirects',
 'tendenci.apps.directories',
 'tendenci.apps.help_files',
 'tendenci.apps.resumes',
 'tendenci.apps.boxes',
 'tendenci.apps.mobile',
 'tendenci.apps.social_auth',
 'tendenci.apps.campaign_monitor',
 'tendenci.apps.wp_importer',
 'tendenci.apps.wp_exporter',
 'tendenci.apps.theme',
 'tendenci.apps.discounts',
 'tendenci.apps.metrics',
 'tendenci.apps.navs',
 'tendenci.apps.tendenci_guide',
 'tendenci.apps.exports',
 'tendenci.apps.events.ics',
 'tendenci.apps.imports',
 'tendenci.apps.handler404',
 'tendenci.apps.reports',
 'tendenci.apps.dashboard',
 'tendenci.apps.social_media',
 'tendenci.apps.announcements',
 'tendenci.apps.forums',
 'djkombu',
 'djcelery',
 'gunicorn',
 'django.contrib.gis',
 'tendenci.apps.committees',
 'tendenci.apps.case_studies',
 'tendenci.apps.donations',
 'tendenci.apps.speakers',
 'tendenci.apps.staff',
 'tendenci.apps.studygroups',
 'tendenci.apps.videos',
 'tendenci.apps.testimonials',
 'tendenci.apps.social_services',
 'tendenci.apps.explorer_extensions',
 'explorer')
Installed Middleware:
('django.middleware.gzip.GZipMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'tendenci.libs.swfupload.middleware.SWFUploadMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'tendenci.libs.swfupload.middleware.SSLRedirectMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'tendenci.apps.profiles.middleware.ProfileLanguageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'pagination.middleware.PaginationMiddleware',
 'tendenci.apps.profiles.middleware.ForceLogoutProfileMiddleware',
 'tendenci.apps.profiles.middleware.ProfileMiddleware',
 'tendenci.apps.base.middleware.Http403Middleware',
 'tendenci.apps.redirects.middleware.RedirectMiddleware',
 'tendenci.apps.mobile.middleware.MobileMiddleware',
 'tendenci.apps.theme.middleware.RequestMiddleware',
 'tendenci.apps.base.middleware.MissingAppMiddleware',
 'tendenci.apps.memberships.middleware.ExceededMaxTypesMiddleware',
 'tendenci.apps.forums.middleware.PybbMiddleware')

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py" in wrapper
  616.                 return self.admin_site.admin_view(view)(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py" in _wrapped_view
  110.                     response = view_func(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py" in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py" in inner
  233.             return view(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py" in change_view
  1519.         return self.changeform_view(request, object_id, form_url, extra_context)
File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py" in _wrapper
  34.             return bound_func(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py" in _wrapped_view
  110.                     response = view_func(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py" in bound_func
  30.                 return func.__get__(self, type(self))(*args2, **kwargs2)
File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py" in inner
  145.                     return func(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py" in changeform_view
  1442.             obj = self.get_object(request, unquote(object_id), to_field)

Exception Type: TypeError at /admin/corporate_memberships/corpmembershipappfield/16/
Exception Value: get_object() takes exactly 3 arguments (4 given)

**Comment by rschipul** [comment]
The Tax Exempt field should be a dropdown with options for Yes and No that correspond to the True and False values required by the system.

**Comment by bleven** [comment]
Just discussed this issue with @jennyq. 
This field relates to all  Boolean fields so though just one field, not a quick fix issue.
