### ISSUE TITLE
Directories needs "starts with" search option

### ISSUE THREAD

**Issue by rschipul** [tendenci/tendenci#448]
The search fields on /directories/ need to include a "starts with" option to allow a user to search for a company name (Headline) that starts with a certain letter.

Best solution would be a choice for "starts with" or "contains" prior to the value field.

**Comment by jennyq** [comment]
Resolved. a413400
Added a dropdown with 'Starts With', 'Contains' and 'Exact' options. And added a A-to-Z list as well.
