### ISSUE TITLE
Hide Member Search from Mega Menu

### ISSUE THREAD

**Issue by bleven** [tendenci/tendenci#450]
Currently if a user is logged into the website (with USER permissions and not a member), they have the ability to see the option for "Member" search on their mega menu admin dropdown
![members](https://cloud.githubusercontent.com/assets/4460314/10799006/7cc5a464-7d78-11e5-9435-b824a1bc9d19.png)

We should remove this option for logged in USERS who are not members as most organizations default to having their member's details private. Users should only have this option on their dropdown admin menu if User = Member

**Comment by bleven** [comment]
Hold on this = User Mega Menu and Member mega menu currently the same. We may want to seperate those out before removing "Member" from the dropdown

**Comment by eschipul** [comment]
The megamenus, which of course are not editable through the admin nav interface but I personally love megamenus. But... the megamenus are nothing more than template files that can be pulled down and the decision process of which menu shows up is usually as simple as a check on the user security level (user, staff, superuser).

This suggests that it might be a problem either in core templates or a template has been pulled down to a particular site and it missed an update.

To your specific request, the current logic in the template is basically "if superuser show X else show Y" which would need to be modified to "if superuser show X elseif setting(allowuserseemember) then show x else show Y"

Did I get that correct and repeat it correctly? 

What amazes me is associations that won't let members search for their peers given most non-profits and associations are primarily oriented towards networking.

I think the solution is a third version of the megamenu. Complexity is tough, but you can onlly make it as easy as possible and no easier, right. Adding this to the 8.0 milestone.

**Comment by jennyq** [comment]
Resolved. The permission has been taken care of. Also see #425.
