### ISSUE TITLE
Customize Dashboard Statistics Page Broken

### ISSUE THREAD

**Issue by bleven** [tendenci/tendenci#451]
A logged in SuperUser has a link on the dashboard (www.example.com/dashboard) to "Customize Dashboard Statistics"

![dashboardstatistics](https://cloud.githubusercontent.com/assets/4460314/10799314/2fef753c-7d7a-11e5-8a59-28b86b21db73.png)

However, when you click this link, no statistics are available to select (www.example.com/dashboard/customize/)

![customizedashboardstatisticspage](https://cloud.githubusercontent.com/assets/4460314/10799316/3625a6b0-7d7a-11e5-877a-de1a95fef6b5.png)

**Comment by jennyq** [comment]
Resolved https://github.com/tendenci/tendenci/commit/887685af8c155802e2eeaeeb9fc484ddfdaa095a
