### ISSUE TITLE
My avatar does not show when I change my username

### ISSUE THREAD

**Issue by ediaz1** [tendenci/tendenci#453]
Whenever I make a new post my e-mail shows up as my username. Within the new post I change the e-mail to a user name I prefer and when I make the post my avatar no longer shows.

**Comment by eschipul** [comment]
The avatars in the forums are pulling in from www.gravatar.com. Simply add a few of your email aliases to your gravatar profile (on their site), I think I have 5, and your image will pull in for all of them.
