### ISSUE TITLE
Forums - Settings for Member only View

### ISSUE THREAD

**Issue by eschipul** [tendenci/tendenci#457]
Setting to allow forums module to have more incremental permissions allowing

- anonymous
- logged in user
- member only
- superuser only

Example: https://www.tendenci.com/forums/

A functional use would be for members of Tendenci (the association) might have rights to vote on a forum poll but regular users could not. Or an internal member-only discussion that should not be indexed in the search engines. This maps to our client repos at https://projects.tendenci.com/issues/1286 but dialog is probably bests held here.

Thanks,

Ed

**Comment by jennyq** [comment]
The permission has been built into the forum categories just as other tendenci apps. Example: https://www.tendenci.com/admin/forums/category/1/ (see the Advanced Permissions under the Permissions section).
