### ISSUE TITLE
Add "Inactive/Archive" Status for Members

### ISSUE THREAD

**Issue by bleven** [tendenci/tendenci#460]
In older iterations of the software we used to be able to Archive a record when 1) we need to archive a record due to a member death or 2) we need to archive a record for someone who asked to be removed from further contact (example: they moved to another region of the country and do not want to maintain their membership). 

Has been requested that we bring this feature back in current version of the software.

**Comment by bleven** [comment]
Per conversation with @eschipul 
"archiving" a record is much the same as a "soft delete" 
every object in Tendenci should have two fields - "status" which is a boolean stored in an INTEGER field type with a value of 0 or 1. 1 means visible and 0 means not visible 

secondarily there is a text field named "statusdetail" which should be (but is not currently) all lowercase and a literal like "active" or "inactive" or "pending" or "archive" 

Ed Schipul the "feature" that is being asked for is  built into the system already, it is the view of the record that was omitted when tendenci 5 was built. technically we can archive a record now by making it inactive.

statusdetail='inactive' 
statusdetail='archive' 
although I don't know that archive is an option at the moment, it is a exclusion logic that was originally used meaning "select * from articles where statusdetail='active' and status=1" 

statusdetail='inactive' is the same technically as "archive"

**Comment by bleven** [comment]
@eschipul it sounds like what we need is two part process

1) See if statusdetail = 'inactive" or statusdetail = 'archive' is currently logic built into Tendenci
2) If it is built into Tendenci, create a view for changing statusdetail to "archive" or "inactive"

For example: 
![screen shot 2015-11-12 at 4 46 44 pm](https://cloud.githubusercontent.com/assets/4460314/11133707/195a87aa-895d-11e5-995e-5eccbea6675a.png)

On the admin edit page for a membership https://www.tendenci.com/admin/memberships/membershipdefault/15/, we have a link for Active > Expired. 
We could have another link or drop down which sets Active > Inactive or to Archive ?

Is that correct?

**Comment by jennyq** [comment]
Yes, similar to Active > Expired, we can add a link Active > Inactive (or Expired > Inactive depending on the current status). And add a field inactivate_dt, in the meantime, to track when the membership record is set to inactive. Thoughts?

**Comment by eschipul** [comment]
Closing given the age.
