### ISSUE TITLE
Drop root privileges in Upstart job

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#461]
Hi,
I realised while doing some work today that the upstart job doesn't set the UID/GUID that it runs under in the configuration file.
I assume that means it runs as root?

If thats the case I suggest setuid/gid should be added to the upstart script in the documentation
setuid www-data
setgid www-data

If you agree I'll organise a branch for it.

**Comment by jennyq** [comment]
Hi @goetzk, great catch! :+1:  Yes, go ahead to update it. The permission of the site directory might also need to be updated accordingly. And don't forget to test it. Thanks!

**Comment by goetzk** [comment]
On 17/11/2015 09:14, Jenny Qian wrote:
> Hi @goetzk great catch! :+1: Yes, go ahead
> to update it. The permission of the site directory might also need to be
> updated accordingly. And don't forget to test it. Thanks!

I'll test this out once I finish working on my ansible role so will try
and get a patch to you in a week or so.
kk

**Comment by eschipul** [comment]
@goetzk does ansible also automate docker deployments as most of our internal sites are on dockers and we will get those hub scripts updated after we get the stand alone server files working for our larger clients that need dedicated servers. Just wondering?

**Comment by goetzk** [comment]
I have proposed a fix in #467 .

@eschipul I don't have any experience with docker myself but the ansible people seem to think they work well.
http://www.ansible.com/docker

There is a module for it too.
http://docs.ansible.com/ansible/docker_module.html
