### ISSUE TITLE
Setup issues with migrations

### ISSUE THREAD

**Issue by gbaman** [tendenci/tendenci#462]
Am having issues setting up Tendenci based off the testing documentation - https://tendenci.readthedocs.org/en/latest/installation/installation.html.
All is fine till I reach 
```
bash migrate_initials.sh    
python deploy.py
```
The migrate_initials.sh script works fine, but the ```python deploy.py``` fails with the output below. 
A little bit more digging and have figured out it is ```python manage.py migrate``` that is failing. To clarify, I am not manually killing it.   
```
Operations to perform:
  Synchronize unmigrated apps: django_admin_bootstrapped, tendenci, accounts, formtools, bootstrap3, gis, api_tasty, tinymce, djkombu, theme, humanize, haystack, model_report, gunicorn, tags, staticfiles, sitemaps, registry, pagination, mobile, admindocs, messages, social_media, styled_forms
  Apply all migrations: staff, accountings, redirects, videos, invoices, imports, locations, email_blocks, captcha, navs, meta, explorer_extensions, registration, stories, case_studies, tendenci_guide, contributions, payments, industries, regions, speakers, entities, contacts, event_logs, forums, sites, corporate_memberships, pages, forms, discounts, contenttypes, wp_importer, tagging, site_settings, theme_editor, ics, announcements, social_services, events, careers, avatar, files, studygroups, exports, newsletters, jobs, explorer, sessions, robots, auth, educations, metrics, notifications, boxes, base, campaign_monitor, make_payments, news, emails, categories, articles, search, committees, handler404, photos, admin, perms, directories, versions, djcelery, social_auth, profiles, recurring_payments, memberships, reports, testimonials, donations, dashboard, resumes, help_files, user_groups, wp_exporter
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states...Killed
```     
- Operating system - Ubuntu 14.04 server   
- Python version - Python 2.7.6   
- Django version - 1.8.4   
- PostgreSQL version -  9.3.10

**Comment by jennyq** [comment]
@gbaman, how much RAM does your system have? Looks like it ran out of memory on the command `migrate`. Unlike south migration, Django migration does consume much more memory.

**Comment by poelzi** [comment]
I ran into the same issue. It seems to be fixed in 1.9 but it is not simple to backport. The bash script worked for me however.

**Comment by gbaman** [comment]
Yip, can confirm it was a RAM issue. The VM only had 1GB of RAM allocated as was for testing. When we bumped it up to 2GB, worked fine. Perhaps worth noting this in the documentation as ```Rendering model states...Killed``` doesn't help explain why it was killed much.

**Comment by alabounty** [comment]
So glad for this thread, I spent too much time trying to figure out why this wasn't working.
