### ISSUE TITLE
Latest djcelery breaks migrations

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#465]
I've just done a new install while doing some testing and appear to have encountered celery/django-celery#391:

```
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying djcelery.0001_initial...
:stderr: Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/tendenci/environment/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
[...]
  File "/srv/tendenci/environment/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/srv/tendenci/environment/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "djcelery_crontabschedule" already exists
```

pip has installed django-celery 3.1.17.

```
(environment)root@tendenci:~# pip list|grep cel
celery (3.1.19)
django-celery (3.1.17)
```

After downgrading to 3.1.16 the migration works. I'm not sure what tendenci components rely on django-celery but this will affect all installs going forward unless an explicit depend on 3.1.16 is added.

**Comment by jennyq** [comment]
@goetzk, what version of django was installed with? Thought that django-celery (3.1.17) should work with the latest django 1.8.6. I'll have to test...

**Comment by eschipul** [comment]
Woukrcfunetgubvascwrlll

**Comment by goetzk** [comment]
I still have the problem after updating to django 1.8.6
```
(environment)root@tendenci:~# pip list |grep Django
Django (1.8.6)
(environment)root@tendenci:~# pip list |grep cele
celery (3.1.19)
django-celery (3.1.17)
(environment)root@tendenci:~# 
``

**Comment by rowanseymour** [comment]
Am using Django 1.8.6. djcelery 3.1.17 gives me 

```django.db.utils.ProgrammingError: relation "djcelery_crontabschedule" already exists```

and djcelery 3.1.16 gives me

```django.db.migrations.loader.BadMigrationError: Migrated app u'djcelery' contains South migrations. Make sure all numbered South migrations are deleted prior to creating Django migrations.```

**Comment by jennyq** [comment]
@rowanseymour, the Django 1.8.6 is the latest release. It doesn't work well with djcelery 3.1.16 so we bumped it to 3.1.17. However, if you update tendenci from tendenci version < 7.1.23, you'd need to fake initial for djcelery by running `python manage.py migrate djcelery 0001 --fake`.

@goetzk, I tested the new installation last week, it worked fine for me. Not sure why didn't work for you. Can you please try again?

**Comment by goetzk** [comment]
will do some time in the next week or so (its doubtful but i might have time to try tomorrow arvo)

**Comment by synotna** [comment]
This came up for me today when updating from 3.1.16 to 3.1.17

**Comment by jennyq** [comment]
@goetzk Is this still an issue? Can you please confirm?

**Comment by goetzk** [comment]
Hi @jennyq ,
I've just done an install where I have wound up with tendenci (7.2.17) and django-celery (3.1.16), I had the same failure.

```
\"creating Django migrations.\" % app_config.label\ndjango.db.migrations.loader.BadMigrationError: Migrated app 'djcelery' contains South migrations. Make sure all numbered South migrations are deleted prior to creating Django migrations.\n", 
```

(sorry about the formatting, its been mangled in flight by Ansible)

**Comment by jennyq** [comment]
@goetzk, maybe you can check why you got django-celery (3.1.16). The latest version of tendenci has django-celery (3.1.17) https://github.com/tendenci/tendenci/blob/master/requirements.txt#L33

**Comment by jennyq** [comment]
Closing it... it should work fine for django-celery 3.1.17.

**Comment by tvanesse** [comment]
Upgrading from `django-celery 3.1.16` to `3.1.17` I got the same issue:

```
$ ./manage.py migrate djcelery
Operations to perform:
  Apply all migrations: djcelery
Running migrations:
  Rendering model states... DONE
  Applying djcelery.0001_initial...Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  ... 
  File "/<path>/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "djcelery_crontabschedule" already exists
```

So...

> Closing it... it should be working fine for django-celery 3.1.17.

...doesn't seem to be the case. Am I the only one to experience the problem?

**Comment by goetzk** [comment]
Just did a new install and didn't experience this problem. Unlike previous installs this is ubuntu without a virtualenv but I don't see why that would be relevant.

```
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 3.16.0-4-amd64 x86_64)
```

```
ubuntu@tendenci-web:/srv/tendenci/website$ pip list |grep -e cele -e Django -e tenden
celery (3.1.23)
Django (1.8.14)
django-celery (3.1.17)
tendenci (7.2.34)
```

Hopefully that means we're in the clear, thanks!

**Comment by stevecj** [comment]
I'm experiencing this problem while trying to update from djcelery 3.1.16 to 3.2.1. I am simultaneously upgrading from Django 1.8 to 1.9, and I don't know whether that is contributing to the problem or not.

**Comment by rtindru** [comment]
Also experiencing this issue while upgrading from Django 1.8 to 1.9 and upgrading djcelery from 3.1.16 to 3.2.1

**Comment by jennyq** [comment]
@rtindru, you shouldn't need to upgrade Django manually - the Django will be upgraded automatically along with other dependencies when you update tendenci with

    pip install -r requirements/tendenci.txt --upgrade

or just

    pip install -r requirements.txt --upgrade

Please uninstall Django and djcelery then run the above command. You might need to fake djcelery 0001.

    python manage.py migrate djcelery 0001 --fake

Please note that tendenci is currently compatible to Django 1.8.x.
