### ISSUE TITLE
Changes to Mega Menu  on T7

### ISSUE THREAD

**Issue by bleven** [tendenci/tendenci#469]
When a Member Logged into their Tendenci Website on T5 they had a dropdown called "My Links" which had links to the following information:

"My User Profile"
"My Invoices"
"My Corporate Membership" (if membership rep)
"My Membership"
"My Content"

![t5 my links](https://cloud.githubusercontent.com/assets/4460314/11543058/2d25a762-9900-11e5-9b5b-cda183f05754.png)

These links seem much more logical than what we have on the dropdown now for members:
Listed Under Their Name:
"Profile"
"Members"
"Groups"

Listed Under Community Tab:
"Members"
"Groups"
"Corporate Membership" (Goes to their own corporate membership)
"Forums" (if activated, in screenshot of the attached not activated)
"Email Administrators"

![community t7 dropdown](https://cloud.githubusercontent.com/assets/4460314/11543181/d2258552-9900-11e5-9062-51dbc0b4354f.png)

![t7memberprofile](https://cloud.githubusercontent.com/assets/4460314/11543132/a1a5385a-9900-11e5-85f6-75131cb6630c.png)

Suggesting we change the dropdown underneath a users name to the following:

"My User Profile"
"My Invoices"
"My Corporate Membership" (if membership rep)
"My Membership"
"My Upcoming Events"
"My Content"

Suggesting we change the dropdown underneath "Community" to the following:
"Membership Search" (If membership search enabled)
"Groups"
"Corporate Membership Search" (if corporate membership enabled)
"Forums" (if activated, in screenshot of the attached not activated)
"Email Administrators"

These links should also be enabled for Super Users
![t7 super users](https://cloud.githubusercontent.com/assets/4460314/11543500/a6c65704-9902-11e5-9a33-79f6e0493614.png)

"My User Profile"
"My Invoices"
"My Corporate Membership" (if membership rep)
"My Membership"
"My Upcoming Events"
"My Content"

**Comment by jennyq** [comment]
Mega menu has been updated with the changes 82e1ee3

**Comment by eschipul** [comment]
Thanks y'all. Going to refer some folks over to this for further dialog on how to improve it more.

**Comment by eschipul** [comment]
Completed. Thank you Becky! You can check out what it evolved into at demo.tendenci.com
