### ISSUE TITLE
Reviewing members to import is clunky

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#471]
Hi,
Having made it to the review stage at http://example.com/memberships/import_default/preview/1/ I can only view 11 rows at a time. I have 4040 records to import so reviewing will be tricky.

What I'd like to request is that the number of rows is larger (25,50,100 would all do) and that there is an option to only show entries which will be skipped. I feel that would be most useful as the entries being skipped are more likely to be interesting than those which work.

thanks,

**Comment by jennyq** [comment]
Those are good suggestions. Thanks! I think the first one is easy to achieve - the only trade-off would be the sacrifice of the performance for the preview page. We'll look into it.

**Comment by eschipul** [comment]
workaround - I had a large org with 80k users to import weekly to update their db to keep the data in sync. they wrote an excel macro to take a random sample of the data and do a test import of say 50 to 100 users. After three trial imports they still had to break it into groups of 10k to prevent timeouts.

In a perfect world we'd have rabbigmq or better use of celery to handle the import. And MOST IMPORTANTLY a way of rolling it back if something went wrong. Thus that means a few things.

1) quiet full database backup in the background with an email to the webmaster to let them know what was going on (not us, but you or whoever is the webmaster in sitesettings.py)
2) queue the import job into smaller chunks and submit them with lots of "sleep=2" or similar to prevent degrading site performance.
3) And (ya nobody likes this but I do think it is fair) prevent any database member imports if the "Similar Users Report" has more than 100 people on it. Data integrity is ultimately a human's job, and we do provide the tools.

Blah blah, I agree we can make the user interface less scary. Hopefully you are on T7 and can do an "Export data" from /explorer/ in json format and even test it after importing locally to postgresql. A great way to run custom reports as well.

All of that said, 4k is a small-ish import. Just be careful on your match type and delete questionable fields and only update fields that are present. Larger clients have run load balancers, cookie routing, huge dbs in the backend and cache for non-logged in users to get to some significant scale. Always fun to play with that stuff.

Closing this one. Feel free to resubmit with some exact specifics and suggestions with links (use demo.tendenci.com for links if you wish) and break it into manageable chunks as your ideas are very much aligned with ours. Serve the membership first! Thanks!

**Comment by eschipul** [comment]
ps - login for demo.tendenci.com is "admin/admin" just please realize it resets every couple of hours completely. Containers are awesome.
