### ISSUE TITLE
Is there a e-Commerce module?

### ISSUE THREAD

**Issue by linb** [tendenci/tendenci#473]
Or in progress?

**Comment by eschipul** [comment]
Sorry for the delay responding @linb . We currently don't have plans for an ecommerce module given the availability of options like shopify and SAML authentication. Basically trying not to reinvent the wheel but tackle the areas of complexity with NPOs that aren't addressed by traditional CMS systems or are overpriced in the proprietary software sector.

That said, if you know of a great django shopping cart there is no reason they can't be loosely coupled with social auth, right? Let us know if you have any ideas please!
