### ISSUE TITLE
User Profile Picture - Upload Error

### ISSUE THREAD

**Issue by Screamingkiwi** [tendenci/tendenci#481]
I am unable to upload profile pictures via the PROFILE tab. I can upload via the backend but not the front end which is ok for me but not for general users. 
[KeyError at :profiles:avatar:76:.pdf](https://github.com/tendenci/tendenci/files/112245/KeyError.at.profiles.avatar.76.pdf)

**Comment by eschipul** [comment]
I recommend we switch the whole site to use gravatar like wordpress does to avoid the registered users uploading and renaming hacks.

The forums module already functions this way. And I see no harm in gravatar given you can associate multiple email addresses with it.

**Comment by jennyq** [comment]
Pushed out a fix https://github.com/tendenci/tendenci/commit/07b349e923b279ce0d6b8161436325ba137e8381

@eschipul Should we completely **replace** avatar with gravatar? Or should we integrate gravatar like forums does, meaning pulling gravatar image only when there is no avatar for the user?

**Comment by jennyq** [comment]
The avatar upload will be removed and avatars will be replaced with gravatars #499.
