### ISSUE TITLE
No Delete Link for Header Images on Pages

### ISSUE THREAD

**Issue by bleven** [tendenci/tendenci#486]
Tendenci Page Add www.example.com/pages/add/ includes a field "Header image". 

Image uploads to Tendenci fine using that field, but once the image is uploaded, there is no link that allows a user to delete the header image. 

We need to integrate a link that allows for deleting of the image.

**Comment by eschipul** [comment]
Agreed. Need to research if we hard coded from the old system the file size for image headers or if there is another legitimate reason.

So while I *do* agree with your ticket and that it is an issue, given you can pull down the template and do a quick work around I'm going to leave this as an 8.x clean up issue.

**Comment by jennyq** [comment]
@bleven, you **can** remove the image after uploading. On page edit, there is a checkbox under the Header image field "Remove current image:xxx". https://www.tendenci.com/pages/edit/266/
