### ISSUE TITLE
ImportError: No module named tendenci.settings

### ISSUE THREAD

**Issue by mattscott** [tendenci/tendenci#487]
Hi there,

I am really sorry if this has been asked before.
I did a search and couldn't find the answer to my question.

I am using A2Hosting and FastCGI.

I used their install guide here for Django:
https://www.a2hosting.com/kb/developer-corner/python/installing-and-configuring-django-with-fastcgi-on-shared-hosting

Everything went well with the "mysite" install of Django (their default name in the instructions).

I then start using this install guide for tendenci itself:
https://tendenci.readthedocs.org/en/latest/installation/installation.html

My folder structure from the Home directory now looks like this:

/home/donateah/
-->djangoenv <-- this is my virtualenv
----->bin
------->(bunch of django dependencies and django libs ie. django-authority, django-avatar)
------->tendenci
----->build
----->include
----->lib
----->lib64
-->public_html
----->mysite (leftover from the a2hosting install)
----->tendenci (this is my <project_name>)

I get all the way down to the Setting up the Site section successfully in your guide.
However, when I run: bash migrate_initials.sh

It goes through a bunch of stuff but errors with the same error for each of them:
ImportError: No module named tendenci.settings

I get the attached error.
![error-1](https://cloud.githubusercontent.com/assets/1444130/13766480/fe2f2216-ea59-11e5-8576-6b4aa0912066.jpg)

Thanks,
Matt

**Comment by jennyq** [comment]
@mattscott what version of django did you install in your environment? Can you please do a `pip freeze` then paste the result here?

**Comment by mattscott** [comment]
Here you go:

(djangoenv)donateah@a2ss24 [~]# pip freeze
Django==1.8.7
Paste==2.0.3
flup6==1.1.1
psycopg2==2.6.1
six==1.10.0
wsgiref==0.1.2
(djangoenv)donateah@a2ss24 [~]#

**Comment by jennyq** [comment]
Your environment doesn't have tendenci installed. Are you using virtualenv? If so, you'll need to remove `sudo` from the commands `pip install xxx` while following the guide https://tendenci.readthedocs.org/en/latest/installation/installation.html#installing-the-requirements

**Comment by mattscott** [comment]
I have run the pip install xxx command several times.

Here is the output:

(djangoenv)donateah@a2ss24 [~/public_html/tendenci]# pip install -r requirements/dev.txt                                      
Downloading/unpacking tendenci>=7,<8 (from -r requirements/tendenci.txt (line 2))
  Running setup.py egg_info for package tendenci

Requirement already satisfied (use --upgrade to upgrade): Django>=1.8,<1.9 in /home/donateah/djangoenv/lib/python2.7/site-packages (from tendenci>=7,<8->-r requirements/tendenci.txt (line 2))
Downloading/unpacking django-formtools>=1.0 (from tendenci>=7,<8->-r requirements/tendenci.txt (line 2))
  Running setup.py egg_info for package django-formtools

Downloading/unpacking pisa (from tendenci>=7,<8->-r requirements/tendenci.txt (line 2))
  Running setup.py egg_info for package pisa

Downloading/unpacking Reportlab==2.5 (from tendenci>=7,<8->-r requirements/tendenci.txt (line 2))
  Running setup.py egg_info for package Reportlab
    ################################################
    #Attempting install of _rl_accel, sgmlop & pyHnj
    #extensions from '/home/donateah/djangoenv/build/Reportlab/src/rl_addons/rl_accel'
    ################################################
    ################################################
    #Attempting install of _renderPM
    #extensions from '/home/donateah/djangoenv/build/Reportlab/src/rl_addons/renderPM'
    # installing with freetype version 21
    ################################################
    Downloading standard T1 font curves
    Finished download of standard T1 font curves


    ########## SUMMARY INFO #########
    ################################################
    #Attempting install of _rl_accel, sgmlop & pyHnj
    #extensions from '/home/donateah/djangoenv/build/Reportlab/src/rl_addons/rl_accel'
    ################################################
    ################################################
    #Attempting install of _renderPM
    #extensions from '/home/donateah/djangoenv/build/Reportlab/src/rl_addons/renderPM'
    # installing with freetype version 21
    ################################################
    Downloading standard T1 font curves
    Finished download of standard T1 font curves
Downloading/unpacking html5lib (from tendenci>=7,<8->-r requirements/tendenci.txt (line 2))
  Running setup.py egg_info for package html5lib

Downloading/unpacking Pillow==2.8.2 (from tendenci>=7,<8->-r requirements/tendenci.txt (line 2))
  Running setup.py egg_info for package Pillow

    warning: no files found matching 'LICENSE' under directory 'docs'
Downloading/unpacking anyjson>=0.2.4 (from tendenci>=7,<8->-r requirements/tendenci.txt (line 2))
  Running setup.py egg_info for package anyjson

Downloading/unpacking django-authority>=0.4 (from tendenci>=7,<8->-r requirements/tendenci.txt (line 2))
  Running setup.py egg_info for package django-authority

    warning: no files found matching '*.html' under directory 'docs'
    warning: no previously-included files matching '*.txt' found under directory 'docs/build'
    no previously-included directories found matching 'docs/build/html/_sources'
Downloading/unpacking django-avatar==2.2.1 (from tendenci>=7,<8->-r requirements/tendenci.txt (line 2))
  Running setup.py egg_info for package django-avatar

Downloading/unpacking django-countries==3.3 (from tendenci>=7,<8->-r requirements/tendenci.txt (line 2))
  Running setup.py egg_info for package django-countries

Downloading/unpacking django-form-utils>=0.1.8 (from tendenci>=7,<8->-r requirements/tendenci.txt (line 2))
  Running setup.py egg_info for package django-form-utils

Downloading/unpacking django-localflavor==1.1 (from tendenci>=7,<8->-r requirements/tendenci.txt (line 2))
  Running setup.py egg_info for package django-localflavor

    warning: no files found matching '*.txt' under directory 'requirements'
Downloading/unpacking django-pagination>=1.0.7 (from tendenci>=7,<8->-r requirements/tendenci.txt (line 2))
  Running setup.py egg_info for package django-pagination

Downloading/unpacking django-picklefield>=0.1.6 (from tendenci>=7,<8->-r requirements/tendenci.txt (line 2))
  Running setup.py egg_info for package django-picklefield

Downloading/unpacking django-simple-captcha==0.4.6 (from tendenci>=7,<8->-r requirements/tendenci.txt (line 2))
  Could not find a version that satisfies the requirement django-simple-captcha==0.4.6 (from tendenci>=7,<8->-r requirements/tendenci.txt (line 2)) (from versions: )
No distributions matching the version for django-simple-captcha==0.4.6 (from tendenci>=7,<8->-r requirements/tendenci.txt (line 2))
Storing complete log in /home/donateah/.pip/pip.log
(djangoenv)donateah@a2ss24 [~/public_html/tendenci]#


Looking at this, it seems to get hung up on django-simple-captcha and stops.

Here is "pip freeze" after running:
(djangoenv)donateah@a2ss24 [~/public_html/tendenci]# pip freeze
Django==1.8.7
Paste==2.0.3
flup6==1.1.1
psycopg2==2.6.1
six==1.10.0
wsgiref==0.1.2
(djangoenv)donateah@a2ss24 [~/public_html/tendenci]#

**Comment by mattscott** [comment]
Okay.

Looks like I was able to hack around and get django-simple-captcha 0.5.1 installed. Did the pip install command after that, and them modified the version of django-simple-captcha in the requirements/tendency.txt file. Re-ran the pip install for tendency, and the install completed.

**Comment by mattscott** [comment]
Hmm...

Running python deploy.py:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/donateah/djangoenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/donateah/djangoenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/donateah/djangoenv/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/donateah/djangoenv/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/donateah/djangoenv/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 91, in handle
    connection.prepare_database()
  File "/home/donateah/djangoenv/lib/python2.7/site-packages/django/contrib/gis/db/backends/postgis/base.py", line 39, in prepare_database
    cursor.execute("CREATE EXTENSION IF NOT EXISTS postgis")
  File "/home/donateah/djangoenv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/donateah/djangoenv/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/donateah/djangoenv/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: permission denied to create extension "postgis"
HINT:  Must be superuser to create this extension.

Traceback (most recent call last):
  File "deploy.py", line 3, in <module>
    subprocess.check_call(['python', 'manage.py',  'migrate', '--noinput'])
  File "/usr/lib64/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', 'manage.py', 'migrate', '--noinput']' returned non-zero exit status 1

**Comment by mattscott** [comment]
NOTE: I had to contact the hosting provider to get them to add the PostGIS Extension for me.

**Comment by mattscott** [comment]
Okay.. making progress.

Tendenci now runs on the development server over port 8000 using:
python manage.py runserver

However I'm having problems getting the .htaccess and fastcgi file to redirect standard apache traffic into Tendenci.

When I try to hit the site, I get an error 500. Unfortunately no error shows up in the apache logs or django logs, so I have no apparent way to troubleshoot this.

The structure of the server is:
--> public_html <dir>
----> .htaccess
----> tendency.fcgi
----> tendency <dir>
------> conf
--------> settings.py

My .htaccess is set to permissions 644:
AddHandler fcgid-script .fcgi
RewriteEngine on
# Set up static content redirect:
RewriteRule static/(.+)$ tendenci/static/$1
# The following two lines are for FastCGI:
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ tendenci.fcgi/$1 [QSA,L]

My tendency.fcgi is set to permissions 755:
#!/home/donateah/.virtualenvs/djangoenv/bin/python
import os, sys

_PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _PROJECT_DIR)
sys.path.insert(0, os.path.dirname(_PROJECT_DIR))

_PROJECT_NAME = _PROJECT_DIR.split('/')[-1]
#os.environ['DJANGO_SETTINGS_MODULE'] = "%s.conf.settings" % _PROJECT_NAME
os.environ['DJANGO_SETTINGS_MODULE'] = "conf.settings"

from django.core.servers.fastcgi import runfastcgi
runfastcgi(method="threaded", daemonize="false")

I have tried both the "conf.settings" and "%s.conf.settings" versions of the tendenci.fcgi file.

pip freeze shows:
BeautifulSoup==3.2.1
Django==1.8.7
Embedly==0.5.0
Geraldo==0.4.16
Markdown==2.6.5
Paste==2.0.3
Pillow==2.8.2
Unidecode==0.04.19
Whoosh==2.7.0
amqp==1.4.9
anyjson==0.3.3
beautifulsoup4==4.3.2
billiard==3.3.0.23
boto==2.38.0
celery==3.1.19
chardet==2.3.0
createsend==3.3.0
django-admin-bootstrapped==2.5.2
django-annoying==0.9.0
django-app-namespace-template-loader==0.3
django-appconf==1.0.1
django-authority==0.10
django-avatar==2.2.1
django-bootstrap-form==3.2
django-bootstrap3==5.4.0
django-celery==3.1.17
django-countries==3.3
django-debug-toolbar==1.4
django-form-utils==1.0.3
django-formtools==1.0
django-haystack==2.4.0
django-kombu==0.9.4
django-localflavor==1.1
django-markdown-deux==1.0.5
django-pagination==1.0.7
django-picklefield==0.3.2
django-ses==0.7.0
django-simple-captcha==0.5.1
django-sql-explorer==0.8
django-storages==1.1.8
django-tagging==0.3.6
django-tastypie==0.12.2
django-timezones==0.2
django-tinymce==1.5.2
docutils==0.12
email-reply-parser==0.3.0
feedparser==5.2.1
flup6==1.1.1
gunicorn==19.3.0
html5lib==1.0b8
httplib2==0.9.2
kombu==3.0.34
markdown2==2.3.1
mimeparse==0.1.3
oauth2==1.9.0.post1
ordereddict==1.1
pdfminer==20110515
pisa==3.0.33
psycopg2==2.6.1
pycrypto==2.6.1
python-dateutil==2.4.2
python-memcached==1.54
python-mimeparse==1.5.1
python-openid==2.2.5
pytz==2015.4
raven==5.1.1
reportlab==2.5
requests==2.9.1
selenium==2.46.0
simple-salesforce==0.67.2
simplejson==3.8.2
six==1.10.0
sqlparse==0.1.19
stripe==1.22.3
tendenci==7.1.397
unicodecsv==0.14.1
webcolors==1.5
wsgiref==0.1.2
xlrd==0.9.3
xlwt==1.0.0

**Comment by mattscott** [comment]
Okay. I figured this out by moving the /public_html/tendenci files to /public_html.
