### ISSUE TITLE
Javascript Erros in Event Creation

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#489]
Bad masonry element: null
ReferenceError: toggle_cusomt_reg_form is not defined.

I just made a fresh install of Tendenci and I am getting this errors in browser console when adding a new event.

**Comment by dco5** [comment]
Where do you guys masonry and for what? Maybe I can help find the problem. Every page I look at has the masonry error.

**Comment by eschipul** [comment]
Masonry is used on a few custom layouts, and I know photologue is outdated. In an ideal world Masonry would be used in photos. All of this goes to say we might not need it at all with 7.x+. 

@jennyq can you think of any reason it would be included?

**Comment by jennyq** [comment]
It's NOT in core, but in the boomerang theme. It's possible that when the boomerang layout was converted to a tendenci theme, it missed some container(s) that masonry.js is looking for. The script is here https://github.com/tendenci/tendenci-project-template/blob/master/themes/boomerang/media/assets/masonry/masonry.js. Need to take a close look at and figure out what is missing.

**Comment by jennyq** [comment]
Pushed a fix to the tendenci-project-template repo https://github.com/tendenci/tendenci-project-template/commit/245114d51cc549e73898c3efab3d676e3426f5d2

**Comment by jennyq** [comment]
The other JS error "ReferenceError: toggle_cusomt_reg_form is not defined" has also been fixed. https://github.com/tendenci/tendenci/commit/d0aefa651378c56be22295b83c95356952390ba4 

Thank you @dco5
