### ISSUE TITLE
Viewing Profiles when using Custom Fields

### ISSUE THREAD

**Issue by mattscott** [tendenci/tendenci#490]
I want to start by thanking the entire Tendenci team for such a great product. I've posted several times, and I feel like this has been a big learning curve, but the site is nearly there now.

At this point, I've got my membership form setup, but due to the oddball nature of our club, we have mostly custom questions and didn't use many of the stock fields. I used user_define fields for the custom questions, which seems to have worked well.

Filling out the membership form works great.

Scenario 1: REGULAR user viewing their own membership

I log in as a REGULAR user, click on My Membership, which takes me to:
http://tempsite.com/memberships/XX/ <--- Where XX is my membership id.
This also works great. Many of the custom field values are displayed in read-only format here.

Then I click on Edit Your Membership towards the top of the displayed info, and I go to:
http://tempsite.com/memberships/applications/XX/edit/

ISSUE #1: This mostly works, because the custom fields are all editable, except ALL of the Choice fields which were drop downs when I initially filled out the form, are now text fields that I can enter whatever I want.

Scenario 2: ADMIN user looking at the same REGULAR membership

If I log out and log in as an ADMIN and I look up that same REGULAR member, the result looks different. I search for the user, open his profile, then click on his membership to go to the same url:
http://tempsite.com/memberships/XX/ <--- Where XX is my REGULAR membership id.

ISSUE #2: If I click on Edit Your Membership towards the top of the displayed info, I go to:
http://tempsite.com/admin/memberships/membershipdefault/XX/?next=/memberships/XX/

This form shows all of the regular fields (70% of which I didn't use in the membership form) and no custom fields at all.

Is there a way to address these two issues?

Thanks,
Matt

**Comment by mattscott** [comment]
Following up on this.

**Comment by jennyq** [comment]
@mattscott, 

For the ISSUE #2, you can see the custom fields under the section Demographics on http://tempsite.com/admin/memberships/membershipdefault/XX/. 

For ISSUE #1, we're aware of it, but it won't be addressed pretty soon because it takes time. I'd suggest to turn off the membership edit for regular users for now. They can edit their profiles anyway.

**Comment by jennyq** [comment]
ISSUE #1 has been resolved. Please update your site with the latest version of Tendenci.
