### ISSUE TITLE
Membership Notices not being sent

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#491]
We just look at the logs for membership renewal notices and expired membership and they are not being sent at all. They are all suppose to be active. The last time the notices were sent was in 2014. How are notices handled? Does the system use a cron job to do this? How can I check if they are working?

**Comment by jennyq** [comment]
The notices are handled via the management command `run_nightly_commands`, which should be scheduled as a cron job. So, please check if the command is on the crontab. http://tendenci.readthedocs.org/en/latest/installation/installation.html#set-up-cron-jobs-for-production-sites

**Comment by dco5** [comment]
Thank you for that, I am getting
30: command not found 
When using:
30 2 * * * /path/to/virtualenv/bin/python /path/to/tendenci/site/manage.py run_nightly_commands
*/60 * * * * /path/to/virtualenv/bin/python /path/to/tendenci/site/manage.py process_unindexed

Any suggestions? I am using the correct path to the virtualenv python and the site dir

**Comment by dco5** [comment]
Do I add this using crontab -e?

**Comment by jennyq** [comment]
Yep

**Comment by dco5** [comment]
Awesome, Thanks!
