### ISSUE TITLE
State Field defaults to AK

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#492]
When a Member is renewing the State field will default to AK always, does not matter if member is from another state. It is very frustrating because since the member sees all the fields completed with his correct info, he does not pause to check the state. Almost ALL members that renew will renew with AK as their state. I just found this out, now I have send emails to all members asking the please correct their state.

**Comment by jennyq** [comment]
@dco5, Did you set up the State field as a Drop Down field with the choices like "AK,..."? To fix the issue, please try to prepend a comma to the choices like this ",AK,...".

**Comment by dco5** [comment]
@jennyq It now defaults to empty, which is much better than defaulting to AK, but ideally it would load the state automatically when renewing membership to the member's state, just like it autoloads all the other information of the member, like address, phone, city, name, etc., but this will work too, specially if the field is required.

**Comment by jennyq** [comment]
It **does** load the state automatically when renewing membership to the member's state if and only if the member's state matches with one of the choices in the State dropdown. Does that make sense?

**Comment by dco5** [comment]
Yes it does make sense now, my bad, I had a space between, , AK, TX, FL, .... that is why it was not matching. Maybe add no spaces between the commas to the help text? But then people will think that no spaces are allowed, which is not the case, is just not spaces after the comma.

**Comment by jennyq** [comment]
Good point. Will update the code to strip the spaces for the choices.
