### ISSUE TITLE
Print-view link mandatory?

### ISSUE THREAD

**Issue by jamesoflol** [tendenci/tendenci#495]
Hi,

Please tell me if I'm missing something here -

I'm not a big fan of the 'print' link at the bottom of each page (and event, news, etc). As far as I can see, there's no way to remove it without changing code. At least in the events app, the link has a CSS class that I could style out of existence:

apps/events/templates/events/meta.html:
`44: <a class="t-meta-print-link" href="{% url "event.print_view" event.pk %}">` ...

But most others seem to not have this class:

apps/pages/templates/pages/meta.html:
`85: {% if page.slug %}<li><a href="{% url 'page.print_view' page.slug %}">` ...

I'm happy to do the work and submit a pull request, if you give the go-ahead for me to add .t-meta-print-link to that link on every app's meta.html page.

Cheers,
James

**Comment by jennyq** [comment]
That's a good idea! Please do go ahead and submit a pull request. Thanks!

**Comment by eschipul** [comment]
Two thoughts - the goal was to have condensed content for SEO that was not cluttered with the typical nav bar and other link rich content which lowers page authority. You can remove this in your templates of course, just realize print views tend to score well particularly if included in sitemap.xml

Closing older tickets. Please create a new ticket if this is still an issue after confirming you are running the latest version.

Ed
