### ISSUE TITLE
subprocess.Popen not running

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#496]
I just made a fresh of Tendenci for an organization and anything that is using subprocess.Popen(["python", "manage.py", ...
Does not want to run, but if I comment the line and run the command without subprocess it runs ok.
I am having that problem with exports and imports. 

Also the notices are not sending even after I added them to crontab. I am getting an email at 2am that all task are running, but still no notices.

Any ideas?

**Comment by jennyq** [comment]
Was it on Ubuntu? What version? And does the site use virtualenv?

**Comment by dco5** [comment]
Ubuntu 14.04 LTS, yes it is using virtualenv.

**Comment by jennyq** [comment]
What is the wsgi server? gunicorn or uwsgi?

**Comment by dco5** [comment]
gunicorn, I followed the instructions from the installation guide, I am using pretty much what  default Tendenci installation uses.

**Comment by jennyq** [comment]
Hmm, no idea. I only saw this happened on uwsgi with virtualenv. 

To exclude if it's not a server problem, can you create a simple python script to see if subprocess works on that server?

**Comment by dco5** [comment]
I created a simple python script and it work doing a subprocess.

**Comment by jennyq** [comment]
Hi @dco5, I did some testing and think you'll need to activate the virtualenv before executing gunicorn in your upstart script. I've updated the doc here http://tendenci.readthedocs.io/en/latest/installation/installation.html#setting-up-upstart.

**Comment by dco5** [comment]
@jennyq YES IS WORKING NOW!!!! THANKS!! This was driving me crazy, I had to create a whole bunch of addons to do the processes without the subprocess.Popen, I can get rid of them

**Comment by jennyq** [comment]
Grad to hear!
