### ISSUE TITLE
Accessing Custom Fields

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#497]
How would I access the custom fields for the membership. Basically the User Defined fields, through the Membership model, Profile model, User model?

I need to create a report based on the User Defined 1 and 2. I am getting all active members:
mems = MembershipDefault.objects.filter(status=True, status_detail="active")
But now I am stuck trying to figure out how to access those fields.

**Comment by jennyq** [comment]
The user defined fields can be accessed through MembershipDemographic model https://github.com/tendenci/tendenci/blob/master/tendenci/apps/memberships/models.py#L2509

**Comment by dco5** [comment]
Perfect! Thanks!
