### ISSUE TITLE
Imported Members ALREADY_ACTIVATED

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#498]
I imported some members, but they they are all expired, we needed to import them so we could send them emails to renew their membership. Now when they go to renew their membership, they get a message : 

> This email "%s" is associated with previous site activity.
>                     Please click %s and we'll send you an email to activate your account and then you 
>                     will be returned to this application.

So they click on the activation link on the email, and the app proceeds to do the activation.
In line 53 of registration/models [Line 53](https://github.com/tendenci/tendenci/blob/master/tendenci/apps/registration/models.py#L48-L54) checks to see if activation_key_expired() inside activation_key_expired [Line 247](https://github.com/tendenci/tendenci/blob/master/tendenci/apps/registration/models.py#L247-L250) it checks is status is ALREADY_ACTIVATED and all the members that are imported are already activated. So there is now way for this members to activate their account and renew their membership. We can erase the members, but then we would lose all their information.

**Comment by jennyq** [comment]
@dco5, I did some digging, but really couldn't replicate the issue. They might already have their user accounts (submitting a contact form creates an inactive account) before you imported them. The activation is processed by the registration module which won't be touched by the membership import. The ALREADY_ACTIVATED status can only be marked when someone clicked the activation link.

A quick fix for you is to fix it at the database level - to activate all users, just set **is_active** field to True in auth_user table.

**Comment by dco5** [comment]
Yes that is exactly what I did, thanks!
