### ISSUE TITLE
Mega Menu - Events Tab Listing too long

### ISSUE THREAD

**Issue by ediaz1** [tendenci/tendenci#500]
When viewing an event in full view the "Events" tab at top, in the mega menu, when clicked shows a long list and cuts off on the 13 inch mac book air screen. It doesn't scroll anywhere to see the rest of the listings.

Example page: [http://create-project.tendenci.net/events/1/](url)
Cuts off after "Roster Report".

**Comment by eschipul** [comment]
Is this on Tendenci 5.x or on 7.x? click support and the version number should display. This is a known issue on 5.x but should not be an issue on bootstrap3 7.x. I am betting this is our error, that we missed something, I am only asking for clarification to be sure we are chasing the correct error. And thank you for submitting the bug!

**Comment by jennyq** [comment]
@ediaz1, I've made dropdown scrollable if too long. In the meantime, I've changed the dropdown list to become 2 columns instead of 1 column. http://create-project.tendenci.net/events/1/
