### ISSUE TITLE
Migration error 

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#501]
I updated tendenci to 7.2.17 
I did migrate and got 
CommandError: Conflicting migrations detected (0004_auto_20160601_2153, 0006_remove_event_group in events).
To fix them run 'python manage.py makemigrations --merge'

so I did the merge and now I have this error in the website:
ProgrammingError: column events_event.group_id does not exist
LINE 1: ...event"."external_url", "events_event"."image_id", "events_ev...
^

**Comment by dco5** [comment]
I dunno what I did, but it asked me to merge again so I said yes and now is working.

**Comment by jennyq** [comment]
That's odd - the migration `0004_auto_20160601_2153` is **not** the same as the one in the core, `0004_auto_20160603_1347`. https://github.com/tendenci/tendenci/tree/master/tendenci/apps/events/migrations. Where did you get this `0004_auto_20160601_2153` from?

**Comment by BenSturmfels** [comment]
@jennyq the requester mentioned they have resolved this, so safe to close.

**Comment by jennyq** [comment]
Closing it. Thanks!
