### ISSUE TITLE
bootstrap-navbar.css in two places for no reason?

### ISSUE THREAD

**Issue by jamesoflol** [tendenci/tendenci#502]
tendenci/apps/memberships/templates/memberships/details.html 
tendenci/apps/memberships/templates/memberships/details_print.html 

\<link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap-navbar.css"\>

I can't find a reason for it. Removed from my inspector to no ill effect. Unless someone can tell me why, I'm going to assume it's accidental (and years old) junk, and I'll put in a PR?

Thanks

**Comment by jennyq** [comment]
Yes, please go ahead. The previous version of bootstrap in Tendenci didn't have the navbar functionality included. With the bootstrap3, the bootstrap-navbar.css is no longer needed.

**Comment by jennyq** [comment]
Removed https://github.com/tendenci/tendenci/commit/4ef1c7cbfb85ca365121214fa5920e1c177222cd Thanks!
