### ISSUE TITLE
Invoice hiccup

### ISSUE THREAD

**Issue by gccfla** [tendenci/tendenci#506]
On the Membership Invoice, the 'Sub Total:' matches 'Total:'  despite intervening, nozero 'Tax:'

Screenshot fragment: 
![shot](https://cloud.githubusercontent.com/assets/20501923/16903651/f4298eaa-4c51-11e6-98db-847d5ce8ea3c.png)

**Comment by jennyq** [comment]
Fixed in the "Sub Total" calculation https://github.com/tendenci/tendenci/commit/b9f7dd9fc4ee0d2d7dfeb92f8725be18d2a58465
