### ISSUE TITLE
Update for Invoice display

### ISSUE THREAD

**Issue by JustinLewisSMA** [tendenci/tendenci#509]
Many members have other people registering them for events. In a lot of situations, the person doing the registration uses multiple different credit cards. The existing Invoices they receive do not give the registrant enough information to determine which card was used for the transaction. I recommend adding to the invoice a line that is similar to:
Visa 4963

Where the 4963 is the last 4 digits of the card that was used. I recommend putting this next to "Method" and replacing where it says "cc".

Also, while updating this, the word "Method" needs a colon at the end to be consistent with the rest of the document.

![invoice](https://cloud.githubusercontent.com/assets/10035936/17950649/61f08dee-6a11-11e6-8c9f-a5cbc40dcb9f.png)

**Comment by jennyq** [comment]
The missing colon has been added https://github.com/tendenci/tendenci/commit/8646e4851c4f0f37593dfb51fd8790ce7f523d87

**Comment by jennyq** [comment]
@JustinLewisSMA , I think it's a nice-to-have feature. However, I'm not sure if it requires PCI compliance if the card type and the last 4 digits of card (e.g. `Visa 4963`) are stored on the site.

@eschipul any thoughts on this?

**Comment by JustinLewisSMA** [comment]
According to page 15 of this: https://www.pcisecuritystandards.org/documents/pci_ssc_quick_guide.pdf

> 3.3 Mask PAN when displayed; the first six and last four digits are the maximum number of digits 
you may display. Not applicable for authorized people with a legitimate business need to see 
the full PAN. Does not supersede stricter requirements in place for displays of cardholder data 
such as on a point-of-sale receipt.

You can display the first 6 and last 4. So doing just the last 4 seems fine. Card type can be determined (mostly) by the first digit as well, so that means displaying card type and last 4 seems like you'd retain compliance just fine.
