### ISSUE TITLE
502 bad gateway and gunicorn missing

### ISSUE THREAD

**Issue by matthewlehew** [tendenci/tendenci#516]
I'm following the installation instructions in the 7.2.41 documentation on an AWS EC2 instance running Ubuntu 14.04.5. When completing the Testing Installation and converting it to a Scalable Installation, I'm getting 502 Bad Gateway errors when trying to access the site. Everything seems to go well when installing, however. 

There is one thing I've noticed: the Upstart script provided contains the following line:

`exec /srv/tendenci/venv/bin/gunicorn -w 2 -b 127.0.0.1:8000 conf.wsgi --max-requests 350`

But when looking in the directory, the gunicorn folder is not present. This is after completing the creation of the virtualenv with:

`sudo virtualenv venv`

`source venv/bin/activate`

I confess I don't know a lot about Django or Virtualenv, so is there a step I'm missing to manually install gunicorn? Additionally, I've noticed that when following the instructions to the letter, I still have to use `sudo` even when the virturalenv is activated.

Any thoughts or troubleshooting tips would be fantastic!

**Comment by eschipul** [comment]
If you installed the virtualenv as "sudo su" - meaning "root" - that would explain it. 

A few questions:
1) Is this the only site on your server? If so you could just change upstart to forward to port 80 (or better yet set up ssl and use 443). 
2) don't post it publicly but you can do at a server level (not in the virtualenv) something like
ls -altF
to check your permissions. Another useful utility is "tree" which would be "sudo apt-get install tree" to see your directory structure. I'd look at the root of your web and your nginx first. because nginx should be catching the gunicorn port 8000 and forwarding it over 80.

Also please look in /var/logs/nginx/ and post those perhaps? 

Lastly turn on "debug" in your "settings.py" file and post what you can share publicly. (watch for exposure of secure stuff - don't post that. If it is required post it in a hidden gist and message me a private gist link and change it later.)

Tying to help. It's late. So any further info is appreciated like OS? version? ("sudo uname -r") etc... and the version of Tendenci (hopefully 7.2+).

**Comment by matthewlehew** [comment]
Thank you for the response! I actually nuked the installation last night to start over, but I'm working through it again. This is the only site on the server.

Here are the specs for the server environment:

- Ubuntu 14.04.5 LTS
- Kernel release: 3.13.0-91-generic
- Tendenci version: 7.2
- Python version: 2.7.6
- Following instructions at: http://tendenci.readthedocs.io/en/latest/installation/installation.html

The AWS way of provisioning Ubuntu servers involves a rootless method where I connect as a user called "ubuntu," which has sudo privileges. I don't do anything with sudo su, either. 

I've noticed that installing pip via the second method (which I do because my Python version is less than 2.7.9) causes all pip actions to face an InsecurePlatformWarning. Also, the instructions say that doing anything in venv allows me to do not use sudo, but I haven't found that to be the case. On the next step, installing Django in venv, if I don't use sudo I get an exception. Here's the readout from creating venv and trying to install Django:

```
ubuntu@ip-10-0-31-24:/srv/tendenci$ sudo virtualenv venv
New python executable in /srv/tendenci/venv/bin/python
Installing setuptools, pip, wheel...done.
ubuntu@ip-10-0-31-24:/srv/tendenci$ source venv/bin/activate
(venv) ubuntu@ip-10-0-31-24:/srv/tendenci$ pip install "Django>=1.8,<1.9"
Collecting Django<1.9,>=1.8
/srv/tendenci/venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/srv/tendenci/venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading Django-1.8.15-py2.py3-none-any.whl (6.2MB)
    100% |████████████████████████████████| 6.2MB 234kB/s
Installing collected packages: Django
Exception:
Traceback (most recent call last):
  File "/srv/tendenci/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/srv/tendenci/venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/srv/tendenci/venv/local/lib/python2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/srv/tendenci/venv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/srv/tendenci/venv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/srv/tendenci/venv/local/lib/python2.7/site-packages/pip/wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/srv/tendenci/venv/local/lib/python2.7/site-packages/pip/wheel.py", line 317, in clobber
    ensure_dir(destdir)
  File "/srv/tendenci/venv/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/srv/tendenci/venv/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/srv/tendenci/venv/lib/python2.7/site-packages/django'
```

It looks like creating venv with sudo is making all of the folders associated with it to be owned by root. Is that desired behavior?

I also read elsewhere that invoking sudo in an active venv passes in a lot of system settings and destinations as opposed to the environment settings, although I don't know enough to know if that's true. If it is, however, that may explain the missing gunicorn and my 502.

**Comment by eschipul** [comment]
late reply. In my VMs and on AWS, yes I do have to install "pip" by doing a "sudo su" first. After that I exit back to the "ubuntu" user (well, I always rename the ubuntu user but that's another topic). and proceed from there.

If this is still an issue running the latest release please let us know.
