### ISSUE TITLE
How to use new middleware

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#519]
Hi,
I can't seem to figure out how to add new middleware to Tendenci (for example http://django-pipeline.readthedocs.io/en/latest/ or https://pypi.python.org/pypi/django-htmlmin). I can't seem to figure out the magic incantation to make it work - is it supported?
I thought it might be me so tried to enable the django-debug-toolbar - which failed as well. 

Is this a bug?

I'm using 7.2.34 on Ubuntu 14.04.

thanks,
kk

**Comment by jennyq** [comment]
@goetzk , you can add new middlewares in the `conf/local_settings.py`. For example, if you want to add two middlewares for `django-htmlmin`, append the following code to your `conf/local_settings.py`.

    MIDDLEWARE_CLASSES = get_setting('MIDDLEWARE_CLASSES')
    MIDDLEWARE_CLASSES += (
        'htmlmin.middleware.HtmlMinifyMiddleware',
        'htmlmin.middleware.MarkRequestMiddleware',
    )

**Comment by jennyq** [comment]
And to enable the `django-debug-toolbar`, just change the setting `DEBUG_TOOLBAR` from `False` to `True` https://github.com/tendenci/tendenci-project-template/blob/master/conf/local_settings.py#L146 Note that the `DEBUG` should be set to `True` as well in order to work.

**Comment by goetzk** [comment]
Hi @jennyq ,
Looking at what you've put above I suspect my missing ingredient was the get_setting('MIDDLEWARE_CLASSES'). Hopefully I will have a chance to try it over the next few days.

**Comment by goetzk** [comment]
@jennyq 
I just tested and can confirm that fixes the problem. Thanks!

**Comment by jennyq** [comment]
Great!
