### ISSUE TITLE
HELPDESK Addin: 404 Not Found after Clicking Accept Button

### ISSUE THREAD

**Issue by jim-fuller** [tendenci/tendenci#521]
On issue [tendenci-960], I tried to accept the answer, but got the 404.

![image](https://cloud.githubusercontent.com/assets/12518763/19530381/42bbe5a4-95f9-11e6-853e-97599bed86a1.png)

![image](https://cloud.githubusercontent.com/assets/12518763/19530338/16ada588-95f9-11e6-99af-317416014bf0.png)

**Comment by jennyq** [comment]
I couldn't reproduce the issue. Were you logged in when you received 404?

**Comment by jennyq** [comment]
Closing it. @jim-fuller feel free to reopen it if needed.
