### ISSUE TITLE
App menus not visible to unauthenticated users

### ISSUE THREAD

**Issue by aprildh31** [tendenci/tendenci#523]
Unauthenticated users no longer see any app menus.

For example, the calendar should have an "Events" menu that lets the user download an "Events ICS" file, or switch from the "Monthly Calendar" to the "Weekly Calendar" or "Events List", as shown here in Tendenci 5: http://metro.org/events/month/

As of Tendenci 6, this "Events" menu is part of the top menu for authenticated users, but cannot be accessed by unauthenticated users.

It looks like the old menus were removed by the following two commits:
https://github.com/tendenci/tendenci/commit/4296f627ef73b0529623b49df9aa6e406f3cda15
https://github.com/tendenci/tendenci/commit/24b1baf11c82003969fbbe100628914aea8fbf7b

It seems that @maxbixly had assumed that the new top menu replaced all of the functionality of the old menus, when in fact it does not replace the functionality of the old menus for unauthenticated users.

Any suggestions for how this can be corrected so that unauthenticated users can access these features? Is there any reason not to add the old menus back in, but only render them for unauthenticated users?

**Comment by eschipul** [comment]
Three is a site setting to hide drop-downs (the white legacy ones) if that is the issue?

**Comment by eschipul** [comment]
I believe this is resolved. Open a new issue if not please. also be sure you are on the 7.3 or whatever the latest version is.
