### ISSUE TITLE
front end interface for super_users to enable and disable django template caching

### ISSUE THREAD

**Issue by eschipul** [tendenci/tendenci#525]
From a client "It would be convenient if there was a setting in Tendenci where the client could turn this on and off for development purposes."

During development a site is typically under a light load and template caching can slow down the development process. Taking a site live and then enabling template caching is the best way to achieve optimal speed. The catch is when you need to do an urgent update like adding a sponsor to the bottom of your home page, caching causes this to not be visible for however long the caching is set.

Thus for live sites it's reasonable to be able to turn off template caching, or perhaps force-refresh a specific template after editing it.

**Comment by dco5** [comment]
When I started developing themes this was a major nightmare. I was pulling my hair out trying to figure out why I could not see the changes I made on the template, very very frustrating, once you know it is still a pain having to restart every time you make a change.

**Comment by aprildh31** [comment]
Agreed. Now that I figured out it wasn't browser caching and since I'm working on a local install right now, I just leave a terminal open and execute `python manage.py clear_cache ; service tendenci restart` periodically while I'm making changes to my custom template. For a small enough site with little traffic it isn't a huge problem (just annoying) but could be an issue for large or high traffic sites.

**Comment by goetzk** [comment]
Just last night I had that conversation with a board member:
"How do I update templates?"
*provides link to template editor*
"I made some edits, how do I make the changes public?"
Uh... you ask me to restart things.

**Comment by goetzk** [comment]
For cross reference, similar to #476

**Comment by eschipul** [comment]
@PaulSD - brilliant. THANK YOU!

@goetzk - I'll close #476 as you noted and cross reference this issue.

**Comment by eschipul** [comment]
Closing as resolved.

**Comment by goetzk** [comment]
+1 awesome work @PaulSD
