### ISSUE TITLE
jobs.css missing from tendenci

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#526]
Hi,
Several templates in the jobs app refer to  jobs.css but the file doesn't appear to be included.
There is a .old version, perhaps it isn't actually old?
```
root@tendenci-web:/srv/tendenci/website# find /usr/local/lib/python2.7/dist-packages/tendenci -name 'jobs.css'
root@tendenci-web:/srv/tendenci/website# find /usr/local/lib/python2.7/dist-packages/tendenci -name 'jobs.css.old'
/usr/local/lib/python2.7/dist-packages/tendenci/apps/jobs/static/css/jobs.css.old
```

Edit: Sorry, that sounded really passive aggressive - it wasn't meant to be! I'm just pleased I finally found the cause of all the jobs.css 404 errors in my logs.

**Comment by PaulSD** [comment]
Problem was introduced by commit e807828e7dbcb4a021be192cb67ac62b911f50e2
It kinda looks like @maxbixly intended to replace jobs.css with a new file and keep jobs.css.old around just for reference, but the new jobs.css wasn't actually committed to git.

Does the page look correct without jobs.css?  If you rename jobs.css.old to jobs.css, does the page look correct?  I'm not sure whether the css link should be removed from the html or the css file should be renamed...

**Comment by goetzk** [comment]
I don't know about rendering correctly but there are definitely attempts to use some of the CSS.
For example,  /jobs/add/

https://github.com/tendenci/tendenci/search?utf8=✓&q=job-wrap

https://github.com/tendenci/tendenci/blob/27dfaaaf8fa84af43058263b99beef15aeafb3b0/tendenci/apps/jobs/static/css/jobs.css.old#L18
