### ISSUE TITLE
Feature Request: Member Dues by Country / GeoDues?

### ISSUE THREAD

**Issue by FourthEstate** [tendenci/tendenci#529]
We are a global public benefit corporation and our membership dues are structured on a global tiered World Bank “fair pricing” policy for every country around the world.   This means that for every member type the dues need to be calculated based on the country of residency.  

You can take a look at how we solved this problem using WordPress at https://www.fourthestate.co/membership/journalist/

This equitable membership dues approach makes membership achievable and globally scaleable. We drew inspiration from the [AMA](https://www.AMA.org). They use that dues model It works for them and It was a smart move for us.

What we need is a membership signup workflow in Tendenci that allows for this innovative dues model. It would certainly make the platform standout among the other AMS solutions.

**Comment by FourthEstate** [comment]
We completed this

**Comment by jennyq** [comment]
Very cool! Did you accomplish it in Tendenci? How did you do it?
