### ISSUE TITLE
Feature Request: Multi Payment Gateways.

### ISSUE THREAD

**Issue by FourthEstate** [tendenci/tendenci#531]
Please give us option to utilize more than one payment gateway solution. For example Stripe OR Paypal based on the payers preference at checkout.   For a significant enough number of our members they may not be US based, or have a credit card  but they have access to PayPal.

Frankly from a business development and customer experience standpoint giving the member the option for payments that best suits their needs is paramount.

**Comment by aprildh31** [comment]
I agree. Although you can process credit card payments through the right PayPal account type, it would be nice to add a second option for credit cards in addition to PayPal or vice-versa.

**Comment by FourthEstate** [comment]
I'd like to add that I don't think that this feature would be that difficult to accommodate since Tendenci already supports Stripe and PayPal.  The key here is making the choice of payment method select-able as pay using Either Stripe or Paypal on the various payment objects.

**Comment by goetzk** [comment]
This would also be beneficial to us.
@jennyq or @eschipul , would you be open to this being a contributed feature? (of course I can't promise anything at this time...)

**Comment by FourthEstate** [comment]
We would contribute some $ to this effort.

**Comment by eschipul** [comment]
Currency conversion makes this impractical. Workaround would be to create multiple sites. Closing this one - EGS
