### ISSUE TITLE
Template loader crashing because django raises different exception

### ISSUE THREAD

**Issue by karyon** [tendenci/tendenci#543]
[here](https://github.com/tendenci/tendenci/blob/9fdd5d73e754ab77be2579ee455928fdf0e3405c/tendenci/apps/theme/template_loaders.py#L76) tendenci's template loader catches `ValueErrors` in case `the joined path was located outside of this particular template_dir`. It seems like in that case a `SuspiciousFileOperation` is raised since django 1.8, see [this commit](https://github.com/django/django/commit/b8ba73cd0cb6a3dbdaeb3df65936970956829de3)

reported originally in: https://github.com/django-compressor/django-compressor/issues/799

**Comment by jennyq** [comment]
Resolved https://github.com/tendenci/tendenci/commit/53dcc24021e9a05fd92bb09284b2fc54b76e0a33. 

@karyon Thank you for pointing it out!
