### ISSUE TITLE
Unable to delete users

### ISSUE THREAD

**Issue by FourthEstate** [tendenci/tendenci#544]
Version: 7.2.48

Unable to Delete Users.  Tendenci fails with non-specific "Opps" Message.

**Comment by jennyq** [comment]
@FourthEstate, I cannot reproduce the error.  To find the specific error message, you can turn on `DEBUG` to `True` in your `conf/local_settings.py`, then restart the site.

**Comment by FourthEstate** [comment]
Here you go Jenny.


IOError at /admin/auth/user/

The path to your Whoosh index '/var/www/members/index.whoosh' is not writable for the current user/group.

Request Method: 	POST
Request URL: 	http://members.fourthestate.co/admin/auth/user/
Django Version: 	1.8.16
Exception Type: 	IOError
Exception Value: 	

The path to your Whoosh index '/var/www/members/index.whoosh' is not writable for the current user/group.

Exception Location: 	/srv/tendenci/venv/local/lib/python2.7/site-packages/haystack/backends/whoosh_backend.py in setup, line 118
Python Executable: 	/srv/tendenci/venv/bin/python
Python Version: 	2.7.6
Python Path: 	

['/var/www/members',
 '/srv/tendenci/venv/bin',
 '/srv/tendenci/venv/lib/python2.7',
 '/srv/tendenci/venv/lib/python2.7/plat-x86_64-linux-gnu',
 '/srv/tendenci/venv/lib/python2.7/lib-tk',
 '/srv/tendenci/venv/lib/python2.7/lib-old',
 '/srv/tendenci/venv/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/srv/tendenci/venv/local/lib/python2.7/site-packages',
 '/srv/tendenci/venv/lib/python2.7/site-packages']

Server time: 	Fri, 6 Jan 2017 16:58:14 -0600

**Comment by FourthEstate** [comment]
OK. I resolved based on the verbose error.

**Comment by jennyq** [comment]
Great!

**Comment by FourthEstate** [comment]
Now I just have a zombie user that doesn’t have a profile.  Any idea on how to fix?

Jeff Brown
Fourth Estate Public Benefit Corporation
www.FourthEstate.co <http://www.fourthestate.co/>
——
The Fourth Estate is an international, independent journalism Public Benefit Corporation.

Together with our members we endeavor to contribute to healthy societies by fostering, supporting, and incubating a sustainable and vibrant free press

**Comment by jennyq** [comment]
When the user logs in, his/her profile would be populated automatically. Or you can force it to populate by accessing the profile e.g. http://yoursite.com/profiles/username/
