### ISSUE TITLE
If Send email option not checked in Contact form, Contact email will be sent to do-not-reply address

### ISSUE THREAD

**Issue by mfmjw** [tendenci/tendenci#550]
I thought the email will be sent to the the Contact Address set in site settings but it was sent to the No-Reply Address

It should also send to the address specified in Send copies to. I didn't see the address in the To field in mail.log. Not sure did the program include the address in the To field or CC field.

**Comment by jennyq** [comment]
Hi @mfmjw, the custom form does send an email to the email addresses specified in the field "Send copies to" when someone submitting the form. The " Send email" checkbox, if checked,  is for sending email to the person who submitted the form with the email content in the "Confirmation Text" field. Not sure how you got the conclusion that it sends to do-not-reply address, but It does NOT.

**Comment by mfmjw** [comment]
It is not confusion, my dear. The mail.log says so. If I don't specify any
email address in "Send copies to" and don't check "Send email", it will
send to No-Reply Address instead of the Contact Email after the Contact
form submission. Please see mail.log details below:

Feb  5 10:00:18 ubuntu postfix/smtp[10332]: 34BFAB5BCE: to=<
donotreply@ssohn.org>, relay=mx.ssohn.org[66.96.140.51]:25, delay=4.4,
delays=0/0/4.2/0.26, dsn=5.0.0, status=bounced (host mx.ssohn.org[66.96.140.51]
said: 550 <> Sender rejected. (in reply to MAIL FROM command))
Feb  5 10:00:19 ubuntu postfix/qmgr[26318]: 34BFAB5BCE: removed

**Comment by eschipul** [comment]
Without more detail and a verification of both site settings and the settings.py/local_settings.py and a trace, this issue isn't something i can research.

I *fully* trust that comments from both @mfmjw and @jennyq are correct. I also know that it could be in site settings or in the form. For spam protection, I agree that a form without a sendto address should go through a cascading series of tests and ultimately (ideally not send at all), but if it must send, it should go into a sink hole. The data is still stored on the site so thee is no loss of data. Heck, if I had my way I'd like it to check spf records before even allowing it to send AT ALL! For now we'll leave that to the relay providers like SES or MG.

If this is resolved on your install, please do "knowledge share" and tell us what it was? And if not resolved, please provide a few more clues to help us track down the issue enough to replicate.

And yes, I do think spammers should go into a sink-hole like no-reply@, if you find the sequence of logic to be illogical please link us to that exact line in the code so we can understand the issue?

It can also be helpful to use links from https://demo.tendenci.com although it does reset every two hours. Still it is a way to have a link to an exact page and you can state the steps to recreate the issue. 

Closing this issue for now as I'm guessing this is resolved. If not feel free to reopen.

Thanks!
