### ISSUE TITLE
Conflicting Migrations

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#551]
I update a tendenci installation from 7.2.23 to 7.2.64
I ran a manage.py migrate to make sure I had all changes in the database and got these message:

CommandError: Conflicting migrations detected (0002_auto_20161208_2003, 0002_auto_20160701_0732 in forms; 0004_auto_20160701_0732, 0005_auto_20160701_1627 in news; 0007_auto_20160521_1154, 0007_auto_20160927_1706 in corporate_memberships; 0006_auto_20161025_1814, 0007_auto_20160701_0732 in profiles).
To fix them run 'python manage.py makemigrations --merge'
so I ran and got this:
python manage.py makemigrations --merge
Merging forms
  Branch 0002_auto_20161208_2003
    - Add field custom_price to formentry
  Branch 0002_auto_20160701_0732
    - Alter field field_function on field

Merging will only work if the operations printed above do not conflict
with each other (working on different fields or models)
Do you want to merge these migration branches? [y/N]

**Comment by jennyq** [comment]
Hi @dco5, the conflicts were caused by the 'manage.py makemigrations' command you ran. Also see my comment here https://github.com/tendenci/tendenci/issues/619
