### ISSUE TITLE
ProgrammingError at /admin/auth/user/ when try to delete user

### ISSUE THREAD

**Issue by krchavdarov** [tendenci/tendenci#554]
Hello everyone,

when i try to delete some user i get:

relation "tendenci_reliefassessment" does not exist
LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "tendenci_...
please help me :)

here is Traceback : http://dpaste.com/15XFA2N

**Comment by jennyq** [comment]
What is the Tendenci version installed? We've never had that relation "tendenci_reliefassessment" in Tendenci version 7.x.x.

**Comment by krchavdarov** [comment]
Current Version: **7.2.58**
if you want i can give you access? :) just give me mail to send us & pw

**Comment by eschipul** [comment]
@krchavdarov it wouldn't hurt for you to make a backup (of course) and upgrade to the latest release of 7.3. I don't know that it will fix it though. We've had a heck of a time with the 1.4 to 1.6 to 1.8 going from South to Django migrations (beta imho) to the 1.8 migrations. So yes, I find I regularly am still faking migrations which is a bit ridiculous. 

Deleting users - the biggest issue there is that some times you want their relational data deleted. Like spammers in the forums module. Sometimes you don't - like when your PR agent leaves you wouldn't want to delete them and have it delete all of your news articles!?

In practice I find two things are very helpful from a procedural perspective.
1) Work work work on that similar users report. Do this weekly. Merge as needed.
2) When someone leaves who added trusted content, or even if a group of people, change all of their names to be the same (e.g. "reporter reporter" as FN and LN and then merge all of them.

I'm guessing you and Jenny already resolved this offline. If not please let me know. Closing the issue on update. 

PLEASE REOPEN if still an issue and I can jump in to look at it as well. Trying to simplify but only as simple as needed.

Lastly, I apologize fro being just a few months behind.
