### ISSUE TITLE
null value in column "donation...

### ISSUE THREAD

**Issue by gregwkeller** [tendenci/tendenci#559]
When trying to clone a Membership Application or register an individual Member I hit the Oops page.  Postgress enters the following Errors a those times:
2017-03-05 11:28:22 CST ERROR:  null value in column "donation_default_amount" violates not-null constraint
2017-03-05 11:38:11 CST ERROR:  null value in column "donation_amount" violates not-null constraint

I think the default underlying form needs a tweak, but I cannot see the "Donation Default Amount" or "Donation Amount" fields in the user interface.

Cheers!

**Comment by jennyq** [comment]
@gregwkeller, I couldn't replicate the issue. What version of tendenci are you on?

**Comment by gregwkeller** [comment]
Hi Jenny - It's Version 7.1, running on Ubuntu 14.04.  I've since built an Ubuntu 16.10 and it's working as expected.  There were several Python/Pip update/trust errors in 14.04 that caused me to abandon hope and move to the updated OS and it's been much cleaner since.

**Comment by jennyq** [comment]
Are you still having the issue? You might need to run tendenci update because the current version is 7.2.70.
