### ISSUE TITLE
Event RSVP Now button not appearing

### ISSUE THREAD

**Issue by mfmjw** [tendenci/tendenci#561]
Not sure why only superuser can see the green RSVP Now button whereas the rest can't. Are there some settings that I am missing?

**Comment by eschipul** [comment]
Can you provide more information on that? There are many things it could be from not having registrations turned on, being past the registration deadline, etc.... One easy way to test is to use the demo site at https://demo.tendenci.com and login as admin/admin and try to recreate the issue.

**Comment by eschipul** [comment]
no further data to debug so closing this issue.
