### ISSUE TITLE
Bug: Corporate Membership Applications Don't Honor Payment Method Selections

### ISSUE THREAD

**Issue by FourthEstate** [tendenci/tendenci#563]
There is another issue where the Corporate Membership application form doesn't honor the selections made on creation or editing.  The result is that ALL available payment options are shown, not just the ones that were selected.

**Comment by eschipul** [comment]
Thank you for the fix and the pull request https://github.com/tendenci/tendenci/pull/564 . Assigned for testing and will push out with next version bump.
