### ISSUE TITLE
Tagging of released versions

### ISSUE THREAD

**Issue by BenSturmfels** [tendenci/tendenci#571]
Thanks for all your work on Tendenci!

Would it be possible to add a Git tag for today's "7.2.75" release and for releases going forward? I'm supporting a Tendenci install which is a few months behind and without the tags it's difficult to match up the PyPI releases to the source code.

For today's release:
```
git tag v7.2.75 c77d687
git push --tags
```

**Comment by jennyq** [comment]
I've added a tag for the latest release `7.2.77`. We'll keep tagging the releases going forward. Thanks!

**Comment by BenSturmfels** [comment]
Brilliant, thanks Jenny!
