### ISSUE TITLE
Programatically adding user defined fields

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#583]
Hi all,
Sorry for this!

I can't seem to follow what is required for User Defined fields, and how to add/manage them programatically.

When I asked about UD fields a year ago - before promptly shelving the problem which involved them -  
rleven explained:

> You can store extra information for users on the site who are members. ( Users who have completed a membership application).
> A users's membership profile page allows for front end visibility of the 30 UD fields (Example: http://example/memberships/600/)
> You can select who has access to view this page via the membership protection settings (http://example.com/settings/module/memberships/%23id_memberprotection)
> You can set the naming of the UD fields through the membership application ( http://example.com/admin/memberships/membershipapp/1/)
> - See more at: https://www.tendenci.com/forums/c/support/evaluation/customisable-data-fields/#sthash.ZouDZNOF.dpuf

https://www.tendenci.com/forums/c/support/evaluation/customisable-data-fields/

My problem is that I have existing users who didn't apply using a form that contains user defined fields. I see ftgo asked about UD fields around the same time (https://github.com/tendenci/tendenci/issues/478) , but don't see an answer to /how/ they should be used in my instance.

What I need to do is:
* Enable a number of UD fields
* Apply that change to all existing users/active memberships (whatever is appropriate)

Is this something that can be done programatically? if yes, any pointers would be very much appreciated.

thanks,
kk

**Comment by jennyq** [comment]
You can either edit their memberships individually or populate the UD fields by membership import.
