### ISSUE TITLE
Add docs and script for running the automated tests

### ISSUE THREAD

**Issue by BenSturmfels** [tendenci/tendenci#593]
There are some automated tests for Tendenci, but there's no documentation for how to run them or a script that I can see. Also, the handful of real tests are obscured by a whole lot of "1+1 == 2" stub tests.

I've tried running `python setup.py test` in a fresh virtualenv with no system site packages, but this fails while installing dependencies:

    pkg_resources.VersionConflict: (html5lib 0.9999999 (/home/ben/work/ws/tendenci/html5lib-0.9999999-py2.7.egg), Requirement.parse('html5lib==1.0b10'))

**Comment by goetzk** [comment]
Speaking of the tests, from a quick look I don't see any new tests added to the repository since 2015. Are tests still wanted, and if so is anyone able to offer a thought on if they should be 'Django style' or 'Pytest style'?
