### ISSUE TITLE
Add support for Python 3

### ISSUE THREAD

**Issue by BenSturmfels** [tendenci/tendenci#595]
While adding support for Python 3 is quite a lot of work, it makes Tendenci a more attractive platform to build on and contribute to. The process of adding this support also tends to flush out hidden bugs related to with text encoding.

**Comment by PaulSD** [comment]
Note that Django 2.0 will drop support for Python 2, so April 2020 (end of support for Django 1.11) is a hard deadline for getting this done.

**Comment by PaulSD** [comment]
Fixed in #659

**Comment by BenSturmfels** [comment]
@jennyq and @PaulSD: I'd be really interested to hear your thoughts on how you'll be approaching the the Python 3/Tendenci 8 upgrade with existing clients. Do envisage that you'll be switching existing clients to T8, or only new clients?

Given that the T8 branch requires a substantially modified project-template, it sounds like this is going to be relatively difficult upgrade path. It sounds like the easiest path may be to load the existing T7 database into a fresh T8 project-template and then port across any custom settings and apps.

Would you be interested in contributions to make T8 compatible with a T7 project template, so that the upgrade could be done incrementally?

@PaulSD thanks for the mountain of work you've done on all this!

**Comment by PaulSD** [comment]
T8 can use an existing project template with only minor changes.  See "Step 4b" in the upgrade instructions: https://github.com/tendenci/tendenci/blob/tendenci8/docs/source/upgrade/upgrade-to-tendenci8.txt#L116  :)

**Comment by BenSturmfels** [comment]
Thanks @PaulSD, that's perfect!

**Comment by jennyq** [comment]
Thanks @PaulSD !

Not sure yet, but we'll try to script the upgrade process if possible.
