### ISSUE TITLE
update_tendenci: ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by krchavdarov** [tendenci/tendenci#610]
Hello dear @jennyq and @eschipul,

my Current Version: 7.2.58  /ubuntu chroot/ today i try from command line run update_tendenci:
/srv/tendenci/venv/bin/python /var/www/tendenci/manage.py update_tendenci

and i get this error: https://pastebin.com/tzf5qPJ1
one more, when i try  /srv/tendenci/venv/bin/python /var/www/tendenci/manage.py migrate
output this error: https://pastebin.com/bt6wJzRp

**cordially please help me :)**
Thank you!

**Comment by eschipul** [comment]
If using a "venv" when you type "workon" are you in the venv?  Typically this would be "venv tendenci" or whatever you called your venv. The output would be helpful.

Another log output that would help would be (inside of the venv)  type "pip freeze" 

?

**Comment by krchavdarov** [comment]
in fact, I can not answer the first question.
for some reason I get this
/srv/tendenci/venv# workon
workon: command not found

pip freeze results: https://pastebin.com/vCjpgvXE

**Comment by jennyq** [comment]
Hi @krchavdarov, please follow the update guide here http://tendenci.readthedocs.io/en/latest/upgrade/point-update.html

    pip install tendenci --upgrade
    python deploy.py

Then restart your site. 

The `update_tendenci` command was initially built for the web interface but it is not being used currently for some reason. We'll revisit it and fix the issue (Thanks for pointing it out!). Given the security, permission, and various ways of tendenci setup on different servers,  I think it's better to just make it a command-line command.

**Comment by jennyq** [comment]
I also found something strange in your migration error: 

    Applying files.0004_auto_20170227_1819...Traceback (most recent call last):

As you can see, there is no such migration `0004_auto_20170227_1819` in the tendenci core  https://github.com/tendenci/tendenci/tree/master/tendenci/apps/files/migrations. You might need to re-create your virtualenv and try again.

**Comment by krchavdarov** [comment]
Hello dear @jennyq,
first thanks! I am glad I helped....though a little bit :)
i suspect there are specifics in my installation - I can not handle this.

after pip: https://pastebin.com/PdvfpdYS
after python deploy.py: https://pastebin.com/6TuZSXYi

if you can help me, I will be very happy
if not, i will look for options :) new installation or ...

**Comment by jennyq** [comment]
Hi @krchavdarov ,

Those commands should be run in your tendenci environment. From your comments above, the virtual env is at /srv/tendenci/venv. So, the first step is to activate your env by this command:

    source /srv/tendenci/venv/bin/activate

**Comment by krchavdarov** [comment]
@jennyq,
great :) after i activated source with this command "source /srv/tendenci/venv/bin/activate"
i run: 
pip install -r requirements.txt --upgrade
python deploy.py

now my lovely Tendenci is broken :))))))) i get this error after makemigrations command:
https://pastebin.com/NBCHXcAt

"A server error occurred.  Please contact the administrator."

serverlog.txt --> https://pastebin.com/7Y5B0Wyw

**Comment by krchavdarov** [comment]
YEAH!!!!!!!!!!!!!
i run: root@spa-devin:/# /srv/tendenci/venv/bin/python /var/www/tendenci/manage.py migrate
and is work again!!!!!!!!!

**Comment by krchavdarov** [comment]
@jennyq  you are my ANGEL!

**Comment by jennyq** [comment]
Great! Please note that you shouldn't run the `makemigrations` command. Doing so would cause some problems in the later migration. Django migration sometimes does that even though there is no actual database changes.

**Comment by krchavdarov** [comment]
interesting! site works ...
but when I try to open:
uri..../profiles/search/
/groups/
or something other modules/apps i get "Oops kor user/admin we caused a problem"
BUT 
i find problem in 7.3 we use:
'dj_pagination.middleware.PaginationMiddleware',
and 
dj_pagination
in old config is "pagination" :)))))


One more final question in my dashboard i have no actual data/stats you can see here:
https://prnt.sc/gz0mx2
https://prnt.sc/gz0mon

give me some advice?

**Comment by jennyq** [comment]
To debug the error, you can set `DEBUG = True` in the conf/local_settings.py, then show us the full traceback. 

As for the site stats, do you have cron jobs set up? In your case, you would need these two commands added to cron jobs:

    30 1 * * * /usr/bin/nice -n 19 /srv/tendenci/venv/bin/python /var/www/tendenci/manage.py run_nightly_commands
    10 * * * * /usr/bin/nice -n 19 /srv/tendenci/venv/bin/python /var/www/tendenci/manage.py process_unindexed

 http://tendenci.readthedocs.io/en/latest/installation/installation.html#set-up-cron-jobs-for-production-sites 

If you want to see the dashboard stats immediately, you can run this command in your tendenci environment:

    python manage.py update_dashboard_stats

**Comment by jennyq** [comment]
It looks like the MEMBERS graph is broken on your dashboard. It is fixed in core but you have the template `dashboard/new.html` pulled to your site. To resolve this issue, you can overwrite it by re-pulling the template through the theme editor /theme-editor/editor/, or simply delete it.

**Comment by krchavdarov** [comment]
yes, i have this crons and the works. also i run manual command:
(venv) root@spa-devin:/# /srv/tendenci/venv/bin/python /var/www/tendenci/manage.py update_dashboard_stats
i get: https://pastebin.com/sEFRbbTk

also i delete dashboard/new.html and now my dashboard is it looks perfect, but no data/stat:
https://prnt.sc/gz1s1f

dear @jennyq, any ideas?

**Comment by jennyq** [comment]
So you got a weird error when running the command `update_dashboard_stats`: `ValueError: unknown locale: UTF-8`. What Ubuntu version are you running? If you type `locale` on the terminal, what is the result?

**Comment by krchavdarov** [comment]
Hmmm I tried different things but I have no results

Ubuntu 16.04 
root@spa-devin:/# locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE=UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
root@spa-devin:/#

**Comment by krchavdarov** [comment]
Yes!!! 
nano /etc/default/locale
write: 
LANG=en_US.UTF-8
LANGUAGE="en_US:en"
LC_ALL=en_US.UTF-8

and............. WIN: https://prnt.sc/gz3miz

DEAR @eschipul dear my angel @jennyq  - YOU ARE BEST!
