### ISSUE TITLE
must be owner of relation pluginmanager_pluginapp

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#617]
I know this most be a more postgresql thing, but I am trying to upgrade a tendenci website and I keep getting "must be owner of relation ......" when doing the migrations, is there a way to assign ownership to all tables to the user at once?

I have been running "ALTER TABLE <table_name> OWNER TO <username>;" everytime I encounter this.

Thanks

**Comment by PaulSD** [comment]
`ALTER DATABASE tendenci OWNER TO tendenci;`

**Comment by dco5** [comment]
Thank you!
