### ISSUE TITLE
Missing CSS files found in Tendenci

### ISSUE THREAD

**Issue by ediaz1** [tendenci/tendenci#625]
These files are empty and causing 404s globally:

jobs.css
news.css
staff-view.css

Suggested solution is to load an empty file to remove the 404 error.

**Comment by jennyq** [comment]
Resolved https://github.com/tendenci/tendenci/commit/3f6db9e2f9b1587e7028adfdff4b3854dbb5ec63 https://github.com/tendenci/tendenci/commit/79aacf015829dd8ca727f6638fbeba3f559f91f1
