### ISSUE TITLE
Error fetching command 'create_size'

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#626]
Error fetching command 'create_size': No module named photos.management.commands
Command 'create_size' skipped

In photos/management/commands/create_size.py:
from photos.management.commands import create_photosize
There is an error importing the module.

**Comment by jennyq** [comment]
@dco5, thank you for spotting the error! Where did you see the command `create_size` being used?  Maybe it should be removed if not used.

**Comment by dco5** [comment]
I used Find Usages and no results

**Comment by jennyq** [comment]
Then it can be removed. Thank you!
