### ISSUE TITLE
Navs App

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#627]
Is there a way to get a nav, for example Nav 3 and do a forloop of each nav item and a forloop of each child? Rendering the menu with {% nav 3 %} is ok, but it breaks some functionally the template I am working with. I know nav_tags has a lot of tags to use, but I can't find one that helps me.

**Comment by jennyq** [comment]
Hi @dco5,

It is not possible currently. I think a tag field is needed in the `Nav` model, then you can do something like this:

    {% list_navs as nav_list limit=1 tags="cool" %}
    {% for nav in nav_list %}
        <div>{{ nav.title }}</div>
        <ul>
        {% for item in nav.top_items %}
            <li><a href="{{ item.url }}">{{ item.label }}</a></li>
            <ul>
            {% for child in item.children %}
                <li><a href="{{ child.url }}">{{ child.label }}</a></li>
            {% endfor %}
            </ul>
        {% endfor %}
        </ul>
    {% endfor %}
