### ISSUE TITLE
memberships_membershipdefault.auto_renew does not exist

### ISSUE THREAD

**Issue by krchavdarov** [tendenci/tendenci#628]
Hello dear Tendenci masters and Merry Christmas :) 

today i upgrade to 7.4.1 and i have problem with memberships:

https://pastebin.com/2nRHP0iM

can you help me to fix this error? :)

**Comment by PaulSD** [comment]
source /srv/tendenci/venv/bin/activate
cd /var/www/tendenci/
python manage.py makemigrations
python manage.py migrate
python deploy.py
python manage.py clear_cache
service tendenci restart

**Comment by PaulSD** [comment]
http://tendenci.readthedocs.io/en/latest/upgrade/point-update.html should probably be updated to include `python manage.py migrate` ...

**Comment by jennyq** [comment]
@PaulSD, the `python manage.py migrate` is already included in the `deploy.py`. But I agree it should be added before `python deploy.py` as it gives better traceback error messages to debug.

@krchavdarov, you shouldn't need to run `python manage.py makemigrations` - it could cause some problems on the migration in the future.  Can you please paste the result of `python manage.py migrate --list`?

**Comment by krchavdarov** [comment]
@jennyq here is my migrate --list: https://pastebin.com/zNNHNQPv
@PaulSD i make couple of time update with no results

**Comment by jennyq** [comment]
@krchavdarov, I found there are lots of extra migrations in your list that don't exist in the version 7.4.1. You can compare yours with my migrate list https://pastebin.com/PafGDPsq.  This is the list of your extra migrations https://pastebin.com/mzs6TsEt. 

Those extra migrations, I believe, were created by the `python manage.py makemigrations` you ran. That is probably the reason why the memberships migration `0007` won't run. You can first clear out those, then run `python manage.py migrate` again.

To clear out the extra migrations, it's probably easy to just remove those entries directly from the table `django_migrations` (with the sql statement like `delete from django_migrations where app='articles' and name='0006_auto_20171227_1420';`).

**Comment by krchavdarov** [comment]
@jennyq after i clean my migrations in db and again run update & deploy i get: https://pastebin.com/hvxfFa9m

**Comment by jennyq** [comment]
You probably accidentally removed the  `contenttypes 0001`. Run this 

    python manage.py migrate contenttypes 0001 --fake

You can also use this command `python manage.py showmigrations` to see which ones have not be migrated. `[X]` means migrated. `[ ]` means not migrated.

**Comment by krchavdarov** [comment]
same error: https://pastebin.com/3dyQ8xb2

**Comment by jennyq** [comment]
python manage.py migrate accountings 0001 --fake

What's the result if you run `python manage.py showmigrations`?

**Comment by krchavdarov** [comment]
@jennyq thanks a lot for your time and help! :1st_place_medal: 
here is answer: https://pastebin.com/0phqRYTL

**Comment by jennyq** [comment]
First of all, clean up the code to remove those migrations you generated in the file system:

    pip uninstall tendenci
    pip install -r requirements/tendenci.txt --upgrade

Then, run `python manage.py migrate`. If you run into errors like this:

    Applying accountings.0001_initial...Traceback (most recent call last):
    ...
    django.db.utils.ProgrammingError: relation "accountings_acct" already exists

Simply fake it with something like `python manage.py migrate accountings 0001 --fake`. Replace `accountings` with the app name, and `0001` with the actual number.

**Comment by BenSturmfels** [comment]
@jennyq looks safe to close

**Comment by jennyq** [comment]
Closing it. @krchavdarov feel free to open a new issue if needed.
