### ISSUE TITLE
The Corporate Membership Report should be listed with the rest of the reports

### ISSUE THREAD

**Issue by JustinLewisSMA** [tendenci/tendenci#632]
www.domain.com/corporatememberships/corp-export/

This should live with the rest of the reports instead of hiding in the Corporate Membership menu. (although it could also be accessible there)

**Comment by jennyq** [comment]
@JustinLewisSMA, good idea! It's been resolved https://github.com/tendenci/tendenci/commit/7b861fe87ea09da7e4795f912d8c37a541266916.
