### ISSUE TITLE
Question: Does helpdesk support group level read permissions

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#634]
Hi,
Is the helpdesk supplied by Tendenci able to have Knowledgeable entries available to different groups of people? I want to have some KB articles available to staff, some to website members and some to public.

If it isn't able to do that, can you suggest a Knowledge base system that will integrate well with tendenci?

(If you follow django-helpdesk I opened issue 581 there while investigating this question)

thanks,
kk

**Comment by jennyq** [comment]
Hi @goetzk, The group level permission is currently not available in the helpdesk KB system. Although you are welcome to do a pull request on that, I'd suggest to check out the Help Files module. I think it's a good alternative. Like most of the Tendenci core modules, you can also customize the label and root url through the site settings /settings/module/help_files/#id_label on your site to suit your needs.

**Comment by goetzk** [comment]
Hi @jennyq ,
thanks for the suggestion - I'll try it out and see how I find it.
(I'll close this for now, I will reopen later if needed)
