### ISSUE TITLE
Dependency install failure.

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#638]
I'm seeing an error trying to download + install dh-pagination.

```
Downloading/unpacking dj-pagination>=2.2.0 (from tendenci==7.3.0)
  Downloading dj-pagination-2.3.2.tar.gz
  Running setup.py (path:/tmp/pip_build_root/dj-pagination/setup.py) egg_info for package dj-pagination
    error in dj-pagination setup command: Invalid environment marker: python_version < "3.0"
    Complete output from command python setup.py egg_info:
    error in dj-pagination setup command: Invalid environment marker: python_version < "3.0"
```

I think it comes directly from tendenci, but I can't seem to download it at the moment to test.
```
root@tendenci-combined:/home/ubuntu/tendenci-install# pip install dh-pagination==2.2.1
Downloading/unpacking dh-pagination==2.2.1
  Could not find any downloads that satisfy the requirement dh-pagination==2.2.1
Cleaning up...
No distributions at all found for dh-pagination==2.2.1
Storing debug log for failure in /home/root/.pip/pip.log
```

Hopefully setting the dependency to 2.2.1 will solve it.

https://pypi.python.org/pypi/dj-pagination/2.2.1

**Comment by jennyq** [comment]
Not sure what is causing this. What OS are you running? We have the latest version 2.3.2 of dj-pagination installed on both ubuntu 14.04 and 16.04 without any problem.

**Comment by jennyq** [comment]
Try to upgrade `pip` and `setuptools` to see if that fixes.

    pip install -U pip setuptools

**Comment by goetzk** [comment]
Hi Jenny,
I'm using a minimal Ubuntu 14.04, created by LXC.
```
root@tendenci-combined:/home/ubuntu/tendenci-install# pip --version
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
root@tendenci-combined:/home/ubuntu/tendenci-install# pip list |grep setup
setuptools (3.3)
root@tendenci-combined:/home/ubuntu/tendenci-install# lsb
lsblk        lsb_release  
root@tendenci-combined:/home/ubuntu/tendenci-install# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```

After updating pip and setuptools the current dj-pagination installed fine. 

(Also note in my initial post, I was trying to install dh-pagination, which explains why it couldn't be installed manually - there is no such thing.)

**Comment by jennyq** [comment]
Glad you got it working.
