### ISSUE TITLE
populate_default_entity appears to trigger signals - how to resolve?

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#640]
Hi,
I've been doing an update and following the minor update guide
http://tendenci.readthedocs.io/en/latest/upgrade/point-update.html

I'm not entirely sure how it does it, but it appears update_settings (tendenci/tendenci/core/site_settings/management/commands/update_settings.py) has caused my sites signals to be processed.

Normally that wouldn't be a problem, but for each of our ~20k accounts we're querying three different services; as you can imagine that has caused some issues.

I'm after the following guidance:
- is this a tendenci issue which should be fixed in update_settings?
- is signals running during deploy.py something I can work around in my signals.py? if so, how would I go about it?

**Comment by jennyq** [comment]
Hi @goetzk, 
The update_settings itself doesn't fire any signal as far as I know. When `manage.py` runs, Django does register bunch of signals. Can you please give us more details about the issue? And does the same issue happen when you run other commands, for example, `clear_cache`?

**Comment by goetzk** [comment]
(This is becoming a habit for me, I need to sort out my email to GitHub).
This is what I sent a few days ago, but not to the ticket:
```
The signal being run was our updated user handler, running on user
post_save.

@receiver(post_save, sender=User)
def updated_user_handler(sender, instance, created, **kwargs):
	etc

I've just re run deploy.py and none of our signals logged activity which
makes me wonder if it was update_settings at all. Given it was a handler
related to user changes, it may have been due to a populate_* command
but until something in our system changes and I can run deploy.py again
I probably can't provide much more information here.
```

I have just established the culprit is populate_default_entity so updated the title accordingly. 

Purely by accident, the script exited due to a python syntax error so I got to see the output of what was causing the issue.

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/tendenci/apps/entities/management/commands/populate_default_entity.py", line 97, in handle
    row.save()
  File "/usr/local/lib/python2.7/dist-packages/tendenci/apps/memberships/models.py", line 610, in save
    super(MembershipDefault, self).save(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tendenci/apps/perms/models.py", line 115, in save
    super(TendenciBaseModel, self).save(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 771, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/srv/tendenci/website/itpa/signals.py", line 106, in professional_to_associate_handler
    utils.discourse_disable_user(instance, 'No professional membership is associated with this address')
  File "/srv/tendenci/website/itpa/utils.py", line 334, in discourse_disable_user
    logger.debug('0 records returned for {1}'.format(membership.user.email))
IndexError: tuple index out of range
Traceback (most recent call last):
  File "deploy.py", line 7, in <module>
    subprocess.check_call(['python', 'manage.py',  'populate_default_entity'])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', 'manage.py', 'populate_default_entity']' returned non-zero exit status 1
```

I'm not sure what the suggested fix should be though - disable signals when running deploy.py? Seems very heavy handed.

**Comment by jennyq** [comment]
What is this `itpa`? It's not a tendenci app, right? If you cannot fix the error, you can comment out the command `populate_default_entity` in the `deploy.py`.

**Comment by goetzk** [comment]
ITPA is my app in the tendenci install which contains local customisations

On 17 February 2018 8:40:09 am AEDT, Jenny Qian <notifications@github.com> wrote:
>What is this `itpa`? It's not a tendenci app, right? If you cannot fix
>the error, you can comment out the command `populate_default_entity` in
>the `deploy.py`.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/tendenci/tendenci/issues/640#issuecomment-366365952

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by goetzk** [comment]
I'm not entirely sure why my models are being saved (I didn't think they inherit from TendenciBaseModel directly or indirectly) but the problem code (row.save() only triggers if they match.

I was going to try disabling the signals something along these lines but then i need to teach deploy.py about django and decided it was too hard - I ran it after manually disabling the signals by briefly commenting them out.

```
diff --git a/deploy.py b/deploy.py
index 75119ca..d9c1b50 100644
--- a/deploy.py
+++ b/deploy.py
@@ -1,9 +1,18 @@
 import subprocess
 
+from django.contrib.auth.models import User
+from django.db.models.signals import post_save
+# Import my signal handler
+from itpa.signals import updated_user_handler
+
 subprocess.check_call(['python', 'manage.py',  'migrate', '--noinput'])
 subprocess.check_call(['python', 'manage.py',  'collectstatic', '--noinput'])
 subprocess.check_call(['python', 'manage.py',  'update_settings'])
 subprocess.check_call(['python', 'manage.py',  'clear_theme_cache'])
+print "disconnecitng signals"
+post_save.disconnect(updated_user_handler, sender=User)
+print "populate_default_entity"
 subprocess.check_call(['python', 'manage.py',  'populate_default_entity'])
+print "about to populate_entity_and_auth_group_columns"
 subprocess.check_call(['python', 'manage.py',  'populate_entity_and_auth_group_columns'])
 subprocess.check_call(['python', 'manage.py',  'loaddata', 'initial_data.json'])
```
