### ISSUE TITLE
ALL admin notice recipients can't be disabled

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#642]
Hi,
I can't see a way to disable "ALL admin notice recipients" (allnoticerecipients). I just looked at the email they were going to and we've clocked up 7000 emails (JFTR, I agree that someone should have been looking at that inbox).

From what I can see, we've received email for:
* New Payments
* Membership applications for free accounts (~6000 on their own)
* Membership applications for paid accounts
* Membership renewals
* Membership approvals

Our back office email is directly configured in the memberships app, so assuming they are receiving those mails (which I will follow up), is there some way the global admins can get out of receiving them too?

thanks,
kk

**Comment by jennyq** [comment]
Hi @goetzk,
If you don't want the global admins (allnoticerecipients) to receive any notice, simply leave that setting blank.

**Comment by goetzk** [comment]
Hi Jenny,
Thanks for the suggestion. If thats the case I mis read the code - I thought if "allnoticerecipients" was blank then the mail would go to the administrator contact.
I've removed the ALL admin notice recipients address and will check if it has worked.

thanks!

**Comment by goetzk** [comment]
For the record, this does work as mentioned. Thanks!
