### ISSUE TITLE
No tag for 7.4.3

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#646]
Hi,
I'm not sure which commit 7.4.3 was released from, but I see it available via pip but not tagged here in git. 
https://pypi.python.org/pypi/tendenci/7.4.3

thanks,

**Comment by goetzk** [comment]
I just found the commit 

https://github.com/tendenci/tendenci/commit/efd16f072e7279c1dac3870fb908d4cb17913c4f

**Comment by jennyq** [comment]
The tag has been added. Thanks!
