### ISSUE TITLE
"oops" message when trying to submit forms

### ISSUE THREAD

**Issue by cybervegan** [tendenci/tendenci#648]
Fresh install following official install instructions, on debian stretch. Eventually got a clean install, and the app up and running, but when trying to save global settings settings (even without making any changes) I get an "oops" message:

Oops andy, we caused a problem

We have been notified of this and will be working on it quickly.

You may want to try this page again in a little bit.

**Comment by jennyq** [comment]
Hi @cybervegan,

To see the real error, you can turn on the debug mode in the conf/local_settings.py

    DEBUG = True

**Comment by BenSturmfels** [comment]
Hi @cybervegan, are you still looking for support here or are you all sorted out?

**Comment by jennyq** [comment]
@cybervegan , It's been a while but we have not heard back from you regarding the issue. Closing it. Feel free to re-open if you're still experiencing the issue.
