### ISSUE TITLE
Auto renew paid memberships as default 

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#649]
Hi.
We've successfully set up auto renewal (thanks for the help so far!) but I can't see a way to make auto 
renewing the default behaviour , which has to be opted out from.

Is that setting configurable by administrators?

thanks,
Karl.

**Comment by jennyq** [comment]
This option is not available currently. Members will have to specifically set up or check the Auto Renew on join.

**Comment by dco5** [comment]
@goetzk How did you manage to get the auto renewal working?

**Comment by goetzk** [comment]
H hi Jenny,
What is required to make it default? Will changing the Auto renew party of the membership model to true work?

I will try and experiment this weekend on a development server if I can.

Thanks
Kk

On 1 March 2018 3:37:51 am AEDT, Jenny Qian <notifications@github.com> wrote:
>This option is not available currently. Members will have to
>specifically set up or check the Auto Renew on join.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tendenci/tendenci/issues/649#issuecomment-369294412

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by goetzk** [comment]
On 1/3/18 05:23, Jaime Lossada wrote:
> @goetzk <https://github.com/goetzk> How did you manage to get the auto
> renewal working?

See the following links for my docs, hopefully at some point they'll
appear on RTD too.

https://github.com/tendenci/tendenci/pull/645/files

https://github.com/tendenci/tendenci/pull/652/files

(thanks for asking, I had forgotten to open the second PR and the code
was in limbo in my fork).

kk

**Comment by goetzk** [comment]
For the record - I couldn't get the form to default to ticked, i guess I'm missing some bits of the chain.
kk

**Comment by goetzk** [comment]
@dco5 Did the docs work for you?

Defaulting to auto renew and choosing the length of time auto renew runs (appears to be tied to membership length) are the two things I haven't got working yet.

**Comment by goetzk** [comment]
For cross reference, #566 is discussing disconnecting membership lengths from payment cycle.
