### ISSUE TITLE
Failing to install on Mac OSX High Sierra

### ISSUE THREAD

**Issue by surajprasad** [tendenci/tendenci#651]
Hi, 
I am keen to use tendenci for our non-profit and empower some of our projects through member participations.
Hae spent the last 3 days trying to get a local copy and try it out before I make decisions. However it seems that the requirements are kind of conflicting. 
I am using python3 in my virtualenv and the following packages are failing;
BeautifulSoup
psycopg2
PDFMiner
Geraldo
CreateSend

I tried by cloning the repo and amending the requirements.txt to have latest versions of some of the packages above and excluding Geraldo, since it does not have any recent versions. After which the requirements.txt installs properly
Then as instructed in the docs, I proceed to django-admin.py createproject --from the template url
And add database information along with running the requirements/dev.txt (which also requires some alteration with the package versions)
After all of this, when I try to migrate it says
"from tendenci.settings import *
ModuleNotFoundError: No module named 'tendenci'"

It has taken considerable amount of research and debugging of my own OS Paths etc. and now I believe things at my end are fine.

I was really happy to see the latest commit about 2 hours ago, after which I made another attempt to install it as per the docs, but I am still at the same place. 

Any help will be greatly appreciated. 

Suraj

**Comment by jennyq** [comment]
Hi @surajprasad, the current tendenci version does not work with python3 yet. You'll need to install Python 2.7 if you don't have it already. We'll migrate to python3 in the next major version (tendenci8) hopefully.

**Comment by surajprasad** [comment]
Hi jennyq,
Thanks for the super quick response. 
I tried installing with python2.7 too, but in that environment the psyzopg2 was creating an error and not allowing me to proceed. 
Do you want me to run a setup with python2.7 and send you details of what I encounter?

Thanks.

**Comment by surajprasad** [comment]
In python2.7 venv, the first place it gets stuck is at psycopg2==2.6.1 with the following error
`Error: could not determine PostgreSQL version from '10.2'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/bd/72srns3d5z9g1vvsf472z7hm0000gp/T/pip-build-SKRKZ4/psycopg2/`

I have postgresql 9.6 installed after removing the 10.2 version but that does not solve the problem. 

As far as I can see, others who have faced similar error, have gone here for a solution [](https://github.com/psycopg/psycopg2/issues/594) but they owner clearly says that the error has been resolved in the psycopg2==2.7 and that there is no plan to patch it in the previous versions. 

I am not sure it this would be helpful, but in the requirements.txt for tendenci, can we somehow ignore the version numbers? or selectively pass different version numbers for specific packages?

I think after, it crosses this hurdle it will stop at a few more packages.

Kindly help.

**Comment by jennyq** [comment]
I've just made the update to the `requirements.txt` to have the latest version `2.7.4` for `psycopg2`. Please try to install tendenci from the master branch on github to see if that resolves the issue.

**Comment by surajprasad** [comment]
After two hours of trying to make this work, it still does not. For some reason, it is still picking up the same version of `Collecting psycopg2==2.6.1 (from tendenci)`
I have tried clearing all my caches, re-installing pip and making new virtual environments etc. 
A git clone gives me the correct requirements.txt file. But the `pip install tendenci` or `pip install --no-cache-dir tendenci` are stuck at the same error. 

If I run the pip install -r tendenci/requirements.txt from the cloned git, everything installs properly, but then, when I try to migrate, it says No Module named **tendenci**

Any suggestions?
Thanks.

**Comment by jennyq** [comment]
In your `requirements/tendenci.txt`, uncomment out `https://github.com/tendenci/tendenci/archive/master.zip` and comment out `tendenci>=7,<8`, then try again please.

**Comment by surajprasad** [comment]
Hi, 
So the requirements checked out fine after using your suggestion. However, there are two further blocks, namely;
geolibs : `GEOS is required and has not been detected. Are you sure it is installed? See also https://docs.djangoproject.com/en/1.8/ref/contrib/gis/install/geolibs/
`
Installing GEOS is not a major hassle though, its pretty straight forward from the link above. 
Afterwards, we encounter 
`ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation`

This takes another `pip install python-magic-bin` before the migrate starts to run. After a good 3-4 minutes however another issue crops up. 

```
return connection.ops.geo_db_type(self)
AttributeError: 'DatabaseOperations' object has no attribute 'geo_db_type'
```
This happens specifically when applying migrations for `Applying social_services.0001_initial...Traceback`

On further reading, I see from this [SO thread](https://stackoverflow.com/questions/46075739/geodjango-postgresql-not-running-migrations-object-has-no-attribute-geo-db-ty) that the backend psycopg2 is the problem and it needs to be replaced by postgis database backend. 
After replacing the backend with the postgis, it throws up another error;
`django.db.utils.ProgrammingError: permission denied to create extension "postgis"
HINT:  Must be superuser to create this extension.`
There isn't a working solution that I can find so far for this, I tried creating the extension both from within the venv and outside by CREATE EXTENSION postgis. While that reports the postgis extension already exists, I am not sure why the migrate cannot pick it up. 
On [Reddit](https://www.reddit.com/r/django/comments/426fd0/geodjango_with_migrations_on_webfaction_no/) there seems to be a workaround for this, but the problem exists in the django 1.8 core. As per that thread the issue has been solved in django 1.9 and upwards. 

I am looking for other solutions to that. 
Hope all this information helps in the next release. 

Best

**Comment by surajprasad** [comment]
It does not seem like I can get past this. 
python manage.py migrate
breaks everytime at the same error

`django.db.utils.ProgrammingError: permission denied to create extension "postgis"
HINT:  Must be superuser to create this extension.`

Would it be wise to ignore the app Social Services while making the migrate, thereby not needing the Postgis backend ?

Waiting for a little more help.

**Comment by jennyq** [comment]
To ignore the Social Services, just comment out the lines for `social_services` in your `conf/local_settings.py` and `conf/local_urls.py`. https://github.com/tendenci/tendenci-project-template/blob/master/conf/local_settings.py#L22  https://github.com/tendenci/tendenci-project-template/blob/master/conf/local_urls.py#L17

**Comment by surajprasad** [comment]
Hi @jennyq,
Thank you for patiently helping me out, I have managed to finally run a local instance of tendenci and we are very pleased of all that it brings out of the box. 

I am dropping you an email for further queries before we make the switch. 

Best.
