### ISSUE TITLE
Missing tags/releases.

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#658]
I saw that 7.4.4 was committed recently (yay), but several places that it could/should be mentioned are still missing

- There is no tag (for 7.4.3 this is #646)
- There is no release (releases don't seem to be made very often!?)

If you have pre deploy testing of some sort I'm happy to contribute code to check for one or both of those being updated if it will be helpful.

**Comment by jennyq** [comment]
Not an issue now.
