### ISSUE TITLE
Read The Docs is out of date

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#687]
I've been noticing contributed documentation isn't being built and added to http://tendenci.readthedocs.io/en/latest/# but only went looking today.

Looks like the last successful build was in November 2017 (29th)
http://readthedocs.org/projects/tendenci/builds/6338122/

Building on the 1st of December 2017 failed:
http://readthedocs.org/projects/tendenci/builds/6349412/

The errors look identical to me and I have no background with sphinx.

Neither commit leaps out at me as being relevant so I assume its something environmental.
https://github.com/tendenci/tendenci/commit/39db2c859697757118c1c239f0534f063e11f36c (failing)
https://github.com/tendenci/tendenci/commit/a3bf8df5678b315ad3a4676de8c95f31edff266a (working)

**Comment by jennyq** [comment]
@goetzk Thank you for reporting it! The issue has been resolved.

**Comment by goetzk** [comment]
Thanks @jennyq !
