### ISSUE TITLE
Discount codes for referred memberships

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#700]
Hi,
I've been trying to find a way to implement a referral scheme which has the following properties:

* existing member refers new member(s)
* new member(s) sign up for paid membership
* new member receives a discount on their membership
* existing member receives a discount on their next renewal

I found a referral field which I've exposed (I mention this in #699) but I can't find a way built in to tendenci to perform the discounting parts.

I see discount codes but they only appear to be for events. Have I missed something on the tendenci side?

**Comment by jennyq** [comment]
@goetzk, the discount code can also be used in memberships. Just make sure 1) the "Discount eligible" checkbox is checked on memberships applications (ex: https://www.example.com/admin/memberships/membershipapp/1/), and 2) the `Applications` field has `memberships` selected when issuing a discount code https://www.example.com/discounts/add/.

**Comment by goetzk** [comment]
@jennyq thanks, that looks like it will work!

I will set it up later and make sure it all behaves as expected but that looks like the ordering is what I had wrong.


Is that documented somewhere? if not I'll organise a short PR.

thanks,

**Comment by jennyq** [comment]
I'm not sure if it's documented or not. Please check the readthedocs http://tendenci.readthedocs.io/en/latest/. Yes, a PR would be nice :).

**Comment by goetzk** [comment]
@jennyq I can't figure out how to apply discounts to Directories or Jobs . Do discounts apply to those things for individuals?

**Comment by jennyq** [comment]
Discounts cannot be applied to Directories and Jobs yet.

**Comment by goetzk** [comment]
That explains that!
I just opened PR documenting discounts set up. Since that enables us to generate discount codes for members I'll close this ticket.

I will open a separate ticket later if/when tying referrals and discounts together becomes a priority for us.

**Comment by goetzk** [comment]
(Actually closing, guess I hit the wrong button all those months ago)
