### ISSUE TITLE
Writing tests for Tendenci

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#703]
In #593 @BenSturmfels enquires about (documentation on) running the Tendenci tests automatically.

As a result of that question I looked at the current tests and I don't see any new tests added to the repository since 2015 (sorry if I missed some newer additions).

Are tests still wanted, and if so is anyone able to offer a thought on if they should be 'Django style' or 'Pytest style'?

**Comment by jennyq** [comment]
@goetzk, Thank you and @BenSturmfels  for bringing up this issue! Testing is very important and we get it. We definitely need to spend more effort on it to ensure a good test coverage for the core functionalities. Let's focus on T11 to have this area improved. Include tests when needed. It's a bit tricky to have to pick a testing approach. As for now, maybe just stick to the 'Django style' if possible. But I think either one is fine as long as you have meaningful tests.

**Comment by goetzk** [comment]
Hi @jennyq ,
Thanks for the feedback. I will close this issue for now but at least now have something to refer back to next time I need to deal with Tendenci/testing.
