### ISSUE TITLE
Setting DEBUG=True prevents you from accessing default membership applications

### ISSUE THREAD

**Issue by replaceafill** [tendenci/tendenci#720]
Could anyone help me double check this? These are the steps to reproduce in a new Tendenci 11 development instance (virtualenv + manage.py runserver):

- Set `DEBUG = False`
- Load the Tendenci 2018 defaults
- Start the instance and go to `/memberships/applications/basic-membership-application/`. The membership application form displays correctly
- Now set `DEBUG = True`. You will also need to add your hostname (e.g. localhost) to `ALLOWED_HOSTS`
- Restart the server and reload `/memberships/applications/basic-membership-application/`. You'll get infinite `--- Logging error ---` messages in your server console

**Comment by jennyq** [comment]
I can reproduce the issue. Thanks @replaceafill ! I'm looking into it..

**Comment by jennyq** [comment]
Changing from

    {% if membership_form.discount_code %}
    {% if membership_form.donation_option_value %}

to

    {% if 'discount_code' in membership_form.fields %}
    {% if 'donation_option_value' in membership_form.fields %}

does the trick.
