### ISSUE TITLE
Membership Reports Improvement

### ISSUE THREAD

**Issue by JustinLewisSMA** [tendenci/tendenci#724]
This report is great:
https://demo.tendenci.com/memberships/reports/members_stats/

You can click on the numbers and see the list of members that fall into that category. Fantastic.

However, we often need to do something with the list of members beyond what is available in the admin. Such as send off a custom mailing list to our mail house, export the list for our 3rd party email program, print name badges, etc.

Can we see about adding a tool to export that filtered list of members directly from the /members_stats/ view, or from the admin view (https://demo.tendenci.com/admin/memberships/membershipdefault/?status_detail=active&membership_type__id__exact=3) you see after you click a number?

**Comment by eschipul** [comment]
Be sure to check out https://demo.tendenci.com/model-report/  - although it isn't completely flexible it is quite powerful.

For the power users, there are unlimited possibilities using "explorer" at https://demo.tendenci.com/explorer/ 

All corporate members for example would be:

`SELECT cp.name, cp.address, cp.address2, cp.city, cp.state, cp.zip, cp.country,
     cp.phone, cp.email, cp.url, cp.number_employees, cp.chapter, cp.tax_exempt,
     cp.annual_revenue, cp.annual_ad_expenditure, cp.description, cp.expectations,
     cp.notes, cp.referral_source, cp.ud1, cp.ud2, cp.ud3, cp.ud4, cp.ud5, cp.ud6,
     cp.ud7, cp.ud8, cm.corporate_membership_type_id, cm.renewal, cm.renew_dt,
     cm.join_dt, cm.expiration_dt, cm.approved, cm.admin_notes, cm.status_detail 
FROM corporate_memberships_corpprofile cp
INNER JOIN corporate_memberships_corpmembership cm
ON cp.id=cm.corp_profile_id
WHERE cm.status_detail <> 'archive'`

All members would be something like:

`SELECT u.first_name, u.last_name, u.email, u.username, u.is_staff, u.is_superuser,
        p.salutation, p.company, p.position_title, p.phone, p.address, p.address2,
        p.member_number, p.city, p.state, p.zipcode, p.country, p.url, p.sex,
        p.address_type, p.phone2, p.fax, p.work_phone, p.home_phone, p.mobile_phone,
        m.membership_type_id, m.renewal, m.certifications, m.work_experience,
        m.referer_url, m.referral_source, m.join_dt, m.expire_dt, m.renew_dt,
        m.primary_practice, m.how_long_in_practice, m.application_approved,
        m.application_approved_dt, m.areas_of_expertise, m.home_state,
        m.year_left_native_country, m.network_sectors, m.networking,
        m.government_worker, m.government_agency, m.license_number,
        m.license_state, m.status_detail
FROM auth_user u
INNER JOIN profiles_profile p
ON u.id=p.user_id
INNER JOIN memberships_membershipdefault m
ON m.user_id=u.id
WHERE u.is_active=True
AND p.status=True
AND m.status_detail <> 'archive'`

Also note the "Schema" button below the sql box.

And a quick tip - if you name them something like "Memberships - blah" then it will group them like directories.

Oh, and they are absolutely AWESOME for SEO to find legacy links that are http vs https for common sites.

Oh and in a perfect world, send us your best queries and we can add them to the fixtures. Or you yourself can do a pull request on fixtures or documentation.

Does that answer your question?

**Comment by JustinLewisSMA** [comment]
I think the /model-report/ is exactly what my staff needs. I'm checking.

As a note, that URL doesn't show up anywhere in our Reports menu! We would have never found this without this issue!

**Comment by eschipul** [comment]
Wow, you are correct! Um.... my bad. I'll take the hit on that one (for not having a link.) Given every site is unique and in numerous languages I guess I've gotten in the habit of just typing the URLs. (no excuse, just an explanation of me being an airhead.)

I also need to do a help file on all of the SQL queries we use in Explorer. Sometimes you just gotta get the data and make it dance in Excel. But ultimately it is so appreciated when people push their best reports back to the community so we can share them with everyone! I think I've got at least 10 just for SEO to locate links to be updated like youtube, linkedin, etc, embeds.

Thanks! 

I'm closing this issue for now but feel free to reopen or create a new issue with further suggestions.
