### ISSUE TITLE
Odd date format in the forums (at least. probably elsewhere as well.)

### ISSUE THREAD

**Issue by laealfaro** [tendenci/tendenci#727]
In the forums,  the date appears as day.month.year.

![dateformatscreenshot](https://user-images.githubusercontent.com/42009342/43722372-1aaeefec-9963-11e8-96b6-a7d9c5068d33.png)
Personally I prefer year.month.day (specifically %Y.%m.%d) for its sortability. The common US format is month/day/year, which may be the least logical but is familiar.
(It would also be nice to either have fixed width font or separate columns for date and time so that it would be easier on the eye to skim.)

**Comment by jennyq** [comment]
Thanks! Fixed it by utilizing the Date Format site setting so that you can adjust it.
