### ISSUE TITLE
Issues in editing template from theme editor after upgrade to tendenci 11

### ISSUE THREAD

**Issue by surajprasad** [tendenci/tendenci#730]
Hi, 
So, we upgraded to tendenci before we were to go live on tendenci, and so far, after the initial hiccups I faced a few months ago when first trying out tendenci, everything was very helpful. It answered all our needs. After upgrading to tendenci 11, things became much better, and we are happy. We plan to go live in about a week's time. 
There is a minor issue however, when we are trying to edit the template files from the theme editor, the edit does not get saved, I also tried uploading files (css/js/html) form the theme editor interface, but the upload fails everytime. 
The log files produce nothing significant. My inspection simply shows a javascript/ajax error; in this file http://13.232.195.209/static/themes/t7-base/js/jquery.form.js it says "[jquery.form] terminating; zero elements found by selector" 
This shows in the console, and its not marked as an error, but more like information. 
Could this be the reason? What could be the solution?

Thanks for this lovely project.

**Comment by jennyq** [comment]
Hi @surajprasad, We've pushed out some fixes lately. Please pull and try again. 

    pip install https://github.com/tendenci/tendenci/archive/master.zip --upgrade
    python manage.py deploy

If you have any template pulled down in your theme_editor under the `theme_editor` directory, please remove it before editing.

**Comment by surajprasad** [comment]
Hi @jennyq 
I am trying to pull in, but it seems to crash.
 
`Looking up "https://github.com/tendenci/tendenci/archive/master.zip" in the cache
  No cache entry available
  Starting new HTTPS connection (1): github.com:443
  https://github.com:443 "GET /tendenci/tendenci/archive/master.zip HTTP/1.1" 302 None
  Status code 302 not in (200, 203, 300, 301)
  Looking up "https://codeload.github.com/tendenci/tendenci/zip/master" in the cache
Killed
`
Any tips?

**Comment by jennyq** [comment]
Is your site on server or in a VM? How much RAM is available to use? A minimum of 3GB of RAM is usually required.

**Comment by surajprasad** [comment]
I am using AWS, just increased the machine stage and I was able to pull and delpoy. However, even now, the situation is same; a slightly detailed console log below;

> 

  | CodeMirror | @ | codemirror.js:1
-- | -- | -- | --
  | CodeMirror.fromTextArea | @ | codemirror.js:1
  | (anonymous) | @ | ?file=templates/head…eme_edit=jordy:2608
  | j | @ | jquery.min.js:2
  | fireWith | @ | jquery.min.js:2
  | ready | @ | jquery.min.js:2
  | I | @ | jquery.min.js:2
"
Not sure if this is due to a server configuration.

**Comment by surajprasad** [comment]
When I try to upload a media file (css etc) or template file from the theme-editor interface, I get the following error;

POST http://13.232.200.57/theme-editor/upload/?theme_edit=boomerang 500 (Internal Server Error)    traditional.xhr.upload.handler.js:222 

uploadFile | @ | traditional.xhr.upload.handler.js:222
-- | -- | --
  | send | @ | upload.handler.controller.js:370
  | now | @ | upload.handler.controller.js:566
  | maybeSendDeferredFiles | @ | upload.handler.controller.js:520
  | maybeDefer | @ | upload.handler.controller.js:494
  | start | @ | upload.handler.controller.js:574
  | upload | @ | upload.handler.controller.js:596
  | _uploadFile | @ | uploader.basic.api.js:1743
  | _onSubmitCallbackSuccess | @ | uploader.basic.api.js:1472
  | (anonymous) | @ | util.js:691
  | _handleCheckedCallback | @ | uploader.basic.api.js:994
  | _upload | @ | uploader.basic.api.js:1733
  | (anonymous) | @ | uploader.basic.api.js:1584
  | then | @ | promise.js:32
  | _onValidateCallbackSuccess | @ | uploader.basic.api.js:1582
  | (anonymous) | @ | util.js:691
  | _handleCheckedCallback | @ | uploader.basic.api.js:994
  | _onValidateBatchCallbackSuccess | @ | uploader.basic.api.js:1547
  | (anonymous) | @ | util.js:691
  | _handleCheckedCallback | @ | uploader.basic.api.js:994
  | _prepareItemsForUpload | @ | uploader.basic.api.js:1603
  | _prepareItemsForUpload | @ | uploader.api.js:685
  | addFiles | @ | uploader.basic.api.js:110
  | _onInputChange | @ | uploader.basic.api.js:1445
  | onChange | @ | uploader.basic.api.js:644
  | (anonymous) | @ | button.js:107

**Comment by jennyq** [comment]
To view the details of the error message, you can set `DEBUG = True` in conf/settings.py.

**Comment by surajprasad** [comment]
@jennyq I have tried that, even with debug turned on, the messages are still the same. 
My guess is that it is probably due to a javascript/AJAX error. As I can read its in the uploader.basic.api.js for the failing uploads through theme-editor interface.

**Comment by jennyq** [comment]
Just noticed the upgrade guide didn't have the themes/ directory included on "Step 7: Update/Fix Permissions". So could be the permission issue. Try this?

    sudo chmod -R ug-x+rwX,o-rwx  /var/www/mysite/themes/

**Comment by surajprasad** [comment]
@jennyq 
That solved it. Thanks a ton. 
:)

**Comment by surajprasad** [comment]
While the saving of template files and uploading is working fine now. 
Uploading of a template file is still failing. (Failing in the templates directory, the upload in media directory works fine)
I have checked the permissions, they seem fine. 
Will check again tomorrow, and update if there could be something else. Its almost morning in India. 
Regards.

**Comment by surajprasad** [comment]
This too was a permissions issue. The ownership of the themes directory has to be with both user & www-data.
Solved and working fine now.
