### ISSUE TITLE
Feature Request - Embedding photo_set in articles/events/pages

### ISSUE THREAD

**Issue by surajprasad** [tendenci/tendenci#732]
1. We really like the photos application and it will help us showcase a lot of our work on the website. While it is easy to pull a photo_set and display it in a template, we would like to have the ability to embed a photo_set (not single photos) in text area fields. So for instance, we can go back to an event page and add a photo set of moments from the festival. Similarly, in some of our articles, if it is possible to embed a photo_set (perhaps a sliding gallery or just a grid) while we are publishing articles. If there is already a way to do this, could someone please show the way?
(One way, I think it could be done is if the edit page for events/articles etc could have a field similar to Embed url (for internal links to photo_sets) is this doable?

**Comment by eschipul** [comment]
@surajprasad I do like the idea of a short code type of embed from the photo albums. Unfortunately it doesn't currently support album embeds. 

I'm guessing you already know that you can embed an image. For example on this page:
https://demo.tendenci.com/photos/sizes/medium-640/1/
below the image there is a code block

`<a href="https://demo.tendenci.com/photos/1/in/1/"><img src="https://demo.tendenci.com/photos/1/640x426/" alt=" Tendenci Stock Photography Photos by Ed Schipul" title=" Tendenci Stock Photography Photos by Ed Schipul"></a>`

I can see this as a good pull request. However for now I tagged it "wish list" and am closing the issue for future reference.
