### ISSUE TITLE
main project docs reference deprecated themes

### ISSUE THREAD

**Issue by eschipul** [tendenci/tendenci#733]
The main readthedocs page instructs people to continue to use the deprecated themes:

Specifically on this page: https://tendenci.readthedocs.io/en/latest/installation/installation.html#live-site-setup

It says to install as follows:

```
django-admin.py startproject --template=https://github.com/tendenci/tendenci-project-template/archive/master.zip mysite
sudo chown root /var/www/
```
This is potentially a licensing issue. While Tendenci the organization has purchased developer licenses for these themes, that does not mean they are GPL (as I learn more about licenses, I'm learning about this stuff too y'all.)  

Therefore the correct repository to be used is:

https://github.com/tendenci/tendenci-base-theme

Unless it can be documented that the previous themes are GNU GPL or similar. 

I think this is worth a discussion?

**Comment by jennyq** [comment]
Hi @eschipul, 
If you look at the `themes/` directory of `tendenci-project-template repo`, there is no themes there https://github.com/tendenci/tendenci-project-template/tree/master/themes. The repo now just serves as a *project* template with the files and folder structure (conf/settings.py, conf/urls.py, requirements/...) for a new tendenci site. The only theme installed with this installation guide is `tendenci2018` theme (a.k.a. tendenci-base-theme), which has been moved to core for easy maintenance https://github.com/tendenci/tendenci/tree/master/tendenci/themes/t7-tendenci2018. The current T11 repo has no other previous themes.

**Comment by eschipul** [comment]
OK, I understand. Thank you for your patience. That's what I get for doing late night test installs.
