### ISSUE TITLE
Tendenci 11 Install: load_tendenci2018_defaults -> RuntimeError: No themes found

### ISSUE THREAD

**Issue by rob-hills** [tendenci/tendenci#736]
I trying to clean-install Tendenci 11 on a shared hosting platform.  I previously had this up and running with Tendenci 7 using a virtual environment and I'm also using a virtual environment for Tendenci 11.

I've followed the instructions at https://tendenci.readthedocs.io/en/latest/installation/installation.html#.  I've run into the error reported at #722 and pushed on IAW the discussion associated with that issue.

When I get to the Preparation step that installs tendenci2018_defaults, I get the following:
```
(tendenci_11) [rhills@web636 tendenci_aeva]$ python manage.py load_tendenci2018_defaults
Traceback (most recent call last):
  File "manage.py", line 19, in <module>
    execute_from_command_line(sys.argv)
  File "/home/rhills/.virtualenvs/tendenci_11/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/rhills/.virtualenvs/tendenci_11/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/rhills/.virtualenvs/tendenci_11/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/rhills/.virtualenvs/tendenci_11/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/home/rhills/.virtualenvs/tendenci_11/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/rhills/.virtualenvs/tendenci_11/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rhills/.virtualenvs/tendenci_11/lib/python3.6/site-packages/tendenci/libs/tinymce/models.py", line 6, in <module>
    from tendenci.libs.tinymce import widgets as tinymce_widgets
  File "/home/rhills/.virtualenvs/tendenci_11/lib/python3.6/site-packages/tendenci/libs/tinymce/widgets.py", line 30, in <module>
    import tendenci.libs.tinymce.settings as tinymce_settings
  File "/home/rhills/.virtualenvs/tendenci_11/lib/python3.6/site-packages/tendenci/libs/tinymce/settings.py", line 16, in <module>
    JS_URL = static(getattr(settings, 'TINYMCE_JS_URL', 'tiny_mce/tiny_mce.js'))
  File "/home/rhills/.virtualenvs/tendenci_11/lib/python3.6/site-packages/tendenci/apps/theme/templatetags/static.py", line 115, in static
    return ThemeStaticNode.handle_simple(path, local_only)
  File "/home/rhills/.virtualenvs/tendenci_11/lib/python3.6/site-packages/tendenci/apps/theme/templatetags/static.py", line 53, in handle_simple
    for cur_theme in get_theme_search_order(theme):
  File "/home/rhills/.virtualenvs/tendenci_11/lib/python3.6/site-packages/tendenci/apps/theme/utils.py", line 138, in get_theme_search_order
    raise RuntimeError('No themes found')
RuntimeError: No themes found
```
I've double-checked the steps in the documentation and I am confident I've not missed anything.

**Comment by rob-hills** [comment]
Also, just spotted this in my app log file:
```
TIME="2018-07-10 08:43:27,798" LEVEL=WARNING PID=38355 LOGGER="py.warnings" MSG="/home/rhills/.virtualenvs/tendenci_11/lib/python3.6/site-packages/tendenci/apps/theme/utils.py:159: UserWarning: Theme "" does not have an "extends" value, using "t7-base"
  warn('Theme "%s" does not have an "extends" value, using "t7-base"'%(theme))
```
I noticed in https://github.com/tendenci/tendenci/issues/722#issuecomment-408253540 a reference to t8-base, so maybe there's an outdated reference somewhere?

**Comment by replaceafill** [comment]
@rob-hills I've seen this error before. In the [Tendenci Preparation section](https://tendenci.readthedocs.io/en/latest/installation/installation.html#tendenci-preparation), copying the tendenci2018 theme files should be done **before** loading the tendenci2018 defaults.

**Comment by jennyq** [comment]
Hi @rob-hills, @replaceafill is right! - theme tendenci2018 needs to be copied before loading the tendenci2018 defaults. The doc has been updated https://tendenci.readthedocs.io/en/latest/installation/installation.html#tendenci-preparation. Thanks for pointing it out! As Ed said, we do need to find a way to make installation smoother.

**Comment by rob-hills** [comment]
Hi @eschipul, @jennyq and @replaceafill, thanks for the prompt replies.  I appreciate the quick change to the install docs.  I also appreciate that until something new has been tried by lots of different people in different scenarios it is impossible to get everything perfect.

Unfortunately, before I posted my bug report, I wondered if copying the theme files needed to be done before running `python manage.py load_tendenci2018_defaults` so *after* the initial error, I copied the theme files over (my equivalent of `cp -r /srv/mysite/lib/python3.6/site-packages/tendenci/themes/t7-tendenci2018/* /var/www/mysite/themes/tendenci2018/`) and then re-ran the load defaults command but got exactly the same error message.

Just now, I confirmed that my `mysite/themes` does indeed contain files copied over.  I also re-ran the mode-set command (`chmod -R -x+X /var/www/mysite/media/`) and then again retried the `python manage.py load_tendenci2018_defaults` -> still the same error.

Do I have to backtrack further?  The docs now indicate that the theme needs to be copied over before running the database initialisation commands (`python manage.py initial_migrate` and `python manage.py deploy`.  These previously ran without any error, do they need to be run prior to copying the theme files over for some reason?

I could start the whole install process again from scratch, but it would be good to know exactly why I can't restart from the current point.

Cheers,

**Comment by jennyq** [comment]
Hi @rob-hills, can you please paste the output of this command here?

    python manage.py diffsettings --all | grep THEME

**Comment by jennyq** [comment]
@rob-hills, I wonder if it is due to lack of permissions. Can you please run the following command then try again?

     sudo chown -R "$(id -u -n)" /var/www/mysite

**Comment by rob-hills** [comment]
Hi @jennyq, thanks for your suggestion.  As this is on a hosted account, I can't sudo and I'd be surprised if permissions were anything but my own on any files in the tree.  Nevertheless, I ran your chown command (without the sudo) just in case.  The command reported no errors but unfortunately it hasn't changed anything, I still get the same error message.

**Comment by jennyq** [comment]
I cannot replicate the issue. Did the `initial_migrate` command run successfully? Have you checked if the `tendenci2018` theme is really copied over? Maybe you can first test it in VirtualBox to see if you can replicate the issue?

**Comment by rob-hills** [comment]
@jennyq, IIRC, the `initial_migrate` command ran without error.

WRT the `tendenci2018` theme, I copied the files from `~/.virtualenvs/tendenci_11/lib/python3.6/site-packages/tendenci/themes/t7-tendenci2018` into `~/.virtualenvs/tendenci_11/tendenci_aeva/media/tendenci2018` and I've run the following command to check they're the same:
`diff <(cd ~/.virtualenvs/tendenci_11/lib/python3.6/site-packages/tendenci/themes/t7-tendenci2018 && find . | sort) <(cd ~/.virtualenvs/tendenci_11/tendenci_aeva/media/tendenci2018/ && find . | sort)`

It reports no differences.

I run Ubuntu so I can do a test run here.  As I don't know exactly how my hoster's environment is configured I'm not sure that installing a Virtualbox of their OS (CentOS) would help, unless I consistently get the error remotely but not at home.

I think I'll start by wiping my hosted system and rerunning the install process from the beginning, just in case I missed something.  I was avoiding doing this in the hope of discovering where I'd gone wrong.

**Comment by rob-hills** [comment]
@jennyq, at the point where I install Tendenci and all its dependencies:
`pip install --no-binary psycopg2 -r requirements/dev.txt --upgrade`
I get this error buried amongst the successful installation reports:
```
django-admin-bootstrapped 2.5.7 has requirement Django<1.9,>=1.8, but you'll have django 1.11.15 which is incompatible.
```
I'm sure I've reported this elsewhere.  Anyway, is there any chance this be causing my problem downstream?  Did you get this error when you last ran the install process?

**Comment by jennyq** [comment]
Hi @rob-hills, you can safely ignore the `django-admin-bootstrapped` warning. It does not affect anything. 

Is `~/.virtualenvs/tendenci_11/tendenci_aeva` your site directory?  The `tendenci2018` theme should be copied to `themes/` NOT `media/`.

**Comment by rob-hills** [comment]
@jennyq I am sorry I didn't reply to this at the time.  This stupid mistake on my part was of course the cause of the problem.  I will close this issue now.  Sorry about all the wasted time!
