### ISSUE TITLE
Paypal Errors

### ISSUE THREAD

**Issue by mgrigajtis** [tendenci/tendenci#739]
The return page generates an error for the user, and the silent IPN endpoint doesn't work at all either.

**Comment by jennyq** [comment]
Fixed. 0c451e5ed5e42d35201c3c346d72048b7803b0bc

@eschipul, this issue is python 3 specific. It is **not** related to the multiple payment gateways functionality in memberships. Regarding the multiple payment gateways functionality https://github.com/tendenci/tendenci/pull/735/commits/1fd3421efb59697ed2b299570bd3a323ea799474, I understand your worries. But I think it has both advantages and downsides. Maybe put it on another branch? Since the commit is contributed by @BenSturmfels, do you have any thoughts on this, @BenSturmfels ?

**Comment by BenSturmfels** [comment]
I'm happy to work on any concerns you have @jennyq and @eschipul. I haven't seen any bugs in the multiple online gateways change per se, but I'm aware that requiring the payment method slug to match the payment gateway module does make setup harder.

**Comment by jennyq** [comment]
@BenSturmfels, We have fixed some issues recently https://github.com/tendenci/tendenci/commit/8fab1e897520bbfe318fb1bacdaf4ccab4da635b. Although we like the concept, managing and reconciling multiple accounts can be troublesome. Is there any production site that is actually using (or going to use) this functionality?

@eschipul, I cannot think of what other issues would come out. Can we just leave it as is for now, or would you like it to be pulled to another branch?

**Comment by jennyq** [comment]
Hi @mgrigajtis, can you please confirm that the fix we pushed out works for you? Thanks!

**Comment by mgrigajtis** [comment]
I will update and check soon.

**Comment by mgrigajtis** [comment]
Just to verify, to update I'm executing the following instructions correct?

https://tendenci.readthedocs.io/en/latest/upgrade/point-update.html

**Comment by jennyq** [comment]
Correct.

**Comment by mgrigajtis** [comment]
Unable to get the upgrade to run:
![image](https://user-images.githubusercontent.com/238225/48565923-a047dc00-e8c7-11e8-85a2-a0207b4c35c2.png)

**Comment by jennyq** [comment]
@mgrigajtis, Looks like it's missing Python header files. Do you have `python3.6-dev` installed?
https://tendenci.readthedocs.io/en/latest/installation/installation.html#system-preparation

**Comment by mgrigajtis** [comment]
Was able to get past that with installing python3.6-dev and libmemcached-dev, but now I get this when running the migration:

![image](https://user-images.githubusercontent.com/238225/48584102-e0728300-e8f6-11e8-9013-0f8151a275ca.png)

**Comment by jennyq** [comment]
That dependency `user_groups.0002` was added due to [this issue](https://github.com/tendenci/tendenci/issues/755). If it is removed or changed to `0001`, it would break new sites. Still thinking how to better address it...

**Comment by jennyq** [comment]
@mgrigajtis, the migration error has been resolved. You can pull directly from github for now. 

    pip install https://github.com/tendenci/tendenci/archive/master.zip --upgrade

**Comment by mgrigajtis** [comment]
It appears to be working, but I still got an email about an IPN error.  Not a huge deal as long as it's working.   Thank you for fixing this as quickly as you did!

**Comment by BenSturmfels** [comment]
@jennyq I believe this issue is ready to be closed.

**Comment by jennyq** [comment]
Thanks @BenSturmfels ! Closing it. @mgrigajtis, I'll check out if I can replicate the IPN error when I get the chance.
