### ISSUE TITLE
UnicodeDecodeErrors with theme tendenci2018

### ISSUE THREAD

**Issue by AdamBark** [tendenci/tendenci#740]
I get these errors from various places in the templates with tendenci11 for example the following line in t7-tendenci2018/templates/base.html contains a non-ascii dash character
`<!-- Tendenci2018 Theme Powered by Tendenci — The Open Source AMS`

**Comment by jennyq** [comment]
Hi @AdamBark, If your system's default locale is UTF-8, this won't be an issue. You might need to configure your system's locale. For example, we're on Ubuntu 18.04, the /etc/default/locale file should have `LANG="en_US.UTF-8"`. You can update it with the command `sudo update-locale LANG="en_US.UTF-8"`.

**Comment by AdamBark** [comment]
Ah, thanks for your help @jennyq. `update-locale` didn't work for me (maybe something docker related) I had to do the following:

1. `apt-get install locales`
2. make sure `en_US.UTF-8 UTF-8` appears in /etc/locale.gen
3. `locale-gen`
4. set the environment variable LANG=en_US.UTF-8

I'll see if I can add it to the docs and submit a PR
