### ISSUE TITLE
Permissions error when uploading files

### ISSUE THREAD

**Issue by rjdini** [tendenci/tendenci#747]
I am running Tendenci 11 on a development site '*****', for a project 'ssn'. 
In general, things are working as expected.
Now I wish to build a form that will enabled registered users to upload files to various categories.
I am testing this upload first as admin.
When I attempt upload I obtain the following permissions error:
(any advice please?)

Request Method: | POST
-- | --
https://*******/files/add/
1.11.15
PermissionError
[Errno 13] Permission denied: '/code/ssn/media/files/files/10adb1e3'
/usr/lib/python3.6/os.py in makedirs, line 220
/venv/bin/uwsgi
3.6.5
['.',  '',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/venv/lib/python3.6/site-packages']
Sun, 21 Oct 2018 19:44:03 +020

**Comment by rjdini** [comment]
The above file problem may be associated with this forms error?

------------------------------
Request Method: | GET
-- | --
https://******/settings/module/forms/
1.11.15
NoReverseMatch
Reverse for 'form_entries' with arguments '('',)' not found. 1 pattern(s) tried: ['forms/entries/(?P<id>\\d+)$']
/venv/lib/python3.6/site-packages/django/urls/resolvers.py in _reverse_with_prefix, line 497
/venv/bin/uwsgi
3.6.5
['.',  '',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/venv/lib/python3.6/site-packages']
Sun, 21 Oct 2018 22:45:32 +0200

**Comment by rjdini** [comment]
Sorry... 
These permission errors are a uwsgi/docker implementation issue.
No need to pursue them here.

**Comment by rjdini** [comment]
Sorry... 
These permission errors are a uwsgi/docker implementation issue.
No need to pursue them here. The matter can be closed.

**Comment by rjdini** [comment]
Sorry....
The permissions errors are a docker/uwsgi implementation issue,
and need not be addressed here. I am closing the issue.

**Comment by rjdini** [comment]
I am reopening this issue because access to the settings/forms stiil elicits the following error,
even in the absence of uwgsi...   
The error appears to be in the 'tendenci2018' style template handling.

Request Method: | GET
-- | --
http://iniforum-dev.iniforum.ch/settings/module/forms/%23id_url
1.11.15
NoReverseMatch
Reverse for 'form_entries' with arguments '('',)' not found. 1 pattern(s) tried: ['forms/entries/(?P<id>\\d+)$']
/srv/venv/lib/python3.6/site-packages/django/urls/resolvers.py in _reverse_with_prefix, line 497
/srv/venv/bin/python
3.6.5
['/var/www/project',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/srv/venv/lib/python3.6/site-packages']
Mon, 22 Oct 2018 04:38:53 +0200

Error during template rendering
In template /srv/venv/lib/python3.6/site-packages/tendenci/themes/t7-base/templates/forms/top_nav_items.html, error at line 77

Reverse for 'form_entries' with arguments '('',)' not found. 1 pattern(s) tried: ['forms/entries/(?P<id>\\d+)$']

** line 77 ** <a href="{% url 'form_entries' app_object.pk %}">{% trans "View Entries" %}</a>

**Comment by jennyq** [comment]
Hi @rjdini, I think this issue has been resolved in this commit https://github.com/tendenci/tendenci/commit/8c37817d5be85386fb4516366479ed446226eb22. Are you on the latest version of T11?

**Comment by rjdini** [comment]
Yes, you are correct jennyq. 
I was trailing behind at 11.0.2
sorry to have wasted your time.
I'm closing the issue.
