### ISSUE TITLE
global restore of standard user level permissions

### ISSUE THREAD

**Issue by rjdini** [tendenci/tendenci#749]
After making changes to some group permissions, I now find that when a member requests their invoices (using the topbar, or dashboard) they get to see _all_ invoices, not only theirs. 
How can I restore the security of the invoice page?
And more generally, how can I globally restore user / member permissions to Tendenci standard levels?

**Comment by jennyq** [comment]
@rjdini, Please check if groups have been granted the "Can view invoice" permission. If so, just remove the permission. It should be easy to do if you don't have a lot of groups. 

If you really want to wipe out all group permissions (restore to their initial state), you can issue a sql statement to your database like this:

    delete from user_groups_group_permissions;

**Comment by rjdini** [comment]
OK @jennyq - I think I see the problem now. It is not in the permissions settings, but rather in the nature of the call for invoices in the /profiles/ view, or when using the invoices call in the user topbar.

In both these cases the call looks (in my case)
https://****/invoices/search/?search_criteria=owner_id&search_text=39&search_method=exact

This call returns the invoices of the present user **but also** any other similar user, even those that have been deleted. Presumably this is because the search is on the record of invoices, and I think it is not constrained sufficiently to the specific identity of the calling user.

This issue may constitute a breach of privacy / security?

**Comment by rjdini** [comment]
A should add - it seems that when a user is deleted, tendenci is willing to use that deleted users' username again. For example John Doe was a user and Tendenci issued him username jdoe.  jdoe generated some invoices. For some reason this user is deleted. Now Jane Doe signs up as user / member. Now she generates some invoices. But when she calls to see her invoices, tendenci returns both John Doe and Jane Doe's invoices.
Perhaps the search should exclude all invoices before the callers join date?

**Comment by jennyq** [comment]
Tendenci does allow to recycle username. But ordinary users will NOT be able to view others' invoices even though they happen to have the same username from a deleted user. However, if they have the same email as the delete user, they will be able to access those invoices that belong to the deleted user. In this case, I think it's fine. 

The logic is that users can view those invoices if they're creator, owner or with the same email address as the bill_to_email:

    invoices = invoices.filter(Q(creator=request.user) |
                      Q(owner=request.user) |
                      Q(bill_to_email__iexact=request.user.email)
                      ).order_by('-create_dt')
https://github.com/tendenci/tendenci/blob/master/tendenci/apps/invoices/views.py#L342

**Comment by rjdini** [comment]
Yes, I agree - Its fine if the email is the only common factor.  

I am forced to use only a few common emails for testing - and so these past invoices are an artefact of this restriction. 

Thanks for your explanation, @jennyq 
I am closing this issue.
