### ISSUE TITLE
Member event registration conditional on paid membership invoice.

### ISSUE THREAD

**Issue by rjdini** [tendenci/tendenci#750]
My use case is that a Member should be able to register for an association event without payment, provided that this user is a fully paid up Member (no outstanding invoices).

If the person attempts to register, but is not paid up, then he should receive immediate notification of this fact, and/or be directed to his invoices.

I cannot see how to set this up. Any suggestions?

**Comment by jennyq** [comment]
Hi @rjdini, this functionality does not exist currently. Sounds a good idea though.

**Comment by rjdini** [comment]
Is it possible for me to contract Tendenci to provide such a 'member in good standing' flag asap?
If so - how should I go about this?

**Comment by eschipul** [comment]
@rjdini - yes, Tendenci can help with that. Yet I would encourage you to also look at some of the people who have contributed code to Tendenci on github. We're a tiny company behind a much larger community and when you help the developers who are helping ALL OF US create change, it's a good thing.

From a conditional logic perspective, given there are tons of UD (user defined fields) in the "profile" object associated with every auth_user, that means there is an easy hook to do an if/then in the template itself.

Does that answer your question?

**Comment by eschipul** [comment]
Another group that we are super grateful to is the people who help make Tendenci the most open and international multilingual ams out there! Huge props to the people who are helping with the documentation and translations. Now up to almost 80 languages on Transifex. https://www.transifex.com/tendenci/tendenci/

**Comment by rjdini** [comment]
OK Thanks @eschipul. I will look into these options.
