### ISSUE TITLE
Search box on /pages/search/ does not function.

### ISSUE THREAD

**Issue by rjdini** [tendenci/tendenci#756]
Also not on the demo site.

**Comment by jennyq** [comment]
It works fine for me (tried in both Chrome and FF). https://demo.tendenci.com/pages/search/?q=Welcome

Does it not show the search results for you, or what exactly is not functioning?

**Comment by rjdini** [comment]
When landing on /pages/search, all pages are shown. However, when text in the search box and submitted, the page does not update with results.

**Comment by rjdini** [comment]
When landing on /pages/search, all pages are shown. However, when text in the search box and submitted, the page does not update with results.

**Comment by rjdini** [comment]
I have been pressing the search button to activate search. That does not work. But pressing enter in the search box, does work.

**Comment by jennyq** [comment]
Fixed https://github.com/tendenci/tendenci/commit/3fda9fa38d11cf733c6e70ff223d3311c4a9ebf9

@rjdini, Thank you for pointing it out!
