### ISSUE TITLE
how to restore lost form with id=1 at /contact/

### ISSUE THREAD

**Issue by rjdini** [tendenci/tendenci#757]
I have in error deleted the /contact/ form id=1, and so have lost my default contact page/form.
How can I restore this form in running installation? 
thanks

**Comment by rjdini** [comment]
OK, I see how to point to a new form in settings.
However, there is no captcha at the bottom of my new form, even though captcha=true in settings.
The email is sent to the CCs, but is not sent to the administrative target

**Comment by rjdini** [comment]
OK captha solved (must point /contact/ not /forms/contact/ ).
Neverthess, the contact form is not being sent to the primary target (as set in settings). CC's go out.

**Comment by eschipul** [comment]
@rjdini - Captcha basic is ok, but you will probably find out you quickly that you want to register with google's recaptcha as described here:
https://www.tendenci.com/help-files/how-use-google-recaptcha-tendenci-site/

Two other solutions - note the "forms" query at the bottom of this help file:
[https://www.tendenci.com/help-files/how-use-django-sql-explorer-tendenci/](https://www.tendenci.com/help-files/how-use-django-sql-explorer-tendenci/)

`SELECT  
       CONCAT('/forms/', f.id, '/'), f.title, 
       f.allow_anonymous_view, f.status, f.status_detail, f.create_dt  
FROM forms_form f  
WHERE  
f.allow_anonymous_view=False  
OR  
f.status=False  
OR  
(f.status_detail<>'active' AND f.status_detail<>'published')  
ORDER BY f.id, f.allow_anonymous_view asc,  
f.status_detail asc`  

Regarding delivery, make sure you are checking /admin/forms/ for that specific form. And also checking the settings globally and for that module. 

Lastly - check your settings and local_settings.py file for your email servers, that they are white listed and that you have SPF files set up for your domain. All of that is explained here:
https://www.tendenci.com/help-files/tendenci-forms-email-notifications/

**Comment by rjdini** [comment]
Thankuou for the pkid advice!! That's really useful - i've been wondering about that.
Anyway - after many hours of effort it turns out that the contact email was being blocked downstream of tendenci, and directed to a spam queue!  
So no fault on the tendenci side. Thanks though for your helpful diagnostic comments - and for the pkid hint.
I'm closing this issue.
