### ISSUE TITLE
Tax calculated before discount on invoices

### ISSUE THREAD

**Issue by martcot** [tendenci/tendenci#763]
Is it normal that amount for the tax on invoice is calculated before to apply discount on subtotal.

**Comment by jennyq** [comment]
Hi @martcot, you have raised a very good question. The short answer is yes.

> If the item is on sale at a reduced price, or with a store coupon issued by the seller, sales tax is charged on the reduced price.  

> If the reduced price is the result of a manufacturer's reimbursement, such as a manufacturer's coupon or rebate or any other third-party's reimbursement, then the sales tax is charged on the full price of the item without regard to the reimbursement to the seller.

https://tax.custhelp.com/app/answers/detail/a_id/1683/~/when-an-item-is-purchased-on-sale%2C-is-sales-tax-due-on-the-original-price-or

So, it boils down to how the discount is interpreted. I think Tendenci is trying to not complicate the things and picked the latter case.

**Comment by eschipul** [comment]
@martcot -  I have been down this road a few times and I agree 100% with @jennyq. The complexity of international tax laws is not a design goal for Tendenci. While there is an underlying general ledger, it is not an accounting system with a full  "balanced ledger," With Tendenci it is ultimately up to each site to determine the overall price and manage disbursement of funds.

Example: 

1) a political group has a gala to fund raise for a candidate. Laws might (hopefully) limit the amount one group can contribute to a candidate. This leads to what I view as questionable allocation of funds if it is at a restaurant that charges tax in that jurisdiction. This is up to the Executive Director and Accountant to allocate.

2) In the US if you attend a fundraiser where the price is $1,500 USD per person, but you receive dinner and there is entertainment provided, as well as the overhead of the staff, with a COGS for each attendee from the venue of say $150, it is up to the 501c3 (NGO designation in the US) then the taxable base becomes 1,500 - 150 =  1,350. Then if the NGO/NPO, in whatever country they are in, can legally add on outside contractors (valet, waiters, alcohol served might be taxable while food is not), there is simply no way to handle all of these contingencies.

It is for these exponentially complex variables internationally [https://www.transifex.com/tendenci/tendenci/ ](https://www.transifex.com/tendenci/tendenci/ )that we leave disbursement of funds to the organization itself.

Personally, when on the board of an NGO, I prefer to raise the price by the minimal difference, state clearly in the description of the event that the tax is included, and leave it to the professionals to be sure everything is 100% in compliance with all applicable laws in whichever jurisdiction applies. There will be attendees who themselves are tax exempt as well, and each country has different ways of documenting and reporting this. That is beyond the scope of an Open AMS and in the purview of accounting, legal, and government officials. 

What we CAN and MUST do is provide the raw data, even if not broken down by COGS or taxes but the raw data, to allow the NGO/NPO/Association to pay any and all fees and taxes they may owe. 

This can always be done via /explorer/ for example if none of the existing exports work.

That said, if you have a particular situation, you might want to consider a custom export in /explorer/ and processing that CSV in Excel or Google Docs, etc, to massage the data for your specific situation prior to importing into your accounting system.

For more on Explorer - here are a few examples: https://www.tendenci.com/help-files/how-use-django-sql-explorer-tendenci/ and while it resets every few hours you can always test on the demo site at https://demo.tendenci.com/explorer/ (login admin/admin).

And note the "schema" button below each query to explore your data directly. I believe we have over 50 custom sql statements for tendenci.com for things like brand name changes, SEO optimization, and many more. You would have to modify them for your specific need, but I'm happy to share them if you want?

Great question BTW. I'm going to modify it and add it (my response) in a more generic fashion as a help file so it shows up in google better.

#peace
