### ISSUE TITLE
Is removing RegistrationProfile objects an issue?

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#764]
Hi,
We have lots of RegistrationProfile objects in our tendenci instance (15k-20k). We're in the process of setting up some automated cleaning to augment that of Tendenci and wondering if its safe/ok/a problem to delete the items which are marked ALREADY_ACTIVATED.

thanks,

**Comment by jennyq** [comment]
Hi @goetzk, it should be safe to delete those items marked as ALREADY_ACTIVATED.

**Comment by goetzk** [comment]
Thanks @jennyq !
