### ISSUE TITLE
Installation tips

### ISSUE THREAD

**Issue by avkovalevs** [tendenci/tendenci#768]
Hello.
I installed tendenci software using the official guide and currently have some questions.
1. I use Ubuntu 18 for production use. I need to tune start/stop scripts.
With postgres database and nginx I havn't a problem. But when I trying to add mysite.service I see that it's not starting correctly.
akovalev@fa-na-tendenci:~$ cat /etc/systemd/system/mysite.service
[Unit]
Description=Start Tendenci instance
Requires=nginx.service postgresql@10-main.service
#Wants=memcached.service
Before=nginx.service
After=postgresql@10-main.service

[Service]
WorkingDirectory=/var/www/mysite
PIDFile=/run/mysite.pid
Type=forking
KillMode=process
Restart=on-failure
ExecStart=/srv/mysite/bin/gunicorn                    \
          --user www-data                               \
          --group www-data                              \
          --workers 4                                   \
          --bind=127.0.0.1:8000                         \
          --pid=/run/mysite.pid                       \
          --pythonpath=/var/www/mysite                \
          --access-logfile=/var/log/mysite/access.log \
          --error-logfile=/var/log/mysite/server.log  \
          --capture-output                              \
          --daemon                                      \
         conf.wsgi

[Install]
WantedBy=multi-user.target
++++++++++++++++++++++++++++++++++++
akovalev@fa-na-tendenci:~$ systemctl status mysite.service
Warning: The unit file, source configuration file or drop-ins of mysite.service changed on disk. Run 'systemctl daemon-reload' to re
● mysite.service - Start Tendenci instance
   Loaded: loaded (/etc/systemd/system/mysite.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-03-04 09:41:54 UTC; 50s ago
  Process: 3717 ExecStart=/srv/mysite/bin/gunicorn --user www-data --group www-data --workers 4 --bind=127.0.0.1:8000 --pid=/run/mys
 Main PID: 3730 (code=exited, status=1/FAILURE)

++++++/var/log/mysite/server.log++++++++++
raceback (most recent call last):
  File "/srv/mysite/bin/gunicorn", line 10, in <module>
    sys.exit(run())
  File "/srv/mysite/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 61, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/srv/mysite/lib/python3.6/site-packages/gunicorn/app/base.py", line 223, in run
    super(Application, self).run()
  File "/srv/mysite/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/srv/mysite/lib/python3.6/site-packages/gunicorn/arbiter.py", line 232, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/srv/mysite/lib/python3.6/site-packages/gunicorn/arbiter.py", line 345, in halt
    self.stop()
  File "/srv/mysite/lib/python3.6/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/srv/mysite/lib/python3.6/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
    self.reap_workers()
  File "/srv/mysite/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/var/log/mysite/server.log' mode='a+' encoding='UTF-8'>
sys:1: ResourceWarning: unclosed <socket.socket fd=8, family=AddressFamily.AF_INET, type=2049, proto=0, laddr=('127.0.0.1', 8000)>
[2019-03-04 03:51:24 -0600] [4403] [ERROR] Exception in worker process
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/var/log/mysite/server.log' mode='a+' encoding='UTF-8'>
sys:1: ResourceWarning: unclosed <socket.socket fd=8, family=AddressFamily.AF_INET, type=2049, proto=0, laddr=('127.0.0.1', 8000)>
[2019-03-04 03:51:24 -0600] [4403] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/config.py", line 565, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib/python3.6/logging/config.py", line 738, in configure_handler
    result = factory(**kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/var/log/tendenci/debug.log'

During handling of the above exception, another exception occurred:

++++++++++++
When I start like:
postgres@fa-na-tendenci:/var/www/mysite$ source /srv/mysite/bin/activate
(mysite) postgres@fa-na-tendenci:/var/www/mysite$ python manage.py runserver
It's running correctly. But I can't undestand how to correctly stop the appliction.
Could you explain the clear method of how to start/stop the tendenci application?

**Comment by jennyq** [comment]
Hi @avkovalevs, please check the documentation for how to start/stop the tendenci application (we've added more commands recently).  
https://tendenci.readthedocs.io/en/latest/installation/installation.html#systemd-setup

Your traceback shows the PermissionError. Check if you have proper permissions set up for `/var/log/tendenci/debug.log`.

**Comment by avkovalevs** [comment]
Hi @jennyq, thank you!
