### ISSUE TITLE
Could not find a version that satisfies the requirement

### ISSUE THREAD

**Issue by jucajuca** [tendenci/tendenci#770]
Hi,
I'm trying to create a docker image with ubuntu 18.10
I get the following error:

Could not find a version that satisfies the requirement tendenci<12,>=11

any ideas?

**Comment by jennyq** [comment]
Hi @jucajuca, it probably has something to do with the Python version. Can you please check the version of Python installed on your system?

**Comment by jucajuca** [comment]
Hi @jennyq, yes, the ubuntu image comes with python2, I installed:
 python3 python3-dev python3-pip python3-virtualenv
and it worked now. thx.

**Comment by jennyq** [comment]
Great!
