### ISSUE TITLE
MembershipApplication error 

### ISSUE THREAD

**Issue by avkovalevs** [tendenci/tendenci#771]
Helllo!
I have an error when I try to save Field (Home->Membership Application->Field (Click on Salutation, then Save).
I got an error below:
"Oops akovalev, we caused a problem
We have been notified of this and will be working on it quickly.
You may want to try this page again in a little bit."

If I click the button 'Save and continue editing' then there is no error.  
These changes I do with a superuser account.
Could you help me with it?

**Comment by jennyq** [comment]
Thank you @avkovalevs for reporting the issue!

**Comment by claudobahn** [comment]
@jennyq the same issue exists here: https://github.com/tendenci/tendenci/blob/master/tendenci/apps/corporate_memberships/admin.py#L526

**Comment by jennyq** [comment]
Fixed as well. https://github.com/tendenci/tendenci/commit/d0810ce8a7f9967eba39f540e2cf4e9446f4078f  Thanks!

**Comment by avkovalevs** [comment]
@jennyq I've changed the file /srv/mysite/lib/python3.6/site-packages/tendenci/apps/memberships/admin.py on the file which you provided (admin.py). But I can't open my site now. When I returned my file back, the site became available. My tendenci version is 11.1.2. What do I need to do?

**Comment by jennyq** [comment]
@avkovalevs, We've just pushed out the a new version of tendenci to PyPI. Can you try to run tendenci update for your site?  
https://tendenci.readthedocs.io/en/latest/upgrade/point-update.html
