### ISSUE TITLE
ics calendar file does not validate / broken

### ISSUE THREAD

**Issue by ghost** [tendenci/tendenci#779]
Hi,

When I access the calendar file using for example the following URL https://mydomain.com/events/ics/ , it does not properly validate and the events do not show.

same for the pattern https://mydomain.com/events/ics/2/

and they appear to be in GMT+00:0 which is not the timezone specified for the event.

Is there a way to let users synchronize the events of our association with their calendar, ie google calendar?

**Comment by jucajuca** [comment]
There is a "Missing DTSTAMP property" see: https://icalendar.org/iCalendar-RFC-5545/3-6-1-event-component.html

probably this should be added somewhere here:
https://github.com/tendenci/tendenci/blob/master/tendenci/apps/events/utils.py

**Comment by jennyq** [comment]
@jucajuca, Great catch! Yes, it appears that DTSTAMP is a required property in the iCalendar Specs.  Pull requests are always welcome. And thank you for fixing the delimiter with CRLF! 

I also see your point on GMT+00:0. Feel free to correct it as well.

**Comment by jucajuca** [comment]
thanks for the suggestions. I wonder if the bug should be marked as won't solve?

**Comment by jennyq** [comment]
No. It can and should be resolved.

**Comment by jennyq** [comment]
The validation errors including "Missing DTSTAMP property" have been resolved in this commit. https://github.com/tendenci/tendenci/commit/3cbb3209a8b692a75a106c93bf00c7bf19f6705a
