### ISSUE TITLE
[Django] ERROR (EXTERNAL IP): Internal Server Error: /

### ISSUE THREAD

**Issue by avkovalevs** [tendenci/tendenci#781]
Hello,
Could you help me understand the error which generate the Tendenci:
Exception Type: TemplateSyntaxError at /
Exception Value: Could not parse the remainder: 'autres' from ''Voir d'autres'
Request information:
USER: AnonymousUser

GET: No GET data

POST: No POST data

FILES: No FILES data

COOKIES:
django_language = 'en-us'
How can I resolve it?

**Comment by jennyq** [comment]
@avkovalevs, there must be a syntax error in one of your templates near the words "Voir d'autres".  Can you find that template and post the content of the template?

**Comment by avkovalevs** [comment]
@jennyq I suppose this is a template of the main page / because when I open it I see 'Oops akovalev, we caused a problem'
How can I find it?
The template has changed other man.

**Comment by jennyq** [comment]
Can you turn on the debug mode (set `DEBUG = True` in the conf/settings.py) to see the traceback?

**Comment by avkovalevs** [comment]
Error during template rendering

In template /var/www/mysite/themes/tendenci2018/templates/homepage.html, error at line 212
Could not parse the remainder: 'autres' from ''Voir d'autres'

**Comment by jennyq** [comment]
Can you remove the trans tag from that sentence? The trans tag accepts English only, not other languages.

**Comment by avkovalevs** [comment]
When I use Escape symbols, the page is working.
''Voir d\'autres'

**Comment by jennyq** [comment]
Ok. I think there is no need to wrap that in a trans tag.
