### ISSUE TITLE
How can I grant access for imported members

### ISSUE THREAD

**Issue by avkovalevs** [tendenci/tendenci#782]
Hello.
I've imported more than 2000 of users and now I need to grant them access to the site as usual members (who can edit his own profile, forum talks, register an event and so on).
They have not a password yet. 
When I imported list some users have not his own e-mails and I provide them default e-mail like member@domain.com.
How to organize access to them? Maybe who has a real e-mail I need to send them a newly generated password? What kind of 'simple' grants need to provide them for the first time? I suppose I need psql script to do a mass update of the grants...Could you advise me?

**Comment by eschipul** [comment]
First things first - there are "users" and "members". These are handled differently. Assuming we are talking about "users" (and membership is actually just an attribute of a user profile object), then using the demo site as an example, you would go to:

https://demo.tendenci.com/profiles/import/
There you have numerous options, including "update". So you set up your groups (groups control security and email newsletters etc.) Set those up at /admin/

Once you get your groups set up, assuming a unique key for the user, you can simply redo the import over and over using subsets to add people to multiple or different groups. On subsequent imports of the same data, check the "update" box to have it update the user record.

I definitely do NOT recommend using the same email address for different users. A better option would be to use some form of password hash like x75rft@example.org or pick the memberid as the import key.

Super_user login - Apps top menu - #4 User Management - user imports

**Comment by eschipul** [comment]
This gets pretty in depth, but for larger organizations with logs of sub-committees and millions of dollars and hundreds of thousands of users, it becomes very important that the "bones" of the house are structured properly.

[https://www.tendenci.com/help-files/entities/](https://www.tendenci.com/help-files/entities/)

Essentially entities are "money" and groups are "security and organization". Both entities and groups must be configured properly for larger organizations. Smaller orgs, say less than 5k, often just have one entity and associate all groups with that one entity. That's now how I designed it to be used, but I guess for some people that works.

Pro Tip: use /explorer/ to select groups of users based on some criteria, like zip code, and then reimport them with the "update" option and you can slice and dice your data a billion ways. There is a help file on explorer here [https://www.tendenci.com/help-files/how-use-django-sql-explorer-tendenci/](https://www.tendenci.com/help-files/how-use-django-sql-explorer-tendenci/)  although for most clients the tons of imports and exports options are plenty.

If you do write a really cool explorer query that others might find helpful, consider a pull request to add it to the fixture maybe?

**Comment by avkovalevs** [comment]
Ed, thank you for the explanation. 
I've added 2000 users during the import phase with Basic Membership. We are a small org with a number of members less than 5k. 
What are the next steps I need to do to move users to a member state?

**Comment by avkovalevs** [comment]
Ed, I want to understand the dependencies between the group->entity->grants.
As I know there are some default groups like 0001 Global communications, 0002 Cause and Mission Outcomes, Committee, Membership: Basic Membership and so on. Each of the group has a relation with the Entity.  When I create a custom group I need to choose one of the predefined entity. How can I understand which of the entity I need to choose? Do I understand correctly that the Entity is the same set of grants? Can I drop or add grants to the Entity when I edit the group?
We want to get a simple structure:
1. 2 Groups - Members, who can log in, write to the forum, read and publish news, get newsletters and so on; Bureau - admin team, a full set of grants.
2. Membership without payment for members
How we can tune it using Entity?

**Comment by eschipul** [comment]
How to fix a bulk import - redo the import.

When you re-import set the fields set as you want them. Meaning select a key of "first_name/last_name/email" (or whatever is unique to your data set. Redo the import with the fields changed how you wish (e.g. add membership id). 

Everyone is a "user". Period. If they can login then they are status=True and status_detail='active'. Status detail is helpful, for example, if members must apply and then be approved before logging in.

Generally try to use the built in imports and exports when possible. And don't forget at /explorer/ you can see your whole database schema and run queries on subsets. There is a help file on explorer at https://www.tendenci.com/help-files/how-use-django-sql-explorer-tendenci/

Groups control security and organizations. Entities are used to track money primarily.

Membership without payment would be a different "membership type" which you can set up in /admin/

Lastly - sorry for the delayed response. I just missed this one. Things are hectic. But I'm glad Tendenci is working for you!

**Comment by eschipul** [comment]
Make your entities first. The default groups are just so people get the idea. When we launch a site a typical start would be (note it's faster to rename the current ones initially then add more as needed):
Entities:
1) rename "0001 The Association" to "Tendenci" (org name)
2) rename "0002..." to be whatever you call your organizational units. Committees, Study Groups, etc....
3) rename "0003..." to be another organizational unit like "Study Groups" of type reporting

If you have a small org you might need only 1 or 2 entities. Some clients just delete them all and keep the entity with the ID of 1. The purpose is for budgeting. If you have a committee that does a golf tournament they might have to make a $100k USD deposit in February for an event in September that brings in $250k. 

Groups handle security as well as make it easy to filter your content. This client doesn't use many groups, but has lots of "membership types". You can see how it looks for example here: https://www.ucda.com/events/32/

This is an example of a group tied to a study group. Note the filter on the events on the right hand side of the page. And you can delegate editing rights to JUST that group to reduce your load.
https://www.spegcs.org/study-groups/permian-basin/
or
https://www.spegcs.org/about-yps/

I can't link to live client financial reports but you can get an idea of how they work from the screen shots here:
https://www.tendenci.com/photos/set/130/

Tendenci is build for large multi-chapter multinational organizations, but it works great for smaller organizations as well. 

I'm a privacy advocate so there are no back-door logins to Tendenci, but I'll be happy to help another developer get the configuration set up if you want to do a skype call. I'm currently in US CST. Skype or Jitsi.

**Comment by avkovalevs** [comment]
Ed, thank you for the explanation. Some things become more clear to me.
