### ISSUE TITLE
KeyError at /memberships/applications/basic-membership-application/  'payment_method'

### ISSUE THREAD

**Issue by avkovalevs** [tendenci/tendenci#783]
Hello,
I have an exception on basic-membership-application:

Django Version: | 1.11.20
-- | --
KeyError
'payment_method'
/srv/mysite/lib/python3.6/site-packages/tendenci/apps/memberships/forms.py in __init__, line 1187
/srv/mysite/bin/python3.6
3.6.7
['/var/www/mysite',  '/srv/mysite/bin',  '/srv/mysite/lib/python36.zip',  '/srv/mysite/lib/python3.6',  '/srv/mysite/lib/python3.6/lib-dynload',  '/usr/lib/python3.6',  '/srv/mysite/lib/python3.6/site-packages']

1186         if not require_payment:
1187             del self.fields['payment_method']
1188         else:
1189             payment_method_qs = self.membership_app.payment_methods.all()
1190             if not (request_user and request_user.is_authenticated and request_user.is_superuser):
1191                 payment_method_qs = payment_method_qs.exclude(admin_only=True)

This exception happens when I trying to add a Membership application to a new user.
If I add a Corporate Membership Application then exception not happened.
How to avoid an exception?

**Comment by jennyq** [comment]
@avkovalevs, thanks for reporting the issue. We'll look into it.

**Comment by jennyq** [comment]
Hi @avkovalevs, I cannot replicate the issue. Are you on the latest version of Tendenci (11.2.8)?

**Comment by avkovalevs** [comment]
No, we use the version of Tendenci 11.1.2.

**Comment by avkovalevs** [comment]
@jennyq Do we need to be updated?
How not to break our system when upgrading?

**Comment by jennyq** [comment]
Yes, upgrading to the latest version is always recommended. If you're afraid of breaking things, back up everything before running the update.

**Comment by avkovalevs** [comment]
@jennyq 
I updated tendency today and this exception still exists.
Example with a user which is not a member yet:
1. In "Community > Users" page, search for last name "Boubel"
2. Click on his name
3. Click on the "+" sign after the word "Memberships"
4. Click on the second "Join" link (membership application) basic-membership-application
5. An error appears

**Comment by jennyq** [comment]
Hmm.. Can you please post the full traceback?

**Comment by avkovalevs** [comment]
Environment:


Request Method: GET
Request URL: https://www.example.org/memberships/applications/basic-membership-application/?username=j73boubel

Django Version: 1.11.20
Python Version: 3.6.7
Installed Applications:
['django_admin_bootstrapped',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.humanize',
 'django.contrib.sitemaps',
 'django.contrib.messages',
 'django.contrib.admindocs',
 'django.contrib.staticfiles',
 'django.contrib.gis',
 'formtools',
 'bootstrap3',
 'dj_pagination',
 'tagging',
 'captcha',
 'haystack',
 'tastypie',
 'timezone_field',
 'gunicorn',
 'tendenci.libs.model_report',
 'tendenci.libs.tinymce',
 'tendenci.libs.uploader',
 'tendenci.apps.entities',
 'tendenci.apps.base',
 'tendenci.apps.site_settings',
 'tendenci.apps.contributions',
 'tendenci.apps.search',
 'tendenci.apps.notifications',
 'tendenci.apps.registration',
 'tendenci.apps.registry',
 'tendenci.apps.api_tasty',
 'tendenci.apps.invoices',
 'tendenci.apps.payments',
 'tendenci.apps.payments.stripe',
 'tendenci.apps.recurring_payments',
 'tendenci.apps.forms_builder.forms',
 'tendenci.apps.accounts',
 'tendenci.apps.files',
 'tendenci.apps.user_groups',
 'tendenci.apps.perms',
 'tendenci.apps.profiles',
 'tendenci.apps.meta',
 'tendenci.apps.tags',
 'tendenci.apps.articles',
 'tendenci.apps.jobs',
 'tendenci.apps.news',
 'tendenci.apps.stories',
 'tendenci.apps.pages',
 'tendenci.apps.events',
 'tendenci.apps.photos',
 'tendenci.apps.memberships',
 'tendenci.apps.corporate_memberships',
 'tendenci.apps.locations',
 'tendenci.apps.industries',
 'tendenci.apps.regions',
 'tendenci.apps.educations',
 'tendenci.apps.careers',
 'tendenci.apps.make_payments',
 'tendenci.apps.accountings',
 'tendenci.apps.emails',
 'tendenci.apps.email_blocks',
 'tendenci.apps.contacts',
 'tendenci.apps.robots',
 'tendenci.apps.versions',
 'tendenci.apps.event_logs',
 'tendenci.apps.categories',
 'tendenci.apps.theme_editor',
 'tendenci.libs.styled_forms',
 'tendenci.apps.newsletters',
 'tendenci.apps.redirects',
 'tendenci.apps.directories',
 'tendenci.apps.help_files',
 'tendenci.apps.resumes',
 'tendenci.apps.boxes',
 'tendenci.apps.mobile',
 'tendenci.apps.campaign_monitor',
 'tendenci.apps.wp_importer',
 'tendenci.apps.wp_exporter',
 'tendenci.apps.theme',
 'tendenci.apps.discounts',
 'tendenci.apps.metrics',
 'tendenci.apps.navs',
 'tendenci.apps.tendenci_guide',
 'tendenci.apps.exports',
 'tendenci.apps.events.ics',
 'tendenci.apps.imports',
 'tendenci.apps.handler404',
 'tendenci.apps.reports',
 'tendenci.apps.dashboard',
 'tendenci.apps.social_media',
 'tendenci.apps.announcements',
 'tendenci.apps.forums',
 'tendenci.apps.committees',
 'tendenci.apps.case_studies',
 'tendenci.apps.donations',
 'tendenci.apps.speakers',
 'tendenci.apps.staff',
 'tendenci.apps.studygroups',
 'tendenci.apps.videos',
 'tendenci.apps.testimonials',
 'tendenci.apps.social_services',
 'tendenci.apps.explorer_extensions',
 'explorer',
 'kombu.transport.django',
 'djcelery',
 'debug_toolbar']
Installed Middleware:
['django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.common.CommonMiddleware',
 'dj_pagination.middleware.PaginationMiddleware',
 'tendenci.apps.profiles.middleware.ForceLogoutProfileMiddleware',
 'tendenci.apps.profiles.middleware.ProfileMiddleware',
 'tendenci.apps.base.middleware.Http403Middleware',
 'tendenci.apps.redirects.middleware.RedirectMiddleware',
 'tendenci.apps.mobile.middleware.MobileMiddleware',
 'tendenci.apps.theme.middleware.RequestMiddleware',
 'tendenci.apps.base.middleware.MissingAppMiddleware',
 'tendenci.apps.memberships.middleware.ExceededMaxTypesMiddleware',
 'tendenci.apps.forums.middleware.PybbMiddleware',
 'tendenci.apps.profiles.middleware.ProfileLanguageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware']



Traceback:

File "/srv/mysite/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/srv/mysite/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/srv/mysite/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/srv/mysite/lib/python3.6/site-packages/tendenci/apps/perms/decorators.py" in wrapped
  80.             return fn(request, *args, **kwargs)

File "/srv/mysite/lib/python3.6/site-packages/tendenci/apps/memberships/views.py" in membership_default_add
  1109.         multiple_membership=multiple_membership, **params)

File "/srv/mysite/lib/python3.6/site-packages/tendenci/apps/memberships/forms.py" in __init__
  1177.             del self.fields['payment_method']

Exception Type: KeyError at /memberships/applications/basic-membership-application/
Exception Value: 'payment_method'

**Comment by jennyq** [comment]
@avkovalevs, at the admin backend https://www.example.org/admin/memberships/membershipapp/1/change/,  do you see the `payment_method` field under the `Fields` section? Or is it checked for "Show" and "Required"?

**Comment by avkovalevs** [comment]
@jennyq all of the checkboxes for payment_method field not selected

**Comment by avkovalevs** [comment]
I added your code to views.py and it solved my issue. Thanks!
