### ISSUE TITLE
event.money_collected not working as I'd expect

### ISSUE THREAD

**Issue by JustinLewisSMA** [tendenci/tendenci#784]
Hello,

Given this template: `/theme-editor/editor/?file=templates/events/include/search-result-spots-taken.html`

I'm running into something that doesn't make sense to me. This might just be because I'm not very competent at coding!

These two variables: `{{ event.money_collected }}` and `{{ event.money_total }}` which come from `https://github.com/tendenci/tendenci/blob/master/tendenci/apps/events/models.py` seem to be set to zero if event.money_outstanding is also zero, because of line 1296
`if total_sum and self.money_outstanding:` 

money_outstanding gets set to 0, which causes the if statement to fail, and then on 1299 it returns 0 instead of total_sum. I think a fix might be to just return total_sum, but I'm not sure.

I hope I'm explaining this correctly, or that I even have it right!

**Comment by jennyq** [comment]
@JustinLewisSMA, Great catch! I think the `money_collected` should just return `total_sum - self.money_outstanding`, and `money_outstanding` should return `balance_sum`. Would you like to do a pull request?

**Comment by JustinLewisSMA** [comment]
Sure! I only barely know what I'm doing so bear with me =)

**Comment by JustinLewisSMA** [comment]
Pull Request merged into master:
https://github.com/tendenci/tendenci/pull/785
