### ISSUE TITLE
Google+ Shutdown - Remove Globally 

### ISSUE THREAD

**Issue by lashirley21** [tendenci/tendenci#793]
Hi, 
We no longer use Google+ at Tendenci because Google+ has shutdown. Please remove Google + globally. Thank You.

**Comment by jennyq** [comment]
Resolved https://github.com/tendenci/tendenci/commit/523b0eabc5d4a3e7d8fc8e461c698bae028d6190

**Comment by lashirley21** [comment]
Thank You Miss Jenny!
