### ISSUE TITLE
Missing Canonical URL 

### ISSUE THREAD

**Issue by lashirley21** [tendenci/tendenci#795]
Hey there! :)

I noticed that the Canonical URL on given pages in the **html head** is missing the FQDN. 
example: <link rel="canonical" href="https://www.tendenci.com/about/" />
Wrong canonical url:  /about 
Correct canonical url: https://www.tendenci.com/about 

Most crucial, I noticed that we only have Canonical URL in  'pages module' and Canonical URL does not exist  in the following modules:
1. news
2. articles
3. events 

Thank you. 
Tendenci

**Comment by jennyq** [comment]
Thanks Shirley!  A fix has been pushed out to convert relative to absolute urls for canonial urls  https://github.com/tendenci/tendenci/commit/97175fe13095fc4b0c010eb4172b4e64b4683830

The Canonical URL does exist in the news, articles and events.
https://github.com/tendenci/tendenci/blob/master/tendenci/themes/t7-base/templates/news/view.html#L13
https://github.com/tendenci/tendenci/blob/master/tendenci/themes/t7-base/templates/articles/view.html#L11
https://github.com/tendenci/tendenci/blob/master/tendenci/themes/t7-base/templates/events/view.html#L14

**Comment by lashirley21** [comment]
Thank You Jenny! You are the best

**Comment by jennyq** [comment]
Resolved. https://github.com/tendenci/tendenci/commit/a0046d24c952d724b8a64606d198128f18db8caa
