### ISSUE TITLE
NestedObjects' object has no attribute 'model_count'

### ISSUE THREAD

**Issue by avkovalevs** [tendenci/tendenci#796]
Hello @jennyq 
The exception happened when I trying to delete the group "Committee1".
Navigation path: Community->Group->Committee1 (Options-Delete).
This group doesn't have any members. 
Could I delete default groups?

Request Method: | GET
-- | --

1.11.20
AttributeError
'NestedObjects' object has no attribute 'model_count'
/srv/mysite/lib/python3.6/site-packages/tendenci/apps/base/utils.py in get_deleted_objects, line 186
/srv/mysite/bin/python3.6
3.6.7
['/var/www/mysite',  '/srv/mysite/bin',  '/srv/mysite/lib/python36.zip',  '/srv/mysite/lib/python3.6',  '/srv/mysite/lib/python3.6/lib-dynload',  '/usr/lib/python3.6',  '/srv/mysite/lib/python3.6/site-packages']
Fri, 19 Jul 2019 08:40:07 -0500

**Comment by jennyq** [comment]
@avkovalevs, thanks for reporting the issue! We'll look into it.
