### ISSUE TITLE
Membership application

### ISSUE THREAD

**Issue by avkovalevs** [tendenci/tendenci#798]
@jennyq at https://github.com/tendenci/tendenci/issues/797 we have an error with Sex filed.
Currently, I need additional consultation.
1. Can we change a basic membership form or it is a default template?
2. We are testing 2 additional membership forms, one with Masculin/Feminin and other with M/F.
I saw in database values stored as 'male'/'female'. After you change in models.py these values still be the same? Do I understand correctly that at the custom membership form fields choice between Masculin and Feminin will add value to the database as male/female?
3. When we rename fields in custom membership forms (on fr-names) I see that new fields added to admin/memberships/membershipappfield/
Is it normal? Because we see duplicate values last_name for example.
![Screenshot_2019-07-26 Select Field to change French Alumni North America Tendenci®](https://user-images.githubusercontent.com/22083701/61950864-e6595180-afb7-11e9-827e-5b7be4dc4030.png)

**Comment by jennyq** [comment]
1. Of course, you can change it.
2. That is correct, the update(workaround) only  allows you to display differently.
3. At the top right corner, there is Filter dropdown, click and select an application, you'll have all fields that belong to that application.

**Comment by avkovalevs** [comment]
Ok, thanks.
Which cases admin will get notifications?  How to emulate notifications?

**Comment by jennyq** [comment]
Admin will get notified when a new member is joined or renewed. You can test it as user not superuser.

**Comment by avkovalevs** [comment]
We have admin e-mail like info@somedomain.com and we emulated user registration.
The user gets a 2-time email notification: 1 - with an activation link, 2 when he becomes a member. 
But admin not received any email notifications about a new member. 
Admin email mentioned in global settings field: ALL admin notice recipients
Where I can see which notifications enabled? How can I check admin email?

**Comment by jennyq** [comment]
Hi @avkovalevs, Besides the "ALL admin notice recipients", there is another setting called "Membership admin notice recipients" at  https://www.yoursite.com/settings/module/memberships/#id_membershiprecipients. Those two settings allow you to specify the recipients of admin notifications for memberships. 

Also, please check if you have this entry in your database. The entry should be there if your site is set up properly.

    select *
    from notifications_noticetype
    where label='membership_joined_to_admin';

**Comment by avkovalevs** [comment]
tendenci=# select *
tendenci-# from notifications_noticetype
tendenci-# where label='membership_joined_to_admin';
 id |           label            |           display           |         description         | default 
----+----------------------------+-----------------------------+-----------------------------+---------
 28 | membership_joined_to_admin | Membership Entry Submission | Membership Entry Submission |       2
(1 row)

**Comment by avkovalevs** [comment]
@jennyq Thank you a lot!

**Comment by jennyq** [comment]
You are welcome. Did the admin email work?

**Comment by avkovalevs** [comment]
Yes

**Comment by jennyq** [comment]
Great!
