### ISSUE TITLE
PayPay integration

### ISSUE THREAD

**Issue by milanmaximo** [tendenci/tendenci#799]
Hello,

I've tried many options to start with PayPal membership and I just follow instructions, but no luck with payments.

All the time I got this "error" link of page https://www.paypal.com/webapps/shoppingcart/error?flowlogging_id=4c190afbf27d2&code=NO_BUSINESS

Does anyone know how to solve this issues with PayPal integration? I can't use stripe, I am not us citizen so from that reason I need PayPal.

Also is it there any other payment options can be integrated on Tendenci and which one that could be? 

Thanks in advance

**Comment by jennyq** [comment]
Hi @milanmaximo,

Looks like your account is not set up properly. Have you checked out this guide? It is described in the section **5. Setup for PayPal Payment Standard**. https://www.tendenci.com/help-files/setting-up-online-payment-processor-and-merchant-provider-on-a-tendenci-site/

All other payment options are listed in there.

**Comment by milanmaximo** [comment]
Hi @jennyq

Thank you so much for your help and sorry for delay.
You were right, I missed some configuration options bacause I want it to try with paypal sendbox options. But now is working with my paypal.

Maybe is not a time, or should I open new ticket or issues, but I am wondering how to create newsletter options?
Is it related to emails because I am still in testing of Tendenci, and I got this message wile I try to send newsletter "
"Email relay is not configured properly. Newsletter cannot be sent."
Thank you so much for help!

**Comment by milanmaximo** [comment]
> No problem. For newsletters module, it has separate settings than regular emails. Make sure you have these four settings set up in your conf/settings.py.
> 
> ```
> NEWSLETTER_EMAIL_HOST = '<email-host>'
> NEWSLETTER_EMAIL_PORT = <email-port>
> NEWSLETTER_EMAIL_HOST_USER = '<email-host-user>'
> NEWSLETTER_EMAIL_HOST_PASSWORD = '<email-host-password>'
> ```
> 
> For more, you can check out the **Post Installation Checklist**. https://tendenci.readthedocs.io/en/latest/testing/post-install-checklist.html

Thank you so much @jennyq for your help and sorry for delay but here is a lot of work :)
Testing is done and everything looks fine.

I just have one more question if you don't mind.

Regarding membership option. 
There is a link in "Fill out our membership application to become a member!" and when I get a page there is a lot of fields for fill in.. name, surname, school, graduate etc ...

Is it there any option  to delete some of the fileds or any option to create new Membership page with just of few new fields such as name, surname, password , dob ... let's say 6 or 7 fields ?

Is it there any link or tutorial how to link this new page directly from main menu (Membership)?
If this is too much question I hope you will forgive me but anyhow will send you the bouquet of flowers for this kind of help :)

**Comment by jennyq** [comment]
> Is it there any option to delete some of the fileds or any option to create new Membership page with just of few new fields such as name, surname, password , dob ... let's say 6 or 7 fields ?

To delete fields, log in as a superuser, then click Memberships -> Admin Backend from top menu. Click the membership application you want to edit. Under the Fields section, there are 3 checkboxes for each field, uncheck the **Show** checkbox (the first checkbox) for the fields you don't want them to show. https://youdomain/admin/memberships/membershipapp/1/change/.

To edit fields, go to Memberships Application -> Fields. Select your membership application in the Filter dropdown. You can drag-drop the fields to change the order. In addition, clicking on a field will bring you to a page where you can further customize the field (to change label, field type, etc..).
https://youdomain/admin/memberships/membershipappfield/?membership_app_id=1

Certainly, you can add a new membership application with the button "Add Membership Application". https://youdomain/admin/memberships/membershipapp/

> Is it there any link or tutorial how to link this new page directly from main menu (Membership)?
If you're logged in as a superuser, you'll see the "Edit Nav" link under the main menu, you can add or change links from there. 

Hope it helps. You may check out some help files regarding memberships https://www.tendenci.com/help-files/topic/33/

**Comment by milanmaximo** [comment]
> > Is it there any option to delete some of the fileds or any option to create new Membership page with just of few new fields such as name, surname, password , dob ... let's say 6 or 7 fields ?
> 
> To delete fields, log in as a superuser, then click Memberships -> Admin Backend from top menu. Click the membership application you want to edit. Under the Fields section, there are 3 checkboxes for each field, uncheck the **Show** checkbox (the first checkbox) for the fields you don't want them to show. https://youdomain/admin/memberships/membershipapp/1/change/.
> 
> To edit fields, go to Memberships Application -> Fields. Select your membership application in the Filter dropdown. You can drag-drop the fields to change the order. In addition, clicking on a field will bring you to a page where you can further customize the field (to change label, field type, etc..).
> https://youdomain/admin/memberships/membershipappfield/?membership_app_id=1
> 
> Certainly, you can add a new membership application with the button "Add Membership Application". https://youdomain/admin/memberships/membershipapp/
> 
> > Is it there any link or tutorial how to link this new page directly from main menu (Membership)?
> > If you're logged in as a superuser, you'll see the "Edit Nav" link under the main menu, you can add or change links from there.
> 
> Hope it helps. You may check out some help files regarding memberships https://www.tendenci.com/help-files/topic/33/

Well @jennyq you are my hero !

Thank you so much for your support and you make everything on simple way!

**Comment by jennyq** [comment]
Great! You're welcome.
