### ISSUE TITLE
Django 1.11 LTS end-of-life April 2020, migration to 2.2 LTS?

### ISSUE THREAD

**Issue by claudobahn** [tendenci/tendenci#803]
See https://www.djangoproject.com/download/#supported-versions

Looks like EOL is approaching rapidly, is there a plan to move to Django 2.2?

**Comment by jennyq** [comment]
Yes we do. We'll start to work on that very soon.

**Comment by jennyq** [comment]
Resolved in T12. The upgrade guide is here: https://tendenci.readthedocs.io/en/latest/upgrade/upgrade-to-tendenci12.html
