### ISSUE TITLE
How best to configuration manage conf/settings.py?

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#804]
Hi,
I'm  back to looking at managing tendenci 11 configuration via configuration management (after a couple of years off) and because local_settings.py has been deprecated it seems a measurably different problem to T7.

I see two main options:
* settings.py: search/replace values in the supplied file to change and add missing values
* settings_local.py: include a separate file in to settings.py which is then configuration managed; put overrides in there (similar to local_settings.py in T7)
* settings.py: regenerate the file from scratch with preferred configuration.

Is there a route you would recommend taking? I am currently doing the former but I don't like it and i'm considering which of the other two to use.

**Comment by PaulSD** [comment]
In T7, there were three relevant settings files:
1) https://github.com/tendenci/tendenci/blob/v7.5.1/tendenci/settings.py set most of the defaults
2) https://github.com/tendenci/tendenci-project-template/blob/tendenci7/conf/settings.py set some additional defaults
3) https://github.com/tendenci/tendenci-project-template/blob/tendenci7/conf/local_settings.py was used to override the two above files with user-specific settings

The above scheme didn't align with what most other Django projects do, the split/redundant default configuration was confusing, and the above scheme made it harder than necessary to upgrade between major Tendenci versions ... So, T11 moved all of the defaults to https://github.com/tendenci/tendenci/blob/master/tendenci/settings.py, adjusted the defaults to minimize the number of user-specific settings that are needed for most installations, dropped local_settings.py, and moved all of the user-specific settings to https://github.com/tendenci/tendenci-project-template/blob/master/conf/settings.py.  In theory, the new tendenci-project-template settings.py file should need little or no changes during future major Tendenci version upgrades, so you can config manage this file in its entirety, and not worry about rebuilding your config using a new upstream version of this file after future upgrades.

Detailed instructions for migrating from the old config scheme to the new scheme are in Step 4 of https://github.com/tendenci/tendenci/blob/master/docs/source/upgrade/upgrade-to-tendenci11.txt

**Comment by goetzk** [comment]
Hi Paul,
Completely managing the file is my preference over adding another file so I'm glad to hear its doable.

thanks,
Karl.
