### ISSUE TITLE
people-search page

### ISSUE THREAD

**Issue by avkovalevs** [tendenci/tendenci#805]
@jennyq hi!
1. How to reduce the list of available choices for the field "Search by"?  
2. When I search by phone and using some digits for filtering I don't understand how to use masking symbols like '*' - for any symbols and '?' - for one symbol. How to search by phone city code? Do I need to specify "()" ?
Thanks.

**Comment by jennyq** [comment]
Hi @avkovalevs,

1) The list of choices for "Search by" field is not customizable. 
2) The phone field is a char field. It doesn't work with wildcards like "*" or "?". You can select "Starts With" or "Contains" to filter certain area codes.

**Comment by avkovalevs** [comment]
Thanks!
