### ISSUE TITLE
"view on site" for Change Membership Application (Admin Backend) return "502 Bad Gateway"

### ISSUE THREAD

**Issue by mfmjw** [tendenci/tendenci#806]
Hi,

Previously it was working fine until I did the following:
1. Delete records from memberships_membershipset
2. Edit ExecStart=/srv/mysite/bin/gunicorn in mysite.service file (Previously it was pointing to the old path /srv/tendenci/venv/bin/gunicorn because I had copied the .service from 7.x. My current version is 11.0)
3. Reboot server

Debug.log
![image](https://user-images.githubusercontent.com/25378218/67099886-46474900-f1f1-11e9-9ea4-1958448f0de3.png)

Appreciate if you could advise how to rectify the issue.

Thank you.

**Comment by jennyq** [comment]
Hi @mfmjw,

Those in the Debug.log are just warnings. Can you set `DEBUG = True` in the conf/settings.py, and paste the traceback for the error?

**Comment by mfmjw** [comment]
As requested.
[image: image.png]
[image: image.png]

**Comment by jennyq** [comment]
You pasted message didn't go through. -  All I can see is these two lines
[image: image.png]
[image: image.png]

**Comment by jennyq** [comment]
Closing it due to lack of response. Feel free to open a new issue if needed.
