### ISSUE TITLE
Support for multiple mail backends

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#807]
Hi,
I've been asked if Tendenci supports multiple mail backends (which from my reading of the code it doesn't) but I thought I'd raise it here as a suggestion in case you could provide an estimate for how long an implementation would take and how (in)sane you find my implementation concept below.

At a minimum I imagine two levels, system and interactive at one level and bulk mail out at another.
- System mail is things like reports or invoices being emailed
- Interactive includes password reset mail
- Bulk mail is anything from 'Content' apps - new forum posts, new pages, news articles and so on.

However as I thought about possible implementation paths I realised that since a new mail proxy class (of some kind) would be required it might be worth passing through the calling component too; enabling per site handling of mail generated by each component.

Implementation thoughts:
A system setting to control mail handling class which can be overriden to change behaviour
```
TENDENCI_MAIL_PROXY='tendnci.utils.MailSendingProxy'
```

A or method to handle the mail with an interface along these lines, calling_application being the tendenci app making the call and priority being its prefered handling level (optional)
```
class MailSendingProxy()
   def init(calling_application, priority=None, **kwargs)
     call usual code
```

In an effort to minimise code churn I'm thinking kwargs would include all the 'stuff' currently passed to the django mail call(s) though if doing the work perhaps its best to do it up front...?

Thoughts?

**Comment by PaulSD** [comment]
What is the actual goal here?

Under the hood, Tendenci uses django.core.mail, and the mail backends plug into django.core.mail.  So, the lack of ability to configure multiple backends is a limitation of django.core.mail, and fixing it the way you are suggesting would imply ripping django.core.mail out of Tendenci and replacing it with something else.  With more information about the actual goal here, I suspect we could find a much easier solution...

For example, I currently use two different outbound email paths for emails to admins and emails to non-admin users.  To do this, I have Tendenci send all of the mail to a postfix server (using a single email backend), then have postfix split the mail using transport_maps based on the destination email address.  I can give you an example config if necessary.

Alternatively, you might be able to implement a custom email backend that splits the emails to multiple other backends based on some conditions (maybe using some sort of introspection to identify the caller without explicitly passing the caller through).  https://github.com/PaulSD/django_log_email shows how to create a custom email backend that calls another email backend, so you could use that as a starting point.

**Comment by jennyq** [comment]
@PaulSD has explained pretty well. Thank you! 
I just wanted to point out that Tendenci does allow you to specify up to two email backends - one for general emails (system generated); the other for newsletters (bulk mail). It also has Django-SES integrated. [https://github.com/django-ses/django-ses](https://github.com/django-ses/django-ses). That is pretty much sufficient from our experience.

**Comment by goetzk** [comment]
On 20/10/19 12:45, Paul Donohue wrote:
> What is the actual goal here?

Hi Paul,
I thought I included it then realised I meant to go back and hadn't 
updated my post.

The tl;dr is to use a high(er) reliability service for sending important 
mail and an alternative for bulk mail.

> Under the hood, Tendenci uses django.core.mail, and the mail backends 
> plug into django.core.mail. So, the lack of ability to configure 
> multiple backends is a limitation of django.core.mail, and fixing it the 
> way you are suggesting would imply ripping django.core.mail out of 
> Tendenci and replacing it with something else. With more information 
> about the actual goal here, I suspect we could find a much easier 
> solution...

I was thinking more of putting in a padding layer in between but not 
fully understanding django's mail implementation I may have actually 
proposed something far more systemic without intending to.

[...]
> Alternatively, you might be able to implement a custom email backend 
> that splits the emails to multiple other backends based on some 
> conditions (maybe using some sort of introspection to identify the 
> caller without explicitly passing the caller through). 
> https://github.com/PaulSD/django_log_email shows how to create a custom 
> email backend that calls another email backend, so you could use that as 
> a starting point.
> 

I hadn't considered introspecting up the tree like that - I'll keep it 
as an option but hopefully won't need to use it.

thanks,
kk

**Comment by goetzk** [comment]
> @PaulSD has explained pretty well. Thank you!
> I just wanted to point out that Tendenci does allow you to specify up to two email backends - one for general emails (system generated); the other for newsletters (bulk mail). It also has Django-SES integrated. https://github.com/django-ses/django-ses. That is pretty much sufficient from our experience.

Hi Jenny,
Thats pretty much what I need to solve here; is the separation documented somewhere? I haven't found anything to describe it.

Karl.

**Comment by eschipul** [comment]
@goetzk - two settings and some DNS entries are needed to configure email sending from a Tendenci AMS.

First is the notification email (reset pw etc....)
https://github.com/tendenci/tendenci/blob/master/tendenci/settings.py#L283

Newsletter configuration is here (any SMTP email server - outbound only)
https://github.com/tendenci/tendenci/blob/master/tendenci/settings.py#L541

There is some documentation here as well on sending emails with Tendenci:
https://tendenci.readthedocs.io/en/latest/testing/post-install-checklist.html

To get email actually DELIVERED you will also need to check your DNS for whichever email providers you are using. We use AWS SES for notices, and any SMTP relay provider like mailgun or mailchimp will work for newsletters. There is a long help file about SPF configuration here:
https://www.tendenci.com/help-files/tendenci-forms-email-notifications/

To your point, YES, email still needs further documentation, I'm just trying to help with the immediate challenges. I'll leave it to @jennyq to confirm if I answered it correctly or not as the codebase is changing rapidly.

Ed

What would be awesome is MFA and SMS reminders .... but that is a different ticket. ;)

**Comment by jennyq** [comment]
@eschipul, those are great info. Thanks!

@goetzk, I've just added the settings for newsletters to `conf/settings.py` [https://github.com/tendenci/tendenci-project-template/blob/master/conf/settings.py#L147](https://github.com/tendenci/tendenci-project-template/blob/master/conf/settings.py#L147). The settings for general emails are in there as well [https://github.com/tendenci/tendenci-project-template/blob/master/conf/settings.py#L134](https://github.com/tendenci/tendenci-project-template/blob/master/conf/settings.py#L134). If you have decided what email backends you'd like to use, you can just  uncomment the corresponding blocks and set up (credentials) accordingly.

**Comment by goetzk** [comment]
@jennyq great work, thanks!
I will leave this open a little longer in case I find the time to write some documentation but for now the examples above have set us on the right path.

@eschipul i would have thought you of all people would know to avoid MFA via SMS :)
I've previously done an MFA implementation on Tendenci,  I'm sure forward porting to T11 will be a tough couple of weeks.

**Comment by goetzk** [comment]
Hi,
I haven't got as far as properly testing this out yet but thought I'd share my results. I've wound up using CeleryEmailBackend for both backends but still plan to split out the main email backend to something else without built in delay.

`django-celery-email==1.1.5` (mid 2016) last version which supports celery3; required for tendenci (https://github.com/pmclanahan/django-celery-email/tree/1.1.5)
`pip install django-celery-email==1.1.5`

Arbitrary example: I want <500 emails sent per hour via bulk mail to ensure headroom for sending dynamic notifications against a sending limit of 500/hour 

# Use django-celery-email for batching bulk mail for delivery
INSTALLED_APPS += ("djcelery_email",)

EMAIL_BACKEND = 'djcelery_email.backends.CeleryEmailBackend'
NEWSLETTER_EMAIL_BACKEND = 'djcelery_email.backends.CeleryEmailBackend'
CELERY_EMAIL_BACKEND = 'django_log_email.backends.EmailBackend'
# Send 1 batch of 8 messages every minute. Thats 480 per hour leaving 20 emails per
# hour after this
CELERY_EMAIL_CHUNK_SIZE = 8
CELERY_EMAIL_TASK_CONFIG = {
    'rate_limit' : '1/m',  
}

still todo: 
- example of how to use django shell to test both mail systems are working
- document properly (sorry, I can't commit to this atm)
