### ISSUE TITLE
How to upload groups using Import?

### ISSUE THREAD

**Issue by avkovalevs** [tendenci/tendenci#813]
Hi @jennyq!
1. Could you please advise me on how to upload members with groups using Import membership?
We have 10 groups already exist in Tendenci. At the first stage, we want to add one of them to each member (1:1). I know we can add two and more groups for each member via forms. But we have 2k+ of members. I tried to upload groups via template (column 'group' or column 'Liaison')  but without any success.
2. We use 11.2.8 version of Tendenci and have plans to move on 11.4.2. Is it enough to use a typical minor upgrade method as mentioned in docs or we need to do some special actions?

**Comment by jennyq** [comment]
Hi @avkovalevs, 1) I'd suggest to upgrade to the latest version (currently 11.4.2) then try again. 2) Yes, a minor upgrade is enough. As a good practice, always back up your site before running upgrade.

**Comment by avkovalevs** [comment]
@jennyq  Thank you! 
Today I've checked the export/import operations and found one strange thing. Our CSV-file size, we used for import,  ~ 1Mb,  when I export all data from Tendenci the final size ~556Mb. The database size equal to 115M. Is it normal? Why we have so huge differences?

**Comment by jennyq** [comment]
So, the data exported is larger than the size of database? How did you export all data, and in what format?

**Comment by avkovalevs** [comment]
Memberships-application->Export
Then I choose:
- Export Active Membership
- Export Main Fields
- Former student (our group with all members)
Then I see Membership CSV Export - Status - Download.
When download starting it shows me 556Mb.

The database size:
tendenci=# \l+ tendenci
                                            List of databases
   Name   | Owner | Encoding | Collate |  Ctype  | Access privileges |  Size  | Tablespace | Description 
----------+-------+----------+---------+---------+-------------------+--------+------------+-------------
 tendenci | fana  | UTF8     | C.UTF-8 | C.UTF-8 | =Tc/fana         +| 115 MB | pg_default | 
          |       |          |         |         | fana=CTc/fana     |        |            |

**Comment by jennyq** [comment]
Strange indeed. I did some tests but couldn't replicate it.

**Comment by eschipul** [comment]
@avkovalevs Possibly serialized images in the files table? For security reasons, depending on how a file is uploaded, files may be in media or may be serialized in the forms database table.

I would definitely NOT ignore it. 

My recommendation would be to go to your /explorer/  URL (or in psql directly) and list files ordered by id DESC for recent files that possibly a spammer uploaded. On our site I got so tired of spammers I have /forums/ excluded in robots.txt. You can also disable that module in site-settings.

Also make sure you have google recaptcha enabled.

There is a good help file on django-data-exporter here:
https://www.tendenci.com/help-files/how-use-django-sql-explorer-tendenci/

Please give us an update when you figure it out?

**Comment by avkovalevs** [comment]
@eschipul 
I run this SQL 'select * from files_file order by id DESC;' and found only 4 records for the 2019 year. Others files from the box.

**Comment by avkovalevs** [comment]
@eschipul @jennyq 
After the upgrade to 11.4.3 and 'vacuum full analyze' the database size increase to 103Mb and Export Active Membership reduced to 576Kb.

**Comment by avkovalevs** [comment]
@jennyq How can I do a mass upload of Groups for members?
Currently export/import templates not contain this column.

**Comment by jennyq** [comment]
@avkovalevs, Glad you resolved the size issue. The AUTOVACUUM deamon should be on by default which will run VACUUM and ANALYZE at regular intervals. Not sure why you had to run manually.

Currently, users can be added to only one group on each import. To add them to multiple groups, you can import multiple times. No plans yet.

**Comment by avkovalevs** [comment]
Ok. What is the column in the template I need to use for the group?

**Comment by jennyq** [comment]
No column needed. On users import https://yoursite.com/profiles/import/, there is a field "Add Users to Group" where you can select a group from the dropdown.

**Comment by avkovalevs** [comment]
Thanks, it helped.
