### ISSUE TITLE
[Django] ERROR (EXTERNAL IP) Invalid HTTP_HOST

### ISSUE THREAD

**Issue by avkovalevs** [tendenci/tendenci#816]
Hello @jennyq!
Time by time I get messages on email from Tendenci site like these:
[Django] ERROR (EXTERNAL IP) Invalid HTTP_HOST header: 'some_ip'  You may need to add 'some_ip' to ALLOWED_HOSTS.
Is this a spam? 
How to react to them?
Thanks!

**Comment by eschipul** [comment]
@avkovalevs it is most likely attacks, but we need more data to say definitively. Some first steps:

Check if both error and access logs are turned on. If not, enable both with log rotation. 
/etc/nginx/sites-enabled/(site-name)

Post relevant errors from logs
/var/log/nginx/(site-name)

Definitely make sure you have captcha turned on. In production we enable recaptcha from google, v2 (check read the docs as this changes over time.)

This really a server configuration question. If the DB is on the same server then Postgres should only be listening for “localhost” or “127.0.0.1”. If you’ve got it in containers it would depend on if your connection is via sockets or ip:port.

Can you provide more details on your configuration? 
Logs
Environment
Firewall config (sudo ufw status numbered)
And turn on debugmode in settings.py

But as you said, it does sound like spammers trying to hit your db directly. I’d take a serious look at your server security configuration and logs.

**Comment by eschipul** [comment]
OSSEC-wazuh agent is also helpful if you configure it to monitor your logs. (“grep” is your friend.)

**Comment by avkovalevs** [comment]
@eschipul  Thank you for help.
----------------------------------E-mail mesage----------
Invalid HTTP_HOST header: '192.168.237.133'. You may need to add '192.168.237.133' to ALLOWED_HOSTS.

Report at /MNEGES
Invalid HTTP_HOST header: '192.168.237.133'. You may need to add '192.168.237.133' to ALLOWED_HOSTS.

Request Method: POST
Request URL: https://192.168.237.133/MNEGES
Django Version: 1.11.26
Python Executable: /srv/mysite/bin/python3.6
Python Version: 3.6.7
Python Path: ['/var/www/mysite', '/srv/mysite/bin', '/srv/mysite/lib/python36.zip', '/srv/mysite/lib/python3.6', '/srv/mysite/lib/python3.6/lib-dynload', '/usr/lib/python3.6', '/srv/mysite/lib/python3.6/site-packages']
Server time: Sat, 14 Dec 2019 19:59:26 -0600
Installed Applications:
['django_admin_bootstrapped',
 'django.contrib.admin',
------------------------------
------access.log.2---------------
/var/log/nginx$ sudo cat access.log.2 
128.14.209.178 - - [13/Dec/2019:12:59:00 +0000] "GET /.well-known/security.txt HTTP/1.1" 404 9630 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
128.14.134.134 - - [13/Dec/2019:13:21:09 +0000] "GET / HTTP/1.1" 200 11644 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
66.240.205.34 - - [13/Dec/2019:14:27:05 +0000] "Gh0st\xAD\x00\x00\x00\xE0\x00\x00\x00x\x9CKS``\x98\xC3\xC0\xC0\xC0\x06\xC4\x8C@\xBCQ\x96\x81\x81\x09H\x07\xA7\x16\x95e&\xA7*\x04$&g+\x182\x94\xF6\xB000\xAC\xA8rc\x00\x01\x11\xA0\x82\x1F\x5C`&\x83\xC7K7\x86\x19\xE5n\x0C9\x95n\x0C;\x84\x0F3\xAC\xE8sch\xA8^\xCF4'J\x97\xA9\x82\xE30\xC3\x91h]&\x90\xF8\xCE\x97S\xCBA4L?2=\xE1\xC4\x92\x86\x0B@\xF5`\x0CT\x1F\xAE\xAF]" 400 182 "-" "-"
5.188.210.101 - - [13/Dec/2019:19:39:10 +0000] "\x05\x01\x00" 400 182 "-" "-"
5.188.210.101 - - [13/Dec/2019:19:40:52 +0000] "\x04\x01\x00P\x05\xBC\xD2e\x00" 400 182 "-" "-"
5.188.210.101 - - [13/Dec/2019:19:41:24 +0000] "GET http://5.188.210.101/echo.php HTTP/1.1" 400 682 "https://www.google.com/" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
185.220.100.252 - - [13/Dec/2019:20:32:16 +0000] "GET / HTTP/1.1" 200 51176 "https://68.183.167.67:443" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"
165.22.73.94 - - [13/Dec/2019:22:12:45 +0000] "\x00\x00\x00 A\x00A\x00A\x00A\x00A\x00A\x00A\x00A\x00A\x00A\x00A\x00A\x00A\x00A\x00A\x00A\x00\xBE\xAF\xFE\xEA" 400 182 "-" "-"
167.172.98.133 - - [14/Dec/2019:00:46:33 +0000] "POST /tbl_add.php?action=%22BaseInfo%22&u=%22NTA0ODUzNTI2ODU2Njc1NDU3Njk1NTY2NjU1MTQ5NzA=%22 HTTP/1.1" 400 182 "-" "-"
196.52.43.99 - - [14/Dec/2019:01:22:10 +0000] "GET / HTTP/1.1" 200 51176 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3602.2 Safari/537.36"
184.105.247.195 - - [14/Dec/2019:01:34:41 +0000] "GET / HTTP/1.1" 200 51176 "-" "-"
188.166.55.116 - - [14/Dec/2019:03:02:00 +0000] "POST /contact/6EF0B8049D8397444E0D1AA9U2DQG/markup HTTP/1.1" 400 81743 "-" "Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Thunderbird/38.1.0 Lightning/4.0.2"
149.56.129.207 - - [14/Dec/2019:03:28:37 +0000] "GET / HTTP/1.1" 400 682 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
167.172.191.63 - - [14/Dec/2019:04:16:51 +0000] "#\xB08DB\xF0\xD1\x98\x1E\x01\xE4\xE0\xDC\xA4=\xB1" 400 182 "-" "-"
23.95.84.74 - - [14/Dec/2019:04:31:27 +0000] "GET / HTTP/1.1" 200 51176 "-" "-"
45.56.78.64 - - [14/Dec/2019:04:54:33 +0000] "GET / HTTP/1.1" 400 182 "-" "-"
164.52.24.162 - - [14/Dec/2019:05:30:14 +0000] "GET / HTTP/1.1" 400 280 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0"
23.95.84.74 - - [14/Dec/2019:05:55:31 +0000] "GET / HTTP/1.1" 200 51176 "-" "-"

**Comment by avkovalevs** [comment]
/var/log/nginx$ sudo cat error.log.2 
2019/12/14 01:36:57 [crit] 2885#2885: *675 SSL_do_handshake() failed (SSL: error:1420918C:SSL routines:tls_early_post_process_client_hello:version too low) while SSL handshaking, client: 184.105.247.195, server: 0.0.0.0:443

**Comment by avkovalevs** [comment]
External opened ports: 443, 22

**Comment by jennyq** [comment]
@avkovalevs, looks like someone was trying to access your site via IP. You can block it by adding a default server block to your nginx configuration like this:

    server {
        listen      80 default_server;
        server_name "";
        return      444;
}

**Comment by avkovalevs** [comment]
@jennyq I added this server block without any changes and after restart Nginx not started.
Do I need to change the server_name parameter?

**Comment by jennyq** [comment]
@avkovalevs, yes, you'll need to add your server IP to the server_name, for example:

    server_name 192.168.237.133;

**Comment by avkovalevs** [comment]
@jennyq thanks!
Recently I got a similar error like this:
Internal Server Error: /ajax

RuntimeError at /ajax
You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 68.183.167.67/ajax/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.

**Comment by jennyq** [comment]
Hi @avkovalevs, you're welcome!
I don't suggest to set APPEND_SLASH=False. It's better to keep it the default value. Why don't you just change the post URL to match with the URL specified in the url patterns?

**Comment by avkovalevs** [comment]
@jennyq  could you explain to me your last phrase? What and where I need to change?
I suppose that both errors in the post (ALLOWED_HOSTS and APPEND_SLASH) has a similar security issue with URLs.

**Comment by jennyq** [comment]
@avkovalevs, 

URLs appended with and without a trailing slash can be treated differently by Google. From SEO's perspective, supporting both would cause duplicate content issue. Tendenci does not support both of them. For example, if you set  APPEND_SLASH=False, accessing your pages without a trailing slash , for example, https://www.example.com/mypage, would result a 404. When APPEND_SLASH is set to True (by default), django does a redirect (through CommonMiddleware) and append a slash if needed. That's why it's better to leave the default value for APPEND_SLASH.

To change those blocks (they are on your home page, right?), you can update your homepage.html template. https://www.example.com/theme-editor/editor/

**Comment by avkovalevs** [comment]
Thanks
