### ISSUE TITLE
Local Dev Environment

### ISSUE THREAD

**Issue by AustinPowered** [tendenci/tendenci#825]
I have a VM running Ubuntu 18.04 with Tendenci Installed and it's running fine. https://utendenci.cbyra.org

I volunteer for a non-profit organization that supports yacht racing on the Chesapeake Bay. Tendenci seems to be an excellent fit with more features than we will ever need. But we will need to make some code changes to add some database fields. Since we are dealing with racing sailboats, we need to add fields so users can enter the name and type of the boats.

Looking at the code, it seems the way education is being added to the database could be adapted to add fields like boat name, boat type, and boat class to a member profile.

I followed the instructions provided in the documentation for [Development Setup](https://tendenci.readthedocs.io/en/latest/installation/installation.html#development-setup) and now I have a git repo on my laptop and can push code changes to the "live site" VM. This process works but I would prefer to run django on my laptop and locally debug the code.

Does anyone have some guidance for configuring a development environment? I'm using pipenv to configure a Python 3.7 virtual environment on a Lenovo T430 with 16GB of RAM running Fedora 30.

Since I'm new to Django, I have successfully been through several online tutorials running Django with VS Code on my Fedora laptop. But I haven't been able to get Tendenci to run on my laptop without crashing.

Perhaps the attachment with console output will shed some light.

Thanks,
AustinPowered
[core-dump.txt](https://github.com/tendenci/tendenci/files/4043461/core-dump.txt)

**Comment by AdamBark** [comment]
That's a strange one. Can you post the actual core dump?

**Comment by AustinPowered** [comment]
With apologies for not replying sooner. After watching the app_log tail to a terminal window, it looked like the volume of the messages could be a factor. Once I set app_log level to INFO the problem has not returned.

Since the goal was being able to use VSCode on my laptop as an IDE, I don't need debug level logging.

Thanks for your reply and thanks to Ed Schipul for calling me directly to discuss this issue.

AustinPowered
