### ISSUE TITLE
Youtube embedding in pages is partially broken

### ISSUE THREAD

**Issue by AdamBark** [tendenci/tendenci#826]
Following the advice at https://www.tendenci.com/help-files/how-do-i-embed-video-my-site/ doesn't really work. A lot of the html code is wiped and it just gives a basic embed which doesn't allow full screen.

**Comment by ediaz1** [comment]
Hi Adam! Thank you for bringing this to our attention! The "allowfullscreen" attribute has been added.

**Comment by AdamBark** [comment]
Thanks!
