### ISSUE TITLE
Template tags question

### ISSUE THREAD

**Issue by JustinLewisSMA** [tendenci/tendenci#831]
Hi! I don't actually know what I'm doing, but I know what I want...

I'd like to pull a list of all of my renewed Corporate Members and display them on a page.

I was thinking something like:
`
   {% load i18n %}
   {% load base_filters %}
   {% load base_tags %}
   {% load theme_tags %}
   {% load corporate_memberships_tags %}
   {% theme_extends "base.html" %}
   
   {% block title %}{{ block.super }} | {{ SITE_GLOBAL_SITEPRIMARYKEYWORDS }}{% endblock %}
   {% block meta_description %}{{ block.super }}{% endblock %}
   {% block meta_keywords %}{{ block.super }}, {{ SITE_GLOBAL_SITESECONDARYKEYWORDS }}{% endblock %}
   
   {% block extra_head %}
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   
   <link rel="icon" href="{{ THEME_URL }}media/img/icons/favicon.ico">
   <link rel="apple-touch-icon" sizes="60x60" href="{{ THEME_URL }}media/img/icons/apple-touch-icon-60x60.png">
   <link rel="apple-touch-icon" sizes="76x76" href="{{ THEME_URL }}media/img/icons/apple-touch-icon-76x76.png">
   <link rel="apple-touch-icon" sizes="144x144" href="{{ THEME_URL }}media/img/icons/apple-touch-icon-144x144.png">
   <link rel="icon" type="image/png" href="{{ THEME_URL }}media/img/icons/android-chrome-144x144.png" sizes="144x144">
   <link rel="icon" type="image/png" href="{{ THEME_URL }}media/img/icons/android-chrome-96x96.png" sizes="96x96">
   <link rel="icon" type="image/png" href="{{ THEME_URL }}media/img/icons/favicon-32x32.png" sizes="32x32">
   <link rel="icon" type="image/png" href="{{ THEME_URL }}media/img/icons/favicon-96x96.png" sizes="96x96">
   <link rel="icon" type="image/png" href="{{ THEME_URL }}media/img/icons/favicon-16x16.png" sizes="16x16">
   <meta name="msapplication-TileColor" content="#ffc40d">
   <meta name="msapplication-wide310x150logo" content="{{ THEME_URL }}media/img/icons/mstile-310x150.png" />
   <meta name="msapplication-square150x150logo" content="{{ THEME_URL }}media/img/icons/mstile-150x150.png" />
   <meta name="msapplication-square310x310logo" content="{{ THEME_URL }}media/img/icons/mstile-310x310.png" />
   <meta name="theme-color" content="#ffffff">
   
   <link rel="stylesheet" href="{{ THEME_URL }}media/css/animate.min.css" type="text/css">
   <link rel="stylesheet" href="{{ THEME_URL }}media/css/creative.css" type="text/css">
   <link rel="stylesheet" href="{{ THEME_URL }}media/css/custom.css" type="text/css">
   {% endblock extra_head %}
   
   {% block body_ids %}sub{% endblock body_ids %}
   {% block body_classes %}sub{% endblock body_classes %}
   {% block html_body %}
   
   {% theme_include "header.html" %}
   
        {% if corporate_membership %}

            
        <div class="corporate">
            <ul>
                {% with corporate_membership.corp_profile as corp_profile %}
                <li>
                    <img alt="{{ corporate_member.name }}" src="{{ corporate_member.ud18 }}" /><br>
                    {{ corporate_member.name }}<br>
                    {{ corporate_member.address }}<br>
                    {{ corporate_member.city }} {{ corporate_member.state }} {{ corporate_member.zip }}<br>
                    {% if corporate_member.ud2 %}  <a href="https://www.twitter.com{{ corporate_member.ud2 }}">{{ corporate_member.ud2 }}</a><br> {% endif %}
                    {% if corporate_member.ud3 %}  <a href="https://www.facebook.com{{ corporate_member.ud3 }}">{{ corporate_member.ud3 }}</a><br> {% endif %}
                </li>
                {% endwith %}
            </ul>
        </div>
        {% endif %}
<footer class="{% block footer_classes %}{% endblock %}col-xs-12 col-sm-12 col-md-12 col-lg-12">
    {% block footer %}
    {% spaceless %}{% theme_include "footer.html" %}{% endspaceless %}
    {% endblock %}
    </footer>
    {% endblock %}`

What am I missing, or, how do I make this work?

**Comment by jennyq** [comment]
Hi @JustinLewisSMA,

I've made some correction for your code. You can replace the code block above from ` {% if corporate_membership %} ` to `{% endif %}` with this block of code to see if that works for you:

    <div class="corporate">
        <ul>
        {% list_corporate_memberships as corpmembership_list renewed_only=True order='-renew_dt' %}
        {% for corporate_member in corpmembership_list %}
            {% with corporate_member.corp_profile as corp_profile %}
            <li>
               {% if corp_profile.ud18  %}
                <img alt="{{ corp_profile.name }}" src="{{ corp_profile.ud18 }}" /><br>
                 {% endif %}
                {{ corp_profile.name }}<br>
                {{ corp_profile.address }}<br>
                {{ corp_profile.city }} {{ corp_profile.state }} {{ corp_profile.zip }}<br>
                {% if corp_profile.ud2 %}  <a href="https://www.twitter.com{{ corporate_member.ud2 }}">{{ corp_profile.ud2 }}</a><br> {% endif %}
                {% if corp_profile.ud3 %}  <a href="https://www.facebook.com{{ corporate_member.ud3 }}">{{ corp_profile.ud3 }}</a><br> {% endif %}
            </li>
            {% endwith %}
         {% endfor %}
        </ul>
    </div>


Hope it helps.

**Comment by JustinLewisSMA** [comment]
Is it possible to get a random order out of this?
In here: https://github.com/tendenci/tendenci/blob/master/tendenci/apps/corporate_memberships/templatetags/corporate_memberships_tags.py

I think I see randomize=True might do it, but I can't seem to get that to work.

`{% list_corporate_memberships as corpmembership_list renewed_only=True randomize=True corporate_membership_type=2 %}`

**Comment by jennyq** [comment]
@JustinLewisSMA, change `randomize` to `random`.

**Comment by JustinLewisSMA** [comment]
That throws an error =/

**Comment by jennyq** [comment]
The error has been fixed. https://github.com/tendenci/tendenci/commit/95922a8e22c6e862a4e54dcf379e8a6beae88195

**Comment by JustinLewisSMA** [comment]
You're amazing!
