### ISSUE TITLE
invoices 404

### ISSUE THREAD

**Issue by avkovalevs** [tendenci/tendenci#832]
Hello @jennyq. I have a couple of questions:
1. Recently I updated Tendenci to 11.4.9 and got error 404 on the page Invoices (account with superuser grants). With debug=true I see the message: 

Page not found (404)
Request Method: | GET
-- | --
https://tendenci.org/invoices/
tendenci.apps.invoices.views.search
No Redirect matches the given query.
What happens with Invoices? 
2. I updated Tendenci to 11.4.9 because I saw that you added features to search by region :)
I trying to input ...LA, Log Angeles, States and so on ...but the result was null rows. 
Could you advise me on a query to see the region values at the database? 
Thanks.

**Comment by ediaz1** [comment]
Hello @avkovalevs,

I noticed that you linked https://tendenci.org/ which doesn't look to exist. Did you instead mean to link to https://www.tendenci.com/?

**Comment by jennyq** [comment]
@avkovalevs, 

That's odd. Can you check if your invoices module is disabled?
https://www.yourdomain/settings/module/invoices/

As for the region, here is a simple query to check the value of the region field:

    select id, region
    from profiles_profile;

**Comment by avkovalevs** [comment]
@ediaz1  Sorry, when I mentioned tendenci.org I mean any domain name.
@jennyq Thanks, I understood what was going on.
