### ISSUE TITLE
Domain name on tendenci

### ISSUE THREAD

**Issue by Nabiil1** [tendenci/tendenci#841]
when i add domain  name to tendenci it won't work till add the port 8000 (e.g: example.com:8000) how i can make it work with out adding port

**Comment by jennyq** [comment]
Hi @Nabiil1,

Thank you for submitting the issue. Can you give us more details on where you add the domain name and what is not working?

**Comment by Nabiil1** [comment]
i install ispconfig first then i install tendenci inside a folder given by ispconfig and to access to website i had to type domain name following with port 8000

**Comment by jennyq** [comment]
I'm not familiar with ispconfig. Maybe you didn't set up your tendenci site to run on 80 or 443?

**Comment by Nabiil1** [comment]
no i haven't do this step, how i could do this

**Comment by jennyq** [comment]
If you look at the doc, it is through Nginx reverse proxy.
https://tendenci.readthedocs.io/en/latest/installation/installation.html#nginx-setup

**Comment by Nabiil1** [comment]
thanks for the help
