### ISSUE TITLE
Event Editing Bug

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#850]
The menus are rendering weirdly when I open an Event for editing.  Open (or add) an event, then click on the 'Fullscreen" button for the Tiny MCE editor.  Once fullscreen the menus  of the editor and Tendenci overlap.  Can't do much if I can't access the menu!  Resizing the window can help to find the menu option that I'm after.
![Events Editor](https://user-images.githubusercontent.com/64681720/80858871-d174c180-8c9f-11ea-816d-6838e178dc18.png)

We're using 12.0.2, but I can also reproduce this fault on the Tendenci Demo site, which is 11.4.2.
I've checked on Firefox and Chrome.

**Comment by jennyq** [comment]
@CWalkden, great catch!
