### ISSUE TITLE
Newsletters include Events Module Content

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#852]
When creating a newsletter, the module content for Events is always included, even when deselected.
We have to manually remove the Events info from the newsletter.
This problem surfaced when we upgraded to 12.0.2, and does not occur on the Tendenci Demo site, which is 11.4.2.

**Comment by jennyq** [comment]
Resolved.
Thanks @CWalkden ! The issue does occur in T11 as well.
