### ISSUE TITLE
Add support for LibreOffice/OpenOffice Document upload

### ISSUE THREAD

**Issue by rob-hills** [tendenci/tendenci#854]
Tendenci limits file uploads to a number of files, mostly Microsoft application documents, PDF and some image files.

Currently Tendenci doesn't support the upload of documents produced by OpenOffice/LibreOffice applications.  As these are open source office products used in preference to their Microsoft equivalents by many organisations, Tendenci should provide support for these.

Relevant document extensions/mimetypes are detailed in the [Wikipedia Open Document page](https://en.wikipedia.org/wiki/OpenDocument_technical_specification)

**Comment by evanspaeder** [comment]
@jennyq We have also seen some OpenOffice files coming through that we need to support.  Just created pull request to resolve this.

**Comment by evanspaeder** [comment]
@jennyq  Can you take a look at this commit and let me know if you agree? 
https://github.com/Everblue-Tech/tendenci/commit/07780f7afceb86a54db22a7250e93580ac0df45a
