### ISSUE TITLE
account activation e-mail template

### ISSUE THREAD

**Issue by avkovalevs** [tendenci/tendenci#855]
Hello @jennyq 
We want to customize the account activation e-mail. How we can do it correctly?
Is there any way to customize login-password and profiles forms?
Both forms need to be translated into French.

Thanks,
Alex

**Comment by jennyq** [comment]
Hi @avkovalevs,
In the theme editor /theme-editor/editor/, you can pull them down to your site to customize them.

For the account activation e-mail
click the button "Customize more templates" -> click "builtin/t7-base" -> click "registration" -> at the right side of the "activation_email.txt", click "copy to custom templates"

For the login template, 
click the button "Customize more templates" -> click "builtin/t7-base" -> click "accounts" -> at the right side of the "login.html", click "copy to custom templates"

For the profiles add/edit forms
click the button "Customize more templates" -> click "builtin/t7-base" -> click "profiles" -> at the right side of the "add_edit.html ", click "copy to custom templates"

**Comment by avkovalevs** [comment]
Thank you @jennyq 
When I click on  "copy to custom templates" I got error "Oops postgres, we caused a problem
We have been notified of this and will be working on it quickly." The message that I got on e-mail: 
FileNotFoundError: No such file or directory /var/www/mysite/themes/tendenci2018/templates/registration/acivation_email.txt

**Comment by jennyq** [comment]
Do those files exist on the file system? If they do exist, check if permissions are set up properly. https://tendenci.readthedocs.io/en/latest/installation/installation.html#permissions

**Comment by avkovalevs** [comment]
@jennyq these files are absent.
Is it possible that these template files were added in some of latest releases? 
root@fa-na-tendenci:/var/www/mysite/themes/tendenci2018/templates# ls -la
total 52
drwxr-x--- 2 postgres www-data  4096 May  9  2019 .
drwxr-x--- 7 postgres www-data  4096 Feb 25  2019 ..
-rw-r----- 1 postgres www-data   213 Feb 25  2019 base-wide.html
-rw-r----- 1 postgres www-data  7515 Nov 19 18:14 base.html
-rw-r----- 1 postgres www-data  1789 Feb 25  2019 default-fullwidth.html
-rw-r----- 1 postgres www-data  2104 Feb 25  2019 default.html
-rw-r----- 1 postgres www-data  1856 Feb 25  2019 footer.html
-rw-r----- 1 postgres www-data  1084 Feb 25  2019 header.html
-rw-r----- 1 postgres www-data 10319 May  9  2019 homepage.html
-rw-r----- 1 postgres www-data  2424 Feb 25  2019 sidebar.html

**Comment by jennyq** [comment]
@avkovalevs, 
Those files didn't get copied over because the themes directory didn't have the write permission for www-data. Please fix the permissions. https://tendenci.readthedocs.io/en/latest/installation/installation.html#permissions

**Comment by avkovalevs** [comment]
@jennyq 
I changed permissions:

**Comment by jennyq** [comment]
You don't need an upgrade to bring those files to the sites. However, T11 is no longer supported, please do upgrade to T12. https://tendenci.readthedocs.io/en/latest/upgrade/upgrade-to-tendenci12.html

**Comment by avkovalevs** [comment]
Fixed. Thanks
