### ISSUE TITLE
Redirects not working for Forums

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#857]
We don't use the Tendenci Forums module, as we have a previously created forum hosted elsewhere.  So we'd like to redirect /forums/ to our other forum.
I've tried to do this in two separate ways:

1. 
In /redirects/ I've put in a redirect from /forums/ to our other site.  In the Demo site I used: https://www.google.com/
This does not redirect.  Typing in /forums/ gets you to /forums/.

2. 
I've disabled the Forums module, by setting /settings/module/forums/%23id_enabled  to False.
Then, in /redirects/, I've redirected from the Forums app to https://www.google.com/.
This does not redirect.  Typing in /forums/ gets you to /forums/.  Not only that, but the Forums work fine, they don't seem to care that they have been disabled.

We're using 12.0.2, but I can also reproduce this on the Tendenci Demo site, which is 11.4.2.
I've tried other redirects with mixes success.  Most work, but occasionally one doesn't.  This one is our most important one, and is nicely reproducible.

**Comment by eschipul** [comment]
Two options - 
1) Disable the module in Tendenci itself at /settings/
2) Redirect via an NGINX proxy

**Comment by eschipul** [comment]
More detail - the entry in your /sites-enabled/ file would be something like these
```
        location /forums/ {
           return 404;
        }
```
or
```
        location  /forums/ {
               root /var/www/example-org/;
        }
```
The other option that comes to mind is commenting it out of urls.py in your "conf" folder.

**Comment by rob-hills** [comment]
@eschipul as @CWalkden mentioned in his original post, the forums module has been disabled on our site.

Does this mean that Tendenci's redirects functionality doesn't work?  Should it be removed?

**Comment by eschipul** [comment]
@rob-hills you are correct and I was hasty in my response. @CWalkden did state the module was disabled.

Should /redirects/ be removed?  Definitely not as they are critical for seo. 

The backstory is between v 4.1 and 5.x as we switched from my original framework written in asp (1997-2001) to django starting in 2009, some things were lost in translation for seo. And SEO is critical to me given it puts Tendenci clearly in the “generates a profit for you” category.

How should redirects work?
302 (use to test) and 301 baseline
redirect url should display as, for example

From: “/my-slug-name/“
To: “/2020/my-dog-name/“

Without the quotes but definitely with the trailing slash. (Except at the end of a GET string of course.)

Further I’d like it to allow fqdn redirects like
From “/blog/“
To: “https://blog.example.org/“

The issue with module names not being allowed could be programmatically resolved. That’s just a legacy django project sequence issue. It just hasn’t been added as an actionable issue or submitted as pull request. Our team internally hosts at AWS mostly (GCP and Azure are both getting better with NGO/NOO pricing which is good for everybody.) 

I just set it up in /etc/nginx/sites-available/example.org on our endpoints which processes it before it ever gets to our docker container private subnet. So it hasn’t been a priority, but I’m wrong a lot so tell me.

Reading between the lines, as much as I like forums, they are major spammer bait. I suggest using google’s recaptcha and (unfortunately) consider not indexing it in robots.txt. 

Spammers are patient. They’ll post a legit question, you answer, the like 9 months or over a year later they edit it with an obfuscated url for pagerank.

Summary:
1. Redirects module needs some love
2. Forums module is best used when secured by user group or members only.

Yet another alternative - add discus at the bottom of content to be discussed.

**Comment by rob-hills** [comment]
@eschipul, thanks for reopening.  Agree re forums, I keep a close eye on ours and have become adept at spotting "sleeper" spammers, but it requires constant attention!

Agree, User Group + members only best.  We don't allow anonymous posters.

**Comment by jennyq** [comment]
Just pushed out a commit https://github.com/tendenci/tendenci/commit/1b3e9167329a920c0c1db45952463d79385bc4fb to make the redirect work for forums.
