### ISSUE TITLE
Cannot assign positions on commitees

### ISSUE THREAD

**Issue by rjdini** [tendenci/tendenci#860]
It is not possible to assign position types to committees, also not to assign users to the positions.
/admin/committees/committee/1/change/

**Comment by eschipul** [comment]
Currently this is not possible as the committee chair is usually given permissions to add/edit their own committee. So the system wouldn't know what to do.

One possible work-around would be to create a "holder user" of the same name as the position or possibly named "vacancy", which ever fits your use case.

And yet another option, if you don't have an actual committee with members yet, you could just add a "page". You can't duplicate a module name in a slug, but you do have the option of creating virtual directories that aren't really there. Scenario

Proposed Committee Test
/comm/communications/  (just added under pages with a similar look and feel as a committee page. Then when the committee actually forms, you can simply go to /redirects/ and add a 302 (test with 302) that sends 
from   /comm/communications/   to   /committees/communications

Once you test it and everything is working, you can change the redirect to a 301.

Lastly if this applies to ALL of your committees, you could remove that section of the template for committees. Instructions on how to do that are in this help file:
[https://www.tendenci.com/help-files/how-do-i-customize-tendenci-core-templates/](https://www.tendenci.com/help-files/how-do-i-customize-tendenci-core-templates/)

**Comment by jennyq** [comment]
Hi @rjdini, 
Are you referring to the Position and User dropdowns under the Officers section on /admin/committees/committee/1/change/? The position dropdown works fine for me. The user dropdown didn't work but it has been fixed https://github.com/tendenci/tendenci/commit/f826454437978687676e2d304d4a6c04630e0ec7. The users that show in the user dropdown are members from the specified Group for the committee.

**Comment by rjdini** [comment]
Thank you - I have upgraded to 12.07 and the above issues are now solved.
