### ISSUE TITLE
Password requirements text incorrectly populating

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#864]
When a user signs themselves up with an account (/accounts/register/), the password complexity requirements are detailed on the form.
We changed the password complexity requirements here: /settings/module/users/%23id_password_requirements_regex
We also changed the password complexity description here: /settings/module/users/%23id_password_text

But the description does not update on /accounts/register/
The text stays like this:  _Use at least 8 characters and 1 number or special character_

**Comment by rob-hills** [comment]
pull #865 offered as fix for this issue.
