### ISSUE TITLE
Newsletter Templates

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#866]
I'd like to create a new template for use in the Newsletters module.
I found this:  /admin/newsletters/newslettertemplate/
The existing templates are not listed.  I tried creating a template, which seemed to work, but it doesn't appear in the list of available templates in the Newsletters module.

Is this how it is supposed to work?

**Comment by jennyq** [comment]
Hi @CWalkden, 

No, the newsletter at admin backend is the one integrated with campaign monitor. We're going to remove it.

In your theme editor /theme-editor/editor/, check if you have the directory "newsletters/templates/default". If the directory doesn't exist,  click the "Customize more templates" button and navigate to the newsletter default templates directory /theme-editor/templates/?app=builtin/t7-base&dir=newsletters/templates/default, then pull down any of those templates. You can either edit the pulled-down template or add a new one under the directory newsletters/templates/default.

**Comment by CWalkden** [comment]
Thanks @jennyq,
We have copied down the templates as suggested, and it looks like we can customise these.
I  can't see a way to rename the template though?  
We can create a new one with the desired name, but how do we get it to the correct directory?  It seems to be created in the templates directory, and I can't see a way to move it.  It is not picked up by the Newsletters module in the templates directory.

**Comment by jennyq** [comment]
They cannot be renamed currently. 

To add new ones, you can go to your site root, then copy them to the directory `themes/tendenci2020/templates/newsletters/templates/default/`. (change tendenci2020 to your theme name if not tendenci2020)
