### ISSUE TITLE
Searching in Files module

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#871]
If you go to the Files module, you see a list of files.
Many of our files have tags.  If you click on a tag (underlined), it is supposed to bring up a search of all files with that tag.  But it doesn't quite work.  If I click on the tag 'minutes', it brings up the search box with "tag:minutes".  But this does not find anything.  The 'tag:' does not seem to be parsed as a command.

I found this because I'm seeing another problem with searching of tags.  I have a number of files with two tags: 'tas' & 'minutes'.  If I use the search string "tas, minutes", I get different results to "minutes, tas".  This is a bit more difficult for people here to reproduce, but I'm hoping that it is related to the above problem (which is easy to reproduce).

**Comment by rob-hills** [comment]
AFAICT, the code in [apps/files/views.py](https://github.com/tendenci/tendenci/blob/master/tendenci/apps/files/views.py#L188) does a literal search for whatever search string is posted.

I assume that tagging is implemented using the django-tagging package, I suspect it should be using the [tag retrieval functionality](https://pvoutput.org/list.jsp?id=1806&sid=2074) in tagging instead?

**Comment by eschipul** [comment]
The discrepancy is odd, but that might be a whoosh thing. To knock out the basics first:
check permissions on both the media, static and the index. Depending on your configuration a chown -R * and checking the cron job is running may solve it.

Helpfiles inherit but explicitly include:
[https://github.com/tendenci/tendenci/blob/5ba6cb05c448dfc9bc575f24588f773280bf2faa/tendenci/apps/help_files/search_indexes.py](https://github.com/tendenci/tendenci/blob/5ba6cb05c448dfc9bc575f24588f773280bf2faa/tendenci/apps/help_files/search_indexes.py)
```
class HelpFileIndex(TendenciBaseSearchIndex, indexes.Indexable):
    question = indexes.CharField(model_attr='question')
    answer = indexes.CharField(model_attr='answer')
    syndicate = indexes.BooleanField(model_attr='syndicate', null=True)
    topic = indexes.MultiValueField()

    # RSS field
    can_syndicate = indexes.BooleanField(null=True)
    order = indexes.DateTimeField()
```
TendenciBaseSearchIndex is defined here:
[https://github.com/tendenci/tendenci/blob/5ba6cb05c448dfc9bc575f24588f773280bf2faa/tendenci/apps/perms/indexes.py](https://github.com/tendenci/tendenci/blob/5ba6cb05c448dfc9bc575f24588f773280bf2faa/tendenci/apps/perms/indexes.py)

@jennyq you are probably better at deciphering why "tag" searches in the help_files module isn't consistent as described by @CWalkden above?

**Comment by rob-hills** [comment]
@CWalkden, @jennyq  I've looked at the code changes made and they will fix the problem caused by the "tag:" string prepended to the search text when you click on a linked tag. However, it will **not** fix other, IMHO more important problem of tag searching not working.

If you give an item two tags, tag1 tag2, it will be found in a search for tag1 and a search for "tag1 tag2", but it **won't** be found by a search for tag2, or for "tag2 tag1"

Maybe this particular problem should become a separate issue?

**Comment by jennyq** [comment]
@rob-hills, Tags are comma delimited. You'll need to separate tags by a **comma**, not a **space**. For example, "word1 word2" is just one tag "word1 word2", while "word1,word2" are two tags, "word1" and "word2".

**Comment by CWalkden** [comment]
Our most pressing issue means that Search cannot find all 40 files I uploaded, even though the tags are the same on all of them.  It either finds 37, or it finds 3, depending on the order I enter the tags.  They are definitely comma delimited.  I'll see if I can reproduce it on the demo site, and raise another issue for it.
