### ISSUE TITLE
UUID' has no len() 

### ISSUE THREAD

**Issue by avkovalevs** [tendenci/tendenci#875]
Hello @jennyq 
We have an issue when creating a group or sending emails for members of the group.

TypeError at /groups/bureau/message/ object of type 'UUID' has no len()
or 
Internal Server Error: /groups/add/

TypeError at /groups/add/
object of type 'UUID' has no len()

Request Method: POST

**Comment by jennyq** [comment]
Hi @avkovalevs, I cannot replicate the error. Are you on the latest version of Tendenci? If not, please upgrade. Also, can you please post the traceback of the exception?

**Comment by avkovalevs** [comment]
We use 11.4.9.

**Comment by jennyq** [comment]
@avkovalevs, T11 is no longer supported. Please upgrade to the latest T12 https://tendenci.readthedocs.io/en/latest/upgrade/upgrade-to-tendenci12.html.
