### ISSUE TITLE
Example newsletters use 'updated' Event date

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#877]
There is a very useful Newsletter function that will automatically populate your newsletter with module content.  For Events, this could be improved:

![Screenshot at 2020-08-10 09-07-31](https://user-images.githubusercontent.com/64681720/89743700-f40d4680-dae8-11ea-87c5-3ed02e976b26.png)

The Event date is the date that the event was last updated.  It would be much more relevant if this was the scheduled date and time for the event.

**Comment by jennyq** [comment]
@CWalkden, Good point!
