### ISSUE TITLE
Formatting of messages to a group

### ISSUE THREAD

**Issue by claudebaudoin** [tendenci/tendenci#886]
Using the messaging feature in groups (for us, the URL is https://database.fa-na.org/groups/faa/message/) the "body" field is a big text block. The formatting we insert in it, specifically blank lines, is lost in the message that is sent. Is this intentional, i.e. is this form of messages supposed to be just a single, run-in paragraph? I tried to insert HTML "<br>" tags but it didn't do anything different.

**Comment by claudebaudoin** [comment]
Oops... After trying <p> tags, it worked. T"But the label "Body text" should really say "Body test (use HTML tags to format). Please consider it a request.

**Comment by jennyq** [comment]
@claudebaudoin, 
Thank you for pointing it out! We'll look at it.
