### ISSUE TITLE
Directory Improvements

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#887]
We've installed version 12.2 on our test server, to test out the advertised improvements to the way that Directories are handled.  Here are the improvements from the changelog:

- Added an option to add a directory for memberships on join approval
- Directory owner or creator can publish their directories if they are created with their memberships or corporate memberships
- If directory for memberships or corporate memberships is enabled, admin can add a directory and associate it with an existing membership or corp membership.
- Included directory_url and directory_edit_url tags for membership and corporate membership notices so that they can be added in the approval notifications to link members to their directory view and edit pages

I can't see any evidence of these features, am I missing something?  Is there any documentation for me to follow?  Do we need to set something up differently to use them?

**Comment by jennyq** [comment]
Hi @CWalkden, 

To enable this functionality in memberships,  you'd need to turn on the setting “Memberships Get Listed in Directories” at https://www.yourdomainname/settings/module/memberships/%23id_adddirectory#id_adddirectory. More info here
https://tendenci.readthedocs.io/en/latest/topic-guides/memberships.html#questions-answers
The setting for corporate memberships is at https://www.yourdomainname/settings/module/corporate_memberships/%23id_adddirectory#id_adddirectory.

**Comment by CWalkden** [comment]
Thanks @jennyq, that was the info I needed to get me started.
The operation looks logical, I like how the Directory is created as 'pending'.  We'll discuss this to see if we would like to implement it.  
A possible future enhancement would be to be able to choose which membership types create Directories.  One of our four standard membership types has Directories, but the other three do not.  So if we implement it we will get hundreds of pending Directories among the dozens that we actually approve.  
We may only enable it for Corporate members, and continue on with our current manual system for the standard members.
