### ISSUE TITLE
newsletters are not searchable in Event Logs

### ISSUE THREAD

**Issue by jclark58** [tendenci/tendenci#892]
Under the menu entries
 Reports/Event log Summary/Newsletters      
clicking on any of the following subcategories produces an error

      view (193)
      edit (45)
      send (40)
      add (24)
      get (20)
      resend (6)

"Application
----------
Select a valid choice. newsletters is not one of the available choices.
These are the different modules like Pages or Articles.
"

"newsletters" does not appear in the dropdown list for Applications field.

**Comment by jennyq** [comment]
Thanks @jclark58 for pointing it out!
