### ISSUE TITLE
Errors generated when cloning membership application

### ISSUE THREAD

**Issue by evanspaeder** [tendenci/tendenci#893]
A second clone of the same membership application produces an error as the slug violates unique constraint.  

For example - application called app1 (id 3) is cloned, slug of clone becomes clone-3-app1.  
A second clone of app1 attempts to create an application with the exact same slug, causing an error. 

I'd like to add a unique value to the slug when cloning, to satisfy the unique constraint. 

@jennyq Is there a particular value that makes sense to use?  Otherwise maybe just an epoch? 

https://github.com/tendenci/tendenci/blob/7d056a215d02e01c8a9067e1dbf969dc7c7054fa/tendenci/apps/memberships/models.py#L2576

**Comment by jennyq** [comment]
No other particular value that I can think of that makes sense to use. Let's go ahead with epoch -  append an epoch time to the original slug. 

    params['slug'] = '%s-%d' % (params['slug'], int(time.time()))

I'll push out the fix. Thanks @evanspaeder !
