### ISSUE TITLE
Large corporate_membership imports fail

### ISSUE THREAD

**Issue by evanspaeder** [tendenci/tendenci#895]
When I import a corporate membership csv larger than 64kb, the preprocess fails.  

Stack Trace: 
```
tendenci_1    | Traceback (most recent call last):
tendenci_1    |   File "manage.py", line 19, in <module>
tendenci_1    |     execute_from_command_line(sys.argv)
tendenci_1    |   File "/srv/mysite/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
tendenci_1    |     utility.execute()
tendenci_1    |   File "/srv/mysite/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
tendenci_1    |     self.fetch_command(subcommand).run_from_argv(self.argv)
tendenci_1    |   File "/srv/mysite/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
tendenci_1    |     self.execute(*args, **cmd_options)
tendenci_1    |   File "/srv/mysite/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
tendenci_1    |     output = self.handle(*args, **options)
tendenci_1    |   File "/srv/mysite/lib/python3.7/site-packages/tendenci/apps/corporate_memberships/management/commands/corp_membership_import_preprocess.py", line 52, in handle
tendenci_1    |     chunk = chunk.decode(encoding)
tendenci_1    |   File "/srv/mysite/lib/python3.7/encodings/cp1254.py", line 15, in decode
tendenci_1    |     return codecs.charmap_decode(input,errors,decoding_table)
tendenci_1    | UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 7968: character maps to <undefined>
```

I added a print(encoding) statement to find the detected character encoding and found that Tendenci was detecting my file encoding to be Windows-1254.  My uploaded file was UTF-8. 

I believe this is because we are detecting encoding on a chunk rather than the full file: 
https://github.com/tendenci/tendenci/blob/a8e2ddeb6050c7d21e199ae0aafd3ce90cf767eb/tendenci/apps/corporate_memberships/management/commands/corp_membership_import_preprocess.py#L43-L55

When I test chardet.detect() on my raw file, I get the correct encoding - UTF-8.

**Comment by evanspaeder** [comment]
@jennyq 
This brings up another issue.  Here we are allowing an upload of any charset.  
In the form validation I hardcoded utf-8.
https://github.com/tendenci/tendenci/blob/a8e2ddeb6050c7d21e199ae0aafd3ce90cf767eb/tendenci/apps/corporate_memberships/forms.py#L925

**Comment by evanspaeder** [comment]
Thanks for the merge @jennyq.  Did you see my comment above?

**Comment by jennyq** [comment]
You're right @evanspaeder . I've pushed out a fix https://github.com/tendenci/tendenci/commit/d20272cb57d5d10074ef5e193eec625dc70b9ec4.
