### ISSUE TITLE
App List is empty ...

### ISSUE THREAD

**Issue by bernd-wechner** [tendenci/tendenci#900]
How confusing:

https://demo.tendenci.com/base/apps-list/

Does same on my install. I'm exploring apps, and trying to pare them down to what our club might need (as tendenci look beautifully rich but supports disabling apps and I see a good many we don't need and the absence of which will make life less confusing for the admins I hand this too).

But how confusing is an empty App List?

**Comment by jennyq** [comment]
@bernd-wechner, Thanks for pointing it out!

**Comment by bernd-wechner** [comment]
And is it fixed?

**Comment by jennyq** [comment]
Yes, fixed in the commit https://github.com/tendenci/tendenci/commit/303b79481f40eef38aa87d8d84b53d5395fc458d. Will be pushed to PyPI with next version bump.

**Comment by bernd-wechner** [comment]
Awesome, thank you! The phone githib app seems not to have shown me what the web page does (the link to the commit that fixed it). Such rapid response is amazing and I think Tendenci rocks!
