### ISSUE TITLE
Bug or Feature?: initial_migrate creates an entity and a group.

### ISSUE THREAD

**Issue by bernd-wechner** [tendenci/tendenci#905]
After creating the initial database and then running:
```
python manage.py initial_migrate
```
to populate it with tables, there is a small surprise on its way. Namely there is an entity and a user group both called Tendenci created.

This appears to break the intent and paradigm of migrations, which related to table definitions not content. 

Why is this s important? Because when setting up a site for a new association it is hand to write the fixtures that define the intended entity, user group and other structures, and load them after the tables are built. Alas if you try that they bomb, on primary key clashes with these two tuples already in the database. 

In fact my general approach and intent has been to get the initial entity and user group structure in place, along with whatever else I know up front and is easy to do by writing fixtures, then start the site up, log in and finish configuring it for use, then dumpdata to capture the fixtures as they stand. The idea then is I could build this site somewhere else, initial_migrate and then load these fixtures and I'd have a startup site for this association.

But this whole workflow with fixtures is broken by the presence of data  in these two tables after an initial_migrate.

I have spent some time trying to find where and when this happens without success so far alas. Any tips in that space are appreciated.

I think it best if these two tuples were created in the deploy step. The instructions for installing suggest these two commands:

```
python manage.py initial_migrate
python manage.py deploy
```
and the first one should create only tables and the second one can and does put data into the tables. This allows us to load fixtures between the two and causes the attempt to load data into models we've populated to fail in the deploy stage, which may be more tolerable. 

Alas this is a problem with Django's fixtures and loaddata and dumpdata. It would be nice if Django loaddata had an option to overwrite database tuples with clashing keys from the the fixture. than this would not  be such an issue. IN the interim Django simply suggest writing a custom command that does that, and that's a possible step too, but it should rest in the tendenci package methinks if we write one. A loaddata that supports a --overwrite option that means a fresh install after deploy installs useful fixtures can be customised with something tailor made.

**Comment by jennyq** [comment]
Resolved. The reason they were created during the initial migration is because the group field initially had a default value "get_default_group" which creates a default group and a default entity.

**Comment by bernd-wechner** [comment]
> Resolved. The reason they were created during the initial migration is because the group field initially had a default value "get_default_group" which creates a default group and a default entity.

Thanks for clarifying Jenny. That suggests feature not bug. BUT can you clarify what this means? Sorry, it's not clear. I did search the entire code base of tendenci and a running site for get_default_group and the most likely causal candidate I find is:

`apps/user_groups/utils.py:def get_default_group():`

which looks like:

```
def get_default_group():
    """
    Get the ID of the default group specified in the global setting
    """
    return Group.objects.get_initial_group_id()
```

which sends us to:

`apps/user_groups/managers.py:    def get_initial_group_id(self):`

which resembles:

```
    def get_initial_group_id(self):
        """
        Returns the id of the default group.
        Can be used to set group initial for forms.
        """
        group_id = get_global_setting('default_group')
        if not group_id:
            group = self.get_or_create_default()
            group_id = group.id

        return group_id
```

which sends us to:

`apps/site_settings/utils.py:def get_global_setting(name):`

and we're rapidly down a rabbit's warren of settings definition code. I can trace this further and maybe try and interpret what you mean, but it seems the problem remains that a migration does this:

`apps/files/migrations/0006_auto_20181115_2145.py:        group_id = get_default_group()`

which does speak to the original quesition of whether it's appropriate for Django migrations to insert data. But that aside, I am trying to work out from your tip whether there is a setting somewhere, possibly on conf/settings.py that is available to us to prevent this from happening, to disable a default group, so that we could then load some fixtures that define entities and groups without any primary key clashes.

**Comment by jennyq** [comment]
As I said, it's been resolved. Now the initial_migrate does **not** insert any data. 

However, the command "deploy" does populate some default or initial data with the commands "update_settings", "populate_default_entity", "loaddata initial_data.json". 
https://github.com/tendenci/tendenci/blob/master/tendenci/apps/base/management/commands/deploy.py

And, you also need to run "load_tendenci_defaults" command to make the tendenci2020 theme work. 

I'd suggest to build your own fixtures based on what's already in the database. Basically, you can add, change or delete any content, then use dumpdata command to create your own fixtures. Note that, delete in Tendenci is mostly soft-delete, meaning the items are not physically deleted from database. So before you run dumpdata, you'd need to clear out the soft deleted items by running the management command "delete_soft_deleted_items". 

    python manage.py delete_soft_deleted_items

**Comment by bernd-wechner** [comment]
My sincere apologies. I missed that terse one word Resolved ;-) Thanks kindly!
