### ISSUE TITLE
Similar user list does not account for capitalization

### ISSUE THREAD

**Issue by SidBergstresser** [tendenci/tendenci#913]
The similar user list (example.com/profiles/similar/) does not account for capitalization of the names. It appears to only show exact matches for names. So two users named "Test User" and "TEST USER" would not show up on the similar users list. Or a more real-world example would be the last name "McDonald" versus "Mcdonald" which would not show up as similar users.

**Comment by jennyq** [comment]
Resolved https://github.com/tendenci/tendenci/commit/609295e8acef78d57daeba5341072e823abc2a6c. Thanks @SidBergstresser for reporting it!
