### ISSUE TITLE
Photos placed over text in Event speakers

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#917]
We have speakers in an Event, and the speakers have photos.  Here is the event:  [https://aeva.asn.au/events/112/](url)
The speakers look good in that view, but if you click on the View All Speakers button, then resize to mobile, the pictures overlap the text.

![Screenshot at 2020-10-28 07-51-20](https://user-images.githubusercontent.com/64681720/97360908-ec448d80-18f2-11eb-91f7-801e7ca15c62.png)

**Comment by eschipul** [comment]
@CWalkden 

First please know I can't replicate the error. However two possible causes. 

1) The most likely is caching of the image which could be a  bug in server config.

2) Second most likely is your CSS is off for mobile viewports. In that scenario, have you tried doing a hard refresh on the browser or clearing cache?

If it is an issue in core, I'd love to solve it "once for all time for all users" but we just need greater detail such as HTML source code of the view on different viewports. The easiest way to do this is in Safari (Mac or PC) to change the self-identifying host header:

<img width="511" alt="aeva-speaker-view-css-display" src="https://user-images.githubusercontent.com/153359/98011876-13510280-1dbe-11eb-8aad-3950211bc1e8.png">

**Comment by CWalkden** [comment]
Hi Ed,
I note that your screenshot is not the view I'm talking about.  As stated in the OP, _that_ view is correct.  To get the fault, from that view press the "View All Speakers" button.  This takes you here: [https://aeva.asn.au/events/112/speakers/](https://aeva.asn.au/events/112/speakers/).  Resize that window to mobile dimensions (I'm using a desktop PC with Firefox or Chrome) and you'll hopefully see the problem.  (I really should have linked that URL to start with!)

The other advice you've written is over my head.  I'd probably have access to get you the info you ask for, but I don't have the knowledge to understand what you've asked for.  I'll point a couple of more technical people towards this thread to see if they can help.

**Comment by rob-hills** [comment]
Hi @eschipul , @CWalkden,

I've just tried this and find exactly the same problem as Christopher.  I've found it doesn't just happen in "Mobile" view either.  If you slowly resize the page (concentrating on reducing the width), at certain widths you get the picture overlapping the text.

For example, at 320 x 480 px dimensions, I get overlap.  Interestingly also at 480 x 320.  These dimensions trigger the "Mobile", 3-bar menu.  But at 900 x 600 px I get the Desktop menu **_and_** the speaker's picture overlapping the text.

For the record, we haven't done anything to the CSS to make this happen.

**Comment by ediaz1** [comment]
Hello,

Here's a possible solution I found. Please view screenshots that shows before and after of code changes results. It looks like we'll need to remove col-xs-3 and add to the CSS to give it better spacing in the margins. The images have a fixed width of 100px so I don't think it would be necessary to have col-xs-3 class. 

Before
![aeva-before](https://user-images.githubusercontent.com/6806304/98550545-dc696980-2261-11eb-8d9a-f572a223be96.png)

After
![aeva-after](https://user-images.githubusercontent.com/6806304/98550608-f0ad6680-2261-11eb-9146-b935ba27e6ce.jpg)

**Comment by jennyq** [comment]
Resolved https://github.com/tendenci/tendenci/commit/ec75182e5849498c074efd7f5ab427bca509ea8f. Also noted that the speaker description is duplicated. Fixed that as well.
