### ISSUE TITLE
Is there a reason the CountrySelectField doesn't use the abreviation?

### ISSUE THREAD

**Issue by theox26** [tendenci/tendenci#923]
https://github.com/tendenci/tendenci/blob/50551af96bbc400a3d0b6362abf9dbf625cacebf/tendenci/apps/base/fields.py#L125

(key, name) works as well and matches the method used in the settings. It would also allow the field to be used more easily to populate a states dropdown based on country.

**Comment by jennyq** [comment]
With that it can show the name of the country instead of the abbreviation on user or member profiles without extra step. Not everybody is familiar with the abbreviation of every country.
