### ISSUE TITLE
Change future events only in a series doesn't work

### ISSUE THREAD

**Issue by claudebaudoin** [tendenci/tendenci#936]
I'm in Events --> Calendar.
I click on a recurring event.
I select Options --> Edit
I change the start and end date of the event (we moved our bi-weekly steering committee meeting to be an hour later).
At the bottom of the edit screen, I select the radio button to change the event I selected and the subsequent one -- as opposed to changing all occurrences.
I then get a confirmation request popup (see attachment) that says the opposite: it asks me to confirm that all events will be changed, INCLUDING PAST ONES.
![Capture](https://user-images.githubusercontent.com/63268131/101123863-924a7e00-35aa-11eb-8bba-e70f5b4495a3.JPG)

Then I decided to go ahead after all, and I clicked on Yes. I then got an error screen that says:
"Oops cbaudoin, we caused a problem
We have been notified of this and will be working on it quickly.
You may want to try this page again in a little bit."

So there seems to be TWO problems on top of one another. Please advise.

**Comment by avkovalevs** [comment]
HI @jennyq!
Could you help with it?
We use the Tendenci version 12.2.1. Does the issue still exist in the new version?
Thanks for your help.

**Comment by jennyq** [comment]
Hi @avkovalevs, 

Thank you for the detailed steps. However,  I couldn't reproduce the oops error. Can you please turn on the debug mode (set `DEBUG = True` in your conf/settings.py, then restart the site) and paste the exception traceback here?

**Comment by avkovalevs** [comment]
Request Method: | POST
-- | --
https://domain.com/events/overview/edit/14/
2.2.16
TypeError
'>' not supported between instances of 'NoneType' and 'NoneType'
/srv/mysite/lib/python3.6/site-packages/tendenci/apps/events/forms.py in clean, line 852
/srv/mysite/bin/python3.6
3.6.7
['/var/www/mysite',  '/srv/mysite/bin',  '/srv/mysite/lib/python36.zip',  '/srv/mysite/lib/python3.6',  '/srv/mysite/lib/python3.6/lib-dynload',  '/usr/lib/python3.6',  '/srv/mysite/lib/python3.6/site-packages']
Sun, 31 Jan 2021 05:12:33 -0600


Environment:


Request Method: POST
Request URL: https://domain.com/events/overview/edit/14/

Django Version: 2.2.16
Python Version: 3.6.7
Installed Applications:
['django_admin_bootstrapped',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.humanize',
 'django.contrib.sitemaps',
 'django.contrib.messages',
 'django.contrib.admindocs',
 'django.contrib.staticfiles',
 'django.contrib.gis',
 'formtools',
 'bootstrap3',
 'dj_pagination',
 'tagging',
 'captcha',
 'haystack',
 'tastypie',
 'timezone_field',
 'gunicorn',
 'tendenci.libs.model_report',
 'tendenci.libs.tinymce',
 'tendenci.libs.uploader',
 'tendenci.apps.entities',
 'tendenci.apps.base',
 'tendenci.apps.site_settings',
 'tendenci.apps.contributions',
 'tendenci.apps.search',
 'tendenci.apps.notifications',
 'tendenci.apps.registration',
 'tendenci.apps.registry',
 'tendenci.apps.api_tasty',
 'tendenci.apps.invoices',
 'tendenci.apps.payments',
 'tendenci.apps.payments.stripe',
 'tendenci.apps.recurring_payments',
 'tendenci.apps.forms_builder.forms',
 'tendenci.apps.accounts',
 'tendenci.apps.files',
 'tendenci.apps.user_groups',
 'tendenci.apps.perms',
 'tendenci.apps.profiles',
 'tendenci.apps.meta',
 'tendenci.apps.tags',
 'tendenci.apps.articles',
 'tendenci.apps.jobs',
 'tendenci.apps.news',
 'tendenci.apps.stories',
 'tendenci.apps.pages',
 'tendenci.apps.events',
 'tendenci.apps.photos',
 'tendenci.apps.memberships',
 'tendenci.apps.corporate_memberships',
 'tendenci.apps.locations',
 'tendenci.apps.industries',
 'tendenci.apps.regions',
 'tendenci.apps.educations',
 'tendenci.apps.careers',
 'tendenci.apps.make_payments',
 'tendenci.apps.accountings',
 'tendenci.apps.emails',
 'tendenci.apps.email_blocks',
 'tendenci.apps.contacts',
 'tendenci.apps.robots',
 'tendenci.apps.versions',
 'tendenci.apps.event_logs',
 'tendenci.apps.categories',
 'tendenci.apps.theme_editor',
 'tendenci.libs.styled_forms',
 'tendenci.apps.newsletters',
 'tendenci.apps.redirects',
 'tendenci.apps.directories',
 'tendenci.apps.help_files',
 'tendenci.apps.resumes',
 'tendenci.apps.boxes',
 'tendenci.apps.mobile',
 'tendenci.apps.campaign_monitor',
 'tendenci.apps.wp_importer',
 'tendenci.apps.wp_exporter',
 'tendenci.apps.theme',
 'tendenci.apps.discounts',
 'tendenci.apps.metrics',
 'tendenci.apps.navs',
 'tendenci.apps.tendenci_guide',
 'tendenci.apps.exports',
 'tendenci.apps.events.ics',
 'tendenci.apps.imports',
 'tendenci.apps.handler404',
 'tendenci.apps.reports',
 'tendenci.apps.dashboard',
 'tendenci.apps.social_media',
 'tendenci.apps.announcements',
 'tendenci.apps.forums',
 'tendenci.apps.committees',
 'tendenci.apps.case_studies',
 'tendenci.apps.donations',
 'tendenci.apps.speakers',
 'tendenci.apps.staff',
 'tendenci.apps.studygroups',
 'tendenci.apps.videos',
 'tendenci.apps.testimonials',
 'tendenci.apps.social_services',
 'tendenci.apps.explorer_extensions',
 'explorer',
 'debug_toolbar']
Installed Middleware:
['django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.common.CommonMiddleware',
 'dj_pagination.middleware.PaginationMiddleware',
 'tendenci.apps.profiles.middleware.ForceLogoutProfileMiddleware',
 'tendenci.apps.profiles.middleware.ProfileMiddleware',
 'tendenci.apps.base.middleware.Http403Middleware',
 'tendenci.apps.redirects.middleware.RedirectMiddleware',
 'tendenci.apps.mobile.middleware.MobileMiddleware',
 'tendenci.apps.theme.middleware.RequestMiddleware',
 'tendenci.apps.base.middleware.MissingAppMiddleware',
 'tendenci.apps.base.middleware.RemoveNullByteMiddleware',
 'tendenci.apps.memberships.middleware.ExceededMaxTypesMiddleware',
 'tendenci.apps.forums.middleware.PybbMiddleware',
 'tendenci.apps.profiles.middleware.ProfileLanguageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware']



Traceback:

File "/srv/mysite/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/srv/mysite/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/srv/mysite/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/srv/mysite/lib/python3.6/site-packages/tendenci/apps/perms/decorators.py" in wrapped
  80.             return fn(request, *args, **kwargs)

File "/srv/mysite/lib/python3.6/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)

File "/srv/mysite/lib/python3.6/site-packages/tendenci/apps/events/views.py" in edit
  621.                     if form_event2.is_valid():

File "/srv/mysite/lib/python3.6/site-packages/django/forms/forms.py" in is_valid
  185.         return self.is_bound and not self.errors

File "/srv/mysite/lib/python3.6/site-packages/django/forms/forms.py" in errors
  180.             self.full_clean()

File "/srv/mysite/lib/python3.6/site-packages/django/forms/forms.py" in full_clean
  382.         self._clean_form()

File "/srv/mysite/lib/python3.6/site-packages/django/forms/forms.py" in _clean_form
  409.             cleaned_data = self.clean()

File "/srv/mysite/lib/python3.6/site-packages/tendenci/apps/events/forms.py" in clean
  852.         if start_dt > end_dt:

Exception Type: TypeError at /events/overview/edit/14/
Exception Value: '>' not supported between instances of 'NoneType' and 'NoneType'

**Comment by jennyq** [comment]
Hi @avkovalevs,

That issue has been resolved already. Please update your site to the latest version of Tendenci. https://tendenci.readthedocs.io/en/latest/upgrade/point-update.html

**Comment by avkovalevs** [comment]
Thank you @jennyq! It helped.
