### ISSUE TITLE
Bug in Forms Module

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#947]
Version 12.2.5.  Editing fields in a form.
1. Add a new field.
2. Select type 'Checkbox' and special functionality 'Subscribe to Group'.
3. Go back and change your mind, select 'Email' instead of 'Checkbox.  The special functionality disappears.
4. Save your form - you'll receive an error "This field's function requires Checkbox as a field type".

The problem is that the special functionality needs to be '--------', but it is 'Subscribe to Group', event though this is not shown and can't be selected.  You need to change the type back to 'Checkbox', fix the special functionality and then change the type back to 'Email'.
This error may be fairly easy to figure out if you only have the one field, but if you've just added 20 of them it can be very frustrating.  Ask me how I know!

**Comment by jennyq** [comment]
Resolved https://github.com/tendenci/tendenci/commit/1342e3b22a054b2f5a0ce64900f1300df079f5a8. Thank you for reporting the issue!
