### ISSUE TITLE
Bug: Cannot add committee members

### ISSUE THREAD

**Issue by bernd-wechner** [tendenci/tendenci#954]
The officer formset has an odd bug I can't pin down quickly. I can reproduce on the demo site:

https://demo.tendenci.com/committees/edit/1/

To do so, create committee, then edit it. You'll land at a URL like the one above.

The try to add committee members. There is a drop down selector for selecting the member and one for the position. 

Click Add Position, as many times as you'd like to create new rows.

You will find it impossible to select a user from rows 2 and on, always the select box in row 1 responds. 

My suspicion is that as the formset is built (new rows added) there is some id confusion (or reuse) so the click event modified the wrong select box. Alternately it might be that the drop down is simply hidden but still there and trapping the click. it seems a bootstrap selector and the element breakdown ad javascript are not trivial and will take more time than I have now to fix, so I just created my committee by adding rows by hand to the database table: `committees_officer`

**Comment by jennyq** [comment]
This issue has been fixed in the tendenci version 12.4.4 and later.
https://github.com/tendenci/tendenci/commit/c3fa2ccf3b2dc776247663a2687789e2e7b8347e
