### ISSUE TITLE
Bug: user modified notifications lack username

### ISSUE THREAD

**Issue by bernd-wechner** [tendenci/tendenci#972]
I just edited some users and I get emails with a subject line:

"User () edited on HoGS"

I've checked the code and that should have the username the brackets there I'm sure, but for now I've not found it easy to trace how and where it gets there. 

I'm willing to be it's from the `user_edited/short.txt` template which contains:

```
{% blocktrans with object.username as objname %}User ({{ objname }}) edited on {{ SITE_GLOBAL_SITEDISPLAYNAME }}{% endblocktrans %}
```
but i haven't found yet precisely where in the code this tenplate is used and `object` is given a value. 

My bet is it's here:

https://github.com/tendenci/tendenci/blob/f99ec9166ea7a076a54bee8d3ac920cb49c24381/tendenci/apps/notifications/models.py#L331

and hence here:

https://github.com/tendenci/tendenci/blob/f99ec9166ea7a076a54bee8d3ac920cb49c24381/tendenci/apps/notifications/models.py#L301

but I haven't yet traced where it gets its `context` from thoroughly. My guess is `object` is missing anyhow.

**Comment by jennyq** [comment]
Great catch! And thank you for fixing it!
