### ISSUE TITLE
No Study Groups Settings

### ISSUE THREAD

**Issue by SidBergstresser** [tendenci/tendenci#980]
The link to Settings for Study Groups is broken and I do not see an option in the full settings either.

![image](https://user-images.githubusercontent.com/48220321/106230162-e2b21680-61bc-11eb-9267-66fd30e018f8.png)

The url is .../settings/module/studygroups/ but it is broken.

There is also not a Study Groups option on the Full Settings page (.../settings/)

**Comment by jennyq** [comment]
Fixed. Thank you @SidBergstresser for pointing it out!
