### ISSUE TITLE
Photos with metadata

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#981]
Tendenci 12.3.3
When uploading a photo via the Photos module, it doesn't work if the photo has metadata.  If I first save the photo without metadata then that version will upload.
The system tries three times and then fails with this message:
![Screenshot at 2021-01-30 21-11-01](https://user-images.githubusercontent.com/64681720/106353581-ba9ef080-633f-11eb-9eab-76e07b088fb0.png)
We also receive an error message via email with the title: ERROR (EXTERNAL IP): Internal Server Error: /photos/batch-add/17
I was going to post the email here, but it contains some details which might be best not published on a public forum (I noticed some stuff to do with Paypal for instance).
I'll attach two photos that can be tested.  One has metadata, one does not.

[Photos.zip](https://github.com/tendenci/tendenci/files/5897747/Photos.zip)

**Comment by eschipul** [comment]
@CWalkden we are looking into this. Github's security scan is not reporting any vuln3rabilities in dependencies in requirements, so this is the first I have heard of it. We *do* want some metadata to upload as photographers deserve credit. It just must be processed properly on save.

**Comment by jennyq** [comment]
Thanks @CWalkden for reporting the issue! It has been fixed.
