### ISSUE TITLE
Edit default newsletter text?

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#992]
There are two blocks of text populated into a newsletter by default.  This one is always there:
_Hello [firstname],
Welcome to the Tendenci newsletter of upcoming events, articles, jobs and more from our membership._

Then when I tick the "Include Login Information" button, I get this text:
_Your login information is listed below. To log into the site, visit https://demo.tendenci.com and enter your Username and Password.
    Username: [username]
If you've forgot your password or need to reset the auto-generated one, follow the instruction here to reset your password: Click Here
If you have any questions, please contact the Site Administrator._

We'd like to edit both of these default texts, but can't figure out where they come from.  Our reasons for editing are:
- We don't use the Jobs module.  But some of our Newsletter editors don't notice where it says jobs, and leave it in.
- This isn't a Tendenci newsletter, so we replace that reference.
- The login text uses different formatting than the welcome text.  It is quite difficult to get it all looking the same with the WYSIWYG editor.
- There is a spelling mistake in the login text ('forgot' instead of 'forgotten'), and it refers to an auto-generated password, which we don't use.
- The login text refers to the Site Administrator, we replace that with a specific email address.

One of our 'HTML people', who is making new Newsletter templates for us, said that the text is being brought in from elsewhere, but it wasn't clear where it came from.  Can we edit it?

**Comment by jennyq** [comment]
Yes, you can edit them by pulling down the templates in the theme editor. Those templates you mentioned are listed in the templates/newsletters https://github.com/tendenci/tendenci/tree/master/tendenci/themes/t7-base/templates/newsletters. For example, here is the login.txt https://github.com/tendenci/tendenci/blob/master/tendenci/themes/t7-base/templates/newsletters/login.txt.

**Comment by CWalkden** [comment]
Thanks @jennyq, we've managed to edit these.
