### ISSUE TITLE
Event Custom Emails

### ISSUE THREAD

**Issue by CWalkden** [tendenci/tendenci#994]
The default registration email for events is great!  Nicely formatted and gives good information.  But sometimes we'd like a custom one, and I'd like some guidance on how to embed fields into a custom email.
The idea is that for a particular (recurring) event, we'd like registrants to bring along their 'ticket'.  We'd like to design an email to look like a ticket, with the registrant's name and chosen pricing displayed.  It would also be good to have a link to their invoice.
Is there a way to include these fields in a custom email? 

Here is an example of the default email.  The 'helpful links' are indeed helpful, and we'd like to re-create them in our custom email:
![Screenshot at 2021-03-07 21-08-46](https://user-images.githubusercontent.com/64681720/110236350-5a781b80-7f89-11eb-894e-cb38279e079a.png)

**Comment by jennyq** [comment]
@CWalkden, 

Everything you needed is already in the template https://github.com/tendenci/tendenci/blob/master/tendenci/themes/t7-base/templates/notification/event_registration_confirmation/full.html#L21. 

Invoice url:

    {{ SITE_GLOBAL_SITEURL }}{% url "invoice.view" reg8n.invoice.pk %}

The following block of code displays name, email, pricing for each registrant in one registration.

                   {% for registrant in registrants %}
                        <div>
                        {% if registrant.get_name %}
                            {{ registrant.get_name }}
                        {% else %}
                            {% trans "Guest #" %}{{ forloop.counter0 }}
                        {% endif %}
                        {% if registrant.email %}
                            ({{ registrant.email }})
                        {% endif %}
                        {% if registrant.pricing.title %}
                        <div>{% trans "Registration Type" %}: {{ registrant.pricing.title }}</div>
                        {% endif %}
                        {% if registrant.custom_reg_form_entry %}
                        {% with registrant.custom_reg_form_entry.roster_field_entry_list as roster_field_list %}
                        {% for field in roster_field_list %}
                            {% if field.value %}
                            <div>{{ field.label }}: {{ field.value }}</div>
                            {% endif %}
                        {% endfor %}
                        {% endwith %}
                        {% endif %}
                        </div>
                    {% endfor %}
