### ISSUE TITLE
Character limit when adding a corporate representative

### ISSUE THREAD

**Issue by SidBergstresser** [tendenci/tendenci#999]
When adding a corporate representative (/corporatememberships/edit_corp_reps/###/), a user must select an existing user in the system and is presented with options that combine name, username, and email address. But if the combination of these three things is greater than 100 characters, it gives an error even though the user has no control over this. Recommend removing the character limit or setting it very high.

![image](https://user-images.githubusercontent.com/48220321/111214198-092ee400-85a8-11eb-9568-5aaac765ecbc.png)

**Comment by jennyq** [comment]
Great catch. Thanks @SidBergstresser !
The maximum number of characters entered to that field could be the sum of the max_length of username, first and last names, and email. Changed it to 800.
